### PR TITLE
JAMES-2759 Various fixes

### PR DESCRIPTION
**Pull request by chibenwa**
Fixes my post-merge comments on https://github.com/linagora/james-project/pull/2442

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[ERROR]   RabbitMQEventBusTest$LifeCycleTest$SingleEventBus$DispatchingWhenNetWorkIssue.dispatchShouldWorkAfterNetworkIssuesForOldRegistration:366 » ConditionTimeout
```

test this please

**Comment by trantienduchn** [comment]
maven test passed
```
Caused by: java.lang.IllegalStateException: no known node for /home/jenkins/build/workspace/605
```

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
```

[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.968 s <<< FAILURE! - in org.apache.james.mpt.imapmailbox.external.james.JamesDeploymentValidationTest
[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR] validateDeployment  Time elapsed: 0.875 s  <<< ERROR!
[6ca0d4c25c6eb6551548574c20a5280f27597460] org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 
[6ca0d4c25c6eb6551548574c20a5280f27597460] 
[6ca0d4c25c6eb6551548574c20a5280f27597460] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:24
[6ca0d4c25c6eb6551548574c20a5280f27597460] LastClientMsg: 10 CREATE appendexpunge
[6ca0d4c25c6eb6551548574c20a5280f27597460] Expected: '10 OK CREATE completed.'
[6ca0d4c25c6eb6551548574c20a5280f27597460] Actual   : ''
[6ca0d4c25c6eb6551548574c20a5280f27597460] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeployment(DeploymentValidation.java:81)
[6ca0d4c25c6eb6551548574c20a5280f27597460] 
[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR] validateDeploymentWithMailsFromSmtp  Time elapsed: 0.081 s  <<< ERROR!
[6ca0d4c25c6eb6551548574c20a5280f27597460] org.apache.james.utils.SMTPSendingException: 
[6ca0d4c25c6eb6551548574c20a5280f27597460] Error upon step RCPT: 451 Unable to process request
[6ca0d4c25c6eb6551548574c20a5280f27597460] 
[6ca0d4c25c6eb6551548574c20a5280f27597460] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeploymentWithMailsFromSmtp(DeploymentValidation.java:87)
```

failed during deployment tests, handled here https://issues.apache.org/jira/browse/JAMES-2792

test this please

**Comment by chibenwa** [comment]
```
[6ca0d4c25c6eb6551548574c20a5280f27597460] [INFO] Apache James :: Server :: JMAP :: Cassandra Integration testing FAILURE [04:49 min]
[ERROR]   GetMessageListMethodTest.setup:114 » ElasticsearchStatus Elasticsearch excepti...
```

test this please

**Comment by chibenwa** [comment]
mvn tests :green_apple: 

```
[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR]   DeploymentValidation.validateDeployment:81 » InvalidServerResponse 
[6ca0d4c25c6eb6551548574c20a5280f27597460] Location: ...
[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR]   DeploymentValidation.validateDeploymentWithMailsFromSmtp:87 » SMTPSending Erro...
```

test this please

**Comment by mbaechler** [comment]
```

[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR] Errors: 
[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR]   DeploymentValidation.validateDeployment:81 » InvalidServerResponse 
[6ca0d4c25c6eb6551548574c20a5280f27597460] Location: ...
[6ca0d4c25c6eb6551548574c20a5280f27597460] [ERROR]   DeploymentValidation.validateDeploymentWithMailsFromSmtp:87 » SMTPSending Erro...
[6ca0d4c25c6eb6551548574c20a5280f27597460] [INFO] 
```

test this please

**Pull request merged**
