### PR TITLE
One fix per day 16

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by mbaechler** [comment]
> But you are looking for conflicts :-)

no `var` here

**Comment by mbaechler** [comment]
> > But you are looking for conflicts :-)
> 
> no `var` here

ok, now I see the kind of conflict ...

pushed-force to rebase on master

**Comment by mbaechler** [comment]
```
[b63d39486e441f9b21dcc11eb09f8e7b27514d68] [ERROR] Errors: 
[b63d39486e441f9b21dcc11eb09f8e7b27514d68] [ERROR]   DiscardProtocolTest.testRecord:84 »  Timed out wait for be notified that read ...
```

test this please

**Comment by mbaechler** [comment]
flaky cache test

```
[b63d39486e441f9b21dcc11eb09f8e7b27514d68] [ERROR] Errors: 
[b63d39486e441f9b21dcc11eb09f8e7b27514d68] [ERROR]   CassandraDumbBlobStoreCacheTest.shouldReturnDataWhenCacheSmallDataInConfigurationTTL » ConditionTimeout
```

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
