### PR TITLE
JAMES-3087 LDAP user listing should filter out users without id field

### PR DESCRIPTION
**Pull request by chibenwa**
Before that a NPE was returned.

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
How about tests for `countUsers()` ?

**Comment by chibenwa** [comment]
```
[cdcf10ea85ca62bd325d372496e5964b2faf5f11] [ERROR] Failures: 
[cdcf10ea85ca62bd325d372496e5964b2faf5f11] [ERROR]   CassandraBlobStoreTest.readBytesShouldPublishReadBytesTimerMetrics 
[cdcf10ea85ca62bd325d372496e5964b2faf5f11] Expected size:<2> but was:<1> in:
[cdcf10ea85ca62bd325d372496e5964b2faf5f11] <[PT0.004687877S, PT0.004020632S]>
```

unrelated.

test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
