### PR TITLE
Imap 370 - Consider supporting the upcoming MOVE extension

### PR DESCRIPTION
**Pull request by chibenwa**
In this PR : 

 - I add the notion of capabilities for Mailbox Managers
 - I solve inheritance bug for MOVE and COPY command
 - I provide unit tests for MOVE and COPY components for IMAP
 - I provide code factorisation between COPY and MOVE commands
 - I provide MPT tests for the MOVE command
 - I announce and enable MOVE command only if supported
 - I provide documentation updates, mostly about mailbox capabilities and MOVE command

### CODE REVIEW

**Comment by chibenwa** [comment]
Raphael, sorry for your comments...
A rebase of the history was needed because of merge conflict.

**Comment by chibenwa** [comment]
Link to comments with discussions : 
 - https://github.com/chibenwa/james-project/commit/1807cf90fe33cf3ab596d680ae1f7cf82dcf491a#commitcomment-16418230
 - https://github.com/chibenwa/james-project/commit/1807cf90fe33cf3ab596d680ae1f7cf82dcf491a#commitcomment-16418240
 - https://github.com/chibenwa/james-project/commit/4988c11727f22aaf911cddca075fdfbf7ec4debb#commitcomment-16418340
 - https://github.com/chibenwa/james-project/commit/b4c52668a54b5511ad27320f5133fb3c3253f085#commitcomment-16418406
 - https://github.com/chibenwa/james-project/commit/e3b75d70bc656905c60965723de0595e790b0e3f#commitcomment-16418496

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Pull request closed without merging**
