### PR TITLE
[Enhencement] CassandraUserMailboxRightsDAO should merge flux on updates

### PR DESCRIPTION
**Pull request by chibenwa**
Before needless synchronisation was performed, waiting for all insert to
complete, all delete to complete, and all insert

Now merge can eagerly subscribe each streams insides.

### CODE REVIEW

**Comment by rouazana** [comment]
I'm ok with [refactor] commit tag, but not with [enhancement]. I think [enhancement] should be replaced by a JIRA

**Comment by mbaechler** [comment]
> Before needless synchronisation was performed, waiting for all insert to
> complete, all delete to complete, and all insert
> 
> Now merge can eagerly subscribe each streams insides.

Can you demonstrate the execution is effectively different? `then` is not performing any synchronization AFAIK and I really think the two versions behave the same.

**Comment by chibenwa** [comment]
> I really think the two versions behave the same.

Merge can interleave the elements of the flux while then will only replay completion

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
MessageFullViewFactoryTest$WithProjectionInvolvedTest.fromMessageResultsShouldComputeWhenProjectionReturnEmpty:883 » NullPointer
```

barely related

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
