### PR TITLE
[Reactor] Replace Mono::switchIfEmpty(Mono.just(x)) by Mono::defaultI…

### PR DESCRIPTION
**Pull request by chibenwa**
…fEmpty(x)

### CODE REVIEW

**Comment by mbaechler** [comment]
do you mean Refactor?

**Comment by chibenwa** [comment]
> do you mean Refactor?

I meant Reactor, but if you really want `REFACTOR` then that's also OK to me ^^

**Comment by mbaechler** [comment]
I don't think Reactor is an accepted keyword for "not opening a JIRA"

**Comment by chibenwa** [comment]
I remember @rouazana proposing it, but OK

**Comment by rouazana** [comment]
> I remember @rouazana proposing it, but OK

I don't remind it. Maybe I mistyped [Refactor] ;)

**Comment by chibenwa** [comment]
`JamesDeploymentValidationTest>DeploymentValidation.validateDeployment:81 » ConditionTimeout`

(test this please)

**Comment by trantienduchn** [comment]
```
[8a2126eae02fdd29375b30e04791553d279b7c4a] Step 3/7 : RUN apt-get install -y git
[8a2126eae02fdd29375b30e04791553d279b7c4a]  ---> Running in 0b5e3fb3d3da
[8a2126eae02fdd29375b30e04791553d279b7c4a] Reading package lists...
[8a2126eae02fdd29375b30e04791553d279b7c4a] Building dependency tree...
[8a2126eae02fdd29375b30e04791553d279b7c4a] Reading state information...
[8a2126eae02fdd29375b30e04791553d279b7c4a] Some packages could not be installed. This may mean that you have
[8a2126eae02fdd29375b30e04791553d279b7c4a] requested an impossible situation or if you are using the unstable
[8a2126eae02fdd29375b30e04791553d279b7c4a] distribution that some required packages have not yet been created
[8a2126eae02fdd29375b30e04791553d279b7c4a] or been moved out of Incoming.
[8a2126eae02fdd29375b30e04791553d279b7c4a] The following information may help to resolve the situation:
[8a2126eae02fdd29375b30e04791553d279b7c4a] 
[8a2126eae02fdd29375b30e04791553d279b7c4a] The following packages have unmet dependencies:
[8a2126eae02fdd29375b30e04791553d279b7c4a]  git : Depends: liberror-perl but it is not going to be installed
[8a2126eae02fdd29375b30e04791553d279b7c4a] [91mE: Unable to correct problems, you have held broken packages.
[8a2126eae02fdd29375b30e04791553d279b7c4a] [0mThe command '/bin/sh -c apt-get install -y git' returned a non-zero code: 100
[8a2126eae02fdd29375b30e04791553d279b7c4a] Running: Shell Script
[8a2126eae02fdd29375b30e04791553d279b7c4a] [966] Running shell script
```

**Comment by Arsnael** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
