### PR TITLE
JAMES-2774 remove duplicated test (rebase issue)

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by chibenwa** [comment]
`ManageableMailQueueContract.dequeueShouldDecreaseQueueSize:82 » AlreadyClosed ...`

test this please

**Comment by trantienduchn** [comment]
```
[e91ef6068fd113ca389a98ce304552bb51446e78] [ERROR] Errors: 
[e91ef6068fd113ca389a98ce304552bb51446e78] [ERROR]   MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:475 » Execution
```
test this please

**Comment by trantienduchn** [comment]
```
[e91ef6068fd113ca389a98ce304552bb51446e78] [ERROR] Errors: 
[e91ef6068fd113ca389a98ce304552bb51446e78] [ERROR]   FilterTest.messageShouldBeAppendedInSpecificMailboxWhenFromRuleMatches:749 » ConditionTimeout
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
