### PR TITLE
JAMES-3031 Fix ENV variable in Dockerfiles

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by tanandy** [comment]
Linked to https://github.com/linagora/james-project/issues/3069

**Comment by mbaechler** [comment]
Why don't we write three `ENV` entries ? I mean, this multiline syntax makes sense for things that allow to reduce the layers but I don't think that's the case for ENVs, right?

**Comment by aduprat** [comment]
According to the documentation, each ENV line is producing a new layer:
" Each ENV line creates a new intermediate layer, just like RUN commands. This means that even if you unset the environment variable in a future layer, it still persists in this layer and its value can’t be dumped. You can test this by creating a Dockerfile like the following, and then building it."

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by tanandy** [comment]
Yes thats also my point of view.  All the time try to reduce layer and even there is no layer (for example) , it will be at least intermediary images. We can merge it

**Comment by mbaechler** [comment]
Well, I read another piece of documentation that said the opposite:

> For example:
>
> ENV myName="John Doe" myDog=Rex\ The\ Dog \
>    myCat=fluffy
>
> and
> 
> ENV myName John Doe
> ENV myDog Rex The Dog
> ENV myCat fluffy
>
> will yield the same net results in the final image.

https://docs.docker.com/engine/reference/builder/#env

**Comment by tanandy** [comment]
yes this it not the best practice documentation. Ofc the result will be the same (we have 3 env vars) but the best syntax is single ENV instruction

**Comment by mbaechler** [comment]
Ok, I checked by myself because the documentation is ambiguous to me: the one-line-per-env generates a layer for each ENV. It's a 0 byte layer but yet it makes sense to avoid it.

So, I'm ok with this PR

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
