### PR TITLE
Reactor: Use handle instead of flatMap for synchronous transformations

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
CI restart

test this please

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal on project james-json: Could not resolve dependencies for project org.apache.james:james-json:jar:3.5.0-SNAPSHOT: Failed to collect dependencies at com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.9.9 -> com.google.guava:guava:jar:25.1-jre -> com.google.errorprone:error_prone_annotations:jar:2.1.3: Failed to read artifact descriptor for com.google.errorprone:error_prone_annotations:jar:2.1.3: Could not transfer artifact com.google.errorprone:error_prone_annotations:pom:2.1.3 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.pom.part (No such file or directory) -> [Help 1]
```
test this please

**Comment by Arsnael** [comment]
```
[5c7a368fe13e2c16541eb62dc0e5970ac687d69f] [INFO] There is 1 error reported by Checkstyle 8.23 with checkstyle.xml ruleset.
[5c7a368fe13e2c16541eb62dc0e5970ac687d69f] [ERROR] src/main/java/org/apache/james/blob/cassandra/CassandraBlobStore.java:[99,39] (whitespace) WhitespaceAround: WhitespaceAround: '->' is not preceded with whitespace.
```

**Comment by Arsnael** [comment]
```
[9fbad87cc44429b4ea60478fa49661568158ad62] [INFO] There are 4 errors reported by Checkstyle 8.23 with checkstyle.xml ruleset.
[9fbad87cc44429b4ea60478fa49661568158ad62] [ERROR] src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraModSeqProvider.java:[47,8] (imports) UnusedImports: Unused import - org.apache.james.util.FunctionalUtils.
[9fbad87cc44429b4ea60478fa49661568158ad62] [ERROR] src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraModSeqProvider.java:[197,38] (whitespace) WhitespaceAround: WhitespaceAround: '->' is not preceded with whitespace.
[9fbad87cc44429b4ea60478fa49661568158ad62] [ERROR] src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java:[243,30] (whitespace) WhitespaceAround: WhitespaceAround: '->' is not preceded with whitespace.
[9fbad87cc44429b4ea60478fa49661568158ad62] [ERROR] src/main/java/org/apache/james/mailbox/cassandra/mail/CassandraMessageMapper.java:[329,34] (whitespace) WhitespaceAround: WhitespaceAround: '->' is not preceded with whitespace.
```

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
```
[35fa6c02feada578ddc5262d88784a081d4efc55] [ERROR] Failed to execute goal on project james-server-util: Could not resolve dependencies for project org.apache.james:james-server-util:jar:3.5.0-SNAPSHOT: Failed to collect dependencies at com.github.steveash.guavate:guavate:jar:1.0.0 -> com.google.guava:guava:jar:25.1-jre -> org.codehaus.mojo:animal-sniffer-annotations:jar:1.14: Failed to read artifact descriptor for org.codehaus.mojo:animal-sniffer-annotations:jar:1.14: Could not transfer artifact org.codehaus.mojo:animal-sniffer-annotations:pom:1.14 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.pom.part (No such file or directory) -> [Help 1]
```
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
