### PR TITLE
[NO_REVIEW] Build trigerring PR - ElasticSearch health checks

### PR DESCRIPTION
**Pull request by chibenwa**
See https://github.com/linagora/james-project/pull/1812

The contributor used a branch name containing a `/` character, invalid for docker names and thus makes our CI fail.

This PR is intended to trigger the build on the latest commit of this PR with a valid branch name

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
common/elasticsearch/src/test/java/org/apache/james/backends/es/ElasticSearchHealthCheckConnectionTest.java:[41,130] cannot find symbol
[83aeda16f53d956056a905137fbfca977e8d2681]   symbol:   variable DEFAULT
[83aeda16f53d956056a905137fbfca977e8d2681]   location: interface org.apache.james.util.docker.RateLimiters
```

Hello @jreijn, seems you are using not up-to-dated codebase, could you rebase your branch on newest master?

**Comment by hoangdat** [comment]
Build triggered. sha1 is original commit.

**Comment by hoangdat** [comment]
Build triggered. sha1 is original commit.

**Comment by chibenwa** [comment]
Not needed anymore

**Pull request closed without merging**
