### PR TITLE
James 1644

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by aduprat** [comment]
:-1: 
The build is broken:
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /james-project/server/protocols/jmap/src/main/java/org/apache/james/jmap/model/GetMessagesResponse.java:[66,68] invalid method reference
  cannot find symbol
    symbol:   method getMessageId()
    location: class org.apache.james.jmap.model.Message

**Comment by mbaechler** [comment]
sorry, that should be fixed now.

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by aduprat** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by mbaechler** [comment]
will open a new one with squashed fixups

**Pull request closed without merging**
