### PR TITLE
Try cassandra 3 support

### PR DESCRIPTION
**Pull request by mbaechler**
follow up of https://github.com/linagora/james-project/pull/1072

### CODE REVIEW

**Comment by mbaechler** [comment]
```
[d89f1dfd92c0d0bc5330b4dc8e7ea058f5cd64ff] [ERROR]   CassandraSetMailboxesMethodTest>SetMailboxesMethodTest.setMailboxesShouldNotCreateWhenOverLimitName:155 1 expectation failed.
[d89f1dfd92c0d0bc5330b4dc8e7ea058f5cd64ff] Expected status code <200> doesn't match actual status code <400>.
[d89f1dfd92c0d0bc5330b4dc8e7ea058f5cd64ff] 
[d89f1dfd92c0d0bc5330b4dc8e7ea058f5cd64ff] [ERROR]   CassandraSetMailboxesMethodTest>SetMailboxesMethodTest.setMailboxesShouldNotUpdateMailboxWhenOverLimitName:187 1 expectation failed.
[d89f1dfd92c0d0bc5330b4dc8e7ea058f5cd64ff] Expected status code <200> doesn't match actual status code <400>.
[d89f1dfd92c0d0bc5330b4dc8e7ea058f5cd64ff] 
```

**Comment by aduprat** [comment]
Build triggered. sha1 is merged.

**Comment by aduprat** [comment]
Build started sha1 is merged.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
Build triggered. sha1 is merged.

**Comment by aduprat** [comment]
Build started sha1 is merged.

**Comment by aduprat** [comment]
Build triggered. sha1 is merged.

**Comment by aduprat** [comment]
Build started sha1 is merged.

**Comment by mbaechler** [comment]
it doesn't want to build, closing it and open a new one

**Pull request closed without merging**
