### PR TITLE
[CI_ONLY] Extract guice modules

### PR DESCRIPTION
**Pull request by Arsnael**
see https://github.com/apache/james-project/pull/260

### CODE REVIEW

**Comment by jeantil** [comment]
Unfortunately I can't access james.open-paas.org to see the error :/ can you tell me what failed ? I'm running mvn verify to try and reproducte the failure in the mean time

**Comment by chibenwa** [comment]
Likely a checkstyle issue regarding import orgering, let me have a look.

**Comment by chibenwa** [comment]
`[ERROR] Failed to execute goal on project james-json: Could not resolve dependencies for project org.apache.james:james-json:jar:3.6.0-SNAPSHOT: Could not transfer artifact com.github.fge:throwing-lambdas:jar:0.5.0 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/com/github/fge/throwing-lambdas/0.5.0/throwing-lambdas-0.5.0.jar.part (No such file or directory) -> [Help 1]`

Nope, you were just very unlucky, Jean!

test this please

**Comment by Arsnael** [comment]
:green_apple: :)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
