### PR TITLE
JAMES-2855 Upgrade spark, rabbitmq amqp, openjpa

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[98bd2cdc76af80b36a6e2d71db3caea4bf1b8bd4] [ERROR] COMPILATION ERROR : 
[98bd2cdc76af80b36a6e2d71db3caea4bf1b8bd4] [ERROR] /james-project/server/container/spring/src/main/java/org/apache/james/container/spring/bean/factory/mailrepositorystore/MailRepositoryStoreBeanFactory.java:[29,42] package org.apache.commons.collections.map does not exist
```

**Comment by trantienduchn** [comment]
```
[3440259c79f4928f089ee85e489003fcbbcf6c53] [INFO] Results:
[3440259c79f4928f089ee85e489003fcbbcf6c53] [INFO] 
[3440259c79f4928f089ee85e489003fcbbcf6c53] [ERROR] Errors: 
[3440259c79f4928f089ee85e489003fcbbcf6c53] [ERROR]   MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:474 » Execution
```

**Comment by trantienduchn** [comment]
test this please

**Comment by trantienduchn** [comment]
close, duplicated with #2586

**Pull request closed without merging**
