### PR TITLE
JAMES-2855 Upgrade rabbitmq client, openjpa

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
got team approval from #2578

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[95aa288b947608f88990ac67939d32dd08542916] + docker logs james-server-jpa-upgrade-rabbitclient-824f0224-4dec-448d-b2d4-bbe31cfe63e4
[95aa288b947608f88990ac67939d32dd08542916] Error occurred during initialization of VM
[95aa288b947608f88990ac67939d32dd08542916] agent library failed to init: instrument
[95aa288b947608f88990ac67939d32dd08542916] Error opening zip file or JAR manifest missing : /root/james-server-jpa-guice.lib/openjpa-3.0.0.jar
```

**Comment by chibenwa** [comment]
test this please

**Pull request closed without merging**
