### PR TITLE
JAMES-2533 remove uses of shaded classes and add a checkstyle rule

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by rouazana** [comment]
```
[2362d1d78b8e85afd8a82424c578414e1d336e7f] [ERROR] Failures: 
[2362d1d78b8e85afd8a82424c578414e1d336e7f] [ERROR]   MailboxManagerStressTest.testStressTest:128 expected:<200> but was:<95>
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
```
[2362d1d78b8e85afd8a82424c578414e1d336e7f] Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by chibenwa** [comment]
Force pushed to solve conflict

**Comment by chibenwa** [comment]
```
[4b9849271e23a2759a07087da898baca0f373c71] [ERROR]   SpamAssassinContract.imapCopiesToSpamMailboxShouldBeConsideredAsSpam:183 » ConditionTimeout
```

test this please

**Comment by aduprat** [comment]
merged

**Pull request closed without merging**
