### PR TITLE
JAMES-2813 Add serialization for Cassandra tasks' AdditionalDetails

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[a69a07f4438c3b01f2f8bb67209099e4402fc469] [ERROR] Failures: 
[a69a07f4438c3b01f2f8bb67209099e4402fc469] [ERROR]   TasksRoutesTest.listShouldListTaskWhenStatusFilter:137 1 expectation failed.
[a69a07f4438c3b01f2f8bb67209099e4402fc469] JSON path [0].type doesn't match.
```

**Comment by Arsnael** [comment]
```
[289c87593836af4ccdef82294dd752a8cc278343] [ERROR] postMappingsActionWithSolvedInconsistenciesQueryParamShouldHaveSuccessfulCompletedTask  Time elapsed: 0.718 s  <<< FAILURE!
[289c87593836af4ccdef82294dd752a8cc278343] java.lang.AssertionError: 
[289c87593836af4ccdef82294dd752a8cc278343] 1 expectation failed.
[289c87593836af4ccdef82294dd752a8cc278343] JSON path type doesn't match.
[289c87593836af4ccdef82294dd752a8cc278343] Expected: is <TaskType{typeName=cassandraMappingsSolveInconsistencies}>
[289c87593836af4ccdef82294dd752a8cc278343]   Actual: cassandraMappingsSolveInconsistencies
[289c87593836af4ccdef82294dd752a8cc278343] 
[289c87593836af4ccdef82294dd752a8cc278343] 	at org.apache.james.webadmin.routes.CassandraMappingsRoutesTest.postMappingsActionWithSolvedInconsistenciesQueryParamShouldHaveSuccessfulCompletedTask(CassandraMappingsRoutesTest.java:126)
[289c87593836af4ccdef82294dd752a8cc278343] 
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] Running org.apache.james.webadmin.service.CassandraMappingsSolveInconsistenciesTaskTest
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.58 s - in org.apache.james.webadmin.service.CassandraMappingsSolveInconsistenciesTaskTest
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] 
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] Results:
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] 
[289c87593836af4ccdef82294dd752a8cc278343] [ERROR] Failures: 
[289c87593836af4ccdef82294dd752a8cc278343] [ERROR]   CassandraMappingsRoutesTest.postMappingsActionWithSolvedInconsistenciesQueryParamShouldHaveSuccessfulCompletedTask:126 1 expectation failed.
[289c87593836af4ccdef82294dd752a8cc278343] JSON path type doesn't match.
[289c87593836af4ccdef82294dd752a8cc278343] Expected: is <TaskType{typeName=cassandraMappingsSolveInconsistencies}>
[289c87593836af4ccdef82294dd752a8cc278343]   Actual: cassandraMappingsSolveInconsistencies
```

**Comment by Arsnael** [comment]
```
[289c87593836af4ccdef82294dd752a8cc278343] [ERROR] postMappingsActionWithSolvedInconsistenciesQueryParamShouldHaveSuccessfulCompletedTask  Time elapsed: 0.718 s  <<< FAILURE!
[289c87593836af4ccdef82294dd752a8cc278343] java.lang.AssertionError: 
[289c87593836af4ccdef82294dd752a8cc278343] 1 expectation failed.
[289c87593836af4ccdef82294dd752a8cc278343] JSON path type doesn't match.
[289c87593836af4ccdef82294dd752a8cc278343] Expected: is <TaskType{typeName=cassandraMappingsSolveInconsistencies}>
[289c87593836af4ccdef82294dd752a8cc278343]   Actual: cassandraMappingsSolveInconsistencies
[289c87593836af4ccdef82294dd752a8cc278343] 
[289c87593836af4ccdef82294dd752a8cc278343] 	at org.apache.james.webadmin.routes.CassandraMappingsRoutesTest.postMappingsActionWithSolvedInconsistenciesQueryParamShouldHaveSuccessfulCompletedTask(CassandraMappingsRoutesTest.java:126)
[289c87593836af4ccdef82294dd752a8cc278343] 
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] Running org.apache.james.webadmin.service.CassandraMappingsSolveInconsistenciesTaskTest
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.58 s - in org.apache.james.webadmin.service.CassandraMappingsSolveInconsistenciesTaskTest
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] 
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] Results:
[289c87593836af4ccdef82294dd752a8cc278343] [INFO] 
[289c87593836af4ccdef82294dd752a8cc278343] [ERROR] Failures: 
[289c87593836af4ccdef82294dd752a8cc278343] [ERROR]   CassandraMappingsRoutesTest.postMappingsActionWithSolvedInconsistenciesQueryParamShouldHaveSuccessfulCompletedTask:126 1 expectation failed.
[289c87593836af4ccdef82294dd752a8cc278343] JSON path type doesn't match.
[289c87593836af4ccdef82294dd752a8cc278343] Expected: is <TaskType{typeName=cassandraMappingsSolveInconsistencies}>
[289c87593836af4ccdef82294dd752a8cc278343]   Actual: cassandraMappingsSolveInconsistencies
```
Seems to come from the no_review commit from #2663 (same issue)

**Comment by remk** [comment]
test this please

**Comment by Arsnael** [comment]
CI job was aborted...

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
