### PR TITLE
[Discussion] More functional style in JMAP

### PR DESCRIPTION
**Pull request by chibenwa**
The idea is to operate in Jmap responses builders and define operations that can be chained.

The result is something declarative like this:

```
return SetMessagePipeline.forOperations(
    when(mailboxIds.isEmpty())
        .then(invalidEmptyMailboxIds(create)),
    whenNot(allMailboxOwned(mailboxIds, mailboxSession))
        .then(invalidMailboxOwner(create)),
    when(isTargeting(create, mailboxSession, Role.OUTBOX))
        .then(outboxPipeline(create, mailboxSession)),
    when(isDraftSaving(create))
        .then(saveDraftPipeline(create, mailboxSession)),
    when(isTargeting(create, mailboxSession, Role.DRAFTS))
        .then(invalidDraftFlag(create)),
    endWith(invalidMailboxIds(create)))
.executeFirst(responseBuilder);
```

Please focus on design level comments.

Current implemented classes:
 - Vacation updates
 - Message creation
 - Mailbox Update

\* Destruction stuff + Get\* stuff are simple enough IMO to not need it.

Remains:
 - Message updates (straightforward IMO)
 - Mailbox creation. Seems trickier.

Limitations:
 - Exceptions. Pipeline throws MailboxException and MessageExceptions... Reasons : Avaoid sneakyThrow everywhere.
 - Pipeline class parameter hell might issue warnings...

Review from https://github.com/linagora/james-project/commit/983649a95b43ef26360bb110121d6ca0dfe15016

### CODE REVIEW

**Comment by mbaechler** [comment]
For what I understand, you try to avoid exception throwing everywhere.
It looks like the composition goal is targeting something that is not a weakness of basic java : I don't see anything you did that we can't do with simple methods.
That being said, concerning the exception avoiding, we already had this discussion a long time ago and we tried to use Either for that purpose.
It was not a good fit at this time because our tools were not good enough, but maybe things changed since then (we'll see that at the end of my comment).
About your solution, I would say : 
1. the precondition part is just the same as using Either (but the downside of your solution is that you mix assertions with protocol encoding)
2. using regular `map` of `flatmap` is more natural to java (8) devs than your new DSL while performing the same thing (the condition is more hidden but we could reuse just that part to define the function to ̀ give to `map`)
3. there's some _noise_ in you DSL because of the way it's designed (not sure we can do better this way), the trade-off is not ok IMO

I suggest if we want to go ahead this way to try vavr.io, they have : 
* Right biased Either
* Validation
* Try
* basic Pattern Matching

We could implement checks as returning Either (or even Validation), then apply methods with map and maybe a mini DSL to describe action steps and finally ends with a pattern matching block to generate the response. WDYT ?

Or we can just switch to Scala (they have right-biased Either since 2.12 https://alvinalexander.com/photos/scala-either-left-right-2.12-biased-map-flatmap ).

**Comment by chibenwa** [comment]
3. Yes, the generics makes it noisy... I don't think I can do better...

**Comment by chibenwa** [comment]
It's not just about exception throwing everywher (I could manage that without introducing the DSL at all, see https://github.com/linagora/james-project/pull/1187 )

It's more about centralizing the logic and making the flow explicit.

I believe that having object for checks, formating responses, and expressing conditions really makes it more explicit.

I have here the full behaviour of the class in the ~15 lines there. IMO other methods also benefits from being more stuctured.

Well, we can have a try with a more classic Either, I imagine.

**Comment by chibenwa** [comment]
Any objections for closing this?

**Pull request closed without merging**
