### PR TITLE
[Refactoring] JAMES-2993 JsonSerializationVerifier adoption

### PR DESCRIPTION
**Pull request by chibenwa**
Much more are to come.

### CODE REVIEW

**Comment by chibenwa** [comment]
I did contribute JsonSerializationVerifier usage for all tasks.

Next step: Event sourcing  serialization test should also rely on it...

**Comment by chibenwa** [comment]
```
[467f0a4ac0b5bb59de4bb8ced9089c1c6af8c605] [ERROR] Failures: 
[467f0a4ac0b5bb59de4bb8ced9089c1c6af8c605] [ERROR]   MappingsSourcesMigrationTaskSerializationTest.taskShouldBeSerializable:43 [Deserialization test] 
[467f0a4ac0b5bb59de4bb8ced9089c1c6af8c605] Expecting:
[467f0a4ac0b5bb59de4bb8ced9089c1c6af8c605]  <org.apache.james.rrt.cassandra.migration.MappingsSourcesMigration$MappingsSourcesMigrationTask@3b2c8bda>
[467f0a4ac0b5bb59de4bb8ced9089c1c6af8c605] to be equal to:
[467f0a4ac0b5bb59de4bb8ced9089c1c6af8c605]  <org.apache.james.rrt.cassandra.migration.MappingsSourcesMigration$MappingsSourcesMigrationTask@688d619c>
[467f0a4ac0b5bb59de4bb8ced9089c1c6af8c605] but was not.
```

**Comment by Arsnael** [comment]
```
[67b5e62c64c3e414dd39f43656c33e5e7dee3aca] [ERROR] Failures: 
[67b5e62c64c3e414dd39f43656c33e5e7dee3aca] [ERROR]   MappingsSourcesMigrationTaskSerializationTest.taskShouldBeSerializable:43 [Deserialization test] 
[67b5e62c64c3e414dd39f43656c33e5e7dee3aca] Expecting:
[67b5e62c64c3e414dd39f43656c33e5e7dee3aca]  <org.apache.james.rrt.cassandra.migration.MappingsSourcesMigration$MappingsSourcesMigrationTask@57b130f6>
[67b5e62c64c3e414dd39f43656c33e5e7dee3aca] to be equal to:
[67b5e62c64c3e414dd39f43656c33e5e7dee3aca]  <org.apache.james.rrt.cassandra.migration.MappingsSourcesMigration$MappingsSourcesMigrationTask@67e4928c>
[67b5e62c64c3e414dd39f43656c33e5e7dee3aca] but was not.
```

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/pull/3015

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/pull/3017

**Pull request closed without merging**
