### PR TITLE
[REFACTORING] Remove Junit4 usage from /protocols

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Review by LanKhuat — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[898c130ab31e9bafa7525f0c325d248e9e09e5d9] docker: Error response from daemon: No such container: git-publish-remove-junit4-protocols-b9c9f87a-cc63-4615-99b2-5bdaa5d65186.
```

test this please

MVN tests :green_apple:

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
