### PR TITLE
JAMES-3305 RabbitMQ EventBus deserialization error handling

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[9a726715c0ae648b042cdcda020b159b7bc0639e] [ERROR] Failures: 
[9a726715c0ae648b042cdcda020b159b7bc0639e] [ERROR]   RabbitMQEventBusTest$LifeCycleTest$MultiEventBus.multipleEventBusStopShouldDeleteAllKeyRegistrationsWorkQueue:794 
[9a726715c0ae648b042cdcda020b159b7bc0639e] Expecting empty but was:<[org.apache.james.backends.rabbitmq.RabbitMQManagementAPI$MessageQueue@4205d5d0]>
```

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
No I think there might be an issue here...

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
