### PR TITLE
JAMES-3035 Switch to apache/tika:1.22 image

### PR DESCRIPTION
**Pull request by chibenwa**
See https://github.com/LogicalSpark/docker-tikaserver/issues/21#issuecomment-581365043
for details

### CODE REVIEW

**Comment by chibenwa** [comment]
So unfair.

`JamesDeploymentValidationTest>DeploymentValidation.validateDeploymentWithMailsFromSmtp:95 » ConditionTimeout`

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
