### PR TITLE
[BUILD ONLY] JAMES-3174 Fix dependency analyze on java 11

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
`[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4] docker: Error response from daemon: No such container: git-publish-james-3174-dependency-analyze-java-11-3c979ac5-ff10-4a3a-a2b9-2ecd9c5d293f.`

test this please

**Comment by chibenwa** [comment]
```
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4] [ERROR]   MemoryTerminationSubscriberTest.dynamicListeningEventsShouldGetOnlyNewEvents 
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4] Expecting:
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4]   <[Cancelled(TaskAggregateId(TaskId{value=11a3d9c6-eb6d-48f2-b6e6-af46d3b7c064}),EventId(42),None)]>
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4] to contain exactly (and in same order):
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4]   <[Failed(TaskAggregateId(TaskId{value=916a19f9-41d4-4ec3-aa51-ee88396c76cc}),EventId(42),None,None,None),
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4]     Cancelled(TaskAggregateId(TaskId{value=11a3d9c6-eb6d-48f2-b6e6-af46d3b7c064}),EventId(42),None)]>
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4] but could not find the following elements:
[6f4d5c56bbc0a4bd37835066f1dd47b86a6deda4]   <[Failed(TaskAggregateId(TaskId{value=916a19f9-41d4-4ec3-aa51-ee88396c76cc}),EventId(42),None,None,None)]>
```

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
