### PR TITLE
[NO_REVIEW] Linshare docker test fast

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

With recent modifications running docker-compose on CI should be OK

**Comment by chibenwa** [comment]
```[6553eb9c96201a2b6a0e792e56d270955401b5e0] [INFO] Apache James Project 3.4.0-SNAPSHOT ................ SUCCESS [ 19.634 s]
[6553eb9c96201a2b6a0e792e56d270955401b5e0] [INFO] Apache JAMES third party ........................... SUCCESS [  0.689 s]
[6553eb9c96201a2b6a0e792e56d270955401b5e0] [INFO] apache-james-linshare 3.4.0-SNAPSHOT ............... SUCCESS [ 10.183 s]
[6553eb9c96201a2b6a0e792e56d270955401b5e0] [INFO] ------------------------------------------------------------------------
[6553eb9c96201a2b6a0e792e56d270955401b5e0] [INFO] BUILD SUCCESS
```

**Comment by Arsnael** [comment]
I will reopen it. The CI modification seems making the rest of the tests unstable. Will work on something else.

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`[6553eb9c96201a2b6a0e792e56d270955401b5e0] .FileNotFoundError: [Errno 2] No such file or directory: '/home/jenkins/build/workspace/420/dockerfiles/third-party/linshare/target/test-classes/docker-compose.yml'`

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/pull/2308

**Pull request closed without merging**
