### PR TITLE
JAMES-2156 issue implementation

### PR DESCRIPTION
**Pull request by sebast26**
This is rebase of PR #1077 as in issue #999. Unfortunately there are some problems with tests. If you don't mind I will work on correcting the issues. Most of the work is done by @P3trur0.

### CODE REVIEW

**Comment by chibenwa** [comment]
Hi @sebast26 

Thanks for volunteering for continuing this work.

There are still a couple of issues with the proposed code...

```
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR] Errors: 
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAAttachmentMapperTest>AttachmentMapperTest.getAttachmentShouldReturnTheAttachmentWhenReferenced:80 » AttachmentNotFound
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAAttachmentMapperTest>AttachmentMapperTest.getAttachmentShouldReturnTheAttachmentsWhenMultipleStored:101 » AttachmentNotFound
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAMemoryMessageWithAttachmentMapperTest>MessageWithAttachmentMapperTest.messagesCanBeRetrievedInMailboxWithRangeTypeOne:173->MessageWithAttachmentMapperTest.saveMessages:196 » InvalidState
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAMemoryMessageWithAttachmentMapperTest>MessageWithAttachmentMapperTest.messagesRetrievedUsingFetchTypeBodyShouldHaveAttachmentsLoadedWhenOneAttachment:139->MessageWithAttachmentMapperTest.saveMessages:196 » InvalidState
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAMemoryMessageWithAttachmentMapperTest>MessageWithAttachmentMapperTest.messagesRetrievedUsingFetchTypeBodyShouldHaveBodyDataLoaded:181->MessageWithAttachmentMapperTest.saveMessages:196 » InvalidState
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAMemoryMessageWithAttachmentMapperTest>MessageWithAttachmentMapperTest.messagesRetrievedUsingFetchTypeFullShouldHaveAttachmentsEmptyWhenNoAttachment:165->MessageWithAttachmentMapperTest.saveMessages:196 » InvalidState
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAMemoryMessageWithAttachmentMapperTest>MessageWithAttachmentMapperTest.messagesRetrievedUsingFetchTypeFullShouldHaveAttachmentsLoadedWhenOneAttachment:123->MessageWithAttachmentMapperTest.saveMessages:196 » InvalidState
[e27bd30fdc6011f56c0b07203e4b26f2855ffa5d] [ERROR]   JPAMemoryMessageWithAttachmentMapperTest>MessageWithAttachmentMapperTest.messagesRetrievedUsingFetchTypeFullShouldHaveAttachmentsLoadedWhenTwoAttachments:131->MessageWithAttachmentMapperTest.saveMessages:196 » InvalidState
```

Could you have a look?

Cheers,

**Comment by sebast26** [comment]
Sure, that was my goal in the first place. ;P

**Comment by blackheaven** [comment]
Hi @sebast26  

Have you had some time to have a look at the test failure? Do you need some help?

Regards.

**Comment by hoangdat** [comment]
Build triggered. sha1 is original commit.

**Comment by hoangdat** [comment]
Build triggered. sha1 is original commit.

**Comment by ReturnHttp402** [comment]
Hi, I'm looking at this task, first start from scratch and later find this pr, while doing unit testing I found there's an issue with the `MessageWithAttachmentMapperTest$$saveMessages()`method, it deeply calls `JPAUidProvider$$lockedNextUid()` method, however when running uts, the `JPAMailbox m = manager.find(JPAMailbox.class, mailboxId.getRawId());`will return null when running ut and after add optional as 
```
JPAMailbox m = Optional.ofNullable(manager.find(JPAMailbox.class, mailboxId.getRawId()))
                    .orElse(new JPAMailbox(mailbox));
```
I will get persistence exception saying the `MAILBOX_ID` cannot accept null value, when I set the mailbox_id obtained from last step `JPAId mailboxId = (JPAId) mailbox.getMailboxId();` then I will get optimistic exception with this message `Attempted to attach deleted instance type "class org.apache.james.mailbox.jpa.mail.model.JPAMailbox" with oid "774084263".  If the instance is new, the version field should be left to its default value.`, I try to change the id generated strategy but the exception still exists. Dose somebody have any idea on this?

**Comment by ReturnHttp402** [comment]
BTW, there's a [jira ticket](https://issues.apache.org/jira/browse/JAMES-1412) which may have some relevance with this, the issue happens when null pointer exception thrown and in finally block to close entity manage but the transaction is still active.

**Comment by trantienduchn** [comment]
Hello @ReturnHttp402, are you testing current `MessageWithAttachmentMapperTest` at master or the `JPAMemoryMessageWithAttachmentMapperTest` in this branch? Is the problem is:
```
JPAMailbox m = manager.find(JPAMailbox.class, mailboxId.getRawId());
```
always returns null?

**Comment by ReturnHttp402** [comment]
> Hello @ReturnHttp402, are you testing current `MessageWithAttachmentMapperTest` at master? or the `JPAMemoryMessageWithAttachmentMapperTest` in this branch? Is the problem is:
> 
> ```
> JPAMailbox m = manager.find(JPAMailbox.class, mailboxId.getRawId());
> ```
> always returns null?

No I'm testing in my own local branch, but I look through the code, my code is very similar with this branch. the find `JPAMailbox` always returns null.

**Comment by trantienduchn** [comment]
I don't have much experiment with this component, could you share to me your branch so I can run that test on my local machine and find out what is wrong?

**Comment by ReturnHttp402** [comment]
> I don't have much experiment with this component, could you share to me your branch so I can run that test on my local machine and find out what is wrong?

I have uploaded my code and you can find in this [pull request](https://github.com/ReturnHttp402/james-project/pull/1)

**Pull request closed without merging**
