### PR TITLE
JAMES-2551 Bind RabbitMQ to cassandra products

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
This allow rabbitmq can be fully registered in guice (RabbitMQMailQueue, MailQueueView...).
TODO:
- replace `ActiveMQMailQueueModule` by `RabbitMQModule` in `CassandraJamesServerMain`
- in tests that used james with `ActiveMQMailQueueModule` before, now will use `RabbitMQModule`, thus, they need `RabbitMQDocker` for each test setup. But most of tests are using Junit 4 Rules. Have to switch them(old tests) to junit 5 in order to register `RabbitMQDocker` inside extensions or reuse the `ReusableRabbitMQExtension` (this one this big, may need separated PR)
- create new product `cassandra-rabbitmq` in guice/run

**Comment by trantienduchn** [comment]
Starting to replace `ActiveMQModule` by `RabbitMQModule` in cassandra james server. This action requires each test which run cassandra james server also need to start docker rabbitmq. That would take much effort to refactor tests and making coupling problem between tests and rabbit docker extension.

**Comment by trantienduchn** [comment]
tests show alot of logs:
```
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no queue 'JamesMailQueue-workqueue-outgoing' in vhost '/', class-id=60, method-id=70)
	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:253)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:336)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:277)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:138)
	at com.rabbitmq.client.impl.ChannelN.basicGet(ChannelN.java:1139)
	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicGet(AutorecoveringChannel.java:431)
	at org.apache.james.queue.rabbitmq.RabbitClient.lambda$poll$4(RabbitClient.java:86)
	at org.apache.james.backend.rabbitmq.RabbitChannelPool.execute(RabbitChannelPool.java:86)
	at org.apache.james.queue.rabbitmq.RabbitClient.poll(RabbitClient.java:87)
	at org.apache.james.queue.rabbitmq.Dequeuer.singleChannelRead(Dequeuer.java:135)
	at com.nurkiewicz.asyncretry.AsyncRetryExecutor.lambda$getWithRetry$1(AsyncRetryExecutor.java:62)
	at com.nurkiewicz.asyncretry.SyncRetryJob.run(SyncRetryJob.java:23)
```

and I really easy to get out of memory while running tests on my machine. The new `DockerRabbitMQTestExtension` might by the reason. But I'm not able to detect it for now.

**Comment by trantienduchn** [comment]
```
[e2f1b072de5940f0f1c11c06617d177310b09c31] 	at org.apache.james.backend.rabbitmq.RabbitMQClusterTest$ClusterNodesFailure.setup(RabbitMQClusterTest.java:165)
[e2f1b072de5940f0f1c11c06617d177310b09c31] Caused by: com.rabbitmq.client.ShutdownSignalException: connection error
[e2f1b072de5940f0f1c11c06617d177310b09c31] 	at org.apache.james.backend.rabbitmq.RabbitMQClusterTest$ClusterNodesFailure.setup(RabbitMQClusterTest.java:165)
[e2f1b072de5940f0f1c11c06617d177310b09c31] Caused by: java.net.SocketException: Connection reset
```
test this please

**Comment by aduprat** [comment]
#1764

**Pull request closed without merging**
