### PR TITLE
Use an existing docker rule

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by mbaechler** [comment]
After some tests, the first test can't work on macos because the container is on a private (unreachable) network, only exposed ports are reachable. We should delete this test.

The second test should not use "localhost" as host because docker can be remote. We should use `DockerClientFactory.instance().dockerHostIpAddress()` but it doesn't work with unix socket access.

To finish this ticket you should propose a fix to `dockerHostIpAddress()` then.

**Comment by aduprat** [comment]
Then, i propose this fix:
https://github.com/aduprat/testcontainers-java/commit/fa0500dc5e43fe648bf15c23107e4cabfeb9779a

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
Update testcontainers library to 1.0.2

**Pull request merged**
