### PR TITLE
try to let the caller of Event Delivery decide where and how to execu…

### PR DESCRIPTION
**Pull request by mbaechler**
…te the delivery

### CODE REVIEW

**Comment by mbaechler** [comment]
```

[6eb1d1f193409a2deec512ed178dd8968c70e815] [ERROR] Errors: 
[6eb1d1f193409a2deec512ed178dd8968c70e815] [ERROR]   RabbitMQEventBusTest$ConcurrentTest.concurrentDispatchShouldDeliverAllEventsToListenersWithSingleEventBus » ShutdownSignal
```
I will try locally

**Comment by mbaechler** [comment]
Works on my machine (tm)

test this please

**Comment by rouazana** [comment]
please don't forget to add a JIRA

**Comment by mbaechler** [comment]
```
[6eb1d1f193409a2deec512ed178dd8968c70e815] [ERROR] Errors: 
[6eb1d1f193409a2deec512ed178dd8968c70e815] [ERROR]   MemorySpamAssassinContractTest.expungingSpamMessageShouldNotImpactSpamAssassinState » ConditionTimeout
```

works for me

test this please

**Comment by chibenwa** [comment]
`DefaultMailboxesProvisioningFilterTest.createMailboxesIfNeededShouldNotGenerateExceptionsInConcurrentEnvironment:94 » Execution`

test this please

**Comment by chibenwa** [comment]
I opened https://issues.apache.org/jira/browse/JAMES-2971

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
