### PR TITLE
JAMES-3192 Upgrade Apache configuration to 2.7

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
test this please

**Comment by chibenwa** [comment]
```
[0c912abadc35078e2273f2b06deeca626c0a2b15] [ERROR] Errors: 
[0c912abadc35078e2273f2b06deeca626c0a2b15] [ERROR]   CassandraConfigurationReadingTest.provideCassandraConfigurationShouldReturnDefaultOnEmptyConfigurationFile:36 » NoClassDefFound
[0c912abadc35078e2273f2b06deeca626c0a2b15] [ERROR]   CassandraConfigurationReadingTest.provideCassandraConfigurationShouldReturnRightConfigurationFile:45 » NoClassDefFound
[0c912abadc35078e2273f2b06deeca626c0a2b15] [ERROR]   QueryLoggerConfigurationTest.fromShouldNotThrowWithMinimalConfigAboutAConstantThresholdSlowQueryLogger:32 » NoClassDefFound
[0c912abadc35078e2273f2b06deeca626c0a2b15] [ERROR]   QueryLoggerConfigurationTest.fromShouldNotThrowWithPersonalizedConfigAboutPercentileSlowQuerryLogger:41 » NoSuchMethod
[0c912abadc35078e2273f2b06deeca626c0a2b15] [ERROR]   QueryLoggerConfigurationTest.fromShouldThrowIfConfigAboutLoggerIsInvalid:54 » NoClassDefFound
```

**Comment by chibenwa** [comment]
Merged

**Comment by chibenwa** [comment]
I will backport this to upcoming 3.5.0

**Pull request closed without merging**
