### PR TITLE
Mailbox session should not be needed to interact with components of a mailbox

### PR DESCRIPTION
**Pull request by chibenwa**
It should only be required at the API level.

Note that tests should still be corrected and that I did not check compilation

### CODE REVIEW

**Comment by chibenwa** [comment]
This breaks JPA... :-(

**Comment by trantienduchn** [comment]
> This breaks JPA... :-(

where does it break? Any workaround?

**Comment by chibenwa** [comment]
> where does it break? 

MailboxSession is kept to isolate transactions.

> Any workaround?

I did not find anything so far. How depressing...

**Comment by chibenwa** [comment]
I don't intend to push this try further

**Pull request closed without merging**
