### PR TITLE
JAMES-3434 Allow the use of aliases for EmailSubmission/set create

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[e80ddf0abf8452d9764e7d7d9fd77492199eafbb] [ERROR] src/main/java/org/apache/james/jmap/rfc8621/RFC8621MethodsModule.java:[28] (imports) ImportOrder: Wrong order for 'org.apache.commons.configuration2.Configuration' import.
```

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
same build issue as #3944 3944

**Comment by Arsnael** [comment]
Still same issue

**Review by LanKhuat — APPROVED** [review]

**Comment by Arsnael** [comment]
```
[bb25893d59f7fe0348a8b5b007584c65d802101a] docker: Error response from daemon: No such container: git-publish-james-3434-alias-596e0fd7-20f5-42a7-a619-bad1203d2672.
```
tssss.... tests are :green_apple: though

test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
