### PR TITLE
JAMES-3024 Add parameterized tests to testing base

### PR DESCRIPTION
**Pull request by remk**
Allow to use parameterized tests in all modules dependent on testing-base

without having to worry about importing the dependency.

This fix the following issue :

if a parameterized test is defined in an interface in a module `A`, a test class implementing this contract in a module `B` will run the tests successfully without finding and testing  the parameterized tests defined in `A` if the module `B` doesn't have the dependency to `junit-jupiter-params`.

### CODE REVIEW

**Comment by trantienduchn** [comment]
no more comment that others

**Comment by mbaechler** [comment]
> Please remove the dependency from all the modules that now no longer require it...

good catch

**Comment by trantienduchn** [comment]
```
ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR] The build could not read 4 projects -> [Help 1]
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   The project org.apache.james:blob-api:3.5.0-SNAPSHOT (/james-project/server/blob/blob-api/pom.xml) has 1 error
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]     'dependencies.dependency.version' for org.junit.jupiter:junit-jupiter-params:jar is missing. @ line 67, column 21
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   The project org.apache.james:blob-cassandra:3.5.0-SNAPSHOT (/james-project/server/blob/blob-cassandra/pom.xml) has 1 error
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]     'dependencies.dependency.version' for org.junit.jupiter:junit-jupiter-params:jar is missing. @ line 74, column 21
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   The project org.apache.james:blob-memory:3.5.0-SNAPSHOT (/james-project/server/blob/blob-memory/pom.xml) has 1 error
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]     'dependencies.dependency.version' for org.junit.jupiter:junit-jupiter-params:jar is missing. @ line 59, column 21
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]   The project org.apache.james:blob-objectstorage-guice:3.5.0-SNAPSHOT (/james-project/server/container/guice/blob-objectstorage-guice/pom.xml) has 1 error
[ee53eb25a068b81f00a5051f31dd9a105be1a30f] [ERROR]     'dependencies.dependency.version' for org.junit.jupiter:junit-jupiter-params:jar is missing. @ line 73, column 21
```

**Comment by Arsnael** [comment]
Was :green_apple: before CI restart

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
