### PR TITLE
JAMES-2236 Ignore headers with dots for ElasticSearch

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[ec5bfaa1779943c486b31d8da2c9d96be4ddb97d] [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 21.138 s - in org.apache.james.jmap.cassandra.CassandraUserProvisionningConcurrencyTest
``` 

test this please

**Comment by chibenwa** [comment]
I will also investigate this "concurrent failure"

**Comment by chibenwa** [comment]
test this please

**Comment by strokyl** [comment]
> Why should we ignore them ? Why not encoding it in a way that actually works ?

I almost leave the same comment than you. But actually what we are currently doing is just really bad anyway. We should just define a subset of header we need to search through and ignore others

**Comment by rouazana** [comment]
I choose to ignore them because this is a very rare failure (headers with dots are really not common, even if valid). If you want I can change this by replacing dots by an other character (underscore?)

**Comment by strokyl** [comment]
> I choose to ignore them because this is a very rare failure (headers with dots are really not common, even if valid). If you want I can change this by replacing dots by an other character (underscore?)

Yes but what about header with underscore then. If we can avoid this uscaping we should do it because this is not going to be easy to do I thinkg

**Comment by rouazana** [comment]
> Yes but what about header with underscore then. If we can avoid this uscaping we should do it because this is not going to be easy to do I thinkg

In the worst case you'll have duplicate, which is not so terrible for headers I guess.

**Comment by strokyl** [comment]
> In the worst case you'll have duplicate, which is not so terrible for headers I guess.

No if we want we could do better: "." -> "_.", "_" -> "__"

**Comment by rouazana** [comment]
I don't find it better, because it means if someone search for an header with (real) underscore in, you need to take care of changing them to double.

**Comment by rouazana** [comment]
Issue created for the indexed headers with dots https://issues.apache.org/jira/browse/JAMES-2241

**Pull request merged**
