### PR TITLE
JAMES-3431 Document DSN setup for the Distributed Server

### PR DESCRIPTION
**Pull request by chibenwa**
- [x] **TODO** manual test this configuration on DEV

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
waiting merge with one approval, draft state and a TODO likely not done yet in the description... Why?

**Comment by chibenwa** [comment]
> waiting merge with one approval, draft state and a TODO likely not done yet in the description... Why?

Mistake sorry.

**Review by remk — APPROVED** [review]

**Comment by chibenwa** [comment]
https://user-images.githubusercontent.com/6928740/105961023-9083cf00-60b0-11eb-833c-950937f55565.mp4

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
