### PR TITLE
JAMES-3046 Stop WebAdmin server between retries

### PR DESCRIPTION
**Pull request by chibenwa**
Not doing so is prone to reusing the same port...

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by LanKhuat — APPROVED** [review]

**Comment by Arsnael** [comment]
```
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR] Errors: 
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   WebAdminServerTest.aSecondRouteWithSameEndpointShouldNotOverridePreviouslyDefinedRoutes:57 » IllegalState
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   WebAdminServerTest.aSecondRouteWithSameEndpointShouldNotOverridePreviouslyDefinedRoutesWhenPublic:80 » IllegalState
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   WebAdminServerTest.getPortShouldReturnPortWhenConfigured:43 » IllegalState Thi...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   WebAdminServerTest.privateRoutesShouldBePrioritizedOverPublicRoutes:103 » IllegalState
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
[680eb86a7eba13fcb6159ff3123b7c978670f46b] [ERROR]   TasksRoutesTest.setUp:66 » IllegalState This must be done before route mapping...
```
Likely related

**Comment by chibenwa** [comment]
test this please

`DiscardProtocolTest.testRecord:84 »  Timed out wait for be notified that read ...`

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
```
[664cdbd1a2b03830d84cfe0ca1538e98d1ba5b22] [ERROR] Failures: 
[664cdbd1a2b03830d84cfe0ca1538e98d1ba5b22] [ERROR]   CassandraMailboxMapperTest$ConsistencyTest.createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox:617 Multiple Failures (1 failure)
[664cdbd1a2b03830d84cfe0ca1538e98d1ba5b22] 	
[664cdbd1a2b03830d84cfe0ca1538e98d1ba5b22] Expected size:<1> but was:<2> in:
[664cdbd1a2b03830d84cfe0ca1538e98d1ba5b22] <[Mailbox{id=5693a110-49a1-11eb-8b98-7d502ae81255, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=name},
[664cdbd1a2b03830d84cfe0ca1538e98d1ba5b22]     Mailbox{id=67dd70e0-49a1-11eb-8b98-7d502ae81255, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=INBOX}]>
[664cdbd1a2b03830d84cfe0ca1538e98d1ba5b22] at CassandraMailboxMapperTest$ConsistencyTest.lambda$createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox$34(CassandraMailboxMapperTest$ConsistencyTest.java:628)
```
flaky? test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
