### PR TITLE
James 1664 : getMessages shold work with OpenPaaS inbox

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by aduprat** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by aduprat** [comment]
s/shold/should in the commit message

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Comment by fvn-linagora** [comment]
:+1:

**Comment by aduprat** [comment]
merged

**Pull request closed without merging**
