### PR TITLE
JAMES-1700 Don't fail in account creation if user already exists

### PR DESCRIPTION
**Pull request by rouazana**
Using thread-weaver to really test racing condition.
Manual mock seems to be necessary as Mockito and thread-weaver seem to conflict.

### CODE REVIEW

**Comment by aduprat** [comment]
:+1:

**Comment by fvn-linagora** [comment]
Mixing regular unit test fixtures and threaded load testing fixtures looks confusing because they are actually different concerns.
Could you move concurrency-related testing into a separate file/class please ?

**Comment by rouazana** [comment]
I thought about that, and I found interesting to be able to call every test for this class from the original source file.
I found also interesting to prove that you can mix thread testing and unit tests (note that it is not load testing).

But I'm ok with you, mixing the two styles is a little confusing, so I can split if needed.

**Comment by rouazana** [comment]
Fixed up

**Comment by fvn-linagora** [comment]
:+1:

**Comment by rouazana** [comment]
test this please

**Pull request merged**
