### PR TITLE
JAMES-2081 ImportEml CLI  command

### PR DESCRIPTION
**Pull request by chibenwa**
Unit tests and follow up for https://github.com/apache/james-project/pull/69

I will add a documentation commit in the beginning of the afternoon... (http://james.apache.org/server/manage-cli.html for new commands details)

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[Building Java 8 james-2081-4ccf856a-127e-4d00-95ca-a1e418976b2e] Failed tests: 
[Building Java 8 james-2081-4ccf856a-127e-4d00-95ca-a1e418976b2e]   CassandraGetMessageListMethodTest>GetMessageListMethodTest.getMessageListShouldWorkWhenCollapseThreadIsFalse:903 1 expectation failed.
[Building Java 8 james-2081-4ccf856a-127e-4d00-95ca-a1e418976b2e] Expected status code <200> doesn't match actual status code <401>.
```

test this please

**Comment by ilkerceng** [comment]
in apache-james-backends-cassandra, the org.apache.james.backends.cassandra.utils.PaggingTest gives me this error :
com.datastax.driver.core.exceptions.syntaxerror no viable alternative at input ı

**Comment by chibenwa** [comment]
This is not expected. What is your envirnmet? (OS and java version?)

Could you please share the full stacktrace @ilkerceng ?

**Comment by ilkerceng** [comment]
i work on Windows 10 with jdk1.8.0_101
stacktrace when running org.apache.james.backends.cassandra.utils.PaggingTest in apache-james-backends-cassandra-utils project

com.datastax.driver.core.exceptions.SyntaxError: line 4:16 no viable alternative at character 'ı'
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at org.apache.james.backends.cassandra.init.CassandraTableManager.lambda$ensureAllTables$0(CassandraTableManager.java:38)
	at java.lang.Iterable.forEach(Unknown Source)
	at org.apache.james.backends.cassandra.init.CassandraTableManager.ensureAllTables(CassandraTableManager.java:38)
	at org.apache.james.backends.cassandra.init.SessionWithInitializedTablesFactory.createSession(SessionWithInitializedTablesFactory.java:40)
	at org.apache.james.backends.cassandra.CassandraCluster.tryInitializeSession(CassandraCluster.java:91)
	at org.apache.james.backends.cassandra.utils.FunctionRunnerWithRetry.lambda$executeAndRetrieveObject$2(FunctionRunnerWithRetry.java:55)
	at java.util.stream.IntPipeline$4$1.accept(Unknown Source)
	at java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.IntPipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.apache.james.backends.cassandra.utils.FunctionRunnerWithRetry.executeAndRetrieveObject(FunctionRunnerWithRetry.java:57)
	at org.apache.james.backends.cassandra.CassandraCluster.<init>(CassandraCluster.java:64)
	at org.apache.james.backends.cassandra.CassandraCluster.create(CassandraCluster.java:53)
	at org.apache.james.backends.cassandra.utils.PaggingTest.setUp(PaggingTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 4:16 no viable alternative at character 'ı'
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:144)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:179)
	at com.datastax.driver.core.RequestHandler.access$2400(RequestHandler.java:49)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:799)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:633)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1075)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:998)
	at com.datastax.shaded.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at com.datastax.shaded.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at com.datastax.shaded.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at com.datastax.shaded.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at com.datastax.shaded.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at com.datastax.shaded.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at com.datastax.shaded.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at com.datastax.shaded.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at com.datastax.shaded.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at com.datastax.shaded.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

java.lang.NullPointerException
	at org.apache.james.backends.cassandra.utils.PaggingTest.tearDown(PaggingTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by chibenwa** [comment]
Hmmm looks like a locale issue. Turkish and it's lowercase "i" without dot is known to be a problem.

Though it might be a Cassandra problem... I did not succeed to reproduce. Please try switching locale to English, and see if it solve. It needs more serious investigation.

Thanks for sharing this.

**Comment by ilkerceng** [comment]
my workspace path includes special turkish character which is 'ı', i will test it with changing 'ı' to 'i'

**Comment by chibenwa** [comment]
Could you share it here?

**Comment by ilkerceng** [comment]
i have downloaded new eclipse and will try it with not including any special trukish character in the path. if it is not the solution, i will switch the locale to English.

**Comment by ilkerceng** [comment]
you are right mr. @chibenwa . the causing error is window display language, i changed it to English(United Kingdom). But beside it, i changed "country or region" section also to United Kingdom also. The problem is resolved.

**Comment by chibenwa** [comment]
We need to investigate it. Is it a problem specific to Windows?

In a perfect world, we should be locale independent.

**Comment by ilkerceng** [comment]
so, i think i should find a pc running any linux distribution set to turkish language locale?

**Comment by ilkerceng** [comment]
i tested it with ubuntu 16.04 linux distribution in turkish language and i got the same error. here is the screen shot.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Tellier Benoit <notifications@github.com> </div><div>Date:11/07/2017  08:01  (GMT+02:00) </div><div>To: linagora/james-project <james-project@noreply.github.com> </div><div>Cc: ilker yıldırım <ilker.ceng@gmail.com>,Mention <mention@noreply.github.com> </div><div>Subject: Re: [linagora/james-project] JAMES-2081 ImportEml CLI command (#889) </div><div>
</div>We need to investigate it. Is it a problem specific to Windows?

In a perfect world, we should be locale independent.

**Pull request merged**
