### PR TITLE
James 1691 move mail from outbox to send after sending

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by mbaechler** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by mbaechler** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
test this please

**Pull request merged**
