### PR TITLE
JAMES-3155 Limit the number of flags updated at the same time

### PR DESCRIPTION
**Pull request by chibenwa**
Large flags operations caused expensive updates to be performed "at once"
by ElasticSearch.

We should rather limit the number of flags being modified at once, and perform then "by batch".

### CODE REVIEW

**Comment by rouazana** [comment]
needs some load testing, no?

**Comment by chibenwa** [comment]
On IMAP ?

**Comment by chibenwa** [comment]
I would expect more stability at the cost of more latencies for this very specific listener.

We prevent a starvation problem here more than a performance issue to be honnest.

**Comment by Arsnael** [comment]
Merged

**Comment by rouazana** [comment]
> We prevent a starvation problem here more than a performance issue to be honnest.

So we introduce a risk to decrease performance, no?

**Comment by chibenwa** [comment]
> So we introduce a risk to decrease performance, no?

Of a process executed asynchronously? We are likely more interested by throughput (and not overwhelming the DB) than the actual latencies for very large flags changes requests.

**Pull request closed without merging**
