### PR TITLE
Faster site generation

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by blackheaven** [comment]
No JIRA number ?

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
deployment tests

test this this

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by Arsnael** [comment]
Tests are :green_apple: 

test this please

**Comment by blackheaven** [comment]
test this please

**Comment by remk** [comment]
> No JIRA number?
:)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
