### PR TITLE
JAMES-3377 Email/query implement hasAttachment FilterCondition

### PR DESCRIPTION
**Pull request by chibenwa**
Also add a test for criterion composition

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

(Deployment tests)

**Review by LanKhuat — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

(Deployment tests)

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
But needs a rebase

**Comment by Arsnael** [comment]
Deployment tests failed

test this please

**Comment by chibenwa** [comment]
Thanks ;-)

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Deployment tests

Can be considered :green_apple:

test this please anyway

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
