### PR TITLE
 JAMES-2590 Change default shards & replica ES configuration values 

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[027239359f95d5b96d0f9261d70b53546a4e81c2] [ERROR]   AbstractMessageSearchIndexTest.sortOnFromShouldWork:1054 
[027239359f95d5b96d0f9261d70b53546a4e81c2] Actual and expected have the same elements but not in the same order, at index 0 actual element was:
[027239359f95d5b96d0f9261d70b53546a4e81c2]   <MessageUid{uid=3}>
[027239359f95d5b96d0f9261d70b53546a4e81c2] whereas expected element was:
[027239359f95d5b96d0f9261d70b53546a4e81c2]   <MessageUid{uid=2}>
[027239359f95d5b96d0f9261d70b53546a4e81c2] 
[027239359f95d5b96d0f9261d70b53546a4e81c2] [ERROR]   AbstractMessageSearchIndexTest.sortOnToShouldWork:1068 
[027239359f95d5b96d0f9261d70b53546a4e81c2] Actual and expected have the same elements but not in the same order, at index 1 actual element was:
[027239359f95d5b96d0f9261d70b53546a4e81c2]   <MessageUid{uid=3}>
[027239359f95d5b96d0f9261d70b53546a4e81c2] whereas expected element was:
[027239359f95d5b96d0f9261d70b53546a4e81c2]   <MessageUid{uid=2}>
[027239359f95d5b96d0f9261d70b53546a4e81c2] 
```

**Comment by chibenwa** [comment]
I am working on this

**Comment by trantienduchn** [comment]
```
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] [INFO] Results:
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] [INFO] 
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] [ERROR] Failures: 
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] [ERROR]   LuceneMessageSearchIndexTest>AbstractMessageSearchIndexTest.sortOnToShouldWork:1068 
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] Actual and expected have the same elements but not in the same order, at index 1 actual element was:
[ae6631c3197a6ce49f5b3adae666bdf02c688f49]   <MessageUid{uid=2}>
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] whereas expected element was:
[ae6631c3197a6ce49f5b3adae666bdf02c688f49]   <MessageUid{uid=3}>
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] 
[ae6631c3197a6ce49f5b3adae666bdf02c688f49] [INFO] 
```
Guys, still fails

**Comment by aduprat** [comment]
```
[ERROR]   LuceneMessageSearchIndexTest>AbstractMessageSearchIndexTest.sortOnToShouldWork:1068 
Actual and expected have the same elements but not in the same order, at index 1 actual element was:
  <MessageUid{uid=2}>
whereas expected element was:
  <MessageUid{uid=3}>
```

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Pull request closed without merging**
