### PR TITLE
James 2415 : remove a lot of unused dependencies from jpa-smtp

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[7288953e2b67938707114b098a4d54caf9c34999] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project cassandra-jmap-integration-testing: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[7288953e2b67938707114b098a4d54caf9c34999] [ERROR] Command was /bin/sh -c cd /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms512m -Xmx1024m -jar /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/target/surefire/surefirebooter6871411987723452302.jar /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/target/surefire/surefire2655046397328426373tmp /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/target/surefire/surefire_8577616935462868813183tmp
```

test this please

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

```
[7288953e2b67938707114b098a4d54caf9c34999] Tests in error: 
[7288953e2b67938707114b098a4d54caf9c34999]   SpamAssassinContract.movingAMailToTrashShouldNotImpactSpamassassinLearning:354 » ConditionTimeout
```

**Comment by chibenwa** [comment]
```
[7288953e2b67938707114b098a4d54caf9c34999] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project cassandra-jmap-integration-testing: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[7288953e2b67938707114b098a4d54caf9c34999] [ERROR] Command was /bin/sh -c cd /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms512m -Xmx1024m -jar /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/target/surefire/surefirebooter857631866686647490.jar /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/target/surefire/surefire6883601581954830699tmp /james-project/server/protocols/jmap-integration-testing/cassandra-jmap-integration-testing/target/surefire/surefire_8578013565029873503058tmp
[7288953e2b67938707114b098a4d54caf9c34999] [ERROR] -> [Help 1]
```

What a shame... test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
