### PR TITLE
[Cucumber Integration tests] RabbitMQ + Swift + Cassandra

### PR DESCRIPTION
**Pull request by trantienduchn**
My Proposal of cucumber tests

### CODE REVIEW

**Comment by trantienduchn** [comment]
:green_apple:

**Comment by chibenwa** [comment]
test this please

Rabbitmq MailQueue

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
All cucumber tests [Part 1](https://github.com/linagora/james-project/pull/1922) & [Part 2](https://github.com/linagora/james-project/pull/1927) passed :trophy:

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
