### PR TITLE
James 2525 1782 fixes

### PR DESCRIPTION
**Pull request by rouazana**
Here are some fixes for #1782 PR.

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[6e8d3d5ba7f23fcead4a68c75c6d389c2624352c] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default) on project blob-objectstorage: Execution default of goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check failed: String index out of range: -1 -> [Help 1]
```

:trollface:

**Comment by rouazana** [comment]
probably a bug in checkstyle :/ I'm trying to find a fix

**Comment by rouazana** [comment]
```
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 12.655 s <<< FAILURE! - in org.apache.james.mpt.imapmailbox.elasticsearch.ElasticSearchUidSearchOnIndexTest
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [ERROR] testSearchAtomsUS(org.apache.james.mpt.imapmailbox.elasticsearch.ElasticSearchUidSearchOnIndexTest)  Time elapsed: 12.589 s  <<< ERROR!
[7352990bdbfff4a4e2da5548cc87546ea6787d79] org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] Location: /org/apache/james/imap/scripts/UidSearchAtomsIndexer.test:2322
[7352990bdbfff4a4e2da5548cc87546ea6787d79] LastClientMsg: A203 UID SEARCH FROM "Timothy"
[7352990bdbfff4a4e2da5548cc87546ea6787d79] Expected: '\* SEARCH 1'
[7352990bdbfff4a4e2da5548cc87546ea6787d79] Actual   : '* SEARCH'
[7352990bdbfff4a4e2da5548cc87546ea6787d79] 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [INFO] 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [INFO] Results:
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [INFO] 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [ERROR] Errors: 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [ERROR]   ElasticSearchUidSearchOnIndexTest>UidSearchOnIndex.testSearchAtomsUS:52 » InvalidServerResponse
```
test this please

**Comment by trantienduchn** [comment]
```
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [ERROR] Errors: 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [ERROR]   SpamAssassinContract.imapCopiesToSpamMailboxShouldBeConsideredAsSpam:183 » ConditionTimeout
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [INFO] 
[7352990bdbfff4a4e2da5548cc87546ea6787d79] [ERROR] Tests run: 653, Failures: 0, Errors: 1, Skipped: 3
```

test this please

**Comment by trantienduchn** [comment]
```
Apache James :: Server :: Web Admin server integration tests FAILURE [01:30 min]
```
could not find failed test. test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
