### PR TITLE
JAMES-2126 Use filename as fallback for attachment names

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
Tests in error: 
  ReadOnlyUsersLDAPRepositoryTest.testShouldStillWorksAfterRestartingLDAP:148 » UsersRepository
```

test this please

**Comment by ddolcimascolo** [comment]
:+1:

**Comment by chibenwa** [comment]
```
Tests in error: 
  ReadOnlyUsersLDAPRepositoryTest.testShouldStillWorksAfterRestartingLDAP:148 » UsersRepository
```

test this please

**Comment by chibenwa** [comment]
```
containerShouldBeReachableOnExposedPort(org.apache.james.jmap.ContainerTest)  Time elapsed: 3.562 sec  <<< ERROR!
org.apache.http.conn.HttpHostConnectException: Connect to 172.17.0.8:80 [/172.17.0.8] failed: Connection refused (Connection refused)
	at org.apache.james.jmap.ContainerTest.containerShouldBeReachableOnExposedPort(ContainerTest.java:45)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.james.jmap.ContainerTest.containerShouldBeReachableOnExposedPort(ContainerTest.java:45)


Results :

Tests in error: 
  ContainerTest.containerShouldBeReachableOnExposedPort:45 » HttpHostConnect Con...
```

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
