### PR TITLE
Since java 9 there's a release parameter that do exactly what animal-…

### PR DESCRIPTION
**Pull request by mbaechler**
…sniffer does

	The idea is to leverage a java > 8 compiler to gain greater compile speed,
	to replace the slow animal-sniffer plugin and to still generate artifacts
	for Java 8

### CODE REVIEW

**Comment by mbaechler** [comment]
before (on my computer):
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:10 min (Wall Clock)
[INFO] Finished at: 2019-07-08T18:20:14+02:00
[INFO] ------------------------------------------------------------------------
```
after:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:51 min (Wall Clock)
[INFO] Finished at: 2019-07-08T18:22:36+02:00
[INFO] ------------------------------------------------------------------------
```
It's an almost 15% improvement

**Comment by Arsnael** [comment]
```
[57d1fbe4f6d79a85d00e65bf3316b7d4789c1a83] /root/compile.sh: 70: /root/compile.sh: unzip: not found
```
test this please

**Comment by mbaechler** [comment]
I will wait for the jdk-11 PR to be ready to rebase that one on the fix required (as they look to be the same)

**Comment by mbaechler** [comment]
CI timings before:
```
[INFO] Total time: 06:08 min (Wall Clock)
```
after:
```
[INFO] Total time:  04:48 min (Wall Clock)
```
It's a 22% improvement for compile step

**Comment by mbaechler** [comment]
```
[025b849e19bbdd4effd04ebfc6430b147f345400] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:499
[025b849e19bbdd4effd04ebfc6430b147f345400] LastClientMsg: c SEARCH FLAGGED
[025b849e19bbdd4effd04ebfc6430b147f345400] Expected: '\* SEARCH 1 2 3 4'
[025b849e19bbdd4effd04ebfc6430b147f345400] Actual   : '* SEARCH'
[025b849e19bbdd4effd04ebfc6430b147f345400] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeployment(DeploymentValidation.java:81)
```

usual failure, can be considered green

**Comment by mbaechler** [comment]
new timing after rebase on master : 
```
[INFO] Total time:  02:43 min (Wall Clock)
```
It starts to look good

**Pull request merged**
