### PR TITLE
Test stability statistics

### PR DESCRIPTION
**Pull request by aduprat**
NO REVIEW, ONLY DATA

### CODE REVIEW

**Comment by aduprat** [comment]
1: OK

**Comment by aduprat** [comment]
test this please

**Comment by chibenwa** [comment]
2: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
3: NOK

https://james.open-paas.org/job/workflow/1106/

```
Tests in error: 
  CassandraSetMessagesMethodTest>SetMessagesMethodTest.setMessageShouldVerifyHeaderOfMessageInInbox:2435 » ConditionTimeout

Tests run: 608, Failures: 0, Errors: 1, Skipped: 2
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
4: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
5: OK

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
6: OK

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
7: OK

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
8: OK

**Comment by aduprat** [comment]
test this please

**Comment by chibenwa** [comment]
9: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
10: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
11 : NOK

```
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] Tests in error: 
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8]   ListScriptsTest.listScriptsShouldWork:45->AbstractSimpleScriptedTestProtocol.scriptTest:78->AbstractProtocolTestFramework.runSessions:104 » InvalidServerResponse
```

```
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.102 sec <<< FAILURE! - in org.apache.james.mpt.managesieve.cassandra.ManageSieveCassandraTest
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] listScriptsShouldWork(org.apache.james.mpt.testsuite.ListScriptsTest)  Time elapsed: 0.074 sec  <<< ERROR!
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] 
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] Location: /org/apache/james/managesieve/scripts/listscripts.test:64
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] Expected one of: 
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8]     "toto2"
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8]     "toto1" ACTIVE
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8]     "mysievescript"
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] Actual: "toto1"
[Building Java 8 tests-stability-a10e1832-6108-4fc1-97ea-e5575f70d1b8] 	at org.apache.james.mpt.testsuite.ListScriptsTest.listScriptsShouldWork(ListScriptsTest.java:45)
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
12: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
13: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
14: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
15: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
16: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
17: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
18: OK

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
10: OK

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
20: OK

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
21: OK

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
22: OK

**Comment by aduprat** [comment]
test this please

**Comment by chibenwa** [comment]
23: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
24: Ok

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Somewhere else : 

```
CassandraGetMessageListMethodTest>GetMessageListMethodTest.getMessageListShouldReturnErrorInvalidArgumentsWhenRequestIsInvalid:102 1 expectation failed.
[Building Java 8 pvn-3-proposal-db13f12c-bb13-4c24-a146-cbd1dbdaf810] Expected status code <200> doesn't match actual status code <401>.
```

https://james.open-paas.org/job/workflow/1195/console

And PR involved https://github.com/linagora/james-project/pull/549

Launched again

**Comment by chibenwa** [comment]
25: Ok

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[Building Java 8 james-1877-4a0e93be-5541-45a7-923a-686b76de95a2] Tests in error: 
[Building Java 8 james-1877-4a0e93be-5541-45a7-923a-686b76de95a2]   CassandraSetMessagesMethodTest>SetMessagesMethodTest.setMessageShouldVerifyHeaderOfMessageInInbox:2435 » 
```

In https://github.com/linagora/james-project/pull/501

https://james.open-paas.org/job/workflow/1200/console

**Comment by chibenwa** [comment]
26: OK

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[Building Java 8 mailbox-285-a7b336e3-4e70-4803-bae1-2fcde5fb2cab] [INFO] Apache James MPT ManageSieve Cassandra ............. FAILURE [ 17.057 s]
```

```
DeleteScriptTest.deleteScriptShouldWork:45->AbstractSimpleScriptedTestProtocol.scriptTest:78->AbstractProtocolTestFramework.runSessions:104 » InvalidServerResponse
[Building Java 8 mailbox-285-a7b336e3-4e70-4803-bae1-2fcde5fb2cab] 
[Building Java 8 mailbox-285-a7b336e3-4e70-4803-bae1-2fcde5fb2cab] Tests run: 14, Failures: 0, Errors: 1, Skipped: 0
```

```
[Building Java 8 mailbox-285-a7b336e3-4e70-4803-bae1-2fcde5fb2cab] Location: /org/apache/james/managesieve/scripts/deletescript.test:76
[Building Java 8 mailbox-285-a7b336e3-4e70-4803-bae1-2fcde5fb2cab] LastClientMsg: DELETESCRIPT "mysievescript"
[Building Java 8 mailbox-285-a7b336e3-4e70-4803-bae1-2fcde5fb2cab] Expected: 'NO \(ACTIVE\) "You may not delete an active script"'
[Building Java 8 mailbox-285-a7b336e3-4e70-4803-bae1-2fcde5fb2cab] Actual   : 'OK'
```

https://james.open-paas.org/job/workflow/1228/console

https://github.com/linagora/james-project/pull/556

**Comment by chibenwa** [comment]
Failed tests: 
  ScrollIterableTest.scrollIterableShouldWorkWhenSizeElement:134 
Expecting:
  <[]>
to contain only:
  <["1", "2"]>
but could not find the following elements:
  <["1", "2"]>

**Comment by chibenwa** [comment]
[Building Java 8 master-5dbbd70c-7fa5-4775-88ac-a5479cfb5cc3] Results :
[Building Java 8 master-5dbbd70c-7fa5-4775-88ac-a5479cfb5cc3] 
[Building Java 8 master-5dbbd70c-7fa5-4775-88ac-a5479cfb5cc3] Tests in error: 
[Building Java 8 master-5dbbd70c-7fa5-4775-88ac-a5479cfb5cc3]   CassandraSetMessagesMethodTest>SetMessagesMethodTest.setMessageShouldVerifyHeaderOfMessageInInbox:2435 » ConditionTimeout

**Comment by chibenwa** [comment]
One more : 

```
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d] Failed tests: 
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d]   CassandraSieveRepositoryTest>AbstractSieveRepositoryTest.setActiveShouldWork:154 
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d] Expecting:
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d]  <[org.apache.james.sieverepository.api.ScriptSummary@72d44895]>
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d] to contain only:
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d]  <[org.apache.james.sieverepository.api.ScriptSummary@72d44896]>
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d] elements not found:
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d]  <[org.apache.james.sieverepository.api.ScriptSummary@72d44896]>
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d] and elements not expected:
[Building Java 8 master-3abf1b90-958b-423f-87b6-3b8dec2e9d5d]  <[org.apache.james.sieverepository.api.ScriptSummary@72d44895]>
```

Seems like CI is grumpy after reboot...

**Comment by chibenwa** [comment]
```
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50] Failed tests: 
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50]   expected:<[2]01> but was:<[4]01>
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50]   expected:<[2]01> but was:<[4]01>
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50]   expected:<40[0]> but was:<40[1]>
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50]   expected:<40[0]> but was:<40[1]>
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50] Tests in error: 
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50]   Unauthorized
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50]   Unauthorized
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50]   CassandraSetMessagesMethodTest>SetMessagesMethodTest.setMessageShouldVerifyHeaderOfMessageInInbox:2435 » ConditionTimeout
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50] 
[Building Java 8 mailet-148-778a9cd7-0983-4e3a-a03c-9c9e33e8dc50] Tests run: 630, Failures: 4, Errors: 3, Skipped: 4
```

**Comment by chibenwa** [comment]
```
[Building Java 8 mailet-145-1-7e8f0f7d-84ab-4577-8263-43762619b127]   CassandraSieveRepositoryTest>AbstractSieveRepositoryTest.setActiveSwitchScriptShouldWork:197 expected:<"[Other script content]"> but was:<"[Hello World]">
```

**Comment by chibenwa** [comment]
```
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22] Failed tests: 
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22]   expected:<40[0]> but was:<40[1]>
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22]   expected:<40[0]> but was:<40[1]>
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22] Tests in error: 
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22]   Unauthorized
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22]   Unauthorized
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22] 
[Building Java 8 mailet-148-9d05ffa7-e182-4617-bbaf-280b9468df22] Tests run: 630, Failures: 2, Errors: 2, Skipped: 4
```

**Comment by chibenwa** [comment]
```
[Building Java 8 mailet-148-a10d4a93-c3b8-48ca-84ed-1290c5e5b5e9] Results :
[Building Java 8 mailet-148-a10d4a93-c3b8-48ca-84ed-1290c5e5b5e9] 
[Building Java 8 mailet-148-a10d4a93-c3b8-48ca-84ed-1290c5e5b5e9] Tests in error: 
[Building Java 8 mailet-148-a10d4a93-c3b8-48ca-84ed-1290c5e5b5e9]   TestDiscardProtocol.testComplete:95 »  Timed out wait for be notified that rea...
[Building Java 8 mailet-148-a10d4a93-c3b8-48ca-84ed-1290c5e5b5e9] 
[Building Java 8 mailet-148-a10d4a93-c3b8-48ca-84ed-1290c5e5b5e9] Tests run: 21, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by chibenwa** [comment]
On : https://github.com/linagora/james-project/pull/559

```
[Building Java 8 james-1908_config_cassandra_multiple_ip-71f40a97-bd88-4280-89bb-00fe6f8c92ce] Tests in error: 
[Building Java 8 james-1908_config_cassandra_multiple_ip-71f40a97-bd88-4280-89bb-00fe6f8c92ce]   CassandraSetMessagesMethodTest>SetMessagesMethodTest.setMessageShouldVerifyHeaderOfMessageInInbox:2435 » ConditionTimeout
```

https://james.open-paas.org/job/workflow/99/console

**Comment by chibenwa** [comment]
```
[Building Java 8 mix-jmap-imap-luc-9986ca9f-7475-4060-84d8-f304d538acb5] Tests in error: 
[Building Java 8 mix-jmap-imap-luc-9986ca9f-7475-4060-84d8-f304d538acb5]   CassandraSieveRepositoryTest.deleteScriptShouldWork »  Unexpected exception, e...
```

**Comment by rouazana** [comment]
[Building Java 8 james-1919-75576f27-a013-40d1-a473-31e9a3e143e2] Tests in error: 
[Building Java 8 james-1919-75576f27-a013-40d1-a473-31e9a3e143e2]   TestDiscardProtocol.testComplete:95 »  Timed out wait for be notified that rea...

**Comment by quynhn** [comment]
test this please

**Comment by chibenwa** [comment]
```
CassandraGetMailboxesMethodTest>GetMailboxesMethodTest.getMailboxesShouldErrorNotSupportedWhenRequestContainsNonNullAccountId:107 1 expectation failed.
[Building Java 8 james-1929-1a72a8d8-fe54-4daa-b6d2-a0c22df4e8e5] Expected status code <200> doesn't match actual status code <401>.
```

**Comment by chibenwa** [comment]
This one is new : 

```
[Building Java 8 james-1925-concurency-ab438839-a613-4c12-9b07-3334fed23d9a] Tests in error: 
[Building Java 8 james-1925-concurency-ab438839-a613-4c12-9b07-3334fed23d9a]   NettySMTPServerTest>AbstractSMTPServerTest.testDeliveryWith4SimultaneousThreads:121->AbstractSMTPServerTest.checkEnvelope:1112 » NullPointer
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
(Having a "Test stability PR" red for ages is kind of "not cool")

**Comment by chibenwa** [comment]
test this please

**Pull request closed without merging**
