### PR TITLE
JAMES-2009 Fix unstable test by removing unneeded modules when jmap t…

### PR DESCRIPTION
**Pull request by quynhn**
…esting

### CODE REVIEW

**Comment by rouazana** [comment]
Can you explain why it is fixing the issue?

**Comment by quynhn** [comment]
> Can you explain why it is fixing the issue?
It does not take time to start server and more consistence when waiting time IMO

> JMAP should be working well with all modules enabled ;-)
Yes, but from here we just testing concurrent on JMAP, why do we need to care about the others protocols?

**Comment by mbaechler** [comment]
recent changes about memory usage make me think we may leak memory too much, don't you think ?

**Comment by quynhn** [comment]
> recent changes about memory usage make me think we may leak memory too much, don't you think ?

I'm not sure, for now it cassandra it ran with -Xms256m -Xmx512m
But anyway, this test ran inconsistency on my local before this change and with this change (just load enough modules that we need) make the test more consistence so we can accept this IMO

**Comment by chibenwa** [comment]
@quynh We are testing a full product in integration tests.

Solving problems by saying (look, this test with an enviromnent like prod is failing, but  hey, if I remove some not used part, it's working) **will not solve any problem on PROD**.

This also proves @mbaechler   right about testing full applications.

**Comment by quynhn** [comment]
I would like to close this one such as the ticket is closed by team leader
https://ci.linagora.com/linagora/lgs/openpaas/james/issues/455

**Pull request closed without merging**
