### PR TITLE
JAMES-3493 Add logs for start and stop of the James server and the JMX module

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Review by chibenwa — COMMENTED** [review]
We would benefit from having a ticket number and a short "why" explanation IMO

**Comment by LanKhuat** [comment]
Have you tested it locally to see if it solves the waiting problem? the server.start() and .stop() process might take a while and i'm not sure if they are fully synchronous

**Comment by chibenwa** [comment]
IMO we would also benefit from having a `INFO JAMES server started` in `GuiceJamesServer::start`

That would ensure that all services are well started, not just the JMX server...

**Comment by Arsnael** [comment]
> Have you tested it locally to see if it solves the waiting problem? the server.start() and .stop() process might take a while and i'm not sure if they are fully synchronous

Don't worry I tested

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
```
[6b705ba364963f006700cd4ea91469a89c2de255] [ERROR] Errors: 
[6b705ba364963f006700cd4ea91469a89c2de255] [ERROR]   DSNRelayTest.setUp:119 » Retryable Connection reset executing PUT http://192.1...
```

Those DSN tests don't look stable?

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[6b705ba364963f006700cd4ea91469a89c2de255] [ERROR] Errors: 
[6b705ba364963f006700cd4ea91469a89c2de255] [ERROR]   DSNRelayTest.setUp:119 » Retryable Connection reset executing PUT http://192.1...
```
.... test this please

**Comment by chibenwa** [comment]
BTW I did not succeed to reproduce it locally....

**Comment by Arsnael** [comment]
```
[6b705ba364963f006700cd4ea91469a89c2de255] [ERROR] Failed to execute goal on project apache-james-mailbox-spring: Could not resolve dependencies for project org.apache.james:apache-james-mailbox-spring:jar:3.6.0-SNAPSHOT: Failed to collect dependencies at org.springframework:spring-orm:jar:4.3.25.RELEASE -> org.springframework:spring-jdbc:jar:4.3.25.RELEASE -> org.springframework:spring-tx:jar:4.3.25.RELEASE: Failed to read artifact descriptor for org.springframework:spring-tx:jar:4.3.25.RELEASE: Could not transfer artifact org.springframework:spring-tx:pom:4.3.25.RELEASE from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/spring-tx/4.3.25.RELEASE/spring-tx-4.3.25.RELEASE.pom: Connection reset -> [Help 1]
```
-__- CI be nice please...

test this please

**Review by LanKhuat — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
How I'm getting trashed by the CI just for adding 3 logs honestly... 

test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
