### PR TITLE
JAMES-2766 Replace old ES version & ports in documents

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
test this please

**Comment by trantienduchn** [comment]
test this please

**Comment by trantienduchn** [comment]
need jenkins CI running on ES 6

**Comment by Arsnael** [comment]
jenkins should be running on ES6 now right?

test this please

**Comment by trantienduchn** [comment]
```
6d9936f75f802569533fcaf1858b9f5c9e0a27c8dd42544405ea2b180cd3e33f
[52dcf1cc1030be7fb374c865ed526357f4b82024] docker: Error response from daemon: Cannot link to a non running container: /elasticSearch-update-es-version-a25dca8a-265c-4084-9e2f-efb0c848b297 AS /james-server-cassandra-update-es-version-a25dca8a-265c-4084-9e2f-efb0c848b297/elasticsearch.
[52dcf1cc1030be7fb374c865ed526357f4b82024] [108] Running shell script
[52dcf1cc1030be7fb374c865ed526357f4b82024] + docker exec cassandra-update-es-version-a25dca8a-265c-4084-9e2f-efb0c848b297 cqlsh -e describe columnfamily system.local;
[52dcf1cc1030be7fb374c865ed526357f4b82024] Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
```
Seems not good, test this please to make sure

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
