### PR TITLE
James 2617 es6 metrics 2

### PR DESCRIPTION
**Pull request by rouazana**
Here is a new PR to make James metrics compatible with Elastic Search 6.

This time I handled integration tests, and also externalized the needed library. This library needs to be released and the version needs to be updated so that we can merge this PR.

Replaces #1981

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[00c2c6d0eea7d3298dcd63237b85088fabcc5f9a] [INFO] ------------------------------------------------------------------------
[00c2c6d0eea7d3298dcd63237b85088fabcc5f9a] [ERROR] Failed to execute goal on project metrics-es-reporter: Could not resolve dependencies for project org.apache.james:metrics-es-reporter:jar:3.3.0-SNAPSHOT: Could not find artifact com.linagora:metrics-elasticsearch-reporter:jar:6.0.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
```

**Comment by rouazana** [comment]
```
test this please
```

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
ABORTED -- test this please

**Comment by rouazana** [comment]
merged

**Pull request merged**
