### PR TITLE
Junit 5 migration

### PR DESCRIPTION
**Pull request by mbaechler**
This is a first batch of changes to migration everything to junit5.
More to come in following batches.
I used structural refactoring or automatic refactoring for most of the changes but when commit message says otherwise.

### CODE REVIEW

**Comment by aduprat** [comment]
Build triggered. sha1 is original commit.

**Comment by aduprat** [comment]
Build started sha1 is original commit.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
Build triggered. sha1 is original commit.

**Comment by aduprat** [comment]
Build started sha1 is original commit.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
Build triggered. sha1 is original commit.

**Comment by aduprat** [comment]
Build started sha1 is original commit.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
Build triggered. sha1 is original commit.

**Comment by aduprat** [comment]
Build started sha1 is original commit.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by chibenwa** [comment]
Maybe some parts of this work could be reused for JUNIT 5 migration for JMAP draft and its integration test suite hence I am not closing this.

**Pull request closed without merging**
