### PR TITLE
Use NIO for RabbitMQ connections

### PR DESCRIPTION
**Pull request by chibenwa**
Tests run on top of DeQueue as Flux use the simple SMTP scenario, CassandraBlobStore.

Before:

capture d ecran de 2018-12-25 14-52-24

After:

capture d ecran de 2018-12-25 14-52-21

Conclusions:

 - 5% thoughput reduction
 - 5% average latencies reductions, 44% p99 reduction

Note: The NIO setup is recommended by RabbitMQ Reactor lib

### CODE REVIEW

**Comment by mbaechler** [comment]
> Note: The NIO setup is recommended by RabbitMQ Reactor lib

Could you provide the link to that ? AFAIK, NIO is still experimental

**Comment by chibenwa** [comment]
> Could you provide the link to that ? AFAIK, NIO is still experimental

Sure: https://projectreactor.io/docs/rabbitmq/milestone/reference/#api-guide-sender

```
ConnectionFactory connectionFactory = new ConnectionFactory();
connectionFactory.useNio();

SenderOptions senderOptions =  new SenderOptions()
    .connectionFactory(connectionFactory)                       
    .resourceManagementScheduler(Schedulers.elastic());   
```

& later on:

```
Reactor RabbitMQ configure by default the Java Client to use NIO, i.e. there’s only one thread that deals with IO. This can be changed by specifying a ConnectionFactory in the SenderOptions.
```

**Comment by chibenwa** [comment]
Let's wait another approuval...

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
