### PR TITLE
JAMES-2958 Domain length validation is done by the model

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```

[3af631a113a317d7467694dec35bd1ef2ce7585b] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[3af631a113a317d7467694dec35bd1ef2ce7585b] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[3af631a113a317d7467694dec35bd1ef2ce7585b] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[3af631a113a317d7467694dec35bd1ef2ce7585b] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`Error injecting constructor, com.datastax.driver.core.exceptions.InvalidQueryException: Keyspace 'apache_james' does not exist`

in deployment tests...

**Comment by Arsnael** [comment]
```
[a066e8230f11a35fe6254da420a81f656d6bec35] [ERROR] Errors: 
[a066e8230f11a35fe6254da420a81f656d6bec35] [ERROR]   MemorySpamAssassinContractTest.deletingSpamMessageShouldNotImpactSpamAssassinState » ConditionTimeout
[a066e8230f11a35fe6254da420a81f656d6bec35] [ERROR]   MemorySpamAssassinContractTest.expungingSpamMessageShouldNotImpactSpamAssassinState » ConditionTimeout
[a066e8230f11a35fe6254da420a81f656d6bec35] [ERROR]   MemorySpamAssassinContractTest.spamShouldBeDeliveredInSpamMailboxOrInboxWhenMultipleRecipientsConfigurations » ConditionTimeout
```
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
