### PR TITLE
[NO_REVIEW] Test deployment tests recent changes

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
cc @blackheaven it fails. Can you have a look?

**Comment by chibenwa** [comment]
CQFD `Caused by: java.io.FileNotFoundException: dockerfiles/run/guice/cassandra-rabbitmq-ldap/destination/conf/blob.properties (No such file or directory)`

Cc @blackheaven

**Comment by chibenwa** [comment]
Making the CI happy should be that easy <3

**Comment by blackheaven** [comment]
The issue is on james-jenkins.

Moreover it is blob.properties:

 * https://github.com/linagora/james-project/blob/master/dockerfiles/run/guice/cassandra-rabbitmq/destination/conf/blob.properties
 * https://github.com/linagora/james-project/blob/master/dockerfiles/run/guice/cassandra-rabbitmq-ldap/destination/conf/blob.properties

**Comment by chibenwa** [comment]
> The issue is on james-jenkins.

I agree having jenkins copying blob.properties or blobstore.properties depending on what's there would be nice.

However either we find a quick fix or revert the merge on james-jenkins.

**Comment by blackheaven** [comment]
No, the issue is that `james-jenkins` is looking for `blob.properties` at the wrong place.

It does not looks for  `blobstore.properties` as your PR name it, I do not see of it fixes the problem.

**Pull request closed without merging**
