### PR TITLE
JAMES-1693  Improve JMAP integration testing speed

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by aduprat** [comment]
:+1:

**Comment by mbaechler** [comment]
You said mailet are slow to start : can we speedup this ? Where is the time spent ?
How long does it take to start Cassandra ?

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Pull request closed without merging**
