### PR TITLE
JAMES-2881 Slightly enhance 'ToHttp' mailets code quality

### PR DESCRIPTION
**Pull request by chibenwa**
Solves @blackheaven comments on https://github.com/linagora/james-project/pull/2684

### CODE REVIEW

**Comment by chibenwa** [comment]
`JamesMailSpoolerTest.threadSuicideShouldAckTheItem:126 » ConditionTimeout Cond...`

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[6f555ba7e6d0c244772f35293e6407340cf5de05] [ERROR] Errors: 
[6f555ba7e6d0c244772f35293e6407340cf5de05] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[6f555ba7e6d0c244772f35293e6407340cf5de05] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[6f555ba7e6d0c244772f35293e6407340cf5de05] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
```
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
