### PR TITLE
[NO REVIEW] JAMES-3214 Remove MailRepository API from Server-Data api

### PR DESCRIPTION
**Pull request by chibenwa**
CI for https://github.com/apache/james-project/pull/209

### CODE REVIEW

**Comment by Arsnael** [comment]
Log output lost

test this please

**Comment by chibenwa** [comment]
```
[5ec679524d4ef8809233f5f43e21d1b97adeb33d] [ERROR] Failures: 
[5ec679524d4ef8809233f5f43e21d1b97adeb33d] [ERROR]   JamesSpringContextTest.springShouldLoadAndAddOnlyOneQuotaUpdaterListener Multiple Failures (2 failures)
[5ec679524d4ef8809233f5f43e21d1b97adeb33d] 	org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sieveparser' defined in class path resource [META-INF/spring/loaders-context.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'configurationManager' of bean class [org.apache.james.managesieve.jsieve.Parser]: Bean property 'configurationManager' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
[5ec679524d4ef8809233f5f43e21d1b97adeb33d] 	java.lang.NullPointerException: <no message>
[5ec679524d4ef8809233f5f43e21d1b97adeb33d] [ERROR] Errors: 
[5ec679524d4ef8809233f5f43e21d1b97adeb33d] [ERROR]   JamesAppSpringMainTest.testServer:27 » BeanCreation Error creating bean with n...
```

**Comment by chibenwa** [comment]
Unrelated

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
