### PR TITLE
MAILBOX-289 Cassandra subscription should not rely on secondary indexes

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[Building Java 8 mailbox-289-c9f80fd2-e471-48a5-b6b4-2c640d1034d9] Tests in error: 
[Building Java 8 mailbox-289-c9f80fd2-e471-48a5-b6b4-2c640d1034d9]   CassandraSieveRepositoryTest>AbstractSieveRepositoryTest.getActivationDateForActiveScriptShouldReturnNonNullAndNonZeroResult:78 » ScriptNotFound
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[Building Java 8 mailbox-289-7595f829-6262-4a1b-9950-0bf22e97c11c] Tests in error: 
[Building Java 8 mailbox-289-7595f829-6262-4a1b-9950-0bf22e97c11c]   CassandraSetMessagesMethodTest>SetMessagesMethodTest.setMessageShouldVerifyHeaderOfMessageInInbox:2868->SetMessagesMethodTest.getMailboxId:161->SetMessagesMethodTest.getAllMailboxesIds:175 » JsonPath
```

Don't see how this could be related so...

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```

[Building Java 8 mailbox-289-e92e3a46-8112-412d-917b-8185d921815e] Tests in error: 
[Building Java 8 mailbox-289-e92e3a46-8112-412d-917b-8185d921815e]   ListScriptsTest.listScriptsShouldWork:45->AbstractSimpleScriptedTestProtocol.scriptTest:78->AbstractProtocolTestFramework.runSessions:104 » InvalidServerResponse
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
Tests in error: 
  CassandraSieveRepositoryTest>AbstractSieveRepositoryTest.getActivationDateForActiveScriptShouldReturnNonNullAndNonZeroResult:78 » ScriptNotFound
```

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
Yes, as we can't change primary key in Cassandra.
We can think on providing a code migration, then we should be able to merge this PR.

**Comment by chibenwa** [comment]
No need. Would work fine without it.
The old primary index behaves as a Primary Key. If you noticed I did not change requests. It means it's fine.

**Comment by rouazana** [comment]
Please test this before merging to be sure :)

**Comment by chibenwa** [comment]
How do you right such tests? Ensuring code that did not change still work on old module ? Isn't that already prooved by green master build?

**Comment by rouazana** [comment]
testing, no checking: you create a cassandra instance with the old code, create some users, then relaunch the james server with the new code, add some users, and check all is fine

**Comment by chibenwa** [comment]
This code is about subscribtions. Not about users. Yes I got the idea.

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
