### PR TITLE
JAMES-2872 fix documentation docker compilation

### PR DESCRIPTION
**Pull request by Arsnael**
Well after this: https://github.com/linagora/james-project/commit/0ff5716977ba6446f2044036087569fc94da682c we need also to upgrade the java version of the Dockerfile to generate the website, or it fails.

I removed as well the plugin `cobertura-maven-plugin`. This plugin is for generating coverage testing reports, which we don't seem to really use, but also this plugin has not been maintained for a long time (2015), and is using some jar tools that was part of java jdk-8 but has been removed in upper versions. So in short, this plugin makes the doc generation fails with java 11, so I removed it

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[64b414575a0e82534ead30989c7a690394a01661] [ERROR] Errors: 
[64b414575a0e82534ead30989c7a690394a01661] [ERROR]   MemoryUploadCucumberTest » Socket Broken pipe (Write failed)
```
test this please

**Comment by trantienduchn** [comment]
```
[64b414575a0e82534ead30989c7a690394a01661] [ERROR] Errors: 
[64b414575a0e82534ead30989c7a690394a01661] [ERROR]   VacationIntegrationTest.jmapVacationShouldNotSendNotificationTwice:240 » ConditionTimeout
[64b414575a0e82534ead30989c7a690394a01661] [ERROR]   MemoryUploadCucumberTest » Socket Broken pipe (Write failed)
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:495 » Execution` test this please

**Comment by Arsnael** [comment]
```
[64b414575a0e82534ead30989c7a690394a01661] [ERROR] Errors: 
[64b414575a0e82534ead30989c7a690394a01661] [ERROR]   MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:495 » Execution
[64b414575a0e82534ead30989c7a690394a01661] [ERROR]   MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:495 » Execution
```
test this please

**Comment by Arsnael** [comment]
Been actually merged with https://github.com/linagora/james-project/pull/2628

**Pull request closed without merging**
