### PR TITLE
These simple tests ensure the docker rule allow to run a container fo…

### PR DESCRIPTION
**Pull request by mbaechler**
…r a test

	It checks HTTP reachability on container IP and exposed port on host

### CODE REVIEW

**Comment by mbaechler** [comment]
It needs a patched version of docker-java, see https://github.com/docker-java/docker-java/pull/457

**Comment by mbaechler** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
Can one of the admins verify this patch?

**Comment by aduprat** [comment]
Can one of the admins verify this patch?

**Comment by mbaechler** [comment]
already merged

**Pull request closed without merging**
