### PR TITLE
JAMES-2885 -  avoid concurrent nexModSeq during flags update

### PR DESCRIPTION
**Pull request by remk**

### CODE REVIEW

**Comment by chibenwa** [comment]
(Imap Select?)

**Comment by remk** [comment]
It's used in jmap. But it should not have a big impact on performance because the concurrent update of the modSeq happens where there is multiple mailbox passed in parameter. In the normal of usage of this method only one mailbox is provided.

I would like to keep this PR in WIP, the time to review the usage of nextModSeq with Reactor in the code base.

**Comment by chibenwa** [comment]
Trust me, concurrent modseq update happen upon first IMAP SELECT (`\recent` flag reset)

**Comment by chibenwa** [comment]
Alternatively, we can set up an IMAP scenario with flags updates on large ranges.

**Comment by chibenwa** [comment]
`WithEncryptedSwiftTest.mailsShouldBeWellReceived » ConditionTimeout Condition ...`

test this please

**Comment by trantienduchn** [comment]
```
[54cb2d4e527c0a5fd8e8cbb3e69568c6cb004373] [ERROR] Crashed tests:
[54cb2d4e527c0a5fd8e8cbb3e69568c6cb004373] [ERROR] org.apache.james.webadmin.routes.DomainsRoutesTest$NormalBehaviour
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[54cb2d4e527c0a5fd8e8cbb3e69568c6cb004373] [ERROR]   EventDeadLettersIntegrationTest.multipleFailedEventsShouldBeCorrectlyProcessedByListenerAfterSuccessfulGroupRedelivery:398 » ConditionTimeout
```

Unrelated

test this please

**Comment by blackheaven** [comment]
```
[INFO] Apache James :: Server :: Mailet :: Mock SMTP Server FAILURE [ 11.082 s]
```

test this please

**Comment by chibenwa** [comment]
Can you open a JIRA ticket for this very interesting job @remk ?

**Comment by remk** [comment]
> Can you open a JIRA ticket for this very interesting job @remk ?

Yes, https://issues.apache.org/jira/browse/JAMES-2885 :)

**Comment by remk** [comment]
Rebased to add ticket number to the commit message

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
