### PR TITLE
Openpaas 1.5.1

### PR DESCRIPTION
**Pull request by remk**
Backport for release 1.5.1

### CODE REVIEW

**Comment by remk** [comment]
test this please

**Comment by rouazana** [comment]
test this pleas

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
```
[4e3eb02dec073c40b48656538a252b0c9cf34974] [ERROR] Errors: 
[4e3eb02dec073c40b48656538a252b0c9cf34974] [ERROR]   GetMessageListMethodTest.setup:114 » ElasticsearchStatus Elasticsearch excepti...
[4e3eb02dec073c40b48656538a252b0c9cf34974] [INFO] 
[4e3eb02dec073c40b48656538a252b0c9cf34974] [ERROR] Tests run: 100, Failures: 0, Errors: 1, Skipped: 0
```
test this please

**Comment by rouazana** [comment]
test this please (CI restart)

**Pull request merged**
