### PR TITLE
[NO_REVIEW] JAMES-2979 Disable FileMailQueueTest.dequeueShouldBeConcurrent 

### PR DESCRIPTION
**Pull request by chibenwa**
As it is unstable 

See apache#180 instead

### CODE REVIEW

**Comment by chibenwa** [comment]
could not reproduce localy btw.

**Comment by mbaechler** [comment]
The FileMailQueue needs some work to handle this case (it's not thread-safe for now). I had a look and it's probably a day or two of work.
Either we declare it broken, document that fact and remove it from future version or we need to fix it.
IMO it doesn't make sense to try to implement a MQ ourselves when we can just embed one (as we did for ActiveMQ).

**Comment by chibenwa** [comment]
Then let's:
 - merge this so that it stops annoying us.
 - Add it on the deprecation wish list.

**Comment by mbaechler** [comment]
I propose that we: disable FileMailQueueTest entirely, write an ADR about why we think it doesn't make sense to continue maintaining this component and add a @Deprecated annotation on it in this PR.

**Comment by chibenwa** [comment]
See https://github.com/apache/james-project/pull/180

**Comment by chibenwa** [comment]
(for CI build purposes)

**Comment by chibenwa** [comment]
```

[dedb45c2c737bf2bd79eafedb132af2ea3b8679e] [ERROR]   EventDeadLettersIntegrationTest.failedEventShouldBeStoredInDeadLetter:252->retrieveFirstFailedInsertionId:197 » IndexOutOfBounds
[dedb45c2c737bf2bd79eafedb132af2ea3b8679e] [ERROR]   EventDeadLettersIntegrationTest.failedEventShouldNotBeInDeadLettersAfterSuccessfulRedelivery:334->retrieveFirstFailedInsertionId:197 » IndexOutOfBounds
```

test this please

**Comment by Arsnael** [comment]
Removed the `waiting_merge` because there is a few minor comments from @mbaechler in apache#180 that need to be fixed

**Comment by chibenwa** [comment]
Well I just fixed his comments and as he already approuved I will re-add the waiting merge label.

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
