### PR TITLE
JAMES-2475 Run Memory JMAP integration tests first

### PR DESCRIPTION
**Pull request by chibenwa**
Use a dependency to enforce build order.

### CODE REVIEW

**Comment by mbaechler** [comment]
It means you annotate what you think is related to memory (you can create an @MemoryIT) and run surefire twice with inclusion/exclusion of the tag
Or the other way around : you annotate @Cassandra and run everything else in the first run

**Comment by chibenwa** [comment]
Actually, I don't want to run things two time. I just want to schedule one before the other.

(I believed we did conclude in this morning meeting that that annotation stuff was too expensive and not desirable)

**Comment by mbaechler** [comment]
You don't run things twice, you run surefire twice with different testsuites.
And no, we didn't conclude it's too expensive in all cases, just for fast/slow tests.
Here, we are talking about a handful of annotations AFAIK.

**Comment by rouazana** [comment]
I'm not sure it worth to introduce these annotations. If you have 2 profiles (one include, one exclude), you do need to run tests twice, and it takes some times (because surefire needs to browse every project).
So even if it's not very beautiful I'm not against adding memory as a test dependency of jmap.

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
