### PR TITLE
James 2107 fix warnings after java 8 transition

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
Tests run: 659, Failures: 5, Errors: 0, Skipped: 2
...
[INFO] Apache James :: Server :: JMAP ..................... FAILURE [01:02 min]
```

Respectively:

```
GetMessagesMethodTest.processShouldReturnTextBodyWhenBodyInPropertyListAndEmptyHtmlBody:310 
GetMessagesMethodTest.processShouldReturnOnlyMandatoryPropertiesOnEmptyPropertyList:244
GetMessagesMethodTest.processShouldReturnHeadersFieldWhenSpecificHeadersRequestedInPropertyList:422 
GetMessagesMethodTest.processShouldReturnAllPropertiesWhenNoPropertyGiven:267 
GetMessagesMethodTest.processShouldAddMandatoryPropertiesWhenNotInPropertyList:288 
```

They all boil down to the same problem:

```
Expecting:
  <[java.util.stream.ReferencePipeline$3@55634720]>
to contain only:
  <[id, subject]>
elements not found:
  <[id, subject]>
and elements not expected:
  <[java.util.stream.ReferencePipeline$3@55634720]>
```

**Comment by mbaechler** [comment]
```
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.931 sec - in org.apache.james.jmap.cassandra.CassandraUserProvisionningConcurrencyTest
13:08:29.549 [ERROR] c.d.d.c.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
13:08:30.550 [ERROR] c.d.d.c.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 2000 milliseconds

Results :

Failed tests: 
  
Expecting:
  <["application/json;charset=utf-8"]>
to contain exactly (and in same order):
  <["application/json; charset=UTF-8"]>
but some elements were not found:
  <["application/json; charset=UTF-8"]>
and others were not expected:
  <["application/json;charset=utf-8"]>

  
Expecting:
  <["application/json;charset=utf-8"]>
to contain exactly (and in same order):
  <["application/json; charset=UTF-8"]>
but some elements were not found:
  <["application/json; charset=UTF-8"]>
and others were not expected:
  <["application/json;charset=utf-8"]>
```

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
merged

**Pull request closed without merging**
