### PR TITLE
James 2195 : rebase on master

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by aduprat** [comment]
Rebase on master -> `push force`

**Comment by aduprat** [comment]
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   null
[ERROR]   null
[ERROR]   null
[ERROR]   null
[ERROR]   null
[ERROR]   null
[ERROR]   null
[ERROR]   null
```

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
```
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

**Comment by aduprat** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Pull request merged**
