### PR TITLE
Swift resilient create container failed when using swift check existent api

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
I think this is a bug of Openstack Swift BlobStore
```
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR] Errors: 
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   ObjectStorageBlobsDAOTest.encryptionWithCustomPayloadCodeCannotBeReadFromUnencryptedDAO:144 » IllegalState
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.readBytesShouldReturnBigSavedData » Completion java.lang.Ill...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.readBytesShouldReturnLongSavedData » Completion java.lang.Il...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.readBytesShouldReturnSavedData » Completion java.lang.Illega...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.readShouldReturnBigSavedData:158 » IllegalState Optional.get...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.readShouldReturnLongSavedData:146 » IllegalState Optional.ge...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.readShouldReturnSavedData:135 » IllegalState Optional.get() ...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.saveShouldSaveEmptyData » Completion java.lang.IllegalStateE...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   BlobStoreContract.saveShouldSaveEmptyInputStream » Completion java.lang.Illega...
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   SwiftKeystone2ObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:92 » Execution
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   SwiftKeystone3ObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:128 » Execution
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   SwiftKeystone3ObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:128 » Execution
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   SwiftKeystone3ObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:128 » Execution
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR]   SwiftTempAuthObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:94 » Execution
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [INFO] 
[7e7381d15a34cf2f54241b2c0b13ddae39ead91c] [ERROR] Tests run: 116, Failures: 0, Errors: 14, Skipped: 0
```

**Comment by chibenwa** [comment]
Could you give us an exact stack-trace?
Did you opened a ticket on their bug-tracker?
Is this easy to fix? If yes, then you could easily become a Apache JCloud contributor ;-)

But let's not that *bug* go unoticed...

**Comment by trantienduchn** [comment]
> Could you give us an exact stack-trace?
> Did you opened a ticket on their bug-tracker?
> Is this easy to fix? If yes, then you could easily become a Apache JCloud contributor ;-)
> 
> But let's not that _bug_ go unoticed...

Okay, I will open again and take care more of this issue.

**Comment by trantienduchn** [comment]
Concrete test for `swift blobstore check existings`. Here is the stacktrace happens when usiing `blobstore.containerExists()`:
```
java.lang.IllegalStateException: Optional.get() cannot be called on an absent value

	at com.google.common.base.Absent.get(Absent.java:43)
	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedSwiftBlobStore.toBlobMetadata(RegionScopedSwiftBlobStore.java:607)
	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedSwiftBlobStore.getBlob(RegionScopedSwiftBlobStore.java:384)
	at org.jclouds.openstack.swift.v1.blobstore.RegionScopedSwiftBlobStore.getBlob(RegionScopedSwiftBlobStore.java:374)
	at duc.home.test.docker.openstack.swift.SwiftTest.getBlobIsGonnaFailWhenContainerExistsIsInvoked(SwiftTest.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:513)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:113)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
```

Next step, I will replace Jean's swift images by image provided by openstack, and repeat that test. If it fail, i'm gonna report a bug to them

**Comment by hoangdat** [comment]
Build triggered. sha1 is merged.

**Comment by hoangdat** [comment]
Build finished. No test results found.

**Comment by hoangdat** [comment]
Build triggered. sha1 is merged.

**Comment by trantienduchn** [comment]
> what's the status of this PR?

Status is: I wrote a non-related to james test that shows Swift BlobStore API failure, but it based on swift image from linagora. not the authentic image from Openstack. Next step will be running that test on openstack swift image and verify the result. If still getting failure, issue will be reported to openstack. 

It's kinda slow progress because It's not in sprint concern and I'm lazy to code at weekends :)

**Comment by rouazana** [comment]
> Status is: I wrote a non-related to james test that shows Swift BlobStore API failure, but it based on swift image from linagora. not the authentic image from Openstack. Next step will be running that test on openstack swift image and verify the result. If still getting failure, issue will be reported to openstack.

> It's kinda slow progress because It's not in sprint concern and I'm lazy to code at weekends :)

Thanks for the status. No problem, can you just plan it next week or next sprint please?

**Comment by trantienduchn** [comment]
I created a ticket in JCOULD repository, https://issues.apache.org/jira/browse/JCLOUDS-1479.
I could not find an authentic openstack swift docker and starting up an openstack swift manually seems complicated. So I use Jean's one. :)

**Comment by trantienduchn** [comment]
issue was resolved, PR here https://github.com/apache/jclouds/pull/14
closing this one

**Pull request closed without merging**
