### PR TITLE
JAMES-2993 Using elastic scheduler in recomputing all

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] [ERROR] Failures: 
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] [ERROR]   MemoryTerminationSubscriberTest.dynamicListeningEventsShouldGetOnlyNewEvents 
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] Expecting:
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1]   <[Cancelled(TaskAggregateId(TaskId{value=cfe7a866-9232-455d-acf9-93ea6c579dcb}),EventId{value=42},None)]>
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] to contain exactly (and in same order):
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1]   <[Failed(TaskAggregateId(TaskId{value=2bd08d33-b00d-4715-bde8-bad74c6ce28d}),EventId{value=42},None,None,None),
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1]     Cancelled(TaskAggregateId(TaskId{value=cfe7a866-9232-455d-acf9-93ea6c579dcb}),EventId{value=42},None)]>
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] but could not find the following elements:
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1]   <[Failed(TaskAggregateId(TaskId{value=2bd08d33-b00d-4715-bde8-bad74c6ce28d}),EventId{value=42},None,None,None)]>
```

**Comment by trantienduchn** [comment]
not related, test this please

**Comment by trantienduchn** [comment]
```
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] [INFO] Running org.apache.james.webadmin.WebAdminUtilsTest
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] Exception in thread "Thread-4813" java.lang.RuntimeException: java.io.IOException: Failed to bind to /0.0.0.0:35689
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.apache.james.webadmin.WebAdminServer.lambda$start$1(WebAdminServer.java:95)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at spark.Service.lambda$init$2(Service.java:582)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at java.base/java.lang.Thread.run(Thread.java:834)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] Caused by: java.io.IOException: Failed to bind to /0.0.0.0:35689
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.server.Server.doStart(Server.java:396)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:149)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at spark.Service.lambda$init$2(Service.java:574)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	... 1 more
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] Caused by: java.net.BindException: Address already in use
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at java.base/sun.nio.ch.Net.bind0(Native Method)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at java.base/sun.nio.ch.Net.bind(Net.java:461)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at java.base/sun.nio.ch.Net.bind(Net.java:453)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	... 9 more
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 60.279 s <<< FAILURE! - in org.apache.james.webadmin.WebAdminUtilsTest
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] [ERROR] serverShouldBeAbletoStartConcurrently  Time elapsed: 60.265 s  <<< ERROR!
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] org.apache.james.util.concurrency.ConcurrentTestRunner$NotTerminatedException
[b5d90f2d50485de3f8e73ae21c07aeb4fa9101d1] 	at org.apache.james.webadmin.WebAdminUtilsTest.serverShouldBeAbletoStartConcurrently(WebAdminUtilsTest.java:38)
```

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
