### PR TITLE
JAMES-2399 Cassandra cucumber tests should add plugins

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[ba3ff0a18e8d64845ab92a4557a3bfe58188c1fc] Tests in error: 
[ba3ff0a18e8d64845ab92a4557a3bfe58188c1fc]   NetworkMatcherIntegrationTest.mailsFromAuthorizedNetworksShouldBeDeliveredWithRemoteAddrInNetwork:105 » ConditionTimeout
```

test this please

**Comment by chibenwa** [comment]
test this please

(Anakin executor is too long)

**Comment by chibenwa** [comment]
test this please (Yoda issue)

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
merged

**Pull request closed without merging**
