### PR TITLE
JAMES-2774 Restart docker RabbitMQ each tests in RabbitMQEventBusTest

### PR DESCRIPTION
**Pull request by trantienduchn**
if it doesn't work, then creating new docker rabbitMQ after each test.

### CODE REVIEW

**Comment by Arsnael** [comment]
Wouldn't it be better to do like Cassandra restart if it impacts too much the perf? After a certain number of tests? I'm not sure how much tests we have in total but seems quite a bunch

**Comment by trantienduchn** [comment]
> Wouldn't it be better to do like Cassandra restart if it impacts too much the perf? After a certain number of tests? I'm not sure how much tests we have in total but seems quite a bunch

there are different test cases fails on CI. Eventually I'm not sure this test isolation level can resolve this unstable issue. Me and Dat faced that problem so many time while developing the RabbitMQEventBus...

**Comment by chibenwa** [comment]
IMO depending on "how it goes on" we might want to have a finner grain approach for this matter, allowing to save precious build time - maybe the restart is only needed in th lifecycle test?

We need build time stats to be backing up the decisions taken here IMO

**Comment by trantienduchn** [comment]
Failure count in recent days:
```
 - 14 times: RabbitMQEventBusTest$LifeCycleTest$SingleEventBus.dispatchShouldWorkAfterNetworkIssuesForOldRegistration
 - 1 time: ManageableMailQueueContract.browseShouldNotFailWhenConcurrentClearWhenIterating » IllegalState
 - 1 time: ManageableMailQueueContract.dequeueShouldDecreaseQueueSize:82 » AlreadyClosed ...
 - 1 time: ManageableMailQueueContract.noAckShouldNotDecreaseSize
 - 1 time: ManageableMailQueueContract.dequeueShouldDecreaseQueueSize
 - 1 time: ManageableMailQueueContract.noAckShouldNotDecreaseSize
```

**Comment by chibenwa** [comment]
Yet, I want the time figures ^^

**Comment by trantienduchn** [comment]
Record:
 - Restart every test: 28'
 - original (not restart): ...

**Comment by chibenwa** [comment]
Original: 17:33 min

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
