### PR TITLE
[TEST SPEED] Minimize configuration to optimize boot time

### PR DESCRIPTION
**Pull request by chibenwa**
25% speedup on my laptop, which encourages me running the wall test suite more often

(1 minute gained)

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Review by remk — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`java.net.BindException: Address already in use`

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`[ERROR]   RabbitMQEventDeadLettersIntegrationTest.multipleFailedEventsShouldBeCorrectlyProcessedByListenerAfterSuccessfulGroupRedelivery:531 » ConditionTimeout`

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
