### PR TITLE
JAMES-3357 Add sortOrder field in the created response for Mailbox/set method

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
Rebased on master to resolve conflicts

**Comment by Arsnael** [comment]
```
[405405eab4119ad09283859039088a3c64dbf1db] [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.4.4:compile (scala-compile-first) on project james-server-jmap-rfc-8621: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```
test this please

**Comment by chibenwa** [comment]
It looks related. Did you try running maven locally (on the rebased version)?

**Comment by Arsnael** [comment]
Odd... will check

**Comment by Arsnael** [comment]
```
[819f9ed098cc71dfc166df02c77ad95bd74948fc] [ERROR]   CassandraMailboxManagerConsistencyTest$FailuresOnDeletion$DeleteTwiceThenCreate.createMailboxShouldCreateWhenMailboxPathDaoFailsOnDeleteById:773 » MailboxExists
```
test this please

**Comment by Arsnael** [comment]
Rebased on latest master

**Comment by chibenwa** [comment]
test this please

Failed in deployment tests

**Comment by Arsnael** [comment]
```
[622cbb5761c60a70c87193d81ad9e9b3a1114998] [ERROR] Errors: 
[622cbb5761c60a70c87193d81ad9e9b3a1114998] [ERROR]   RabbitMQEventBusTest$ConcurrentTest.concurrentDispatchKeyShouldDeliverAllEventsToListenersWithSingleEventBus » RetryExhausted
```
test this please

**Comment by Arsnael** [comment]
tests and deployment tests are :green_apple: 

```
[622cbb5761c60a70c87193d81ad9e9b3a1114998] [ERROR] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000633c00000, 484442112, 0) failed; error='Not enough space' (errno=12)
```
will take a look...

test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
