### PR TITLE
JAMES-2310 Improve Netty performances [Contribution]

### PR DESCRIPTION
**Pull request by chibenwa**
See https://github.com/apache/james-project/pull/98

### CODE REVIEW

**Comment by rouazana** [comment]
test this please
OutOfMemory Java heap space

**Comment by rouazana** [comment]
test this please
again OutOfMemory Java heap space

**Comment by chibenwa** [comment]
test this please
again OutOfMemory Java heap space

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
