### PR TITLE
JAMES-2284 Move methods from interface to implementation (deprecate t…

### PR DESCRIPTION
**Pull request by aduprat**
…he interface)

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
```

Failed tests: 
  TasksRoutesTest.listShouldReturnEmptyWhenNonMatchingStatusFilter:155 1 expectation failed.
JSON path  doesn't match.
Expected: a collection with size <0>
  Actual: [{additionalInformation=null, submitDate=2018-01-19T13:47:14.238+0000, type=unknown, taskId=fb2ed537-5bb3-4d70-aaf1-4ec1214aeb57, status=waiting}]
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
