### PR TITLE
JAMES-1680 Support ids parameter in getMailboxes query

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by mbaechler** [comment]
is it a github bug or there's some modifications missing ?

**Comment by aduprat** [comment]
Yes it is, every changes are in the commit ea7d7a227b1de48d39eff319a13dffc5ecb3658e ...

**Comment by rouazana** [comment]
:+1:

**Comment by fvn-linagora** [comment]
:+1:

**Pull request merged**
