### PR TITLE
James-2245 Use cryptographically strong RNG

### PR DESCRIPTION
**Pull request by thithib**
Git was showing me "^M" characters in the first commit diff after editing because it was in dos fileformat (with CRLF terminators). I then converted the two guilty source files to unix fileformat (with LF terminators). I don't know if it was the right thing to do (many source files in the James source tree seem to be using the dos fileformat). If not, sorry, tell me and I will delete the commit.

### CODE REVIEW

**Comment by rouazana** [comment]
Any chance to be blocking due to lack on entropy on production server?

**Comment by rouazana** [comment]
I mean generally the use of SecureRandom should be limited to get a good seed and then use a weaker random function but with this seed. Is it still the case? If yes this PR must be changed.

**Comment by thithib** [comment]
As explained in the Jira ticket, java.util.Random is a Linear Congruential Generator so future values are predictable if an attacker is able to observe enough output values. This has nothing to do with the seed but with the way those pseudo-random numbers are generated (using modular equations).

As for the behavior in case of lack of entropy, blocking might indeed happen if for instance we call SecureRandom methods like nextInt() faster than the OS is able to provide random bytes. I am checking the consequences of using the `NativePRNGNonBlocking` [Number Generation Algorithm](https://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SecureRandom) instead of the default one.

**Comment by thithib** [comment]
Ok so `NativePRNG` is the default for Linux and OS X and it uses `/dev/urandom` as the source of entropy for nextBytes() calls (which nextInt(), nextDouble() and the like depends on) and thus does not block. `NativePRNGBlocking` would be even more robust as it uses `/dev/random` as its entropy source but as a consequence it could block. More information about that [here](https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom/) and [here](https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SecureRandomImp).

That means that the current PR will not cause blocking on Linux and OS X. The PRNG will just "degrade" in terms of randomness in case of heavy demand for random output values.

On Windows, the algorithm defaults to `SHA1PRNG` which, from what I understand, leverages the Windows Crypto API and should not block. But I'm not 100% sure about that currently.

**Pull request merged**
