### PR TITLE
JAMES-3383: Email/Query expose allowed sort in accountCapabilities

### PR DESCRIPTION
**Pull request by nvduc91**
The works already done, just need to adjust the supported options for now:
"receivedAt", "sentAt"

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]
Have you been running `SessionRoutesTest` ?

It should be breaking too.

**Review by chibenwa — APPROVED** [review]
A easy one ;-)

**Comment by chibenwa** [comment]
```
[88f68454fc2788778acf3d133eca6af5010718b0] java.lang.Exception: Timed out wait for be notified that read is complete
[88f68454fc2788778acf3d133eca6af5010718b0] 	at org.apache.james.mpt.DiscardProtocolTest.testRecord(DiscardProtocolTest.java:84)
[88f68454fc2788778acf3d133eca6af5010718b0] 
[88f68454fc2788778acf3d133eca6af5010718b0] [INFO] 
[88f68454fc2788778acf3d133eca6af5010718b0] [INFO] Results:
[88f68454fc2788778acf3d133eca6af5010718b0] [INFO] 
[88f68454fc2788778acf3d133eca6af5010718b0] [ERROR] Errors: 
[88f68454fc2788778acf3d133eca6af5010718b0] [ERROR]   DiscardProtocolTest.testRecord:84 »  Timed out wait for be notified that read ...
```

Already known unfrequent instability - sometime happens.

test this please

**Review by Arsnael — APPROVED** [review]

**Review by remk — APPROVED** [review]

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
