### PR TITLE
[NO_REVIEW] JAMES-2717 Run everything on docker ES

### PR DESCRIPTION
**Pull request by trantienduchn**
Just for testing, It's not meant to be merged

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[8366c2236c5ea127a50a1c7273005ca811392b2c] [ERROR]   CassandraMessageIdToImapUidDAOTest.updateShouldUpdateModSeq:203 
```
test this please

**Comment by trantienduchn** [comment]
```
[0631a359951e7e08bc340bcc42ef35e63aeef938] 2019-05-09 10:03:19,917 WARN  [elasticsearch[Thermo][transport_client_worker][T#7]{New I/O worker #28863}] - [org.elasticsearch.netty.channel.socket.nio.AbstractNioSelector]- Unexpected exception in the selector loop.
[0631a359951e7e08bc340bcc42ef35e63aeef938] java.lang.OutOfMemoryError: Direct buffer memory
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at java.nio.Bits.reserveMemory(Bits.java:695)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.channel.socket.nio.SocketReceiveBufferAllocator.newBuffer(SocketReceiveBufferAllocator.java:64)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.channel.socket.nio.SocketReceiveBufferAllocator.get(SocketReceiveBufferAllocator.java:41)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:62)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[0631a359951e7e08bc340bcc42ef35e63aeef938] 	at java.lang.Thread.run(Thread.java:748)
```
Not so good

**Comment by chibenwa** [comment]
Can you try to restart ES container let's say every 100 test, just to see?

**Comment by chibenwa** [comment]
Or try closing the ES ClientProvider when shutting down James server - this is some kind of leak related to connection not being reused like it was done with the Embedded ES

**Comment by trantienduchn** [comment]
```
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR] Failures: 
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   CassandraBulkOperationTest.setMessagesShouldFailForHugeNumberOfEmailsToTrashWhenChunksConfigurationAreTooBig:118 1 expectation failed.
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] Expected status code <400> but was <200>.
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] 
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR] Errors: 
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   DeletedMessagesVaultTest.setup:130 » Creation Unable to create injector, see t...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
[4bd41b82bd7007626f4b43c70eb3429998e9ab04] [ERROR]   SetVacationResponseTest.setup:70 » Creation Unable to create injector, see the...
```

**Comment by trantienduchn** [comment]
```
[425debcb08865f428cc2c5e9dd7f9df20785df60] [ERROR] shouldSendANoticeWhenThresholdExceeded  Time elapsed: 3.115 s  <<< ERROR!
[425debcb08865f428cc2c5e9dd7f9df20785df60] java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by trantienduchn** [comment]
remember to create a ticket about the cassandra bulk operation bug

**Comment by trantienduchn** [comment]
> remember to create a ticket about the cassandra bulk operation bug

https://ci.linagora.com/linagora/lgs/openpaas/james/issues/1201

**Comment by trantienduchn** [comment]
```
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [ERROR] Failures: 
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [ERROR]   RabbitMQEventBusTest$LifeCycleTest$SingleEventBus.dispatchShouldWorkAfterNetworkIssuesForOldRegistration:323 
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] Wanted but not invoked:
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] mailboxListener.event(
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496]     org.apache.james.mailbox.events.MailboxListener$MailboxAdded@bf1a1130
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] );
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] -> at org.apache.james.mailbox.events.RabbitMQEventBusTest$LifeCycleTest$SingleEventBus.dispatchShouldWorkAfterNetworkIssuesForOldRegistration(RabbitMQEventBusTest.java:323)
```
test this please

**Comment by trantienduchn** [comment]
good new :)
```
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [INFO] Apache James :: Server :: JMAP :: Cassandra Integration testing SUCCESS [28:04 min]
```
```
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [ERROR] Errors: 
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [ERROR]   SpamAssassinContract.movingAMailToTrashShouldNotImpactSpamassassinLearning:370 » ConditionTimeout
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [INFO] 
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [ERROR] Tests run: 718, Failures: 0, Errors: 1, Skipped: 3
```
test this please

**Comment by trantienduchn** [comment]
```
[0832c30b6a4dd359d6de5b23ca9f550ea55f6496] [ERROR]   MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:475 » Execution
```
test this please

**Comment by trantienduchn** [comment]
the goal is achieved

**Pull request closed without merging**
