### PR TITLE
JAMES-1926 hasAttachments should not take care of inline attachments

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by aduprat** [comment]
No, only unit tests for such simple features which modifications impact only one class.

**Comment by rouazana** [comment]
maybe only one class is impacted, but also result from the JMAP api, so it's worth a test, no?

**Comment by chibenwa** [comment]
Please cherry-pick : https://github.com/chibenwa/james-project/commit/8d1747b65343380f121d60d68a9caea9cc60e039 One line integration test... Who say better ?

**Comment by aduprat** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Pull request merged**
