### PR TITLE
JAMES-2599 Grafana board for blobstore metrics

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
I got a problem with grafana, boards is able to display in long time range e.g > 6hs. But decreasing time range to < 6h, grafana doesn't show charts.

**Comment by chibenwa** [comment]
That is not too much of a big deal I already saw this.

Do you have a screenshot?

**Comment by rouazana** [comment]
> That is not too much of a big deal I already saw this.

This is my biggest deal with Grafana, but that's not related to this work.

**Comment by trantienduchn** [comment]
> One more suspicious point. Swift BlobStore upload being to fast, although I used ~20MB files.

Updated there are too many small blob saving operations, then they drag down timer metrics to short time range of saving blobs. When I looked at charts of big blobs storing, I have no way to get it.I think it would be better to have another axis called size goes with timer axis. How do you think?

**Comment by chibenwa** [comment]
It is doable: let's have a look at this tomorrow.

**Comment by chibenwa** [comment]
Merged

**Comment by trantienduchn** [comment]
Grafana board after asynchronize swift blobstore. Sounds reasonable.
new

**Pull request closed without merging**
