### PR TITLE
JAMES-3116 Mutualize count and unseen read/write in CassandraMailboxCounterDAO

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[cf26a516532f86c1f7361de6c3212f80d3c8b0e6] [ERROR] Errors: 
[cf26a516532f86c1f7361de6c3212f80d3c8b0e6] [ERROR]   DiscardProtocolTest.testRecord:84 »  Timed out wait for be notified that read ...
```

test this please

**Comment by mbaechler** [comment]
Good idea, it requires load-testing

**Comment by chibenwa** [comment]
## Before

Capture d’écran de 2020-03-19 13-53-24


## After

Capture d’écran de 2020-03-19 13-53-24

Conclusion: MessageManager::append 10% avarage reduction, p99 average drop

This don't dramatically changes the application behaviour but is a nice enhancement

**Comment by rouazana** [comment]
the images are the same...

**Comment by chibenwa** [comment]
> the images are the same...

My mistake...

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
