### PR TITLE
use try-with-resource in more places

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by trantienduchn** [comment]
test this please

**Comment by chibenwa** [comment]
```
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] Failed tests: 
[341d303c6fd0db5b0f3e4246c544870b6b1f833d]   PaggingTest Multiple Failures (2 failures)
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	<no message> in java.lang.NullPointerException
[341d303c6fd0db5b0f3e4246c544870b6b1f833d]   CassandraSchemaVersionDAOTest Multiple Failures (2 failures)
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	<no message> in java.lang.NullPointerException
[341d303c6fd0db5b0f3e4246c544870b6b1f833d]   CassandraTypeProviderTest.getDefinedUserTypeShouldNotReturnNullNorFailWhenTypeIsDefined Multiple Failures (2 failures)
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	<no message> in java.lang.NullPointerException
[341d303c6fd0db5b0f3e4246c544870b6b1f833d]   CassandraTypeProviderTest.initializeTypesShouldCreateTheTypes Multiple Failures (2 failures)
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	<no message> in java.lang.NullPointerException
[341d303c6fd0db5b0f3e4246c544870b6b1f833d]   CassandraTypeProviderTest.initializeTypesShouldNotFailIfCalledTwice Multiple Failures (2 failures)
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	java.lang.IllegalStateException: Can't use this cluster instance because it was previously closed
[341d303c6fd0db5b0f3e4246c544870b6b1f833d] 	<no message> in java.lang.NullPointerException
```

**Comment by chibenwa** [comment]
Looks like maildir is broken ... 

`[fda43695361ed4f65dc64b1daae4c8a1db97249b] [INFO] Apache James MPT Imap Mailbox - Maildir ............ FAILURE [ 43.994 s]`

**Comment by mbaechler** [comment]
:+1:

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
