### PR TITLE
JAMES-2855 Correct log4j-over-slf4j bridge

### PR DESCRIPTION
**Pull request by trantienduchn**
- Instead of using slf4j-log4j which does it in the reverse way
 - I kept `james-project/server/container/spring/pom.xml` to use log4j and exclude all slf4j dependencies

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[ca241018d59353ebc00bcf5cacc2a470c8a62000] [ERROR]   JettyHttpServerFactoryTest.shouldBeAbleToLoadEmptyMappingConfiguration:76 NoClassDefFound
[ca241018d59353ebc00bcf5cacc2a470c8a62000] [ERROR]   JettyHttpServerFactoryTest.shouldCreateServersAsDescribedInXmlConfiguration:36 NoClassDefFound
[ca241018d59353ebc00bcf5cacc2a470c8a62000] [ERROR]   JettyHttpServerFactoryTest.shouldThrowOnConflictingPortConfiguration:69 » ExceptionInInitializer
[ca241018d59353ebc00bcf5cacc2a470c8a62000] [ERROR]   JettyHttpServerFactoryTest.shouldThrowOnEmptyFilterName:84 NoClassDefFound Cou...
[ca241018d59353ebc00bcf5cacc2a470c8a62000] [ERROR]   JettyHttpServerFactoryTest.shouldThrowOnEmptyServletName:57 NoClassDefFound Co...
[ca241018d59353ebc00bcf5cacc2a470c8a62000] [ERROR]   JettyHttpServerFactoryTest.shouldThrowOnUnavailableFilterName:90 NoClassDefFound
[ca241018d59353ebc00bcf5cacc2a470c8a62000] [ERROR]   JettyHttpServerFactoryTest.shouldThrowOnUnavailableServletName:63 NoClassDefFound
```

**Comment by chibenwa** [comment]
`assandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution` test this please

**Comment by chibenwa** [comment]
```
[31467dad723cad646a795b5a7b40a53a2185d50a] [ERROR] testConfProtocolSouldReturnConfFile(org.apache.james.container.spring.filesystem.FileSystemImplTest)  Time elapsed: 0 s  <<< ERROR!
[31467dad723cad646a795b5a7b40a53a2185d50a] java.lang.NoClassDefFoundError: Could not initialize class spark.Service
[31467dad723cad646a795b5a7b40a53a2185d50a] 
[31467dad723cad646a795b5a7b40a53a2185d50a] [ERROR] testConfProtocolSouldReturnConfFile(org.apache.james.container.spring.filesystem.FileSystemImplTest)  Time elapsed: 0 s  <<< ERROR!
[31467dad723cad646a795b5a7b40a53a2185d50a] java.lang.NullPointerException
```

What's going on here?

**Comment by trantienduchn** [comment]
```
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] SLF4J: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. 
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] SLF4J: See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] Exception in thread "main" java.lang.ExceptionInInitializerError
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] 	at org.apache.james.cli.ServerCmd.<clinit>(ServerCmd.java:79)
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] Caused by: java.lang.IllegalStateException: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details
```
fails at deployment tests

**Comment by chibenwa** [comment]
**Proposal**: migrate Spring logging with *logback*. This requires a vote and decent communication on user mailing list...

**Comment by trantienduchn** [comment]
```
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] + docker logs james-server-spring-configurations2-slf4j-bridge-eac89066-586a-46ea-80be-aefe5ae034d8
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] wrapper  | --> Wrapper Started as Console
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] wrapper  | Launching a JVM...
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | 
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | SLF4J: Detected both log4j-over-slf4j.jar AND bound slf4j-log4j12.jar on the class path, preempting StackOverflowError. 
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | SLF4J: See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | WrapperSimpleApp: Unable to locate the class org.apache.james.app.spring.JamesAppSpringMain: java.lang.ExceptionInInitializerError
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | 
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | WrapperSimpleApp Usage:
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    |   java org.tanukisoftware.wrapper.WrapperSimpleApp {app_class} [app_arguments]
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | 
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    | Where:
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    |   app_class:      The fully qualified class name of the application to run.
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    |   app_arguments:  The arguments that would normally be passed to the
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] jvm 1    |                   application.
[8101d1c1bade19ca994fdd69f6e24fcef4ad2245] wrapper  | <-- Wrapper Stopped
```

**Comment by trantienduchn** [comment]
weird, mvn dependency:tree doesn't show any `log4j-over-slf4j` in spring project

**Comment by chibenwa** [comment]
test this please (restart)

**Comment by trantienduchn** [comment]
```
[681a06a48d0a1557fc45847f399ed018096c7563] [ERROR] Errors: 
[681a06a48d0a1557fc45847f399ed018096c7563] [ERROR]   MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:495 » Execution
```
test this please

**Comment by trantienduchn** [comment]
:beers: yesssss

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
