### PR TITLE
JAMES-2808 Play search contract over BlobStore DeletedMessageVault

### PR DESCRIPTION
**Pull request by chibenwa**
See https://github.com/linagora/james-project/pull/2520

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[68d339c8bb7b124a522fea5ea2be1462a8eab611] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:499
[68d339c8bb7b124a522fea5ea2be1462a8eab611] LastClientMsg: c SEARCH FLAGGED
[68d339c8bb7b124a522fea5ea2be1462a8eab611] Expected: '\* SEARCH 1 2 3 4'
[68d339c8bb7b124a522fea5ea2be1462a8eab611] Actual   : '* SEARCH'
```
can be considered :green_apple:

**Comment by trantienduchn** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
