### PR TITLE
JAMES-1950 Add JVM metrics in Grafana

### PR DESCRIPTION
**Pull request by chibenwa**
List of added metrics (obtained threw inspection) (? might require finding applicable value indexed on ES): 

 - **jvm.file.descriptor** : ratio of open/max file descriptors

-------------------------------------------------------

 - **jvm.gc.?.count** : count of GC
 - **jvm.gc.?.time** : time in GC

-------------------------------------------------------

 - **jvm.threads.count** : Count of threads
 - **jvm.threads.new.count**
 - **jvm.threads.runnable.count**
 - **jvm.threads.blocked.count**
 - **jvm.threads.waiting.count**
 - **jvm.threads.timed_waiting.count**
 - **jvm.threads.terminated.count**
 - **jvm.threads.daemon.count**
 - **jvm.threads.deadlock.count**

-------------------------------------------------------

 - **jvm.memory.total.init**
 - **jvm.memory.total.used**
 - **jvm.memory.total.max**
 - **jvm.memory.total.committed**
 - **jvm.memory.heap.init**
 - **jvm.memory.heap.used**
 - **jvm.memory.heap.max**
 - **jvm.memory.heap.committed**
 - **jvm.memory.heap.usage** (ratio)
 - **jvm.memory.non-heap.init**
 - **jvm.memory.non-heap.used**
 - **jvm.memory.non-heap.max**
 - **jvm.memory.non-heap.committed**
 - **jvm.memory.non-heap.usage** (ratio)
 - **jvm.memory.heap.init**
 - **jvm.memory.total.init**
 - **jvm.memory.total.init**
 - **jvm.memory.total.init**
 - **jvm.memory.total.init**
 - **jvm.memory.pools.?.usage** (Ratio)
 - **jvm.memory.pools.?.max**
 - **jvm.memory.pools.?.used**
 - **jvm.memory.pools.?.committed**
 - **jvm.memory.pools.?.used-after-gc**
 - **jvm.memory.pools.?.init**

-------------------------------------------------------

 - **jvm.class.loading.loaded**
 - **jvm.class.loading.unloaded**

### CODE REVIEW

**Comment by quynhn** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
