### PR TITLE
JAMES-2074 Build projects in parallel

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by rouazana** [comment]
```
[a910f14dce8f8448131061190a4c03af6e8396f4] [BuilderThread 1] [ERROR] Errors: 
[a910f14dce8f8448131061190a4c03af6e8396f4] [BuilderThread 1] [ERROR]   CassandraEventSourcingDLPConfigurationStoreTest » NoClassDefFound Could not in...
[a910f14dce8f8448131061190a4c03af6e8396f4] [BuilderThread 1] [ERROR]   CassandraMailRepositoryUrlStoreTest » ExceptionInInitializer
[a910f14dce8f8448131061190a4c03af6e8396f4] [BuilderThread 1] [INFO] 
[a910f14dce8f8448131061190a4c03af6e8396f4] [BuilderThread 1] [ERROR] Tests run: 82, Failures: 53, Errors: 2, Skipped: 0
[a910f14dce8f8448131061190a4c03af6e8396f4] [BuilderThread 1] [INFO] 
```

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
:green_apple: in 1 hr 30 min
test this please

**Comment by aduprat** [comment]
```
[m2ain] [ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[main] [ERROR] Command was /bin/sh -c cd /james-project/server/protocols/webadmin/webadmin-data && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms512m -Xmx1024m -jar /james-project/server/protocols/webadmin/webadmin-data/target/surefire/surefirebooter2996262105780372141.jar /james-project/server/protocols/webadmin/webadmin-data/target/surefire 2018-08-29T11-23-33_614-jvmRun16 surefire1024863897325772630tmp surefire_3102476451960425018501tmp
[main] [ERROR] Error occurred in starting fork, check output in log
[main] [ERROR] Process Exit Code: 100
[main] [ERROR] Crashed tests:
[main] [ERROR] org.apache.james.webadmin.routes.GroupsRoutesTest$NormalBehaviour
[main] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[main] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[main] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$600(ForkStarter.java:115)
[main] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:362)
[main] [ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$1.call(ForkStarter.java:342)
[main] [ERROR] 	... 4 more
```
test this please

**Comment by aduprat** [comment]
```
[BuilderThread 2] [ERROR]   SpamAssassinInvokerTest.learnAsHamShouldReturnTrueWhenLearningWorks:116 » UncheckedIO
```

**Comment by aduprat** [comment]
```
[BuilderThread 2] [ERROR]   SpamAssassinInvokerTest.learnAsHamShouldReturnTrueWhenLearningWorks:116 » UncheckedIO
\\\

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
```
[c4d84c17324a53aaaa6f9553f8fc91be29b9a2ca] ely affect performance. Consider preparing the statement only once. [main] [INFO] Apache James :: Server :: Data :: JCR Persistence .. SUCCESS [ 25.847 s]
[c4d84c17324a53aaaa6f9553f8fc91be29b9a2ca] Query='INSERT INTO modseq (nextModseq,mailboxId)[main] [INFO] Apache James :: Server :: Data :: JDBC Persistence . FAILURE [01:20 min]
[c4d84c17324a53aaaa6f9553f8fc91be29b9a2ca]  VALUES (:nextModseq,:mailboxId) IF NOT EXISTS;'
```

test this please

**Comment by aduprat** [comment]
```
[BuilderThread 2] [ERROR]   SpamAssassinInvokerTest.scanMailShouldModifyHitsField:52 » UncheckedIO java.ne...
```

**Comment by aduprat** [comment]
```
09:54:16.[BuilderThread 3] [ERROR]   SpamAssassinInvokerTest.scanMailShouldMarkAsSpamWhenMessageAlreadyLearnedAsSpam:104 » UncheckedIO
```

**Comment by chibenwa** [comment]
Conflicts, port binding issues had not been solved (thanks JMX)

**Pull request closed without merging**
