### PR TITLE
James 1852 - Have the side menus for James-project

### PR DESCRIPTION
**Pull request by chibenwa**
screenshot from 2016-10-27 10-59-30

screenshot from 2016-10-27 10-59-42

screenshot from 2016-10-27 10-59-57

screenshot from 2016-10-27 11-00-03

screenshot from 2016-10-27 11-00-18

screenshot from 2016-10-27 11-00-26

screenshot from 2016-10-27 11-00-33

### CODE REVIEW

**Comment by chibenwa** [comment]
New pages  : 

screenshot from 2016-10-27 12-00-13

screenshot from 2016-10-27 12-00-17

**Comment by chibenwa** [comment]
screenshot from 2016-10-27 12-06-18

**Comment by Laura-Royet** [comment]
- "James component" must me removed from the side menu.
- On each landing page project the "Overview" part is not clearly mentioned because you chose that these overview pages correspond to the link behind each name project button. I think it's not obvious for a user to click on the name project to access to its overview. This is due to the fact that each name project button already contain subsections. I think that a name part should not be a link to an overview page.
- In Server part:
      - "Sources on GitHub" should be replaced by "Sources" as the sources are also on Apache.
      - Advantages page: this page should not contains the title "Advantages" as we never repeat the name part as the title of a page and the six advantages must be shown as six parts with level title you are using here for "Advantages"
- In Mailets part: could you move "Javadoc" before "Issue Tracker" to keep the same order everywhere.
- In Mailbox part:  you chose that "Framework" section is the name of a subsection as well as the page containing the content of the previous "Mailbox API" page?
- In Protocols part: "Download releases" link is missing.

**Comment by chibenwa** [comment]
it's hard to answer your comments individually as you make it being one big comment on github

**Comment by chibenwa** [comment]
> "James component" must me removed from the side menu.

Menus needs a name

**Comment by chibenwa** [comment]
> On each landing page project the "Overview" part is not clearly mentioned because you chose that these overview pages correspond to the link behind each name project button. I think it's not obvious for a user to click on the name project to access to its overview. This is due to the fact that each name project button already contain subsections. I think that a name part should not be a link to an overview page.

I need a landing page. Should I create a blank one ? Do you want me to duplicate, and add an Overview entry ?

**Comment by chibenwa** [comment]
> "Sources on GitHub" should be replaced by "Sources" as the sources are also on Apache.

Ok

**Comment by chibenwa** [comment]
> Advantages page: this page should not contains the title "Advantages" as we never repeat the name part as the title of a page and the six advantages must be shown as six parts with level title you are using here for "Advantages"

Ok

**Comment by chibenwa** [comment]
> In Mailets part: could you move "Javadoc" before "Issue Tracker" to keep the same order everywhere.

Ok

**Comment by chibenwa** [comment]
> In Protocols part: "Download releases" link is missing.

Ok

**Comment by chibenwa** [comment]
> In Mailbox part: you chose that "Framework" section is the name of a subsection as well as the page containing the content of the previous "Mailbox API" page?

Yep, I need a landing page there and don't want to introduce new pages. I got a NPE when I put collapse=false, I don't want to invest time on the issue.

**Comment by Laura-Royet** [comment]
Yes, sorry about  the too big comment.
OK to keep "James component" as the name menu.
OK to remove "overview" page on each project.
OK for your answer about section Mailbox part.

**Pull request merged**
