### PR TITLE
JAMES-3420 Avoid logging user password upon webadmin user creation

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by nvduc91 — APPROVED** [review]
cool!

**Comment by chibenwa** [comment]
`docker: Error response from daemon: No such container: git-publish-avoid-pwd-cff28e9b-9afc-4406-98f1-64420cebb07b`

mvn tests :green_apple: 

test this please

**Comment by chibenwa** [comment]
test this please

**Review by LanKhuat — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
