### PR TITLE
JAMES-2074 Run James on random ports (clone)

### PR DESCRIPTION
**Pull request by trantienduchn**
clone of https://github.com/linagora/james-project/pull/1640
Ci build didn't get triggered

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[ccadd972e138822c9a875be901c99cdff1b70a49] [ERROR] Errors: 
[ccadd972e138822c9a875be901c99cdff1b70a49] [ERROR]   SpamAssassinContract.spamShouldBeDeliveredInSpamMailboxWhenSameMessageHasAlreadyBeenMovedToSpam:136 » ConditionTimeout
[ccadd972e138822c9a875be901c99cdff1b70a49] [INFO] 
[ccadd972e138822c9a875be901c99cdff1b70a49] [ERROR] Tests run: 608, Failures: 0, Errors: 1, Skipped: 1
```
test this please

**Comment by chibenwa** [comment]
I will remove the parrallel execution part as discussed a few days before

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Forced pushed to solve conflict

**Comment by chibenwa** [comment]
CI is no more triggered

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/pull/1696

**Pull request closed without merging**
