### PR TITLE
JAMES-2799 GhostMailbox logs should be in debug level

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[e6d4f2c8743a684d292af37e0738a7e3cd7a39e9] [ERROR] Errors: 
[e6d4f2c8743a684d292af37e0738a7e3cd7a39e9] [ERROR]   SetMessagesMethodTest.setup:162 » ElasticsearchStatus Elasticsearch exception ...
```
test this please

**Comment by Arsnael** [comment]
```
[e6d4f2c8743a684d292af37e0738a7e3cd7a39e9] [ERROR] Errors: 
[e6d4f2c8743a684d292af37e0738a7e3cd7a39e9] [ERROR]   RabbitMQEventBusTest$LifeCycleTest$SingleEventBus$DispatchingWhenNetWorkIssue.dispatchShouldWorkAfterNetworkIssuesForOldRegistration:366 » ConditionTimeout
```
test this please

**Comment by mbaechler** [comment]
```
Caused by: hudson.AbortException: missing workspace /home/jenkins/build/workspace/714 on ci-james-04
```
My CI is crazy

test this please

**Comment by Arsnael** [comment]
```
[e6d4f2c8743a684d292af37e0738a7e3cd7a39e9] ADD failed: stat /var/lib/docker/tmp/docker-builder665770916/destination/james-server-cassandra-ldap-guice.jar: no such file or directory
```

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
