### PR TITLE
use OP current version of RabbitMQ to check James compatibility

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by mbaechler** [comment]
```

[31fe3937c70749957f5ea2ae63079b74e15b1993] [ERROR] sendingOneHundredMessagesShouldBeRandomlyAssignedToEveryMailboxesOfEveryUsers  Time elapsed: 322.707 s  <<< ERROR!
[31fe3937c70749957f5ea2ae63079b74e15b1993] org.awaitility.core.ConditionTimeoutException: 
[31fe3937c70749957f5ea2ae63079b74e15b1993] Assertion condition defined as a lambda expression in org.apache.james.smtp.SmtpRandomStoringTest 
[31fe3937c70749957f5ea2ae63079b74e15b1993] Expecting:
[31fe3937c70749957f5ea2ae63079b74e15b1993]  <121L>
[31fe3937c70749957f5ea2ae63079b74e15b1993] to be between:
[31fe3937c70749957f5ea2ae63079b74e15b1993]  [400L, 800L] within 10 seconds.
[31fe3937c70749957f5ea2ae63079b74e15b1993] 	at org.apache.james.smtp.SmtpRandomStoringTest.sendingOneHundredMessagesShouldBeRandomlyAssignedToEveryMailboxesOfEveryUsers(SmtpRandomStoringTest.java:156)
[31fe3937c70749957f5ea2ae63079b74e15b1993] Caused by: java.lang.AssertionError: 
[31fe3937c70749957f5ea2ae63079b74e15b1993] 
[31fe3937c70749957f5ea2ae63079b74e15b1993] Expecting:
[31fe3937c70749957f5ea2ae63079b74e15b1993]  <121L>
[31fe3937c70749957f5ea2ae63079b74e15b1993] to be between:
[31fe3937c70749957f5ea2ae63079b74e15b1993]  [400L, 800L]
[31fe3937c70749957f5ea2ae63079b74e15b1993] 	at org.apache.james.smtp.SmtpRandomStoringTest.checkMailboxesHaveBeenFilled(SmtpRandomStoringTest.java:178)
[31fe3937c70749957f5ea2ae63079b74e15b1993] 	at org.apache.james.smtp.SmtpRandomStoringTest.lambda$sendingOneHundredMessagesShouldBeRandomlyAssignedToEveryMailboxesOfEveryUsers$4(SmtpRandomStoringTest.java:156)
```

Doesn't seem related

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[INFO] Apache James :: Mailbox :: Event :: RabbitMQ implementation FAILURE [04:16 min]
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
it was green before CI restart

**Comment by mbaechler** [comment]
I close it, we know we can merge it if needed.

**Pull request closed without merging**
