### PR TITLE
JAMES-3115 Fail when typo in mailet-container configuration file

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by trantienduchn** [comment]
a test ?

**Comment by chibenwa** [comment]
> a test ?

Can't be tested easily as you can't inject a HierarchicalConfiguration object (our current testing strategy) as the xml is not valid, and we can hardly swap classpath configuration files.

Sorry.

**Comment by mbaechler** [comment]
`ConfigurationProvider` being an interface you can at least test part of your modifications I guess

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
