### PR TITLE
JAMES-3105 Limit concurrency of mailbox counters recomputation

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by mbaechler** [comment]
Why do we need to limit that? Did you observe something wrong?

**Comment by chibenwa** [comment]
> Why do we need to limit that? Did you observe something wrong?

2 nested flatMaps makes 16*16 = 256 potentially concurrent operations which is the pool size of the cassandra driver

I thus observe many "busy pool" exception.

**Comment by chibenwa** [comment]
An alternative would be to increase driver pool size.

**Comment by mbaechler** [comment]
Thank you for the explanation, what about reasoning on the actual driver capacity to choose the right numbers?

We could:
1. have high-priority/low-priority work queues for cassandra queries
2. tag low-priority queries to avoid them to make interactive traffic slow
3. use reactor to limit the number of queries at any given time (align pending queries capacity to the number of concurrent queries we run in reactor)

That would allow to tune the number of concurrent queries without breaking the application

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
