### PR TITLE
JAMES-2607 don't warn on missing batchsizes configuration file

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by mbaechler** [comment]
CI is trying to apply the PR on top of master instead of using the PR target.

**Comment by hoangdat** [comment]
Build triggered. sha1 is merged.

**Comment by hoangdat** [comment]
Build started sha1 is merged.

**Comment by hoangdat** [comment]
Build finished. No test results found.

**Comment by hoangdat** [comment]
Build triggered. sha1 is merged.

**Comment by hoangdat** [comment]
Build started sha1 is merged.

**Comment by trantienduchn** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
```
[ERROR] Errors: 
[ERROR]   SpamAssassinInvokerTest.learnAsHamShouldAllowToForgetSpam » ContainerFetch Can...
[ERROR]   SpamAssassinInvokerTest.learnAsHamShouldReturnTrueWhenLearningWorks » ContainerFetch
[ERROR]   SpamAssassinInvokerTest.learnAsSpamShouldReturnTrueWhenLearningWorks » ContainerFetch
[ERROR]   SpamAssassinInvokerTest.scanMailShouldMarkAsHamWhenMessageAlreadyLearnedAsHam » ContainerFetch
[ERROR]   SpamAssassinInvokerTest.scanMailShouldMarkAsSpamWhenKnownAsSpam » ContainerFetch
[ERROR]   SpamAssassinInvokerTest.scanMailShouldMarkAsSpamWhenMessageAlreadyLearnedAsSpam » ContainerFetch
[ERROR]   SpamAssassinInvokerTest.scanMailShouldModifyHeadersField » ContainerFetch Can'...
[ERROR]   SpamAssassinInvokerTest.scanMailShouldModifyHitsField » ContainerFetch Can't g...
[ERROR]   SpamAssassinInvokerTest.scanMailShouldModifyRequiredHitsField » ContainerFetch
```
test this please

**Comment by chibenwa** [comment]
You need to backport the SPamAssassin 3.4.2 fix

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
won't backport

**Comment by aduprat** [comment]
test this please

**Pull request closed without merging**
