### PR TITLE
JAMES-3117 PeriodicalHealthChecksTest should use reactive health check

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by mbaechler** [comment]
It's not clear, aside the tag, that the tests were broken. Could you mention that in the commit message, please?

**Comment by chibenwa** [comment]
> It's not clear, aside the tag, that the tests were broken. Could you mention that in the commit message, please?

Will do upon merge.

**Comment by chibenwa** [comment]
(And I **hate** mocks)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
