### PR TITLE
James 2476 Upgrade Lucene

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please (no build output)

**Comment by trantienduchn** [comment]
test this please (no build output)

**Comment by chibenwa** [comment]
Can be considered :green_apple: 

(would need a master rebase)

**Comment by trantienduchn** [comment]
rebased

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
🍏

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
