### PR TITLE
[Build time] Speedup ComputeMessageFastViewProjectionListenerTest

### PR DESCRIPTION
**Pull request by chibenwa**
One minute build time gains

### CODE REVIEW

**Comment by chibenwa** [comment]
> could you explain why it speeds up tests?

Because we ensured it do end up in dead-letter, which takes 8 retries of 100ms with a 0.5 jitter factor... That's long.

**Comment by chibenwa** [comment]
merged

**Comment by mbaechler** [comment]
> > could you explain why it speeds up tests?
> 
> Because we ensured it do end up in dead-letter, which takes 8 retries of 100ms with a 0.5 jitter factor... That's long.

It should be written as a comment in the code

**Comment by chibenwa** [comment]
Here you are, even if I concider this quite obvious https://github.com/linagora/james-project/pull/3236

**Pull request closed without merging**
