### PR TITLE
WIP - static cassandra setup in test

### PR DESCRIPTION
**Pull request by remk**
Define cassandra setup in unit test as static.
Allow to avoid re-preparing all prepared statement which give the two following benefits : 
- no more logs pollution
- slightly faster unit test

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[63e1eda894040899cc7a438d6cea8aafc4024388] Step 4/22 : ADD destination/james-server-app-3.4.0-SNAPSHOT-app.zip /root/james-server-app-3.4.0-SNAPSHOT-app.zip
[63e1eda894040899cc7a438d6cea8aafc4024388] ADD failed: stat /var/lib/docker/tmp/docker-builder616848163/destination/james-server-app-3.4.0-SNAPSHOT-app.zip: no such file or directory
```

**Comment by mbaechler** [comment]
The logs is not a real problem, it can easily be ignored with some config.
How much time do we gain?
it breaks isolation between tests further so it should come with a high gain to worth it

**Comment by remk** [comment]
> The logs is not a real problem, it can easily be ignored with some config.
> How much time do we gain?
> it breaks isolation between tests further so it should come with a high gain to worth it

I don't think that we lose so much isolation. 
The cassandra db was already shared between tests.
The tables are still truncated after each tests

The goal is really to initialize the DAO only once.

**Comment by mbaechler** [comment]
Ok

**Comment by remk** [comment]
test this please

**Comment by remk** [comment]
test this please

**Comment by chibenwa** [comment]
```
[7bbc6733f8d543730f474bb55a0f6282a47764c8] [ERROR] Errors: 
[7bbc6733f8d543730f474bb55a0f6282a47764c8] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
```

test this please

**Comment by remk** [comment]
```
Could not update commit status of the Pull Request on GitHub.
java.io.IOException: {
  "documentation_url": "https://developer.github.com/v3/#abuse-rate-limits",
  "message": "You have triggered an abuse detection mechanism. Please wait a few minutes before you try again."
```

test this please

**Comment by mbaechler** [comment]
I didn't get that we are actually testing the same instance of DAOs in several tests.
I don't agree to do that, i'm pretty sure we gain almost nothing in term of execution time while lowering isolation a lot.

**Comment by remk** [comment]
> I didn't get that we are actually testing the same instance of DAOs in several tests.
> I don't agree to do that, i'm pretty sure we gain almost nothing in term of execution time while lowering isolation a lot.

The DAO are supposed to be immutable. No ?

**Comment by mbaechler** [comment]
> The DAO are supposed to be immutable. No ?

The tests are supposed to check some properties.

First, there's no such DAO-are-immutable rule.
Second, if we want to define this rule, there's nothing to enforce it.

The less you assume to work (from the test point of view), the more your tests help you.

**Pull request closed without merging**
