### PR TITLE
Run intellij inspections : java language feature migration

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
```
[f2f88030c17c6911f0e7ec62d5b0b80770830d63] [ERROR] src/main/java/org/apache/james/protocols/netty/NettyProtocolTransport.java:[27,8] (imports) UnusedImports: Unused import - java.util.Iterator.
```

**Comment by chibenwa** [comment]
```
[INFO] Apache James :: Protocols :: LMTP .................. FAILURE [  0.636 s]
Checkstyle violation

[efa901b05a58d54365396f7ae95a4ed4f6763659] [ERROR] src/main/java/org/apache/james/protocols/lmtp/core/DataLineMessageHookHandler.java:[23,8] (imports) UnusedImports: Unused import - java.util.Iterator.
```

**Comment by Arsnael** [comment]
```
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR] Errors: 
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.connectIMAPServerShouldSendShabangOnConnect » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.connectLMTPServerShouldSendShabangOnConnect » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.connectOnSecondaryIMAPServerIMAPServerShouldSendShabangOnConnect » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.connectPOP3ServerShouldSendShabangOnConnect » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.connectSMTPServerShouldSendShabangOnConnect » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.copyBatchSizeShouldEqualsConfigurationValue » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.hostnameShouldBeRetrievedWhenRestarting » Creation Un...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.hostnameShouldBeUsedAsDefaultDomain » Creation Unable...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJamesServerTest.moveBatchSizeShouldEqualsConfigurationValue » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraJmapJamesServerTest.connectJMAPServerShouldRespondBadRequest » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraMailRepositoryIntegrationTest.deniedSenderMailShouldBeStoredInCassandraMailRepositoryWhenConfigured » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraNodeConfTest$NormalBehaviour.serverShouldStartServiceWhenNodeIsReachable:80 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraNodeConfTest$OneFailedNode.serverShouldStartServiceWhenNodeIsReachable:100 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraNodeConfTest$UseMappedPort.configShouldWorkWithNonDefaultPort:117 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraWithTikaTest.connectIMAPServerShouldSendShabangOnConnect » Creation U...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraWithTikaTest.connectLMTPServerShouldSendShabangOnConnect » Creation U...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraWithTikaTest.connectOnSecondaryIMAPServerIMAPServerShouldSendShabangOnConnect » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraWithTikaTest.connectPOP3ServerShouldSendShabangOnConnect » Creation U...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraWithTikaTest.connectSMTPServerShouldSendShabangOnConnect » Creation U...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraWithTikaTest.hostnameShouldBeRetrievedWhenRestarting » Creation Unabl...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraWithTikaTest.hostnameShouldBeUsedAsDefaultDomain » Creation Unable to...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   DefaultCassandraJamesServerTest.cassandraJamesServerShouldStartWithNoConfigurationFile » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   ESReporterTest.timeMetricsShouldBeReportedWhenImapCommandsReceived » Creation ...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   ESReporterTest.timeMetricsShouldBeReportedWhenJmapRequestsReceived » Creation ...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   FixingGhostMailboxTest.ghostMailboxBugShouldChangeMailboxId » Creation Unable ...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   FixingGhostMailboxTest.ghostMailboxBugShouldDiscardOldContent » Creation Unabl...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   FixingGhostMailboxTest.mergingMailboxTaskShouldBeInformative » Creation Unable...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   FixingGhostMailboxTest.oldGhostedMailboxShouldNoMoreBeAccessible » Creation Un...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   FixingGhostMailboxTest.webadminCanMergeTwoMailboxes » Creation Unable to creat...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   FixingGhostMailboxTest.webadminCanMergeTwoMailboxesRights » Creation Unable to...
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToCassandraWhenStartService:90->assertThatServerStartCorrectly:114 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToElasticSearchWhenStartService:99->assertThatServerStartCorrectly:114 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldStartAtDefault:81->assertThatServerStartCorrectly:114 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraSchemaVersionStartUpCheckTest.serverShouldStartSuccessfullyWhenBetweenMinAndMaxVersion:105 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraSchemaVersionStartUpCheckTest.serverShouldStartSuccessfullyWhenMaxVersion:95 » Creation
[3566826edea2de4fe896c8ae79d55b3387ad3319] [ERROR]   CassandraSchemaVersionStartUpCheckTest.serverShouldStartSuccessfullyWhenMinVersion:115 » Creation
```

**Comment by chibenwa** [comment]
```
[3566826edea2de4fe896c8ae79d55b3387ad3319] 1) No implementation for java.util.Set<org.apache.james.eventsourcing.eventstore.cassandra.dto.EventDTOModule<?, ?>> was bound.
[3566826edea2de4fe896c8ae79d55b3387ad3319]   while locating java.util.Set<org.apache.james.eventsourcing.eventstore.cassandra.dto.EventDTOModule<?, ?>>
[3566826edea2de4fe896c8ae79d55b3387ad3319]     for the 1st parameter of org.apache.james.eventsourcing.eventstore.cassandra.JsonEventSerializer.<init>(JsonEventSerializer.java:52)
[3566826edea2de4fe896c8ae79d55b3387ad3319]   while locating org.apache.james.eventsourcing.eventstore.cassandra.JsonEventSerializer
[3566826edea2de4fe896c8ae79d55b3387ad3319]     for the 2nd parameter of org.apache.james.eventsourcing.eventstore.cassandra.EventStoreDao.<init>(EventStoreDao.java:57)
[3566826edea2de4fe896c8ae79d55b3387ad3319]   while locating org.apache.james.eventsourcing.eventstore.cassandra.EventStoreDao
[3566826edea2de4fe896c8ae79d55b3387ad3319]     for the 1st parameter of org.apache.james.eventsourcing.eventstore.cassandra.CassandraEventStore.<init>(CassandraEventStore.java:39)
[3566826edea2de4fe896c8ae79d55b3387ad3319]   at org.apache.james.modules.eventstore.CassandraEventStoreModule.configure(CassandraEventStoreModule.java:35) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.apache.james.modules.eventstore.CassandraEventStoreModule)
```

**Comment by chibenwa** [comment]
```

[9fdf448c4cc6af03dc9abe6873687b4ac1ac17e4] [ERROR]   ObjectStorageBlobsDAOTest » ExceptionInInitializer
[9fdf448c4cc6af03dc9abe6873687b4ac1ac17e4] [ERROR]   SwiftKeystone2ObjectStorageBlobsDAOBuilderTest » NoClassDefFound Could not ini...
[9fdf448c4cc6af03dc9abe6873687b4ac1ac17e4] [ERROR]   SwiftKeystone3ObjectStorageBlobsDAOBuilderTest » NoClassDefFound Could not ini...
[9fdf448c4cc6af03dc9abe6873687b4ac1ac17e4] [ERROR]   SwiftTempAuthObjectStorageBlobsDAOBuilderTest » NoClassDefFound Could not init...
```

**Comment by chibenwa** [comment]
```
[7414c2af92c15ed972f8d25831d208d50f704d1d] 
[7414c2af92c15ed972f8d25831d208d50f704d1d] [ERROR] Retrieving message should display keywords as jmap flag  Time elapsed: 1.559 s  <<< ERROR!
[7414c2af92c15ed972f8d25831d208d50f704d1d] com.google.inject.ConfigurationException: 
[7414c2af92c15ed972f8d25831d208d50f704d1d] Guice configuration errors:
[7414c2af92c15ed972f8d25831d208d50f704d1d] 
[7414c2af92c15ed972f8d25831d208d50f704d1d] 1) No implementation for org.apache.commons.configuration2.HierarchicalConfiguration<org.apache.commons.configuration2.tree.ImmutableNode> was bound.
[7414c2af92c15ed972f8d25831d208d50f704d1d]   Did you mean?
[7414c2af92c15ed972f8d25831d208d50f704d1d]     org.apache.commons.configuration2.HierarchicalConfiguration bound  at org.apache.james.modules.mailbox.MailboxListenerFactory$MailboxListenerBuilder.lambda$build$1(MailboxListenerFactory.java:78)
[7414c2af92c15ed972f8d25831d208d50f704d1d] 
[7414c2af92c15ed972f8d25831d208d50f704d1d]   while locating org.apache.commons.configuration2.HierarchicalConfiguration<org.apache.commons.configuration2.tree.ImmutableNode>
[7414c2af92c15ed972f8d25831d208d50f704d1d]     for the 5th parameter of org.apache.james.mailbox.quota.mailing.listeners.QuotaThresholdCrossingListener.<init>(QuotaThresholdCrossingListener.java:57)
[7414c2af92c15ed972f8d25831d208d50f704d1d]   while locating org.apache.james.mailbox.quota.mailing.listeners.QuotaThresholdCrossingListener
[7414c2af92c15ed972f8d25831d208d50f704d1d] 
```

eg CassandraGetMailboxesMethodTest

**Comment by chibenwa** [comment]
Just rebased.

**Comment by chibenwa** [comment]
```
[cce490f7c8cf3be8b641cb5ee87494af1c814677] java.io.IOException: Failed to bind to /0.0.0.0:38537
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.server.Server.doStart(Server.java:396)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:149)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at spark.Service.lambda$init$2(Service.java:574)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at java.base/java.lang.Thread.run(Thread.java:834)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] Caused by: java.net.BindException: Address already in use
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at java.base/sun.nio.ch.Net.bind0(Native Method)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at java.base/sun.nio.ch.Net.bind(Net.java:461)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at java.base/sun.nio.ch.Net.bind(Net.java:453)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)
[cce490f7c8cf3be8b641cb5ee87494af1c814677] 	... 9 common frames omitted
```

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
