### PR TITLE
JAMES-2855 Upgrade maven-surefire-plugin 2.22.0 -> 2.22.2

### PR DESCRIPTION
**Pull request by trantienduchn**
This suppose to resolve the bug of junit engine can not run tests

### CODE REVIEW

**Comment by trantienduchn** [comment]
relates to #2612

**Comment by chibenwa** [comment]
```
[0e4d0a8e954584d529c4fca8f028c81cce1d475b] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project james-server-lifecycle-api: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test failed: java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory: org.junit.platform.launcher.core.LauncherFactory -> [Help 1]
```

**Comment by trantienduchn** [comment]
IDK why it doesn't happen on my machine, same enviorinment, same maven, same junit, same platform, test this please

**Comment by chibenwa** [comment]
Try "docker compilation" on your machine as well, this is the reference environment

**Comment by Arsnael** [comment]
Could reproduce it on local, with docker compilation without skipping tests... seems adding `junit-platform-launcher` as a dependency is doing the trick...

**Comment by Arsnael** [comment]
Also I took out the deps declaration in the surefire plugin in `jmap-integration-testing`, as I remember you said you had issues with junit5 upgrade on this, could have been potentially the version mix issue?

**Comment by trantienduchn** [comment]
this PR is expired, it is meant to be fixing Junit 5.5.1 but current master was reverted back to 5.2.0, see the related #2630

**Pull request closed without merging**
