### PR TITLE
James 1807 : implement search with the new multimailboxsearch API

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by aduprat** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this pleas

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Pull request merged**
