### PR TITLE
JAMES-2220 Flags update should not fail when a user is missing its Ou…

### PR DESCRIPTION
**Pull request by chibenwa**
…tbox

This could happen on the face of some mailbox inconsistencies upon JMAP
system mailboxes initial provisioning.

### CODE REVIEW

**Review by remk — APPROVED** [review]
no test ?

**Comment by chibenwa** [comment]
Nope, no tests. The set up is painful, specific to cassandra, and the fix obvious...

**Review by Arsnael — APPROVED** [review]
Don't we want to create the outbox maybe in this case if it's missing from an init problem then?

**Comment by chibenwa** [comment]
`Don't we want to create the outbox maybe in this case if it's missing from a provisioning problem then?`

The issue is these people outbox is "halth written"

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
