### PR TITLE
James 1587

### PR DESCRIPTION
**Pull request by rouazana**
Write a compliant Cassandra Domain Repository

### CODE REVIEW

**Comment by mbaechler** [comment]
:+1:

**Comment by mbaechler** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by mbaechler** [comment]
merged

**Pull request closed without merging**
