### PR TITLE
JAMES-2774 Small fixes in RabbitMQ eventBus test

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
FYI https://github.com/linagora/james-project/pull/2428 seems related

**Comment by chibenwa** [comment]
Unit tests seemsok, crashedin deployment tests

```
[18e5800bfa0293790a3104720b4da26763bc936f] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:24
[18e5800bfa0293790a3104720b4da26763bc936f] LastClientMsg: 10 CREATE appendexpunge
[18e5800bfa0293790a3104720b4da26763bc936f] Expected: '10 OK CREATE completed.'
[18e5800bfa0293790a3104720b4da26763bc936f] Actual   : ''
[18e5800bfa0293790a3104720b4da26763bc936f] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeployment(DeploymentValidation.java:81)
```

test thisplease

**Comment by Arsnael** [comment]
```
[18e5800bfa0293790a3104720b4da26763bc936f] [ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.85 s <<< FAILURE! - in org.apache.james.mpt.imapmailbox.external.james.JamesDeploymentValidationTest
[18e5800bfa0293790a3104720b4da26763bc936f] [ERROR] validateDeployment  Time elapsed: 0.764 s  <<< ERROR!
[18e5800bfa0293790a3104720b4da26763bc936f] org.apache.james.mpt.protocol.ProtocolSession$InvalidServerResponseException: 
[18e5800bfa0293790a3104720b4da26763bc936f] 
[18e5800bfa0293790a3104720b4da26763bc936f] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:24
[18e5800bfa0293790a3104720b4da26763bc936f] LastClientMsg: 10 CREATE appendexpunge
[18e5800bfa0293790a3104720b4da26763bc936f] Expected: '10 OK CREATE completed.'
[18e5800bfa0293790a3104720b4da26763bc936f] Actual   : ''
[18e5800bfa0293790a3104720b4da26763bc936f] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeployment(DeploymentValidation.java:81)
[18e5800bfa0293790a3104720b4da26763bc936f] 
[18e5800bfa0293790a3104720b4da26763bc936f] [ERROR] validateDeploymentWithMailsFromSmtp  Time elapsed: 0.074 s  <<< ERROR!
[18e5800bfa0293790a3104720b4da26763bc936f] org.apache.james.utils.SMTPSendingException: 
[18e5800bfa0293790a3104720b4da26763bc936f] Error upon step RCPT: 451 Unable to process request
[18e5800bfa0293790a3104720b4da26763bc936f] 
[18e5800bfa0293790a3104720b4da26763bc936f] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeploymentWithMailsFromSmtp(DeploymentValidation.java:87)
```
crashed again in deployment tests... should we get worried?

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
