### PR TITLE
JAMES-2486 Clone

### PR DESCRIPTION
**Pull request by blackheaven**
See #1566

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[74490ddecb83be662e3d740ee37820b55018d5e6] [INFO] --- maven-checkstyle-plugin:2.17:check (default) @ james-server-mailets ---
[74490ddecb83be662e3d740ee37820b55018d5e6] [INFO] There are 2 errors reported by Checkstyle 8.5 with checkstyle.xml ruleset.
[74490ddecb83be662e3d740ee37820b55018d5e6] [ERROR] src/main/java/org/apache/james/transport/mailets/jsieve/VacationAction.java:[22,8] (imports) UnusedImports: Unused import - java.time.Period.
[74490ddecb83be662e3d740ee37820b55018d5e6] [ERROR] src/main/java/org/apache/james/transport/mailets/jsieve/VacationAction.java:[24,8] (imports) UnusedImports: Unused import - java.time.temporal.TemporalUnit.
```

**Comment by trantienduchn** [comment]
```
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [INFO] -------------------------------------------------------------
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] COMPILATION ERROR : 
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [INFO] -------------------------------------------------------------
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[38,17] package org.junit does not exist
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[39,17] package org.junit does not exist
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[40,17] package org.junit does not exist
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[41,17] package org.junit does not exist
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[42,23] package org.junit.rules does not exist
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[52,12] cannot find symbol
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   symbol:   class TemporaryFolder
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   location: class org.apache.james.JPAJamesServerTest
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[51,6] cannot find symbol
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   symbol:   class Rule
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   location: class org.apache.james.JPAJamesServerTest
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[54,6] cannot find symbol
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   symbol:   class After
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   location: class org.apache.james.JPAJamesServerTest
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[74,6] cannot find symbol
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   symbol:   class Before
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   location: class org.apache.james.JPAJamesServerTest
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[81,6] cannot find symbol
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   symbol:   class After
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   location: class org.apache.james.JPAJamesServerTest
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [ERROR] /james-project/server/container/guice/jpa-smtp/src/test/java/org/apache/james/JPAJamesServerTest.java:[86,6] cannot find symbol
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   symbol:   class Test
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25]   location: class org.apache.james.JPAJamesServerTest
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [INFO] 11 errors 
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [INFO] -------------------------------------------------------------
[f8c69d4d47ad4b0d519601eb449dc3a0b41f3c25] [INFO] ------------------------------------------------------------------------
```

**Comment by chibenwa** [comment]
test this please (no build output)

**Comment by chibenwa** [comment]
```
[60df89cdd37e65f113ae99461fbf17fd33f21d50] Tests in error: 
[60df89cdd37e65f113ae99461fbf17fd33f21d50]   RabbitMQClusterTest$ClusterNodesFailure.connectingToAClusterWithAFailedRabbit:225 » AlreadyClosed
```

**Comment by chibenwa** [comment]
Forced pushed to solve conflict

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
