### PR TITLE
JAMES-2873 Add test to ensure DistributedTaskManager track nodes correctly

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please (restart)

**Comment by chibenwa** [comment]
```
[823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR] Failures: 
[823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR]   RabbitMQWorkQueueTest.givenTwoWorkQueuesOnlyTheFirstOneIsConsumingTasks:114 
[823b226a82a00d54d7c14f757899a4edd32d60ee] taskManagerWorker.executeTask(<any>);
[823b226a82a00d54d7c14f757899a4edd32d60ee] Wanted 100 times:
[823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueueTest.givenTwoWorkQueuesOnlyTheFirstOneIsConsumingTasks(RabbitMQWorkQueueTest.java:114)
[823b226a82a00d54d7c14f757899a4edd32d60ee] But was 1 time:
[823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueue.executeTask(RabbitMQWorkQueue.java:112)
[823b226a82a00d54d7c14f757899a4edd32d60ee] 
[823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR]   RabbitMQWorkQueueTest.workerShouldConsumeSubmittedTask:82 
[823b226a82a00d54d7c14f757899a4edd32d60ee] Expecting:
[823b226a82a00d54d7c14f757899a4edd32d60ee]  <TaskId{value=3c7f4081-aa30-11e9-bf6c-2d3b9e84aafd}>
[823b226a82a00d54d7c14f757899a4edd32d60ee] to be equal to:
[823b226a82a00d54d7c14f757899a4edd32d60ee]  <TaskId{value=2c7f4081-aa30-11e9-bf6c-2d3b9e84aafd}>
[823b226a82a00d54d7c14f757899a4edd32d60ee] but was not.
[823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR]   RabbitMQWorkQueueTest.workerShouldConsumeTwoSubmittedTask:92 
[823b226a82a00d54d7c14f757899a4edd32d60ee] taskManagerWorker.executeTask(
[823b226a82a00d54d7c14f757899a4edd32d60ee]     <Capturing argument>
[823b226a82a00d54d7c14f757899a4edd32d60ee] );
[823b226a82a00d54d7c14f757899a4edd32d60ee] Wanted 2 times:
[823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueueTest.workerShouldConsumeTwoSubmittedTask(RabbitMQWorkQueueTest.java:92)
[823b226a82a00d54d7c14f757899a4edd32d60ee] But was 1 time:
[823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueue.executeTask(RabbitMQWorkQueue.java:112)
[823b226a82a00d54d7c14f757899a4edd32d60ee] 
```

Seems related

**Comment by remk** [comment]
> ```
> [823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR] Failures: 
> [823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR]   RabbitMQWorkQueueTest.givenTwoWorkQueuesOnlyTheFirstOneIsConsumingTasks:114 
> [823b226a82a00d54d7c14f757899a4edd32d60ee] taskManagerWorker.executeTask(<any>);
> [823b226a82a00d54d7c14f757899a4edd32d60ee] Wanted 100 times:
> [823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueueTest.givenTwoWorkQueuesOnlyTheFirstOneIsConsumingTasks(RabbitMQWorkQueueTest.java:114)
> [823b226a82a00d54d7c14f757899a4edd32d60ee] But was 1 time:
> [823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueue.executeTask(RabbitMQWorkQueue.java:112)
> [823b226a82a00d54d7c14f757899a4edd32d60ee] 
> [823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR]   RabbitMQWorkQueueTest.workerShouldConsumeSubmittedTask:82 
> [823b226a82a00d54d7c14f757899a4edd32d60ee] Expecting:
> [823b226a82a00d54d7c14f757899a4edd32d60ee]  <TaskId{value=3c7f4081-aa30-11e9-bf6c-2d3b9e84aafd}>
> [823b226a82a00d54d7c14f757899a4edd32d60ee] to be equal to:
> [823b226a82a00d54d7c14f757899a4edd32d60ee]  <TaskId{value=2c7f4081-aa30-11e9-bf6c-2d3b9e84aafd}>
> [823b226a82a00d54d7c14f757899a4edd32d60ee] but was not.
> [823b226a82a00d54d7c14f757899a4edd32d60ee] [ERROR]   RabbitMQWorkQueueTest.workerShouldConsumeTwoSubmittedTask:92 
> [823b226a82a00d54d7c14f757899a4edd32d60ee] taskManagerWorker.executeTask(
> [823b226a82a00d54d7c14f757899a4edd32d60ee]     <Capturing argument>
> [823b226a82a00d54d7c14f757899a4edd32d60ee] );
> [823b226a82a00d54d7c14f757899a4edd32d60ee] Wanted 2 times:
> [823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueueTest.workerShouldConsumeTwoSubmittedTask(RabbitMQWorkQueueTest.java:92)
> [823b226a82a00d54d7c14f757899a4edd32d60ee] But was 1 time:
> [823b226a82a00d54d7c14f757899a4edd32d60ee] -> at org.apache.james.task.eventsourcing.distributed.RabbitMQWorkQueue.executeTask(RabbitMQWorkQueue.java:112)
> [823b226a82a00d54d7c14f757899a4edd32d60ee] 
> ```
> 
> Seems related

fixed in https://github.com/linagora/james-project/pull/2626
need rebase

**Comment by remk** [comment]
The work done on this PR has been move back to #2569

**Pull request closed without merging**
