### PR TITLE
[NO_REVIEW] Build triggering PR - JPA SMTP dockerfile

### PR DESCRIPTION
**Pull request by chibenwa**
See https://github.com/linagora/james-project/pull/1826

The contributor used a branch name containing a `/` character, invalid for docker names and thus makes our CI fail.

This PR is intended to trigger the build on the latest commit of this PR with a valid branch name

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[93da178cb994ade33c1f04c9b75dc85266fb11d0] [ERROR]   RabbitMQClusterTest$ClusterSharing.queuesShouldBeDeclarableOnAnotherNode » Completion
[93da178cb994ade33c1f04c9b75dc85266fb11d0] [ERROR]   RabbitMQClusterTest$ClusterSharing.queuesShouldBeShared » Completion org.testc...
[93da178cb994ade33c1f04c9b75dc85266fb11d0] [ERROR]   RabbitMQClusterTest$ClusterSharing.rabbitMQManagerShouldReturnThreeNodesWhenAskingForStatus » Completion
```

test this please

**Comment by trantienduchn** [comment]
was :green_apple: , closing this

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
