### PR TITLE
James 3025

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[bdfcf66e6c3f6c1c1a8874f475dbe1dcb969b1d4] [ERROR] Errors: 
[bdfcf66e6c3f6c1c1a8874f475dbe1dcb969b1d4] [ERROR]   RabbitMQSelectedInboxTest.testStatusITALY » Runtime java.lang.IllegalStateExce...
```

**Comment by mbaechler** [comment]
The failure should be a flacky test because it shouldn't be related to that commit in anyway.

test this please

**Comment by Arsnael** [comment]
```
[ERROR]   WebAdminUtilsTest.serverShouldBeAbletoStartConcurrently:38 » NotTerminated
```
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
