### PR TITLE
JAMES-3020 provide guice binding for AdditionalInformationUpdated event

### PR DESCRIPTION
**Pull request by remk**

### CODE REVIEW

**Comment by chibenwa** [comment]
(no test ?)

**Comment by remk** [comment]
> (no test ?)

i don't know how to test this in a simple way in this module.
We need to launch a task via the webadmin which take more time than the default polling interval (30s), and change the additionalInformation.

**Comment by chibenwa** [comment]
> i don't know how to test this in a simple way in this module.
We need to launch a task via the webadmin which take more time than the default polling interval (30s), and change the additionalInformation.

Aren't we able to configure the poll interval to a more reasonable value (1s ?) via Guice constant injection so that we can consider writing an integretion test?

**Comment by remk** [comment]
```
Running: End of Workflow
org.jenkinsci.plugins.workflow.cps.steps.ParallelStepException: Parallel step 4909f7c45b05bf554f0507bfcc8ec37c7000dd0c failed
	at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.checkAllDone(ParallelStep.java:153)
	at org.jenkinsci.plugins.workflow.cps.steps.ParallelStep$ResultHandler$Callback.onFailure(ParallelStep.java:119)
	at org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$FailureAdapter.receive(CpsBodyExecution.java:294)
	at com.cloudbees.groovy.cps.impl.ThrowBlock$1.receive(ThrowBlock.java:68)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:58)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:145)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:19)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:33)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable$1.call(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.runInSandbox(GroovySandbox.java:106)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:30)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:164)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:274)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$000(CpsThreadGroup.java:74)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:183)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:181)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:112)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: hudson.AbortException: script returned exit code 125
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.check(DurableTaskStep.java:203)
	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.run(DurableTaskStep.java:154)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
```
Could be considered green.
test this please

**Comment by remk** [comment]
```
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 14:12:31.216 [ERROR] s.h.m.GeneralError - 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] java.lang.RuntimeException: null
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.apache.james.webadmin.routes.ErrorRoutes.lambda$defineInternalError$0(ErrorRoutes.java:49)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at spark.RouteImpl$1.handle(RouteImpl.java:72)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at spark.http.matching.Routes.execute(Routes.java:61)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1682)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.server.Server.handle(Server.java:505)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:781)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:917)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 	at java.base/java.lang.Thread.run(Thread.java:834)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.267 s - in org.apache.james.webadmin.routes.ErrorRoutesTest
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Results:
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR] Errors: 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR]   WebAdminUtilsTest.serverShouldBeAbletoStartConcurrently:38 » NotTerminated
```

test this please

**Comment by remk** [comment]
```
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO]  T E S T S
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] -------------------------------------------------------
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Running org.apache.james.mpt.imapmailbox.external.james.DockerDeploymentValidationSpringJPATest
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.006 s - in org.apache.james.mpt.imapmailbox.external.james.DockerDeploymentValidationSpringJPATest
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Running org.apache.james.mpt.imapmailbox.external.james.DockerDeploymentValidationGuiceJPATest
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.apache.james.mpt.imapmailbox.external.james.DockerDeploymentValidationGuiceJPATest
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Running org.apache.james.mpt.imapmailbox.external.james.JamesDeploymentValidationTest
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 78.12 s <<< FAILURE! - in org.apache.james.mpt.imapmailbox.external.james.JamesDeploymentValidationTest
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR] validateDeploymentWithMailsFromSmtp  Time elapsed: 10.614 s  <<< ERROR!
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation was not fulfilled within 10 seconds.
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Results:
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR] Errors: 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR]   JamesDeploymentValidationTest>DeploymentValidation.validateDeploymentWithMailsFromSmtp:95 » ConditionTimeout
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 2
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] ------------------------------------------------------------------------
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] BUILD FAILURE
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] ------------------------------------------------------------------------
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Total time:  01:25 min (Wall Clock)
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [INFO] Finished at: 2020-01-07T10:56:08Z
```

test this please

**Comment by rouazana** [comment]
```
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR] Errors: 
[4909f7c45b05bf554f0507bfcc8ec37c7000dd0c] [ERROR]   MemorySpamAssassinContractTest.spamShouldBeDeliveredInSpamMailboxWhenSameMessageHasAlreadyBeenMovedToSpam » ConditionTimeout
```
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
