### PR TITLE
JAMES-2119 create cassandra table and types in parallel

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[Building Java 8 james-2119-0f493f6d-37b1-44dc-a475-189246d68d38] Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/172.17.0.3:9042] Timed out waiting for server response
```

Server timeout in cassandra-guice tests. Maybe too high concurrency.

(I did not get these issues with async queries as far as I remember)

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
that may be the typical "my computer has 4 cores and the server has 16" issue, let's try one more time

**Comment by chibenwa** [comment]
```
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.236 sec - in org.apache.james.modules.mailbox.CassandraSessionModuleTest

Results :

Tests in error: 
  CassandraLogConfigurationTest.serverShouldStartWithMinimalConfigAboutAConstantThresholdSlowQueryLogger:79->assertThatServerStartCorrectly:119 » Provision
  CassandraLogConfigurationTest.serverShouldStartWithPersonalizedConfigAboutPercentileSlowQuerryLogger:97->assertThatServerStartCorrectly:119 » Provision
  CassandraNodeConfTest.configShouldWorkWithNonDefaultPort:91->assertThatServerStartCorrectly:95 » Provision
  CassandraNodeConfTest.serverShouldStartServiceWhenNodeIsReachable:71->assertThatServerStartCorrectly:95 » Provision
  CassandraNodeConfTest.serverShouldStartWhenOneCassandraNodeIsUnreachable:82->assertThatServerStartCorrectly:95 » Provision
  JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToCassandraWhenStartService:83->assertThatServerStartCorrectly:108 » Provision
  JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToElasticSearchWhenStartService:93->assertThatServerStartCorrectly:108 » Provision
  JamesServerWithRetryConnectionTest.serverShouldStartAtDefault:73->assertThatServerStartCorrectly:108 » Provision
```

```
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/172.17.0.3:9042] Timed out waiting for server response
```


Maybe we can try the version with async statements?

**Comment by chibenwa** [comment]
As privately discussed with @mbaechler  (sorry for that!) we need to constraint concurrency (4 seems to be the magic number) in order to get enhanced results.

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Rebase needed on master to solve JPA troubbles (different version of DockerFiles combined with weak build workspace isolation)

**Comment by chibenwa** [comment]
Seems slower...

```
[INFO] Apache James :: Server :: Cassandra - guice injection FAILURE [  01:07 h]
```

I'll try decrease the magic number to 2...

**Comment by chibenwa** [comment]
Still needed? Isn't this also done in cassandra docker pr?

**Comment by mbaechler** [comment]
yes, done with parallelstream in cassandra-in-docker PR.

**Pull request closed without merging**
