### PR TITLE
JAMES-2709 Increase LinShare startup timeouts

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Sorry not convinced by that... When I took a look the error messages I saw were on a timeout with the `linshare-init` image (last one). We do already a 

```
.waitingFor(Wait.forLogMessage(WAIT_FOR_LDAP_INIT_LOG, 1)
    .withStartupTimeout(Duration.ofMinutes(10)))
```
It seems the log message never came in those issues. Meaning there was probably an issue perhaps with the interaction of that image with the backend and the rest (it's the one provisioning linshare). We are already waiting 10 minutes for that so the extra waiting timeout 5 on the above level sounds like it's not gonna change anything

I'm almost thinking if we should just not put back what you did before with the manual provisioning to linshare, at least we wouldn't need to depend on that docker image anymore, if it's really the issue...

**Comment by chibenwa** [comment]
`LinshareBlobExportMechanismProvidingTest.<clinit>:29 » ExceptionInInitializer`

Seems that you are right

**Comment by chibenwa** [comment]
Not the right approach...

**Pull request closed without merging**
