### PR TITLE
[Git] Ignore glowroot folder for docker compilation

### PR DESCRIPTION
**Pull request by Arsnael**
Very simple PR... just tired of having the glowroot folder polluting my Git after I compile docker images of James locally

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[d1e3a3cc1e4838180fcfc0bd64227472132b9888] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[d1e3a3cc1e4838180fcfc0bd64227472132b9888] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[d1e3a3cc1e4838180fcfc0bd64227472132b9888] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[d1e3a3cc1e4838180fcfc0bd64227472132b9888] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
```
test this please

**Comment by Arsnael** [comment]
```
[ERROR]   MemorySpamAssassinContractTest.spamShouldBeDeliveredInSpamMailboxOrInboxWhenMultipleRecipientsConfigurations » ConditionTimeout
```

**Comment by Arsnael** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
