### PR TITLE
JAMES-2482 Upgrade apache ant

### PR DESCRIPTION
**Pull request by trantienduchn**
```
org.apache.ant:ant ................................... 1.7.1 -> 1.10.5 GDF [ant] 1.10.5 // Used for MPT
org.apache.ant:ant-antunit ................................ 1.1 -> 1.4 GDF [ant] 1.4 // Used for MPT
```

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
rebase master

**Comment by trantienduchn** [comment]
🍏

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
