### PR TITLE
JAMES−2290 Fix unstable test: DiscreteDistributionTest.partitionShoul…

### PR DESCRIPTION
**Pull request by chibenwa**
…dSupportDuplicatedDistributionEntry

We encountered the following failure:

```
[ERROR]   DiscreteDistributionTest.partitionShouldSupportDuplicatedDistributionEntry:112
Expecting:
   <668532L>
 to be close to:
   <662936L>
 by less than <5000L> but difference was <5596L>.
 (a difference of exactly <5000L> being considered valid)
```

A difference of 10.000 seems reasonable too and more unlikely to break.

### CODE REVIEW

**Comment by mbaechler** [comment]
it means actually going from a 5% tolerance to a 10% one, that's it?

**Comment by chibenwa** [comment]
From 0,5% to 1% tolerance given that there is a million entries, wich seems more acceptable than the numbers you present...

Thanks for the proposal.

**Comment by chibenwa** [comment]
`MemorySpamAssassinContractTest.movingAMailToTrashShouldNotImpactSpamassassinLearning » ConditionTimeout`

**Comment by chibenwa** [comment]
Playing with MersenneTwister, I see little stability enhencements, which means that the low tolerance is to blame, but the better generator could of course be adopted.

**Comment by chibenwa** [comment]
`RemoteDeliveryErrorHandlingTest.remoteDeliveryShouldStoreTemporaryFailureAsPermanentWhenExceedsMaximumRetries:268 » ConditionTimeout`

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
