### PR TITLE
One fix per day 11

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[e1a12bfc7fc72fb5cb17f5916cc14f4f5df6ce25] [ERROR] Errors: 
[e1a12bfc7fc72fb5cb17f5916cc14f4f5df6ce25] [ERROR]   MemorySpamAssassinContractTest.expungingSpamMessageShouldNotImpactSpamAssassinState » ConditionTimeout
```
test this please

**Comment by mbaechler** [comment]
Aborted by JamesAdmin while doing deployment tests ... please do that with more care.

test this please

**Comment by Arsnael** [comment]
> Aborted by JamesAdmin while doing deployment tests ... please do that with more care.
> 
> test this please

Your build was going on for longer than a day... Obviously something was wrong. I admit I forgot to mention it here though

**Comment by mbaechler** [comment]
no build logs

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
