### PR TITLE
MAILBOX-268 Handle bad Content-Type in attachments

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by rouazana** [comment]
Optional without Java 8 is not very interesting. As you are using it only inside a class, I think using null would be simpler to write.
Furthermore, I think you should not ignore an attachment because of its missing contentType. You can use for example application/octet-stream which is pretty generic.

**Comment by mbaechler** [comment]
guava is already there, so introducing Optional is a good step to java 8 and it makes it clear that no value is not a bug (null is always ambigous). :+1:

**Comment by aduprat** [comment]
1/ keep Optional
2/ adding a default ContentType

**Comment by rouazana** [comment]
:+1:

**Comment by mbaechler** [comment]
👍

**Comment by aduprat** [comment]
merged

**Pull request closed without merging**
