### PR TITLE
Propose validation when deserialize JmapRuleDTO 

### PR DESCRIPTION
**Pull request by nvduc91**
Handle validation at JmapRequest parsing level

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]
Looks good (if it passes the integration tests :-) )

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Build output lost.

test this please

**Comment by nvduc91** [comment]
```
[ERROR] Failures: 
[15089992cf4b93e8526e7f108d8a80990ed5787a] [ERROR]   MemorySendMDNMethodTest>SendMDNMethodTest.sendMDNShouldIndicateMissingFields:398 1 expectation failed.
[15089992cf4b93e8526e7f108d8a80990ed5787a] JSON path [0][1].description doesn't match.
[15089992cf4b93e8526e7f108d8a80990ed5787a] Expected: a string containing "problem: 'subject' is mandatory"
[15089992cf4b93e8526e7f108d8a80990ed5787a]   Actual: 'subject' is mandatory
[15089992cf4b93e8526e7f108d8a80990ed5787a] 
[15089992cf4b93e8526e7f108d8a80990ed5787a] [ERROR]   MemorySendMDNMethodTest>SendMDNMethodTest.sendMDNShouldIndicateMissingFieldsInDisposition:465 1 expectation failed.
[15089992cf4b93e8526e7f108d8a80990ed5787a] JSON path [0][1].description doesn't match.
[15089992cf4b93e8526e7f108d8a80990ed5787a] Expected: a string containing "problem: 'actionMode' is mandatory"
[15089992cf4b93e8526e7f108d8a80990ed5787a]   Actual: 'actionMode' is mandatory
```
I dont know if it related or not? @chibenwa

**Comment by chibenwa** [comment]
I think the sendMdn is being tried being deserialized as a JMAP filtering rule

**Comment by nvduc91** [comment]
> I think the sendMdn is being tried being deserialized as a JMAP filtering rule

I will check if it cause a breaking changes or not.

**Review by remk — APPROVED** [review]

**Comment by nvduc91** [comment]
Change the way message printout

**Review by Arsnael — APPROVED** [review]

**Review by remk — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
