### PR TITLE
Switch reUseforks=true in surrefire

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
MailRepositoryContract.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult:474 » Execution
```

test this please

**Comment by chibenwa** [comment]
```
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [ERROR] testServer(org.apache.james.app.spring.JamesAppSpringMainTest)  Time elapsed: 3.064 s  <<< ERROR!
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverConnector' defined in class path resource [META-INF/org/apache/james/spring-server.xml]: Invocation of init method failed; nested exception is java.io.IOException: Cannot bind to URL [rmi://127.0.0.1:9999/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.NoSuchObjectException: no such object in table]
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] Caused by: java.io.IOException: Cannot bind to URL [rmi://127.0.0.1:9999/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.NoSuchObjectException: no such object in table]
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] Caused by: javax.naming.CommunicationException
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] Caused by: java.rmi.NoSuchObjectException: no such object in table
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [INFO] 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [INFO] Results:
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [INFO] 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [ERROR] Errors: 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [ERROR]   JamesAppSpringMainTest.testServer:27 » BeanCreation Error creating bean with n...
```

test this please

**Comment by Arsnael** [comment]
same as above
```
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [ERROR] testServer(org.apache.james.app.spring.JamesAppSpringMainTest)  Time elapsed: 2.67 s  <<< ERROR!
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverConnector' defined in class path resource [META-INF/org/apache/james/spring-server.xml]: Invocation of init method failed; nested exception is java.io.IOException: Cannot bind to URL [rmi://127.0.0.1:9999/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.NoSuchObjectException: no such object in table]
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] Caused by: java.io.IOException: Cannot bind to URL [rmi://127.0.0.1:9999/jmxrmi]: javax.naming.CommunicationException [Root exception is java.rmi.NoSuchObjectException: no such object in table]
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] Caused by: javax.naming.CommunicationException
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] Caused by: java.rmi.NoSuchObjectException: no such object in table
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 	at org.apache.james.app.spring.JamesAppSpringMainTest.testServer(JamesAppSpringMainTest.java:27)
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [INFO] 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [INFO] Results:
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [INFO] 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [ERROR] Errors: 
[74395d292ab7ef33a2d4f81233fb6a6855c53ad1] [ERROR]   JamesAppSpringMainTest.testServer:27 » BeanCreation Error creating bean with n...
```
test this please

**Comment by chibenwa** [comment]
```
[INFO] Total time: 02:04 h
```

test this please

**Comment by chibenwa** [comment]
:green_apple:  relaunching...

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[INFO] Apache James :: Server :: Blob :: Object storage ... FAILURE [10:05 min]

BucketBlobStoreContract.saveConcurrentlyWithNonPreExistingBucketShouldNotFail:153 » NotTerminated
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`JamesMailSpoolerTest.threadSuicideShouldAckTheItem:126 » ConditionTimeout Cond...`

test this please

**Comment by chibenwa** [comment]
:green_apple: before CI reboot

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
(Just rebased)

**Comment by chibenwa** [comment]
`MailsShouldBeWellReceived.mailsShouldBeWellReceived:63 » ConditionTimeout Cond...`

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`MemoryUploadCucumberTest » Socket Broken pipe (Write failed)` test this please

**Comment by chibenwa** [comment]
test this please (restart)

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please (was :green_apple:  )

**Comment by chibenwa** [comment]
13 min faster on master

**Comment by chibenwa** [comment]
test this please (was :green_apple: )

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
