### PR TITLE
[Refactoring] Java 11 'var' in JMAP Draft code

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by mbaechler** [comment]
I think there's no consensus yet in the team regarding `var` usage.

My opinion: when we affect a value and the type of it is not obvious, it makes reading harder.

So I'm ok to use it cases like:

```
var foo = new Foo();
```

but less ok with:

```
var foo = callMyDomainRelatedMethod();
```

WDYT?

**Comment by chibenwa** [comment]
Depends where you read the code. 

In an IDE ctrl + click makes it easy to find a type. Github code highlighting is also helpfull.

Var alignement + syntax highlighting is also nice IMO but might be systematic in a block of code to be beneficial.

**Comment by mbaechler** [comment]
> Depends where you read the code.
> 
> In an IDE ctrl + click makes it easy to find a type. Github code highlighting is also helpfull.

Why would we make it available one step further?

**Comment by chibenwa** [comment]
Let's takes examples:

`var attachments = entry.getValue().getAttachments();`

:+1: easy to understand that it is some sub classes of collection of attachments.

```
        var inMailboxes = buildFilterMailboxesSet(messageListRequest.getFilter(), FilterCondition::getInMailboxes);
        var notInMailboxes = buildFilterMailboxesSet(messageListRequest.getFilter(), FilterCondition::getNotInMailboxes);
        var sorts = SortConverter.convertToSorts(messageListRequest.getSort());
```

Feels also OK because the naming is good enough. We don't need the type information redundancy for easy understanding.

**Comment by mbaechler** [comment]
> Let's takes examples:
> 
> `var attachments = entry.getValue().getAttachments();`
> 
> +1 easy to understand that it is some sub classes of collection of attachments.

But I don't know if it's a Set or a List, for example. I may have some importance.
 
> ```
>         var inMailboxes = buildFilterMailboxesSet(messageListRequest.getFilter(), FilterCondition::getInMailboxes);
>         var notInMailboxes = buildFilterMailboxesSet(messageListRequest.getFilter(), FilterCondition::getNotInMailboxes);
>         var sorts = SortConverter.convertToSorts(messageListRequest.getSort());
> ```
> 
> Feels also OK because the naming is good enough. We don't need the type information redundancy for easy understanding.

It really depends what is the remaining of the method.

**Comment by chibenwa** [comment]
> But I don't know if it's a Set or a List, for example. I may have some importance.

If it have an importance then I agree not to use it.

Here IMO it don't.

> It really depends what is the remaining of the method.

Then let's discuss specific usage to refine our usage of `var` rather than staying generic.

**Comment by chibenwa** [comment]
> IMO we should limit var usage to very complex types, removing types decrease readability.

That for sure makes longs debate short ^^

**Comment by blackheaven** [comment]
If length is important to you...

What is it all about?

We try to provide value to our customers through Apache James.
In order to do this over a long period of time we have to take care of the maintainability of our project, to keep the cost of adding value constant (at worst).

To achieve that we have a numerous of things to look at carefully, I choose to pick two of them relevant to this PR:

 * System stability
 * Readability

Type system should, we correctly used, ensure a huge part of the system stability, meaning, giving a common contract between some subsystems, when the contract is changed on broken, everything should stop. That's the canary in the coal mine. When we use `var`, the contract check is delayed to it's usages, making the "debug" harder to do.

Readability is also in play, sure, not putting tedious types improve "plain" reading of a piece of code. On the other hand, you have to mentally retain the type of each element after finding them out. It is a very high cognitive overhead I do not want to have.

**Comment by rouazana** [comment]
My 2 personal cents:

> Depends where you read the code.
> 
> In an IDE ctrl + click makes it easy to find a type.

Easy but longer, so not very interesting.

> Github code highlighting is also helpfull.

How? I cannot get any type looking at your PR.

As we have more time reading code than writing code (even when writing code), I'm against this change as it slows down my reading the code.

I can eventually tolerate it in some cases stated by Matthieu and Gautier, in particular when the type is duplicated in the line (it allows to reduce boilerplate). But it should not be generalized, because in some cases you don't use the exact same type (think of Collection/List, List/ImmutableList, etc.).

Again, that's just my personal opinion.

**Comment by chibenwa** [comment]
Ok, the reasons are interesting, I am closing this controvercial contribution

**Pull request closed without merging**
