### PR TITLE
Fix Checkstyle errors and Eclipse warnings

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by chibenwa** [comment]
Rebased to solve conflicts

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   RabbitMQClusterTest$ClusterSharing.queuesShouldBeDeclarableOnAnotherNode:131 » IO
```

test this please

**Comment by rouazana** [comment]
never mind, it's not related

**Comment by rouazana** [comment]
```
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR] Errors: 
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   SpamAssassinContract.deletingSpamMessageShouldNotImpactSpamAssassinState:540 » ConditionTimeout
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   SpamAssassinContract.imapMovesToSpamMailboxShouldBeConsideredAsSpam:230 » ConditionTimeout
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   SpamAssassinContract.spamShouldBeDeliveredInSpamMailboxWhenSameMessageHasAlreadyBeenMovedToSpam:136 » ConditionTimeout
```
test this please

**Comment by chibenwa** [comment]
```
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   RabbitMQClusterTest$ClusterNodesFailure.connectingToAClusterWithAFailedRabbit » Completion
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   RabbitMQClusterTest$ClusterSharing.queuesShouldBeDeclarableOnAnotherNode » Completion
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   RabbitMQClusterTest$ClusterSharing.queuesShouldBeShared » Completion org.testc...
[0bd884d5cc6150744c1425f71ebb11e0b212ca59] [ERROR]   RabbitMQClusterTest$ClusterSharing.rabbitMQManagerShouldReturnThreeNodesWhenAskingForStatus » Completion
```

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
