### PR TITLE
JAMES-2037 Use Flux for MessageManager::search

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
`Caused by: java.net.BindException: Address already in use`

test this please

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
tests are :green_apple: 

test this please

**Review by LanKhuat — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
