### PR TITLE
[WIP] Jdk9

### PR DESCRIPTION
**Pull request by rouazana**
Just some curiosity... :)

### CODE REVIEW

**Comment by Arsnael** [comment]
> Just some curiosity... :)

How about some curiosity with Jdk11 instead? :)

**Comment by rouazana** [comment]
> How about some curiosity with Jdk11 instead? :)

That will be the next step :)

**Comment by trantienduchn** [comment]
```
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateCompositeProcessorTest.testGhostProcessor:94 » NoClassDefFound ja...
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateCompositeProcessorTest.testNoErrorProcessor:126 » NoClassDefFound
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateCompositeProcessorTest.testNoRootProcessor:111 » NoClassDefFound ...
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateMailetProcessorTest.mailetProcessingShouldNotResultInAnExceptionWhenMailetThrows:235 » NoClassDefFound
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateMailetProcessorTest.matcherProcessingShouldCaptureExceptionAsMailAttributeWhenMatcherThrows:202 » NoClassDefFound
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateMailetProcessorTest.matcherProcessingShouldNotResultInAnExceptionWhenMatcherThrows:163 » NoClassDefFound
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateMailetProcessorTest.testSimpleRouting:72 » NoClassDefFound javax/...
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR]   AbstractStateMailetProcessorTest.testSimpleRoutingMatchAll:117 » NoClassDefFound
...

[8e5b87da7e8369b8c3af58930b36a361f826a0ce] [ERROR] mailetProcessingShouldNotResultInAnExceptionWhenMailetThrows  Time elapsed: 0.023 s  <<< ERROR!
[8e5b87da7e8369b8c3af58930b36a361f826a0ce] java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
```

**Comment by rouazana** [comment]
github 502, test this please

**Comment by rouazana** [comment]
```
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 	Suppressed: java.lang.IncompatibleClassChangeError: Class org.apache.activemq.ActiveMQMessageConsumer does not implement the requested interface java.lang.AutoCloseable
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 		at org.apache.james.queue.jms.JMSMailQueue.$closeResource(JMSMailQueue.java:487)
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 		at org.apache.james.queue.jms.JMSMailQueue.flush(JMSMailQueue.java:522)
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 		... 59 more
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 	Suppressed: java.lang.IncompatibleClassChangeError: Class org.apache.activemq.ActiveMQSession does not implement the requested interface java.lang.AutoCloseable
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 		at org.apache.james.queue.jms.JMSMailQueue.$closeResource(JMSMailQueue.java:487)
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 		at org.apache.james.queue.jms.JMSMailQueue.flush(JMSMailQueue.java:523)
[56981a780ca4f94bd1e5ad7f22ea9a43cecff680] 		... 59 more
``` ... help?

**Comment by Arsnael** [comment]
```
[ERROR] Errors: 
[ERROR]   ConcurrentTestRunnerTest.runShouldPerformAllOperationsEvenOnOccasionalExceptions:230 » NotTerminated
```
test this please

**Comment by remk** [comment]
test this please

**Comment by remk** [comment]
test this please

**Comment by Arsnael** [comment]
Ignore my last commit, seems the issue still remains...

**Comment by mbaechler** [comment]
test this please

**Comment by rouazana** [comment]
see https://github.com/linagora/james-project/pull/2501

**Pull request closed without merging**
