### PR TITLE
[NO_REVIEW]  James 2739 fixed browse mails from queue

### PR DESCRIPTION
**Pull request by blackheaven**
SEE https://github.com/apache/james-project/pull/165

### CODE REVIEW

**Comment by blackheaven** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project james-server-guice-custom-mailets-dependency: Fatal error compiling: invalid flag: --release -> [Help 1]
```

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/pull/2721

**Pull request closed without merging**
