### PR TITLE
Replace org.apache.james by ${project.groupId} where appropriate

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

```
[18cc0ff2fad3be381c0a172cb2e2ba1ebdd782ee] Failed tests: 
[18cc0ff2fad3be381c0a172cb2e2ba1ebdd782ee]   SpamAssassinInvokerTest.learnAsSpamShouldReturnTrueWhenLearningWorks:94 expected:<[tru]e> but was:<[fals]e>
```

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
Many errors while running `mvn clean install`

```
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR] The build could not read 4 projects -> [Help 1]
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]   
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]   The project org.apache.james.protocols:protocols-imap:3.1.0-SNAPSHOT (/james-project/protocols/imap/pom.xml) has 8 errors
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:apache-james-mailbox-api:jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 76, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:apache-james-mailbox-api:test-jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 80, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:apache-james-mailbox-store:jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 86, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:apache-mime4j-core:jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 91, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:apache-mime4j-dom:jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 95, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:james-server-util:jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 99, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:james-server-util-java8:jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 104, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]     'dependencies.dependency.version' for org.apache.james:metrics-api:jar is missing. @ org.apache.james.protocols:protocols-imap:[unknown-version], /james-project/protocols/imap/pom.xml, line 108, column 21
[0953a751405f9e8c28c4cf9ebb0621a011e8f4b0] [ERROR]   
```

**Comment by rouazana** [comment]
:+1:

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
