### PR TITLE
JAMES-2500 Don't fail when RabbitMQCluster fails to stop

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
```
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [INFO] Apache James :: Server :: Mail Queue :: RabbitMQ 3.2.0-SNAPSHOT FAILURE [03:47 min]
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [INFO] ------------------------------------------------------------------------
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [INFO] BUILD FAILURE
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [INFO] ------------------------------------------------------------------------
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [INFO] Total time: 01:50 h
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [INFO] Finished at: 2018-07-27T02:32:09Z
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [INFO] ------------------------------------------------------------------------
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project james-server-queue-rabbitmq: There are test failures.
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [ERROR] 
[5203d2b905ee8f400c5c67d7efec4a61a41a43e1] [ERROR] Please refer to /james-project/server/queue/queue-rabbitmq/target/surefire-reports for the individual test results.
```

**Comment by trantienduchn** [comment]
I looked at `ClusterNodesFailure::connectingToAClusterWithAFailedRabbit` code. According my diagnosis, after `cluster.getRabbitMQ3().stop();`, but channel has not been acknowledged that `rabitmq3` leaved yet, then it still keep connection to `rabbitmq3`=> exception happen. I ran this test several times and got some random fails with same error above. We need a delay between stoping rabbitmq03 and invoking `channel`'s operations. I purpose my fixup by simply reverting old code and updating DockerRabbitMQ. See https://github.com/trantienduchn/james-project/commit/1195319cc0171e2487c566e916f6973029994a34

**Comment by chibenwa** [comment]
I did comment directly on your fix.

You actually change the test from:

 - `What happens when a node we have a connection to fails`

into

 - `What happens when we try to establish a connection to a cluster with a failed node`

Which is actually different...

**Comment by trantienduchn** [comment]
I think I didn't change that test purpose, you can look at commit history of `ClusterNodesFailure::connectingToAClusterWithAFailedRabbit` there was a commit that moved `cluster.getRabbitMQ3().stop();` from outside into inside try catch block to dealing with `testcontainers upgrade conflict with docker rabbitmq` in recent days.

The problem with old testcontainers  was it's still able to retrieve container host & port although the containers has been stopped. new testcontainers fixed that problem and once you stop a docker, you are not able to retrieve host & port anymore and will throw an exception, but the test still did that => test fails.

**Comment by chibenwa** [comment]
Ok then let me write fix that don't change the behaviour

**Comment by trantienduchn** [comment]
JIRA ticket (JAMES-2500) at beginning of revert commit message!

**Comment by chibenwa** [comment]
No it should be clear which commit got reverted ;-) 

(That is an exception)

**Comment by chibenwa** [comment]
test this please (build result lost)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
