### PR TITLE
Fix logging for already created ElasticSearch index

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal on project james-server-lifecycle-api: Could not resolve dependencies for project org.apache.james:james-server-lifecycle-api:jar:3.5.0-SNAPSHOT: Failed to collect dependencies at com.google.guava:guava:jar:25.1-jre -> org.codehaus.mojo:animal-sniffer-annotations:jar:1.14: Failed to read artifact descriptor for org.codehaus.mojo:animal-sniffer-annotations:jar:1.14: Could not transfer artifact org.codehaus.mojo:animal-sniffer-annotations:pom:1.14 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.pom.part (No such file or directory) -> [Help 1]
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
