### PR TITLE
JAMES-3431 Migrate Mailet integration tests to JUNIT 5

### PR DESCRIPTION
**Pull request by chibenwa**
```
~/Documents/james-project/server/mailet/integration-testing$ git checkout master
~/Documents/james-project/server/mailet/integration-testing$ grep 'import org.junit.Test;' * -R | wc -l
41
~/Documents/james-project/server/mailet/integration-testing$ git checkout JAMES-3431-junit-5
~/Documents/james-project/server/mailet/integration-testing$ grep 'import org.junit.Test;' * -R | wc -l
0
~/Documents/james-project$ grep 'import org.junit.Test;' * -R | wc -l
315
```

Killed quite a bunch of those...

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]
Thanks

**Review by remk — APPROVED** [review]

**Review by rouazana — COMMENTED** [review]
could you please remove the visibility modifiers where accurate also please?

**Comment by chibenwa** [comment]
> could you please remove the visibility modifiers where accurate also please?

Not sure it is a necessary time investment but yeah sure I (or we, if someone else wonna help) can do it.

**Review by Arsnael — APPROVED** [review]

**Review by LanKhuat — APPROVED** [review]

**Review by remk — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
