### PR TITLE
Mailet 107 Integration tests

### PR DESCRIPTION
**Pull request by chibenwa**
Integration tests for https://github.com/apache/james-project/pull/54

### CODE REVIEW

**Comment by chibenwa** [comment]
Split from https://github.com/linagora/james-project/pull/364

**Comment by chibenwa** [comment]
```
[Building Java 8 mailet-107-3094289f-63f8-4d0c-9fe8-24f406363077] [INFO] Apache James MPT Core .............................. FAILURE [01:04 min]

[Building Java 8 mailet-107-3094289f-63f8-4d0c-9fe8-24f406363077] Tests in error: 
[Building Java 8 mailet-107-3094289f-63f8-4d0c-9fe8-24f406363077]   TestDiscardProtocol.testComplete:95 »  Timed out wait for be notified that rea...


[Building Java 8 mailet-107-3094289f-63f8-4d0c-9fe8-24f406363077] testComplete(org.apache.james.mpt.TestDiscardProtocol)  Time elapsed: 60.049 sec  <<< ERROR!
[Building Java 8 mailet-107-3094289f-63f8-4d0c-9fe8-24f406363077] java.lang.Exception: Timed out wait for be notified that read is complete
[Building Java 8 mailet-107-3094289f-63f8-4d0c-9fe8-24f406363077] 	at org.apache.james.mpt.TestDiscardProtocol.testComplete(TestDiscardProtocol.java:95)
```

Does not looks linked to my code... Is the build unstable ?

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
👍

**Comment by rouazana** [comment]
:+1:

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Again build instability : 
```
[Building Java 8 mailet-107-da162c6b-7023-469a-ab9c-b6aee7d5819c] [INFO] Apache James :: Server :: SMTP ..................... FAILURE [ 24.495 s]


[Building Java 8 mailet-107-da162c6b-7023-469a-ab9c-b6aee7d5819c] Tests in error: 
[Building Java 8 mailet-107-da162c6b-7023-469a-ab9c-b6aee7d5819c]   SMTPServerTest.testConnectionLimit:374 » SMTPConnectionClosed Connection close...
```

**Pull request closed without merging**
