### PR TITLE
JAMES-2709 Debug logs for LinShare containers

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by mbaechler** [comment]
```
[e1619999e41e92d5bcbdd342c7de43abb82cd456] [ERROR] Errors: 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] [ERROR]   GetMessageListMethodTest.setup:114 » ElasticsearchStatus Elasticsearch excepti...
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[e1619999e41e92d5bcbdd342c7de43abb82cd456] [ERROR] exportShouldShareTheDocumentViaLinshareWhenJmapDelete  Time elapsed: 0.012 s  <<< ERROR!
[e1619999e41e92d5bcbdd342c7de43abb82cd456] java.lang.ExceptionInInitializerError
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 	at org.apache.james.jmap.methods.integration.LinshareBlobExportMechanismIntegrationTest.<clinit>(LinshareBlobExportMechanismIntegrationTest.java:85)
[e1619999e41e92d5bcbdd342c7de43abb82cd456] Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 	at org.apache.james.jmap.methods.integration.LinshareBlobExportMechanismIntegrationTest.<clinit>(LinshareBlobExportMechanismIntegrationTest.java:85)
[e1619999e41e92d5bcbdd342c7de43abb82cd456] Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 	at org.apache.james.jmap.methods.integration.LinshareBlobExportMechanismIntegrationTest.<clinit>(LinshareBlobExportMechanismIntegrationTest.java:85)
[e1619999e41e92d5bcbdd342c7de43abb82cd456] Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 	at org.apache.james.jmap.methods.integration.LinshareBlobExportMechanismIntegrationTest.<clinit>(LinshareBlobExportMechanismIntegrationTest.java:85)
[e1619999e41e92d5bcbdd342c7de43abb82cd456] Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*The following user provider for domain '.*' was successfully created.*'

[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:11:51,588 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:11:51,589 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:01,722 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  using stale statistics instead of current ones because stats collector is not responding
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:01,728 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> FATAL:  could not write init file
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:21,572 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:21,572 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:31,710 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  using stale statistics instead of current ones because stats collector is not responding
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:31,716 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> FATAL:  could not write init file
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:51,589 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:12:51,589 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:13:01,723 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  using stale statistics instead of current ones because stats collector is not responding
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:13:01,728 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> FATAL:  could not write init file
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:13:21,587 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 
[e1619999e41e92d5bcbdd342c7de43abb82cd456] 2019-06-25 03:13:21,587 DEBUG [tc-okhttp-stream-1517116047] - [org.apache.james.linshare.Linshare]- <linshare-database> LOG:  could not close temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
```

No space left on device

CI runner: `Running on ci-james-05 in /home/jenkins/build/workspace/workflow`

test this please

**Comment by Arsnael** [comment]
```
[e1619999e41e92d5bcbdd342c7de43abb82cd456] [ERROR]   SpamAssassinContract.spamShouldBeDeliveredInSpamMailboxOrInboxWhenMultipleRecipientsConfigurations:628 » ConditionTimeout
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
