### PR TITLE
JAMES-2820 Reduce Mono.defer usages in UnionBlobStore

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by blackheaven** [comment]
> Could you explain in your commit message why defer is an issue?

sure

> Do you have benchmarks associated with this change?

it will change nothing

**Comment by mbaechler** [comment]
As far as I understand, we use defer as many time as before

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
> As far as I understand, we use defer as many time as before

We use one Provider less

**Pull request merged**
