### PR TITLE
JAMES-2641 Remove MailboxEventDispatcher

### PR DESCRIPTION
**Pull request by chibenwa**
This extra component is no more needed as event firing will be done on the EventBus / Delegating listener directly

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[3f7bd1b1514c169b59a5d75cf992bc4ea4f413d7] [ERROR] COMPILATION ERROR : 
[3f7bd1b1514c169b59a5d75cf992bc4ea4f413d7] [INFO] -------------------------------------------------------------
[3f7bd1b1514c169b59a5d75cf992bc4ea4f413d7] [INFO] Using 'UTF-8' encoding to copy filtered resources.
[3f7bd1b1514c169b59a5d75cf992bc4ea4f413d7] [INFO] skip non existing resourceDirectory /james-project/mpt/impl/imap-mailbox/elasticsearch/src/main/resources
[3f7bd1b1514c169b59a5d75cf992bc4ea4f413d7] [ERROR] /james-project/mpt/impl/imap-mailbox/inmemory/src/test/java/org/apache/james/mpt/imapmailbox/inmemory/host/InMemoryHostSystem.java:[78,140] cannot find symbol
[3f7bd1b1514c169b59a5d75cf992bc4ea4f413d7]   symbol:   method getEventDispatcher()
[3f7bd1b1514c169b59a5d75cf992bc4ea4f413d7]   location: variable mailboxManager of type org.apache.james.mailbox.store.StoreMailboxManager
```

**Comment by aduprat** [comment]
Was :green_apple: before restarting the CI.

**Comment by openpaas-james** [comment]
Build triggered. sha1 is merged.

**Comment by openpaas-james** [comment]
Build started sha1 is merged.

**Comment by openpaas-james** [comment]
Build finished. No test results found.

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
