### PR TITLE
JAMES-2344 Log with failed stacktraces on SpamAssassin in production

### PR DESCRIPTION
**Pull request by chibenwa**
Sadly the stack trace did not allow to debug as part of it was swallowed....

### CODE REVIEW

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
```

[main] ERROR org.apache.jsieve - Parse failed. Reason: Encountered "<EOF>" at line 2, column 19.
Was expecting one of:
    <IDENTIFIER> ...
    <TAG> ...
    <NUMBER> ...
    <QUOTED_STRING> ...
    <MULTI_LINE> ...
    ";" ...
    "{" ...
    "(" ...
    "[" ...
    
[cluster2-reconnection-1] ERROR com.datastax.driver.core.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
[cluster1-reconnection-1] ERROR com.datastax.driver.core.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
[dockerjava-netty-1-5] INFO org.apache.james.backends.cassandra.DockerCassandraRule - 
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.352 sec - in org.apache.james.mpt.managesieve.cassandra.CassandraCheckScriptTest
```
test this please

**Comment by chibenwa** [comment]
Build results lost

test this please

**Comment by chibenwa** [comment]
```
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] [main] ERROR org.apache.jsieve - Parse failed. Reason: Encountered "<EOF>" at line 2, column 19.
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] Was expecting one of:
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     <IDENTIFIER> ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     <TAG> ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     <NUMBER> ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     <QUOTED_STRING> ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     <MULTI_LINE> ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     ";" ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     "{" ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     "(" ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     "[" ...
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]     
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] [cluster1-reconnection-1] ERROR com.datastax.driver.core.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] [cluster2-reconnection-0] ERROR com.datastax.driver.core.ControlConnection - [Control connection] Cannot connect to any host, scheduling retry in 1000 milliseconds
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] [dockerjava-netty-1-5] INFO org.apache.james.backends.cassandra.DockerCassandraRule - 
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.985 sec - in org.apache.james.mpt.managesieve.cassandra.CassandraCheckScriptTest
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] 
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] Results :
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] 
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] Tests in error: 
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13]   PutScriptTest.putScriptShouldWork:59 » InvalidServerResponse 
[9e0bec23ba5756344ae647e1d1ae26d93bd62b13] Location: /org/a...
```

**Comment by chibenwa** [comment]
Mailbox Cassandra failure

```
[e74ae22c2dd9a05149aeab65459743abe99a2217] Failed tests: 
[e74ae22c2dd9a05149aeab65459743abe99a2217]   AbstractSubscriptionManagerTest.subscribeShouldBeIdempotent Multiple Failures (2 failures)
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	Can't use this cluster instance because it was previously closed
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	<no message> in java.lang.NullPointerException
[e74ae22c2dd9a05149aeab65459743abe99a2217]   AbstractSubscriptionManagerTest.unsubscribeShouldBeIdempotent Multiple Failures (2 failures)
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	Can't use this cluster instance because it was previously closed
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	<no message> in java.lang.NullPointerException
[e74ae22c2dd9a05149aeab65459743abe99a2217]   AbstractSubscriptionManagerTest.user1ShouldBeAbleToSubscribeOneMailbox Multiple Failures (2 failures)
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	Can't use this cluster instance because it was previously closed
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	<no message> in java.lang.NullPointerException
[e74ae22c2dd9a05149aeab65459743abe99a2217]   AbstractSubscriptionManagerTest.user1ShouldBeAbleToSubscribeTwoMailbox Multiple Failures (2 failures)
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	Can't use this cluster instance because it was previously closed
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	<no message> in java.lang.NullPointerException
[e74ae22c2dd9a05149aeab65459743abe99a2217]   AbstractSubscriptionManagerTest.user1ShouldBeAbleToUnsubscribeOneMailbox Multiple Failures (2 failures)
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	Can't use this cluster instance because it was previously closed
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	<no message> in java.lang.NullPointerException
[e74ae22c2dd9a05149aeab65459743abe99a2217]   AbstractSubscriptionManagerTest.user1ShouldNotHaveAnySubscriptionByDefault Multiple Failures (2 failures)
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	Can't use this cluster instance because it was previously closed
[e74ae22c2dd9a05149aeab65459743abe99a2217] 	<no message> in java.lang.NullPointerException
```

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
