### PR TITLE
[NO_REVIEW] JAMES-3477 Drop MimeMessageCopyOnWriteProxy

### PR DESCRIPTION
**Pull request by chibenwa**
Base PR: https://github.com/apache/james-project/pull/282

Previous implementation was not thread safe as demonstrated
by @jeantil and @mbaechler. Upon concurrent writes and disposes
it leads to corruption of the underlying message, throwing
NullPointerExceptions and leads to data loss. [1]

Attempts to make it thread safe like [2] were complex, error
prone (double read-write lock involved!), and ultimately did
not manage to protect 'optimized' raw access to the underlying
data thus not fully addressing the concurrency issues.

Benchmarks were conducted in order to compare the Copy On
Write implementation with its always-copy equivalent. We
highlighted minor benefits of the copy-on-write version (
up to a few percent) both on compute time and memory allocation.
Only for bigger messages (10MB) did we reach higher differences,
of around 10%.

Note that the actual copy uses DeferredFileOutputStream
(commons.io) thus limits memory usage to 100KB upon copy.

[1] https://github.com/apache/james-project/pull/280/commits/09b5554bbcbbb98757910d59bac54f97ee1f8b4f
[2] https://github.com/apache/james-project/pull/280
[3] https://github.com/apache/james-project/pull/280#issuecomment-745211736

### CODE REVIEW

**Comment by chibenwa** [comment]
Spotted in the logs:

```
java.lang.NullPointerException: null
	at org.apache.james.blob.mail.MimeMessageStore$MimeMessageEncoder.messageToArray(MimeMessageStore.java:90)
	at org.apache.james.blob.mail.MimeMessageStore$MimeMessageEncoder.encode(MimeMessageStore.java:76)
	at org.apache.james.blob.mail.MimeMessageStore$MimeMessageEncoder.encode(MimeMessageStore.java:72)
	at org.apache.james.blob.api.Store$Impl.save(Store.java:84)
	at org.apache.james.queue.rabbitmq.Enqueuer.saveMail(Enqueuer.java:89)
	at org.apache.james.queue.rabbitmq.Enqueuer.enQueue(Enqueuer.java:72)
	at org.apache.james.queue.rabbitmq.RabbitMQMailQueue.lambda$enQueue$0(RabbitMQMailQueue.java:85)
	at com.github.fge.lambdas.runnable.RunnableChainer.lambda$sneakyThrow$215(RunnableChainer.java:71)
	at org.apache.james.metrics.api.MetricFactory.lambda$runPublishingTimerMetric$0(MetricFactory.java:58)
	at org.apache.james.metrics.api.MetricFactory.decorateSupplierWithTimerMetric(MetricFactory.java:37)
	at org.apache.james.metrics.api.MetricFactory.runPublishingTimerMetric(MetricFactory.java:57)
	at org.apache.james.queue.rabbitmq.RabbitMQMailQueue.enQueue(RabbitMQMailQueue.java:84)
	at org.apache.james.mailetcontainer.impl.JamesMailSpooler.reEnqueue(JamesMailSpooler.java:199)
	at org.apache.james.mailetcontainer.impl.JamesMailSpooler.handleError(JamesMailSpooler.java:181)
	at org.apache.james.mailetcontainer.impl.JamesMailSpooler.performProcessMail(JamesMailSpooler.java:166)
	at org.apache.james.mailetcontainer.impl.JamesMailSpooler.lambda$processMail$6(JamesMailSpooler.java:152)
	at reactor.core.publisher.MonoRunnable.subscribe(MonoRunnable.java:49)
	at reactor.core.publisher.MonoUsing.subscribe(MonoUsing.java:109)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4210)
	at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:199)
	at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:4195)
	at reactor.core.publisher.MonoSubscribeOn$SubscribeOnSubscriber.run(MonoSubscribeOn.java:124)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Likely related....

**Comment by chibenwa** [comment]
```

[adc3a78b8202145591d6932b36a07d7832a27979] [ERROR] Errors: 
[adc3a78b8202145591d6932b36a07d7832a27979] [ERROR]   MailSpoolTest.sendShouldEnQueueTheMail:61 » NullPointer
[adc3a78b8202145591d6932b36a07d7832a27979] [ERROR]   MailSpoolTest.sendShouldPositionJMAPRelatedMetadata:73 » NullPointer
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR] Failures: 
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailboxChangeTest.shouldMatchBeanContract:40 EqualsVerifier found a problem in class MailboxChange.
[c84e83460c71a25a97a63dc399ef528f1b300feb] -> Significant fields: equals does not use isCountChange, or it is stateless.
[c84e83460c71a25a97a63dc399ef528f1b300feb] 
[c84e83460c71a25a97a63dc399ef528f1b300feb] For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailboxChangeTest.shouldThrowOnNullAccountId:45 
[c84e83460c71a25a97a63dc399ef528f1b300feb] Expecting code to raise a throwable.
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailboxChangeTest.shouldThrowOnNullDate:65 
[c84e83460c71a25a97a63dc399ef528f1b300feb] Expecting code to raise a throwable.
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailboxChangeTest.shouldThrowOnNullState:55 
[c84e83460c71a25a97a63dc399ef528f1b300feb] Expecting code to raise a throwable.
[c84e83460c71a25a97a63dc399ef528f1b300feb] [INFO] 
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR] Tests run: 271, Failures: 4, Errors: 0, Skipped: 0
```
related?

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`no known node for /home/jenkins/build/workspace/1155` test this please

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
```
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   CassandraMailboxMapperTest$ConsistencyTest.createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox:617 Multiple Failures (1 failure)
[c84e83460c71a25a97a63dc399ef528f1b300feb] 	
[c84e83460c71a25a97a63dc399ef528f1b300feb] Expected size:<1> but was:<2> in:
[c84e83460c71a25a97a63dc399ef528f1b300feb] <[Mailbox{id=9e44a300-49a2-11eb-9bec-0f24510532b2, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=name},
[c84e83460c71a25a97a63dc399ef528f1b300feb]     Mailbox{id=b0358840-49a2-11eb-9bec-0f24510532b2, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=INBOX}]>
[c84e83460c71a25a97a63dc399ef528f1b300feb] at CassandraMailboxMapperTest$ConsistencyTest.lambda$createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox$34(CassandraMailboxMapperTest$ConsistencyTest.java:628)
```

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   CassandraMailboxMapperTest$ConsistencyTest.createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox:617 Multiple Failures (1 failure)
[c84e83460c71a25a97a63dc399ef528f1b300feb] 	
[c84e83460c71a25a97a63dc399ef528f1b300feb] Expected size:<1> but was:<2> in:
[c84e83460c71a25a97a63dc399ef528f1b300feb] <[Mailbox{id=9e44a300-49a2-11eb-9bec-0f24510532b2, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=name},
[c84e83460c71a25a97a63dc399ef528f1b300feb]     Mailbox{id=b0358840-49a2-11eb-9bec-0f24510532b2, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=INBOX}]>
[c84e83460c71a25a97a63dc399ef528f1b300feb] at CassandraMailboxMapperTest$ConsistencyTest.lambda$createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox$34(CassandraMailboxMapperTest$ConsistencyTest.java:628)
```
you sure it's not related?

**Comment by jeantil** [comment]
@Arsnael This test was already failing 12 days ago on apache master in https://builds.apache.org/blue/organizations/jenkins/james%2FApacheJames/detail/PR-268/38/pipeline

which resulted in me addind an Unstable tag https://github.com/apache/james-project/commit/493192daab00fd1566d7756c3d961694b5027141 (sorry if the commit date is wrong I rewrote history quite a few times on that branch)

Now maybe the assertion was wrong on master :)

**Comment by Arsnael** [comment]
@jeantil no you might be right. I think I saw this test failing somewhere else after as well. It's likely flaky.

Thanks for notifying though :)

**Comment by jeantil** [comment]
It may have been flaky before because of the concurrency issue, it may even have incorrectly reported correct results and occasionnally failed on correct results because of the concurrency issue. 
Since the concurrency issue is fixed by this PR, it may now be reliably be failing :/ not because this PR introduces a regression but because it brings a previous bug to light in a consistent manner

**Comment by Arsnael** [comment]
well could have been, but then I tried to run it locally on this PR and I could not make it break. Sooooo... not so sure what's going on then^^'

**Comment by chibenwa** [comment]
> Since the concurrency issue is fixed by this PR

It's indepandant Jean. I miss insight on what happens and cannot reproduce it locally.

https://github.com/linagora/james-project/pull/4138 attempts to reproduce it , and adds Cassandra query logging so that I have a better idea of what happens.

**Comment by chibenwa** [comment]
> you sure it's not related?

Sure. MailboxManager do not rely on javax.mail MimeMessage.

**Comment by jeantil** [comment]
>It's indepandant Jean. I miss insight on what happens and cannot reproduce it locally.

good, I'll leave it tagged unstable for now then :p

**Comment by chibenwa** [comment]
```
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR] Errors: 
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$ClearMail.clearMailQueueShouldDeleteAllMailsInQueueWhenNoQueryParameters:997 » NullPointer
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$ClearMail.clearMailQueueShouldHaveDetailsWhenNoQueryParameters:960 » NullPointer
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$DeleteMail$HttpBodies.deleteMailsTasksShouldHaveDetailsWhenNameIsGiven:708 » NullPointer
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$DeleteMail$HttpBodies.deleteMailsTasksShouldHaveDetailsWhenRecipientIsGiven:743 » NullPointer
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$DeleteMail$HttpBodies.deleteMailsTasksShouldHaveDetailsWhenSenderIsGiven:671 » NullPointer
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$DeleteMail$SideEffects.deleteMailsShouldDeleteMailsWhenNameIsGiven:823 » NullPointer
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$DeleteMail$SideEffects.deleteMailsShouldDeleteMailsWhenRecipientIsGiven:855 » NullPointer
[c84e83460c71a25a97a63dc399ef528f1b300feb] [ERROR]   MailQueueRoutesTest$DeleteMail$SideEffects.deleteMailsShouldDeleteMailsWhenSenderIsGiven:789 » NullPointer
```

**Comment by chibenwa** [comment]
(only the last commit is new)

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
No longer needed as builds can be conducted against Apqache infra directly...

**Pull request closed without merging**
