### PR TITLE
James 1841 Improve server website a bit

### PR DESCRIPTION
**Pull request by chibenwa**
screenshot from 2016-10-19 13-56-21

Here you see default index (moved to v3)
 - It has links to previous version
 - Every side menu had been merged in one

screenshot from 2016-10-19 13-56-41

You see here the "Objective" page I found interesting on previous website.

screenshot from 2016-10-19 13-56-53

And now Feature page. I did my best to update it.

I also remove some not needed anymore pages and removed comments. Also hunted typo.

### CODE REVIEW

**Comment by Laura-Royet** [comment]
Apache James Server 3 tab is not updated isn't it ?
- The news regarding 3.0-beta4 release should be replaced by the 3.0 release as soon as this release will be out. For the moment we could add something here about this imminent release ?
- Protocols list is not updated
- the work on experimental module is now done so we could change this sentence ?

**Comment by chibenwa** [comment]
> For the moment we could add something here about this imminent release ?

Ok

> Protocols list is not updated

Ok

> the work on experimental module is now done so we could change this sentence ?

I miss context to understand this remark

**Comment by Laura-Royet** [comment]
About experimental module, the sentence is the following : "We are currently working on an experimental module which goal is to simplify the configuration process. This module only supports the Cassandra backend yet, and may be started with docker. "
Is this thing has not already be done ?

**Comment by Laura-Royet** [comment]
- Where is "useful RFCs" part now (previously present in James Server section) ?
- Where is "Source" part now  (previously present in James Server section) ?
- What will contain now the Documentation > Server v3 part ?
- Why did you put the unworking link to Snapshot Apache James 3.0 in the "Apache James Server 3" tab ?

**Comment by chibenwa** [comment]
> Where is "useful RFCs" part now (previously present in James Server section) ?

I will add it as TAB

> Where is "Source" part now (previously present in James Server section) ?

Added to menu

> What will contain now the Documentation > Server v3 part ?

Removed

> Why did you put the unworking link to Snapshot Apache James 3.0 in the "Apache James Server 3" tab ?

Removed

**Comment by chibenwa** [comment]
screenshot from 2016-10-20 14-21-14

Adding RFC page

**Comment by chibenwa** [comment]
New visuals requested by @mbaechler : 

screenshot from 2016-10-20 17-54-37

screenshot from 2016-10-20 17-54-50

screenshot from 2016-10-20 17-54-53

screenshot from 2016-10-20 17-54-58

screenshot from 2016-10-20 17-55-07

**Comment by mbaechler** [comment]
Apache James Server : 
* we should remove the banner with news
* the description is too broad : we should have a "James" tab that describe the project, sever tab should say "that's the project that put together all the parts to provide a running service, bla bla bla".
* we should not talk about James 2. Maybe having a tab for it would allow to not pollute main tab and make information accessible too ?
* we shouldn't talk about lost features, there's the feature tabs for that.

Other pages seem ok.

**Comment by Laura-Royet** [comment]
Apache James Server : 
Please add a "s" at the end of "test" in : "The James team is working hard...write more test"

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Banner with news removed

**Comment by chibenwa** [comment]
Lost feature removed

**Comment by chibenwa** [comment]
Tab for James 2 created

**Pull request closed without merging**
