### PR TITLE
MAILBOX-271 CassandraMailboxSessionMapperFactory should not create ma…

### PR DESCRIPTION
**Pull request by chibenwa**
…ppers on a per-request basis

Note : Now we can prepare every query in the mailbox project. Would you like me to do it ?

### CODE REVIEW

**Comment by mbaechler** [comment]
I saw that during review but you have to break the design of mapper to fix it.
The right way to do that is to split mappers from DAO and make DAO a service (no new instance)

**Comment by mbaechler** [comment]
👍

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Pull request merged**
