### PR TITLE
MPT-41 Re-enable deployment tests

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] -------------------------------------------------------
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b]  T E S T S
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] -------------------------------------------------------
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] Running org.apache.james.mpt.imapmailbox.external.james.JamesDeploymentValidationTest
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.629 sec <<< FAILURE! - in org.apache.james.mpt.imapmailbox.external.james.JamesDeploymentValidationTest
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] validateDeployment  Time elapsed: 0.411 sec  <<< ERROR!
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] java.nio.channels.UnresolvedAddressException
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] 	at org.apache.james.mpt.imapmailbox.suite.DeploymentValidation.validateDeployment(DeploymentValidation.java:50)
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] 
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] 
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] Results :
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] 
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b] Tests in error: 
[55d605a8756ec86e29f9ec7ee4a4041b09d94a2b]   DeploymentValidation.validateDeployment:50 » UnresolvedAddress
```

**Comment by chibenwa** [comment]
See this fix: https://github.com/linagora/james-jenkins/pull/102

Required in order for that branch to be :green_apple:

**Comment by chibenwa** [comment]
Forced pushed to resolve conflict....

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by chibenwa** [comment]
test this please

```
 > git -c core.askpass=true fetch --tags --progress https://github.com/linagora/james-jenkins +refs/heads/*:refs/remotes/origin/*
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://github.com/linagora/james-jenkins
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:735)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:983)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1016)
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:109)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:109)
	at org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition.create(CpsScmFlowDefinition.java:58)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:179)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress https://github.com/linagora/james-jenkins +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/linagora/james-jenkins/': Empty reply from server

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1591)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1379)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:86)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:324)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:733)
	... 8 more
ERROR: Error fetching remote repo 'origin'
Finished: FAILURE
```

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/pull/1610 solved this

**Pull request closed without merging**
