### PR TITLE
[NO_REVIEW] Adapt java-11 compilation image to gradle & produce guice artifacts

### PR DESCRIPTION
**Pull request by Arsnael**
See https://github.com/apache/james-project/pull/231

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[56a3dc84912bdfe3f70768aa7430c97d0d7ea343] /root/compile.sh: 68: /root/compile.sh: ./gradlew: Permission denied
```

Was fine on my local...

**Comment by rouazana** [comment]
> ```
> [56a3dc84912bdfe3f70768aa7430c97d0d7ea343] /root/compile.sh: 68: /root/compile.sh: ./gradlew: Permission denied
> ```
> 
> Was fine on my local...

As you are installing Gradle first, you should not rely on gradlew but directly on `/usr/bin/gradle`

**Comment by Arsnael** [comment]
> As you are installing Gradle first, you should not rely on gradlew but directly on `/usr/bin/gradle`

Yes I just updated that and ti compiles

**Comment by Arsnael** [comment]
```
[6434c59ea68db30bc98495602051b8542d6eacf0] + docker cp james-parent-test-gradle-ci-transition-0f275c6e-a949-4f40-9bd1-2a5b4a002f02:cassandra-rabbitmq-ldap/destination/james-server-cassandra-rabbitmq-ldap-guice.lib destination
[6434c59ea68db30bc98495602051b8542d6eacf0] Error response from daemon: Could not find the file cassandra-rabbitmq-ldap/destination/james-server-cassandra-rabbitmq-ldap-guice.lib in container james-parent-test-gradle-ci-transition-0f275c6e-a949-4f40-9bd1-2a5b4a002f02
```
Well not surprised... Forgot to modify all Docker files in the `run` folder for each implementation

**Comment by Arsnael** [comment]
```
[d6ef8a9e40fe34d86941b5a6d994a83f3e1b986f] Error response from daemon: Could not find the file cassandra-rabbitmq-ldap/destination/james-server-cassandra-rabbitmq-ldap-guice.lib in container james-parent-test-gradle-ci-transition-f369d0ff-b787-4168-8b46-e1ca3db77a99
```

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
I have this issue when I try to compile for example `cassandra-rabbitmq` guice product into a jar and run it with other docker containers :

```
1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1086)
        at org.apache.james.GuiceJamesServer.start(GuiceJamesServer.java:91)
        at org.apache.james.JamesServerMain.main(JamesServerMain.java:30)
        at org.apache.james.CassandraRabbitMQJamesServerMain.main(CassandraRabbitMQJamesServerMain.java:51)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/internal/util/$Maps
        at com.google.inject.assistedinject.BindingCollector.<init>(BindingCollector.java:34)
        at com.google.inject.assistedinject.FactoryModuleBuilder.<init>(FactoryModuleBuilder.java:206)
        at org.jclouds.openstack.keystone.catalog.config.ServiceCatalogModule$RegionModule.configure(ServiceCatalogModule.java:117)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:61)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:344)
        at com.google.inject.spi.Elements.getElements(Elements.java:103)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:137)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:405)
        at org.jclouds.ContextBuilder.buildInjector(ContextBuilder.java:328)
        at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:615)
        at org.jclouds.ContextBuilder.buildView(ContextBuilder.java:595)
        at org.apache.james.blob.objectstorage.swift.SwiftTempAuthObjectStorage$BlobStoreBuilder.get(SwiftTempAuthObjectStorage.java:68)
        at org.apache.james.blob.objectstorage.swift.SwiftTempAuthObjectStorage$BlobStoreBuilder.get(SwiftTempAuthObjectStorage.java:55)
        at org.apache.james.blob.objectstorage.ObjectStorageBlobStoreBuilder$ReadyToBuild.build(ObjectStorageBlobStoreBuilder.java:99)
        at org.apache.james.modules.objectstorage.ObjectStorageDependenciesModule.buildObjectStore(ObjectStorageDependenciesModule.java:70)

[...]

Caused by: java.lang.ClassNotFoundException: com.google.inject.internal.util.$Maps
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 99 more
```
Seems to be a dependency issue with Guice module `com.google.inject.extensions::guice-multibindings`. So I tried to do like with the maven poms, where we exclude it, but I still have the error. Maybe I missed something or did something wrong... Will investigate more tomorrow

**Pull request closed without merging**
