### PR TITLE
[NO_REVIEW] JAMES-3261 Build a ZIP distribution for Guice memory 

### PR DESCRIPTION
**Pull request by chibenwa**
https://github.com/apache/james-project/pull/221

### CODE REVIEW

**Comment by chibenwa** [comment]
`RabbitMQDeletedMessageVaultIntegrationTest>DeletedMessageVaultIntegrationTest.vaultExportShouldExportZipContainsVaultMessagesToShareeWhenImapDeletedMailbox:543 
[5054118e0da2b2741ee6a84352bba97f5f194b57] Expecting zipFile to contains 1 entries but actually contains (0) entries`

unrelated

test this please

**Comment by chibenwa** [comment]
It's the CI code:

```
[3dc8fa1e06125645b954a9e0fc86267d68202d4b] + cd dockerfiles/run/guice/memory
[3dc8fa1e06125645b954a9e0fc86267d68202d4b] + docker cp james-parent-test-james-3261-689ae584-fae4-4b2a-b6a8-b4528cc63ab5:memory/destination/james-server-memory-guice.jar destination
[3dc8fa1e06125645b954a9e0fc86267d68202d4b] Error response from daemon: Could not find the file memory/destination/james-server-memory-guice.jar in container james-parent-test-james-3261-689ae584-fae4-4b2a-b6a8-b4528cc63ab5
```

**Comment by Arsnael** [comment]
Conflicts with master branch

**Comment by chibenwa** [comment]
> Conflicts with master branch

Yes however as Eugen asked me to minimize diff in pom, this work is currently on hold

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
No longer needed as builds can be conducted against Apqache infra directly...

**Pull request closed without merging**
