### PR TITLE
JAMES-3000 bump scala version to 2.13.1

### PR DESCRIPTION
**Pull request by remk**

### CODE REVIEW

**Comment by remk** [comment]
```
[cbad6f3317320b81f4922557cbbb0574e145ff43] [INFO] Running org.apache.james.queue.file.FileMailQueueFactoryTest
[cbad6f3317320b81f4922557cbbb0574e145ff43] [INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.766 s - in org.apache.james.queue.file.FileMailQueueFactoryTest
[cbad6f3317320b81f4922557cbbb0574e145ff43] [INFO] Running org.apache.james.queue.file.FileMailQueueTest
[cbad6f3317320b81f4922557cbbb0574e145ff43] [ERROR] Tests run: 73, Failures: 0, Errors: 1, Skipped: 9, Time elapsed: 72.032 s <<< FAILURE! - in org.apache.james.queue.file.FileMailQueueTest
[cbad6f3317320b81f4922557cbbb0574e145ff43] [ERROR] dequeueShouldBeConcurrent  Time elapsed: 61.183 s  <<< ERROR!
[cbad6f3317320b81f4922557cbbb0574e145ff43] org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in org.apache.james.queue.api.MailQueueContract that uses java.util.concurrent.ConcurrentLinkedDeque, java.util.concurrent.ConcurrentLinkedDequeint was not fulfilled within 60 seconds.
[cbad6f3317320b81f4922557cbbb0574e145ff43] 
[cbad6f3317320b81f4922557cbbb0574e145ff43] [INFO] 
[cbad6f3317320b81f4922557cbbb0574e145ff43] [INFO] Results:
[cbad6f3317320b81f4922557cbbb0574e145ff43] [INFO] 
[cbad6f3317320b81f4922557cbbb0574e145ff43] [ERROR] Errors: 
[cbad6f3317320b81f4922557cbbb0574e145ff43] [ERROR]   FileMailQueueTest.dequeueShouldBeConcurrent » ConditionTimeout Condition with ...
```

**Comment by remk** [comment]
test this please

**Comment by Arsnael** [comment]
```
FileMailQueueTest.dequeueShouldBeConcurrent » ConditionTimeout Condition with ...
```
test this please

**Comment by remk** [comment]
> I forgot but I think I remember there was a reason before why we refrained from bumping the scala version... What was it again and are we good now?

It was before of eclipse support. But as it doesn't work already there is no reason to postpone this upgrade. I detailed this in the Jira ticket.

**Comment by trantienduchn** [comment]
Read it

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
