### PR TITLE
JAMES-2523 Fix GuiceJamesServer RemoteDelivery/DeliveryRunnable thread leak

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [ERROR] Failures: 
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [ERROR]   WebAdminServerIntegrationTest.postShouldDoMigrationAndUpdateToTheLatestVersion:276 1 expectation failed.
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] Response body doesn't match expectation.
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] Expected: is "{\"version\":6}"
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3]   Actual: {"version":4}
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] 
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [INFO] 
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [ERROR] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
```
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [INFO] Results:
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [INFO] 
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [ERROR] Errors: 
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [ERROR]   DomainUserMaildirMailboxManagerTest>MailboxManagerTest.creatingConcurrentlyMailboxesWithSameParentShouldNotFail:988 » Execution
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [ERROR]   FullUserMaildirMailboxManagerTest>MailboxManagerTest.creatingConcurrentlyMailboxesWithSameParentShouldNotFail:988 » Execution
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [INFO] 
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [ERROR] Tests run: 131, Failures: 0, Errors: 2, Skipped: 68
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [INFO] 
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [INFO] ------------------------------------------------------------------------
[d8a6ebf492db7ef0240e8a2ccc890e6efd35dcd3] [INFO] Reactor Summary:
```
test this please

**Comment by chibenwa** [comment]
I found 2 more similar problems:
 - For ES deleteByQuery stuff
 - For mixed event delivery cleanup.

I contributed the patches...

**Comment by chibenwa** [comment]
test this please (maildir)

**Comment by chibenwa** [comment]
```
[aa6341541fff9488da2a9a6061883237f7063d75] Error executing docker rm --force=true --volumes=true git-publish-james-2523-49e950ed-373b-40dc-b4bd-3c6d769d39e9 : no known node for /home/jenkins/build/workspace/664
```

test this please

**Comment by chibenwa** [comment]
test this please (maildir)

**Comment by blackheaven** [comment]
test this please

**Comment by chibenwa** [comment]
```
[56194e8f36f959af5f3e6d4048dde8031503653a] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project cassandra-jmap-integration-testing: There was a timeout or other error in the fork -> [Help 1]
[56194e8f36f959af5f3e6d4048dde8031503653a] [ERROR]
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
CI no more run on this...

**Pull request closed without merging**
