### PR TITLE
WIP for building test

### PR DESCRIPTION
**Pull request by aduprat**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[2def8e723b449102feecf3e8f4e56cfd43790031] fromStrictNoUnwrapShouldThrowWhenEmpty(org.apache.james.mailbox.model.CidTest)  Time elapsed: 0 sec  <<< ERROR!
[2def8e723b449102feecf3e8f4e56cfd43790031] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[2def8e723b449102feecf3e8f4e56cfd43790031] 
[2def8e723b449102feecf3e8f4e56cfd43790031] fromShouldThrowWhenBlank(org.apache.james.mailbox.model.CidTest)  Time elapsed: 0.001 sec  <<< ERROR!
[2def8e723b449102feecf3e8f4e56cfd43790031] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[2def8e723b449102feecf3e8f4e56cfd43790031] 
[2def8e723b449102feecf3e8f4e56cfd43790031] fromShouldThrowWhenEmpty(org.apache.james.mailbox.model.CidTest)  Time elapsed: 0 sec  <<< ERROR!
[2def8e723b449102feecf3e8f4e56cfd43790031] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[2def8e723b449102feecf3e8f4e56cfd43790031] 
[2def8e723b449102feecf3e8f4e56cfd43790031] fromShouldThrowWhenEmptyAfterRemoveTags(org.apache.james.mailbox.model.CidTest)  Time elapsed: 0 sec  <<< ERROR!
[2def8e723b449102feecf3e8f4e56cfd43790031] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[2def8e723b449102feecf3e8f4e56cfd43790031] 
[2def8e723b449102feecf3e8f4e56cfd43790031] fromStrictNoUnwrapShouldThrowWhenNull(org.apache.james.mailbox.model.CidTest)  Time elapsed: 0.001 sec  <<< ERROR!
[2def8e723b449102feecf3e8f4e56cfd43790031] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[2def8e723b449102feecf3e8f4e56cfd43790031] 
[2def8e723b449102feecf3e8f4e56cfd43790031] fromShouldThrowWhenNull(org.apache.james.mailbox.model.CidTest)  Time elapsed: 0 sec  <<< ERROR!
[2def8e723b449102feecf3e8f4e56cfd43790031] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[2def8e723b449102feecf3e8f4e56cfd43790031] 
[2def8e723b449102feecf3e8f4e56cfd43790031] fromStrinctNoUnwrapShouldThrowWhenBlank(org.apache.james.mailbox.model.CidTest)  Time elapsed: 0 sec  <<< ERROR!
[2def8e723b449102feecf3e8f4e56cfd43790031] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
```

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
test this please (yoda)

**Comment by aduprat** [comment]
test this please (yoda)

**Comment by aduprat** [comment]
```
Failed tests: 
  ElasticSearchIndexerTest.deleteByQueryShouldWorkWhenMultipleMessages:182 expected:<[1]L> but was:<[3]L>
```
test this please

**Comment by aduprat** [comment]
```
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache James Project 3.1.0-SNAPSHOT ................ SUCCESS [  2.007 s]
[INFO] Apache James :: Server ............................. SUCCESS [  1.319 s]
[INFO] Apache James :: Server :: Lifecycle API ............ SUCCESS [  1.466 s]
[INFO] Apache James :: Server :: Common Utilities :: Java 8 SUCCESS [ 19.601 s]
[INFO] Apache James :: Server :: Task ..................... SUCCESS [  3.728 s]
[INFO] Apache JAMES backends common ....................... SUCCESS [  0.502 s]
[INFO] Apache James Cassandra backend ..................... SUCCESS [ 53.651 s]
[INFO] apache-james-backends-es ........................... SUCCESS [ 20.506 s]
[INFO] apache-james-backends-jpa .......................... SUCCESS [  0.807 s]
[INFO] Apache James :: Core Domain Objects ................ SUCCESS [  3.995 s]
[INFO] Apache James :: Event Sourcing ..................... SUCCESS [  0.428 s]
[INFO] Apache James :: Event sourcing :: pojo ............. SUCCESS [  0.609 s]
[INFO] Apache James :: Event Sourcing :: Event Store :: API SUCCESS [  0.661 s]
[INFO] Apache James :: Event sourcing :: core ............. SUCCESS [  0.662 s]
[INFO] Apache James :: Event sourcing :: Event Store :: Cassandra SUCCESS [  1.236 s]
[INFO] Apache James :: Event sourcing :: Event Store :: Memory SUCCESS [  1.355 s]
[INFO] Apache James :: Java Mail Extension ................ SUCCESS [  0.497 s]
[INFO] Apache James :: Mailbox ............................ SUCCESS [  0.397 s]
[INFO] Apache James :: Mailbox :: API ..................... SUCCESS [ 22.634 s]
[INFO] Apache James :: MDN ................................ SUCCESS [ 12.396 s]
[INFO] Apache James :: Metrics ............................ SUCCESS [  0.389 s]
[INFO] Apache James :: Metrics :: API ..................... SUCCESS [  0.490 s]
[INFO] Apache James :: Server :: Common Utilities ......... SUCCESS [  6.769 s]
[INFO] Apache James :: Mailbox :: Store Framework ......... SUCCESS [ 37.951 s]
[INFO] Apache James :: Mailbox :: Caching ................. SUCCESS [  0.897 s]
[INFO] Apache James :: Server :: Blob ..................... SUCCESS [  0.387 s]
[INFO] Apache James :: Server :: Blob :: API .............. SUCCESS [  0.581 s]
[INFO] Apache James :: Server :: Blob :: Cassandra ........ SUCCESS [  1.520 s]
[INFO] Apache James :: Mailets parent and aggregator ...... SUCCESS [  0.395 s]
[INFO] Apache James :: Mailet API ......................... SUCCESS [  0.844 s]
[INFO] Apache James :: Basic Mailet Toolkit ............... SUCCESS [  4.663 s]
[INFO] Apache James :: Server :: Filesystem API ........... SUCCESS [  0.628 s]
[INFO] Apache James :: Server :: Core ..................... SUCCESS [ 13.345 s]
[INFO] Apache James :: Server :: Testing .................. SUCCESS [  2.083 s]
[INFO] Apache James :: Server :: MailRepository :: API .... SUCCESS [  0.843 s]
[INFO] Apache James :: Server :: Data  :: API ............. SUCCESS [  3.016 s]
[INFO] Apache James :: Mailbox :: Cassandra ............... SUCCESS [25:10 min]
[INFO] Apache James :: Mailbox :: In Memory ............... SUCCESS [ 19.425 s]
[INFO] Apache James :: Mailbox :: Tika .................... SUCCESS [ 19.458 s]
[INFO] Apache James :: Mailbox :: ElasticSearch ........... SUCCESS [03:17 min]
[INFO] Apache James :: Mailbox :: HBase ................... SUCCESS [01:18 min]
[INFO] Apache James :: Mailbox :: JCR ..................... SUCCESS [01:28 min]
[INFO] Apache James :: Mailbox :: JPA ..................... SUCCESS [ 31.905 s]
[INFO] Apache James :: Mailbox :: Kafka ................... SUCCESS [  1.009 s]
[INFO] Apache James :: Mailbox :: Lucene Index ............ SUCCESS [ 10.157 s]
[INFO] Apache James :: Mailbox :: Maildir ................. SUCCESS [ 18.957 s]
[INFO] Apache James :: Mailbox :: Scanning ................ SUCCESS [  6.826 s]
[INFO] Apache James :: Mailbox :: Tools ................... SUCCESS [  4.904 s]
[INFO] Apache James :: Mailbox :: Spring .................. SUCCESS [  4.644 s]
[INFO] Apache James :: Mailbox :: Zookeeper Sequence Provider SUCCESS [  2.776 s]
[INFO] Apache James :: Server :: DNS Service :: API ....... SUCCESS [  0.998 s]
[INFO] Apache James :: Server :: Data :: Library .......... SUCCESS [  3.089 s]
[INFO] Apache James :: Server :: Data  :: MEMORY .......... SUCCESS [  4.168 s]
[INFO] Apache James :: Mailbox :: Plugin :: Quota Mailing . SUCCESS [  1.169 s]
[INFO] Apache James :: Mailbox :: Plugin :: Quota Mailing :: Cassandra SUCCESS [  1.285 s]
[INFO] Apache James :: Mailbox :: Plugin :: Quota Mailing :: Memory SUCCESS [  0.807 s]
[INFO] Apache James :: Mailbox :: Plugin :: Quota Search :: API SUCCESS [  2.350 s]
[INFO] Apache James :: Mailbox :: Plugin :: Quota Search :: ElasticSearch SUCCESS [  4.318 s]
[INFO] Apache James :: Mailbox :: Plugin :: Quota Search :: Scanning SUCCESS [  0.715 s]
[INFO] Apache James :: Mailbox :: Plugin :: SpamAssassin .. SUCCESS [  2.010 s]
[INFO] Apache James :: AI Mailets ......................... SUCCESS [  1.229 s]
[INFO] Apache James :: Crypto Mailets ..................... SUCCESS [  1.953 s]
[INFO] Apache James :: ICalendar Mailets .................. SUCCESS [  4.232 s]
[INFO] Apache James :: Mailetdocs Maven Plugin ............ SUCCESS [  3.564 s]
[INFO] Apache James :: Standard Mailets ................... SUCCESS [  3.090 s]
[INFO] Apache James :: Metrics :: Dropwizard .............. SUCCESS [  0.653 s]
[INFO] Apache James :: Metrics :: Logger .................. SUCCESS [  0.485 s]
[INFO] Apache James MPT ................................... SUCCESS [  0.382 s]
[INFO] Apache James MPT All ............................... SUCCESS [  1.140 s]
[INFO] Apache James :: Protocols .......................... SUCCESS [  0.412 s]
[INFO] Apache James :: Protocols :: API ................... SUCCESS [  2.232 s]
[INFO] Apache James :: Protocols :: IMAP .................. SUCCESS [ 48.262 s]
[INFO] Apache James MPT Core .............................. SUCCESS [  6.988 s]
[INFO] Apache James MPT AntLib ............................ SUCCESS [  3.258 s]
[INFO] Apache James MPT Application ....................... SUCCESS [  2.089 s]
[INFO] Apache James :: Server :: Mailbox Adapter .......... SUCCESS [  3.148 s]
[INFO] Apache James MPT Imap Mailbox ...................... SUCCESS [  0.377 s]
[INFO] Apache James MPT Imap Mailbox Core ................. SUCCESS [  1.856 s]
[INFO] Apache James MPT Imap Mailbox - Cassandra .......... SUCCESS [ 38.133 s]
[INFO] Apache James MPT Imap Mailbox - Cyrus .............. SUCCESS [  1.201 s]
[INFO] Apache James MPT Imap Mailbox - ElasticSearch ...... SUCCESS [  1.537 s]
[INFO] Apache James MPT Imap Mailbox - External James ..... SUCCESS [  0.437 s]
[INFO] Apache James MPT Imap Mailbox - HBase .............. SUCCESS [  1.878 s]
[INFO] Apache James MPT Imap Mailbox - InMemory ........... SUCCESS [  2.341 s]
[INFO] Apache James MPT Imap Mailbox - JCR ................ SUCCESS [  0.536 s]
[INFO] Apache James MPT Imap Mailbox - JPA ................ SUCCESS [  2.490 s]
[INFO] Apache James MPT Imap Mailbox - LuceneSearch ....... SUCCESS [  2.428 s]
[INFO] Apache James MPT Imap Mailbox - Maildir ............ SUCCESS [  1.031 s]
[INFO] Apache James :: Protocols :: ManageSieve ........... SUCCESS [  1.238 s]
[INFO] Apache James MPT ManageSieve ....................... SUCCESS [  0.377 s]
[INFO] Apache James MPT ManageSieve Core .................. SUCCESS [  1.273 s]
[INFO] Apache James :: Server :: Data :: Cassandra Persistence SUCCESS [02:33 min]
[INFO] Apache James MPT ManageSieve Cassandra ............. SUCCESS [03:35 min]
[INFO] Apache James :: Server :: Data :: File Persistence . SUCCESS [  5.180 s]
[INFO] Apache James MPT ManageSieve File .................. SUCCESS [ 10.394 s]
[INFO] Apache James MPT SMTP .............................. SUCCESS [  0.380 s]
[INFO] Apache James MPT SMTP Core ......................... SUCCESS [  1.484 s]
[INFO] Apache James :: Server :: Data :: JMAP ............. SUCCESS [  6.597 s]
[INFO] Apache James :: Server :: Data :: JMAP :: Cassandra persistance SUCCESS [ 54.119 s]
[INFO] Apache James :: Server :: DNS Service :: Implementation SUCCESS [  1.311 s]
[INFO] Apache James :: Server :: DNS Service :: Library ... SUCCESS [  2.691 s]
[INFO] Apache James :: Server :: Guice .................... SUCCESS [  0.381 s]
[INFO] Apache James :: Server :: Guice :: Configuration ... SUCCESS [  0.676 s]
[INFO] james-server-guice-utils ........................... SUCCESS [  0.539 s]
[INFO] Apache James :: Server :: Guice :: Mailbox ......... SUCCESS [  2.377 s]
[INFO] Apache James :: Protocols :: Netty Implementation .. SUCCESS [  1.413 s]
[INFO] Apache James :: Server :: Protocols Library ........ SUCCESS [  1.005 s]
[INFO] Apache James :: Server :: IMAP ..................... SUCCESS [  1.724 s]
[INFO] Apache James :: Server :: Guice :: Imap ............ SUCCESS [  0.986 s]
[INFO] Apache James :: Server :: Mail Queue :: API ........ SUCCESS [  0.866 s]
[INFO] Apache James :: Server :: Mail Queue :: Memory ..... SUCCESS [  0.782 s]
[INFO] Apache James :: Protocols :: SMTP .................. SUCCESS [ 13.745 s]
[INFO] Apache James :: Server :: SMTP ..................... SUCCESS [ 17.843 s]
[INFO] Apache James :: Protocols :: LMTP .................. SUCCESS [  5.600 s]
[INFO] Apache James :: Server :: LMTP ..................... SUCCESS [  1.325 s]
[INFO] Apache James :: Server :: Guice :: Lmtp ............ SUCCESS [  1.014 s]
[INFO] Apache James :: Server :: Mailetcontainer API ...... SUCCESS [  0.653 s]
[INFO] Apache James :: Server :: Mailetcontainer Camel .... SUCCESS [  8.197 s]
[INFO] Apache James :: Server :: Guice :: Mailet .......... SUCCESS [  2.706 s]
[INFO] Apache James :: Server :: Guice :: Netty ........... SUCCESS [  0.823 s]
[INFO] Apache James :: Protocols :: POP3 .................. SUCCESS [  5.230 s]
[INFO] Apache James :: Server :: POP3 ..................... SUCCESS [  4.981 s]
[INFO] Apache James :: Server :: Guice :: Pop ............. SUCCESS [  0.930 s]
[INFO] Apache James :: Server :: Guice :: Smtp ............ SUCCESS [  0.982 s]
[INFO] Apache James :: Server :: JWT ...................... SUCCESS [  4.099 s]
[INFO] Apache James :: Server :: Web Admin :: Core ........ SUCCESS [ 12.584 s]
[INFO] Apache James :: Server :: Guice :: Webadmin ........ SUCCESS [  1.284 s]
[INFO] Apache James :: Server :: Mailets .................. SUCCESS [ 47.491 s]
[INFO] Apache James :: Server :: Onami .................... SUCCESS [  2.246 s]
[INFO] Apache James :: Server :: Mail Queue :: JMS ........ SUCCESS [  1.974 s]
[INFO] Apache James :: Server :: Mail Queue :: ActiveMQ ... SUCCESS [  1.454 s]
[INFO] Apache James :: Server :: Guice Common ............. SUCCESS [ 36.830 s]
[INFO] metrics-es-reporter ................................ SUCCESS [ 32.202 s]
[INFO] Apache James :: Server :: Guice :: ES metric reporter SUCCESS [  2.484 s]
[INFO] Apache James :: Server :: Jetty .................... SUCCESS [  3.392 s]
[INFO] Apache James :: Server :: JMAP ..................... SUCCESS [01:15 min]
[INFO] Apache James :: Server :: Guice :: Jmap ............ SUCCESS [  3.014 s]
[INFO] Apache James :: Server :: Guice :: JMX ............. SUCCESS [  2.214 s]
[INFO] Apache James :: Server :: Guice :: Mailbox :: Plugin :: SpamAssassin SUCCESS [  1.427 s]
[INFO] Apache James :: Server :: ManageSieve .............. SUCCESS [  0.799 s]
[INFO] Apache James :: Server :: Guice :: Managedsieve .... SUCCESS [  0.960 s]
[INFO] Apache James :: Server :: Web Admin :: Cassandra ... SUCCESS [  4.656 s]
[INFO] Apache James :: Server :: Guice :: Webadmin :: Cassandra SUCCESS [  1.828 s]
[INFO] Apache James :: Server :: Web Admin :: data ........ SUCCESS [  1.696 s]
[INFO] Apache James :: Server :: Guice :: Webadmin :: Data  SUCCESS [  1.289 s]
[INFO] Apache James :: Server :: Web Admin :: mailbox ..... SUCCESS [  2.570 s]
[INFO] Apache James :: Server :: Guice :: Webadmin :: Mailbox SUCCESS [  1.291 s]
[INFO] Apache James :: Server :: Web Admin :: MailQueue ... SUCCESS [  3.596 s]
[INFO] Apache James :: Server :: Guice :: Webadmin :: MailQueue SUCCESS [  1.264 s]
[INFO] Apache James :: Server :: MailRepository :: Memory . SUCCESS [  0.711 s]
[INFO] Apache James :: Server :: Web Admin :: MailRepository SUCCESS [  5.677 s]
[INFO] Apache James :: Server :: Guice :: Webadmin :: MailRepository SUCCESS [  1.269 s]
[INFO] Apache James :: Server :: Web Admin :: Swagger ..... SUCCESS [  1.252 s]
[INFO] Apache James :: Server :: Guice :: Webadmin :: Swagger SUCCESS [  1.267 s]
[INFO] Apache James :: Server :: JMAP :: Integration testing SUCCESS [  0.400 s]
[INFO] Apache James :: Server :: JMAP :: Integration testing Common SUCCESS [ 16.872 s]
[INFO] Apache James :: Server :: MailRepository :: Cassandra SUCCESS [  1.030 s]
[INFO] Apache James :: Server :: Cassandra - guice injection SUCCESS [  5.635 s]
[INFO] Apache James MPT SMTP Cassandra .................... SUCCESS [  7.512 s]
[INFO] Apache James MPT Maven2 Plugin ..................... SUCCESS [  2.222 s]
[INFO] Apache James :: Server :: Client ................... SUCCESS [  2.512 s]
[INFO] Apache James :: Server :: Data :: HBase Persistence  SUCCESS [01:16 min]
[INFO] Apache James :: Server :: Data :: JCR Persistence .. SUCCESS [  6.463 s]
[INFO] Apache James :: Server :: Data :: JDBC Persistence . SUCCESS [ 10.655 s]
[INFO] Apache James :: Server :: Data :: JPA Persistence .. SUCCESS [  6.057 s]
[INFO] Apache James :: Server :: Data :: LDAP Implementation SUCCESS [  1.906 s]
[INFO] Apache James :: Server :: FetchMail ................ SUCCESS [  1.795 s]
[INFO] Apache James :: Server :: Mail Queue :: File ....... SUCCESS [  0.864 s]
[INFO] Apache James :: Server :: Container Spring ......... SUCCESS [  2.192 s]
[INFO] Apache James :: Server :: App ...................... SUCCESS [ 22.743 s]
[INFO] Apache James :: Server :: Memory - guice injection . SUCCESS [ 19.570 s]
[INFO] Apache James :: Server :: Cli :: Integretion ....... SUCCESS [ 35.840 s]
[INFO] Apache James :: Server :: Data :: LDAP Implementation :: Integration testing SUCCESS [01:00 min]
[INFO] Apache James :: Server :: Cassandra/Ldap - guice injection SUCCESS [  5.069 s]
[INFO] Apache James :: Server :: Guice :: Mailet :: Custom testing mailets SUCCESS [  0.718 s]
[INFO] Apache James :: Server :: JPA - guice common ....... SUCCESS [  2.018 s]
[INFO] Apache James :: Server :: JPA - guice injection .... SUCCESS [ 29.375 s]
[INFO] Apache James :: Server :: JPA + SMTP - guice injection SUCCESS [  6.913 s]
[INFO] Apache James :: Karaf :: Features .................. SUCCESS [  0.509 s]
[INFO] Apache James :: Karaf :: James Server .............. SUCCESS [  2.683 s]
[INFO] Apache James :: Karaf :: Integration tests ......... SUCCESS [  1.353 s]
[INFO] Apache James :: Server :: Mailets Integration Testing SUCCESS [08:03 min]
[INFO] Apache James :: Server :: JMAP :: Cassandra Integration testing SUCCESS [56:48 min]
[INFO] Apache James :: Server :: JMAP :: Memory Integration testing SUCCESS [15:42 min]
[INFO] Apache James :: Server :: Web Admin server integration tests SUCCESS [01:50 min]
[INFO] Apache James :: Server :: Web Admin ................ SUCCESS [  0.386 s]
[INFO] Apache James :: Server :: Mail Queue :: RabbitMQ 3.1.0-SNAPSHOT SUCCESS [  0.605 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:20 h
[INFO] Finished at: 2018-06-01T10:11:33Z
[INFO] ------------------------------------------------------------------------
```

**Comment by rouazana** [comment]
```
[INFO] Apache James :: Event sourcing :: Event Store :: Cassandra SUCCESS [  1.236 s]
```
This one sound strange

**Comment by rouazana** [comment]
And also these ones:
```
[INFO] Apache James MPT Imap Mailbox - Cassandra .......... SUCCESS [ 38.133 s]
[INFO] Apache James :: Server :: Guice :: Webadmin :: Cassandra SUCCESS [  1.828 s]
```

**Pull request closed without merging**
