### PR TITLE
JAMES-3247 Do not throw in StoreMessageManager.appendMessage when the temporary file disappears

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by blackheaven** [comment]
No, it would requires to mock things and use multiple threads.

**Comment by remk** [comment]
do you have a fix in another PR for the stacktrace present in the issue which concern a temporary file with the prefix `imap-literal` and not `imap` ?

**Comment by blackheaven** [comment]
```
[2234f07f152e10a1a7fc0537e87029ab94dad042] 16:51:01.847 [ERROR] i.s.j.Reader - no dataType defined for implicit param `recipient`! resolved parameter will not have a type defined, and will therefore be not compliant with spec. see https://github.com/swagger-api/swagger-core/issues/2556.
```

Mmmhh

test this please

**Comment by blackheaven** [comment]
> I think that the stacktrace present in the issue concerns a temporary file with the prefix `imap-literal` and not the present file which has an `imap` prefix ?

Good catch.

**Pull request closed without merging**
