### PR TITLE
[REFACTROING] Guava Preconditions should use String formatting

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by trantienduchn** [comment]
s/REFACTROING/REFACTORING

**Comment by chibenwa** [comment]
```
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR] Failures: 
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR]   DomainMappingsRoutesTest$IllegalInputs.addDomainMappingShouldReturnBadRequestWhenDomainDestinationTooLong:455 1 expectation failed.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] JSON path details doesn't match.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] Expected: is "Domain name length should not exceed 255 characters"
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd]   Actual: Domain name length should not exceed %d characters [255]
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] 
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR]   DomainMappingsRoutesTest$IllegalInputs.addDomainMappingShouldReturnBadRequestWhenDomainSourceTooLong:439 1 expectation failed.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] JSON path details doesn't match.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] Expected: is "Domain name length should not exceed 255 characters"
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd]   Actual: Domain name length should not exceed %d characters [255]
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] 
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR]   DomainsRoutesTest$NormalBehaviour.putShouldReturnBadRequestWhenDomainNameIsTooLong:222 1 expectation failed.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] JSON path details doesn't match.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] Expected: is "Domain name length should not exceed 255 characters"
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd]   Actual: Domain name length should not exceed %d characters [255]
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] 
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR]   UserRoutesTest$WithVirtualHosting.deleteShouldReturnBadRequestWhenUsernameIsTooLong 1 expectation failed.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] JSON path details doesn't match.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] Expected: is "username length should not be longer than 255 characters"
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd]   Actual: username length should not be longer than %d characters [255]
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] 
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR]   UserRoutesTest$WithVirtualHosting.putShouldReturnBadRequestWhenUsernameIsTooLong 1 expectation failed.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] JSON path details doesn't match.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] Expected: is "username length should not be longer than 255 characters"
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd]   Actual: username length should not be longer than %d characters [255]
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] 
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR]   UserRoutesTest$WithoutVirtualHosting.deleteShouldReturnBadRequestWhenUsernameIsTooLong 1 expectation failed.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] JSON path details doesn't match.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] Expected: is "username length should not be longer than 255 characters"
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd]   Actual: username length should not be longer than %d characters [255]
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] 
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] [ERROR]   UserRoutesTest$WithoutVirtualHosting.putShouldReturnBadRequestWhenUsernameIsTooLong 1 expectation failed.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] JSON path details doesn't match.
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd] Expected: is "username length should not be longer than 255 characters"
[479756f36a9cad1bfdd844384dd5cbc4c902e2dd]   Actual: username length should not be longer than %d characters [255]
```

**Comment by Arsnael** [comment]
CI restart

test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
