### PR TITLE
JAMES-2026 add credit to longhost_ for the design

### PR DESCRIPTION
**Pull request by strokyl**

### CODE REVIEW

**Comment by Laura-Royet** [comment]
the credits should be to "Neoma by Linagora"

**Comment by chibenwa** [comment]
This is a request by @MichaelBailly

**Comment by Laura-Royet** [comment]
"Thanks to Neoma by Linagora for the website design" with an embedded link (http://www.neoma-interactive.com/).

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
