### PR TITLE
[CI_ONLY] JAMES-2774 Channel Pool for RabbitMQEvenBus

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by blackheaven** [comment]
```
[INFO] Apache James :: Server :: Cassandra with RabbitMQ - guice injection FAILURE [  02:00 h]
```

not good

test this please

**Comment by trantienduchn** [comment]
it passed on my local

**Comment by trantienduchn** [comment]
same error

**Comment by trantienduchn** [comment]
passed all maven tests in local

**Pull request closed without merging**
