### PR TITLE
JAMES-3027 Encryption CassandraMessageFastViewProjection

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR] Errors: 
[a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithDefaultAwsS3Test.mailsShouldBeWellReceived » SMTPSending Error upon step D...
[a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithDefaultAwsS3Test.oneHundredMailsShouldBeWellReceived » SMTPSending Error u...
[a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithEncryptedAwsS3Test.mailsShouldBeWellReceived » SMTPSending Error upon step...
[a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithEncryptedAwsS3Test.oneHundredMailsShouldBeWellReceived » SMTPSending Error...
```

**Comment by Arsnael** [comment]
> ```
> [a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR] Errors: 
> [a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithDefaultAwsS3Test.mailsShouldBeWellReceived » SMTPSending Error upon step D...
> [a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithDefaultAwsS3Test.oneHundredMailsShouldBeWellReceived » SMTPSending Error u...
> [a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithEncryptedAwsS3Test.mailsShouldBeWellReceived » SMTPSending Error upon step...
> [a88d9d475edcf41950a4266aacb0a70e0c9df6b2] [ERROR]   WithEncryptedAwsS3Test.oneHundredMailsShouldBeWellReceived » SMTPSending Error...
> ```

I think those errors might be related to @chibenwa PR : https://github.com/linagora/james-project/pull/3037#issuecomment-574477462

**Comment by trantienduchn** [comment]
> I think those errors might be related to @chibenwa PR

I'm fixing it

**Comment by mbaechler** [comment]
I don't have any clue what it this PR for, what problem it solves.
Please explain it to me (:

**Comment by remk** [comment]
What is the migration procedure ?

**Comment by chibenwa** [comment]
> What is the migration procedure ?

Upgrading James will result of existing MessageFastView projection entries being dropped.

This means temporary (lazy compute under the hood) performance cost, that can be mitigated via the awesome recompute endpoint.

**Comment by chibenwa** [comment]
> I don't have any clue what it this PR for, what problem it solves.
> Please explain it to me (:

Sure: In case sevaral james server, for different tenants share a common Cassandra database, then isolation between them is achieved via 'keyspace', and enforced via, for instance, Cassandra ACLs.

That being said, setting up a second line of defence for critical data (like message body content, or sub-parts of it like previews) can be valuable for exposure mitigation, for instance in case of ACL misconfiguration & 01 James cluster compromission. Message content of other James server can not be disclosed via Cassandra.

That being said, message textual content is also present in ElasticSearch, for which we have no mitigation strategies...

**Comment by trantienduchn** [comment]
The related issue here https://issues.apache.org/jira/browse/JAMES-3027

**Comment by Arsnael** [comment]
Was :green_apple: before CI restart

**Comment by mbaechler** [comment]
Thank you for the explanation. I understand now what the goal is. However, I never heard tenant isolation was a priority for the project.
As said in another PR: if we want to be serious about crypto, it requires much more than the hack we have to encrypt a byte array with a key.
If we decide we want to implement this isolation feature, we must draw a plan about how we encrypt/decrypt things first.

**Comment by trantienduchn** [comment]
Will be opened again when ready

**Pull request closed without merging**
