### PR TITLE
[Cucumber tests] delete unused test life cycle callbacks

### PR DESCRIPTION
**Pull request by trantienduchn**
I checked, the beforeAll and afterAll callback don't affect any at all to setup cassandra containers startup or shutdown. Cassandra container starting is triggered by another tricky method call. It's `DockerCassandraRule.getHost()`, it will automatically starting cassandra container  by trigger static code block of `DockerCassandraSingleton` . `start()` & `stop()` methods from `DockerCassandraRule` don't reach to `DockerCassandraSingleton` but `getHost()` does. Here is the code of `DockerCassandraRule`:
```java
public class DockerCassandraRule implements TestRule {
    ...
    public void start() {}     // doesn't reach to DockerCassandraSingleton.singleton to trigger static method
    public void stop() {}     // doesn't reach to DockerCassandraSingleton.singleton to trigger static method
    public Host getHost() {
        return DockerCassandraSingleton.singleton.getHost(); // triger static block execution
    } 
   ....
}
```

Here is the code of `DockerCassandraSingleton`: 
```java
public class DockerCassandraSingleton {
    public static final DockerCassandra singleton = new DockerCassandra();
    static {
        singleton.start();   // when some statements reach to DockerCassandraSingleton, then static block will be triggered
    }
    ....
}
```

If I was right. This PR will be green

### CODE REVIEW

**Comment by trantienduchn** [comment]
Starting docker cassandra here is implicit, I would like to make it being more explicit by calling `start()` method instead of `getHost()`.

**Comment by rouazana** [comment]
nice catch!

```
[309accbf10a97cc0d138a3db5ece5c5ff566c877] [ERROR] Errors: 
[309accbf10a97cc0d138a3db5ece5c5ff566c877] [ERROR]   RabbitMQClusterTest$ClusterSharing.queuesShouldBeDeclarableOnAnotherNode:145 » IO
[309accbf10a97cc0d138a3db5ece5c5ff566c877] [ERROR]   RabbitMQClusterTest$ClusterSharing.queuesShouldBeShared » Completion org.rnort...
[309accbf10a97cc0d138a3db5ece5c5ff566c877] [ERROR]   RabbitMQClusterTest$ClusterSharing.rabbitMQManagerShouldReturnThreeNodesWhenAskingForStatus » Completion
```
test this please

**Comment by trantienduchn** [comment]
test this please, rabbit cluster test again

**Comment by trantienduchn** [comment]
```
[c0eaa5cb607c99ea686025bf3ebff612c29a8c1c] [ERROR] Errors: 
[c0eaa5cb607c99ea686025bf3ebff612c29a8c1c] [ERROR]   SpamAssassinContract.imapCopiesToSpamMailboxShouldBeConsideredAsSpam:183 » ConditionTimeout
[c0eaa5cb607c99ea686025bf3ebff612c29a8c1c] [INFO] 
[c0eaa5cb607c99ea686025bf3ebff612c29a8c1c] [ERROR] Tests run: 654, Failures: 0, Errors: 1, Skipped: 1
```
test this plese

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
