### PR TITLE
JAMES-2993 Webadmin support: user scoped JMAP message previews recompute

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797] [ERROR] Failed to execute goal on project event-sourcing-pojo: Could not resolve dependencies for project org.apache.james:event-sourcing-pojo:jar:3.5.0-SNAPSHOT: Failed to collect dependencies at com.google.guava:guava:jar:25.1-jre -> com.google.errorprone:error_prone_annotations:jar:2.1.3: Failed to read artifact descriptor for com.google.errorprone:error_prone_annotations:jar:2.1.3: Could not transfer artifact com.google.errorprone:error_prone_annotations:pom:2.1.3 from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.pom.part (No such file or directory) -> [Help 1]
```

test this please

**Comment by Arsnael** [comment]
```
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797] [ERROR] Failures: 
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797] [ERROR]   RecomputeUserPreviewsTaskSerializationTest.deserializeShouldReturnTheExpectedDomainObject:57 
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797] Expecting:
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797]  <"bob">
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797] to be equal to:
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797]  <Username{localPart=bob, domainPart=Optional.empty}>
[7c6c2b5d3b1120c2b017c5fee889b7721ff2e797] but was not.
```

**Comment by chibenwa** [comment]
We reschedule the priority of this work in order to succeed the Sprint

**Comment by chibenwa** [comment]
Mergezd

**Pull request closed without merging**
