### PR TITLE
MIME4J-0.8.3 Upgrade to mime4J 0.8.3

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[55b0e70fd2be1eebd9634e91ee5c03679a3d6d05] [ERROR] Failed to execute goal on project javax-mail-extension: Could not resolve dependencies for project org.apache.james:javax-mail-extension:jar:3.4.0-SNAPSHOT: Could not find artifact org.apache.james:apache-mime4j-core:jar:0.8.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by chibenwa** [comment]
We will have to be a bit patient, it takes up to a few days...

**Comment by chibenwa** [comment]
Now this should be good cf: https://mvnrepository.com/artifact/org.apache.james/apache-mime4j-core/0.8.3

test this please

**Comment by trantienduchn** [comment]
```
[55b0e70fd2be1eebd9634e91ee5c03679a3d6d05] [ERROR] Failed to execute goal on project james-server-queue-jms: Could not resolve dependencies for project org.apache.james:james-server-queue-jms:bundle:3.4.0-SNAPSHOT: Could not transfer artifact org.apache.activemq:activemq-openwire-legacy:jar:5.15.5 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/activemq/activemq-openwire-legacy/5.15.5/activemq-openwire-legacy-5.15.5.jar from central failed: Connection reset -> [Help 1]
```

**Comment by chibenwa** [comment]
Should still exist...

https://mvnrepository.com/artifact/org.apache.activemq/activemq-openwire-legacy/5.15.5

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
