### PR TITLE
 JAMES-2149 Create domain mappings via webadmin [CONTRIBUTION]

### PR DESCRIPTION
**Pull request by chibenwa**
CI for https://github.com/apache/james-project/pull/119

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please (build result lost)

**Comment by chibenwa** [comment]
Reported build result:

```
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [INFO] There are 26 errors reported by Checkstyle 8.5 with checkstyle.xml ruleset.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[26] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'com.github.fge.lambdas.consumers.ThrowingBiConsumer'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[27] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'com.github.steveash.guavate.Guavate'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[28] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'io.swagger.annotations.Api'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[29] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'io.swagger.annotations.ApiImplicitParam'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[30] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'io.swagger.annotations.ApiImplicitParams'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[31] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'io.swagger.annotations.ApiOperation'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[32] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'io.swagger.annotations.ApiResponse'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[33] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'io.swagger.annotations.ApiResponses'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[34] (imports) CustomImportOrder: Import statement for 'org.apache.james.core.Domain' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[35] (imports) CustomImportOrder: Import statement for 'org.apache.james.rrt.api.RecipientRewriteTable' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[36] (imports) CustomImportOrder: Import statement for 'org.apache.james.rrt.api.RecipientRewriteTableException' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[37] (imports) CustomImportOrder: Import statement for 'org.apache.james.rrt.lib.Mapping' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[38] (imports) CustomImportOrder: Import statement for 'org.apache.james.rrt.lib.MappingSource' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[39] (imports) CustomImportOrder: Import statement for 'org.apache.james.rrt.lib.Mappings' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[40] (imports) CustomImportOrder: Import statement for 'org.apache.james.webadmin.Routes' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[41] (imports) CustomImportOrder: Import statement for 'org.apache.james.webadmin.utils.ErrorResponder' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[42] (imports) CustomImportOrder: Import statement for 'org.apache.james.webadmin.utils.JsonTransformer' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[43] (imports) CustomImportOrder: Import statement for 'org.eclipse.jetty.http.HttpStatus' is in the wrong order. Should be in the 'SPECIAL_IMPORTS' group, expecting group 'STANDARD_JAVA_PACKAGE' on this line.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[44] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'spark.HaltException'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[45] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'spark.Request'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[46] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'spark.Response'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[47] (imports) CustomImportOrder: Imports without groups should be placed at the end of the import list: 'spark.Service'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[55] (imports) CustomImportOrder: Wrong lexicographical order for 'java.util.List' import. Should be before 'javax.ws.rs.Produces'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[56] (imports) CustomImportOrder: Wrong lexicographical order for 'java.util.Map' import. Should be before 'javax.ws.rs.Produces'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[57] (imports) CustomImportOrder: Wrong lexicographical order for 'java.util.Optional' import. Should be before 'javax.ws.rs.Produces'.
[0f7cca769367be82fcf05803a81a1a2949cad8b1] [ERROR] src/main/java/org/apache/james/webadmin/routes/DomainMappingsRoutes.java:[58] (imports) CustomImportOrder: Wrong lexicographical order for 'java.util.function.Function' import. Should be before 'javax.ws.rs.Produces'.
```

**Comment by chibenwa** [comment]
```
[9aaf512765f67bce4a72dfdd9538620e307c2607] [ERROR] src/main/java/org/apache/james/rrt/lib/MappingsImpl.java:[29,8] (imports) UnusedImports: Unused import - java.util.List.
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[1bad15b732eaba9936b86ed3bf66bf69406eb62c] Tests in error: 
[1bad15b732eaba9936b86ed3bf66bf69406eb62c]   GroupMappingTest.messageShouldRedirectToUserContainingSlash:473 » ConditionTimeout
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
merged

**Pull request closed without merging**
