### PR TITLE
James 1691 move mail from outbox to send after sending

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
I just wonder if this is the right way to do it....

I mean : 
 - when dequeued the mail is not yet sent, it will be sent when processed by RemoteDelivery or LocalDelivery mailet.
 - I wonder if Mailets would not be a more classic way to do this ... Without adding code...

**Comment by chibenwa** [comment]
ToSenderFolder might do the job.
Or you can introduce your own mailet.

**Comment by rouazana** [comment]
As discussed Mailet seems a good idea, but for now we'll keep this implementation.
Of course we are open to change our mind and move this implementation as a mailet later.

**Comment by rouazana** [comment]
New PR: https://github.com/linagora/james-project/pull/159

**Pull request closed without merging**
