### PR TITLE
Revert "[Refactoring] Port FixingGhostMailboxTest to use distributed …

### PR DESCRIPTION
**Pull request by Arsnael**
…product"

Unfortunately, this commit made the build very unstable. I could reproduce it locally on master, by repeating the test `ghostMailboxBugShouldDiscardOldContent` in `FixingGhostMailboxTest` 50 times... Then it was breaking a lot of times. After reverting this commit, the 50 times test was green locally.

I'm not sure about the reason why it's so unstable yet, but I think it's better to revert this for now asap, as it disturbs the other builds too much.

### CODE REVIEW

**Comment by trantienduchn** [comment]
There's possbile that the old test use cassandra product, while the newest uses distributed product, there's might by some latency due to the distributed event bus, or something else....

**Comment by Arsnael** [comment]
> There's possbile that the old test use cassandra product, while the newest uses distributed product, there's might by some latency due to the distributed event bus, or something else....

Likely yes, we could investigate further but the priority is to get the CI more stable for now I think :)

**Comment by trantienduchn** [comment]
please replace `@Tag(BasicFeature.TAG)` by `@Category(BasicFeature.class)` and update the surefire in the pom to enable this test

**Comment by Arsnael** [comment]
> please replace `@Tag(BasicFeature.TAG)` by `@Category(BasicFeature.class)` and update the surefire in the pom to enable this test

Why? This revert is on the port to distributed systems... but it was already (and is still) a JUnit 5 test class, thus `@Tag` is still appropriate right?

Can I ask a question though? Are those tags really necessary? We enable that group in the poms to be tested, but when do we exclude it? Never right? Logically even if we removed the tags, the tests would still be executed I think? So why needing those? I didn't get why it was there in the first place actually...?

**Comment by trantienduchn** [comment]
> please replace @Tag(BasicFeature.TAG) by @Category(BasicFeature.class) and update the surefire in the pom to enable this test

my bad, it's written in Junit 5 before.

**Comment by trantienduchn** [comment]
my attempt to fix this #3052

**Comment by Arsnael** [comment]
> my attempt to fix this #3052

#3053 :)

**Pull request merged**
