### PR TITLE
JAMES-2118 use reuseForks for maven-surefire-plugin instead of deprec…

### PR DESCRIPTION
**Pull request by mbaechler**
…ated forkMode

### CODE REVIEW

**Comment by chibenwa** [comment]
Benign failure: timeout in Guice Cassandra. Maybe due to proliferation of docker containers on CI.

I will test that later

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
```
Failed tests: 
  ReadOnlyUsersLDAPRepositoryTest.testShouldStillWorksAfterRestartingLDAP:148 expected:<[tru]e> but was:<[fals]e>
```

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
Something must be wrong, I can't believe we are unlucky there, it always break when launching JPA app.

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
Rebase needed on master to solve JPA troubbles (different version of DockerFiles combined with weak build workspace isolation)

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
