### PR TITLE
James 2721 builder-like API to restart cassandra between tests

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
```
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraAuthenticatePlainTest »  The @Rule 'cassandraServer' must not be stat...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraAuthenticatedStateTest »  The @Rule 'cassandraServer' must not be sta...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraConcurrentSessionsTest »  The @Rule 'cassandraServer' must not be sta...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraCondstoreTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraCopyTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraEventsTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraExpungeTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraFetchBodySectionTest »  The @Rule 'cassandraServer' must not be stati...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraFetchBodyStructureTest »  The @Rule 'cassandraServer' must not be sta...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraFetchHeadersTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraFetchTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraListingTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraListingWithSharingTest »  The @Rule 'cassandraServer' must not be sta...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraMailboxAnnotationTest »  The @Rule 'cassandraServer' must not be stat...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraMailboxWithLongNameErrorTest »  The @Rule 'cassandraServer' must not ...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraMoveTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraNonAuthenticatedStateTest »  The @Rule 'cassandraServer' must not be ...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraPartialFetchTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraQuotaTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraRenameTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraSearchTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraSecurityTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraSelectTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraSelectedInboxTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraSelectedStateTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraUidSearchOnIndexTest »  The @Rule 'cassandraServer' must not be stati...
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraUidSearchTest »  The @Rule 'cassandraServer' must not be static.
[8bef764e097ca203efebb3a163668dbf22ac7624] [ERROR]   CassandraUserFlagsSupportTest »  The @Rule 'cassandraServer' must not be stati...
```

**Comment by trantienduchn** [comment]
```
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQAuthenticatePlainTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQAuthenticatedStateTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQConcurrentSessionsTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQCondstoreTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQCopyTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQEventsTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQFetchBodySectionTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQFetchBodyStructureTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQFetchHeadersTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQFetchTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQListingTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQListingWithSharingTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQMailboxAnnotationTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQMailboxWithLongNameErrorTest »  The @Rule 'rabbitMQRule' must not be s...
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQMoveTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQNonAuthenticatedStateTest »  The @Rule 'rabbitMQRule' must not be stat...
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQPartialFetchTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQQuotaTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQRenameTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQSearchTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQSecurityTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQSelectTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQSelectedInboxTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQSelectedStateTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQUidSearchTest »  The @Rule 'rabbitMQRule' must not be static.
[350b033aa1e9de179a4b324d3ed851730f3539fa] [ERROR]   RabbitMQUserFlagsSupportTest »  The @Rule 'rabbitMQRule' must not be static.
```

**Comment by mbaechler** [comment]
It took 2h17 to run the build with test, is it ok ?

**Pull request merged**
