### PR TITLE
MAILBOX-352 Put MailboxId inside MailboxEvent(literally)

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR] Errors: 
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR]   MailQueueContract.concurrentEnqueueDequeueShouldNotFail:387 » NotTerminated
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [INFO] 
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR] Tests run: 187, Failures: 0, Errors: 1, Skipped: 0
```
test this please

**Comment by chibenwa** [comment]
`[INFO] Apache James :: Server :: JMAP :: RabbitMQ + Swift + Cassandra Integration testing FAILURE [50:52 min]`

test this please

**Comment by chibenwa** [comment]
`MailQueueContract.concurrentEnqueueDequeueShouldNotFail:387 » NotTerminated`

test this please

**Comment by chibenwa** [comment]
```
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR] Failures: 
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR]   ManageableMailQueueContract.getSizeShouldReturnMessageCountWhenSeveralMails:71 expected:<[2]L> but was:<[3]L>
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR] Errors: 
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR]   MailQueueContract.concurrentEnqueueDequeueShouldNotFail:387 » NotTerminated
```

test this please

**Comment by trantienduchn** [comment]
```
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR] Errors: 
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR]   SwiftTempAuthObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:94 » Timeout
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [INFO] 
[153e58ffbe46451bc1b96c8d8cdb8685fde22376] [ERROR] Tests run: 124, Failures: 0, Errors: 1, Skipped: 0
```
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
