### PR TITLE
JAMES-3407 Do not test read repairs on outdated schema verison

### PR DESCRIPTION
**Pull request by chibenwa**
Known to be failing as the code has not been made to handle such subtilities...

Here is a flacky test output:

```
[ERROR]   CassandraMailboxMapperTest$ConsistencyTest.createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox:617 Multiple Failures (1 failure)

Expected size:<1> but was:<2> in:
<[Mailbox{id=88fcc460-49bf-11eb-84d0-b78591c28a40, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=name},
    Mailbox{id=9a2095a0-49bf-11eb-84d0-b78591c28a40, namespace=#private, user=Username{localPart=user, domainPart=Optional.empty}, name=INBOX}]>
at CassandraMailboxMapperTest$ConsistencyTest.lambda$createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox$34(CassandraMailboxMapperTest$ConsistencyTest.java:628)
```

What is stricking is that createAfterPreviousDeleteOnFailedCreateShouldCreateAMailbox
do not rely on "name" mailbox, which do not appear in the test.

Likely an asynchronous read repair being triggered, that violates
test encapsulation...

### CODE REVIEW

**Comment by chibenwa** [comment]
Drafted. Likely needs 10 runs without the issue to give it a go...

**Review by Arsnael — APPROVED** [review]

**Comment by Arsnael** [comment]
some timeouts with RabbitMQ integration tests

test this please

**Comment by chibenwa** [comment]
`No such container: git-publish-james-3407-flacky-c613d3d8-fe6c-4f95-9265-1dc941c27937.`

Passed the possible flacky test but test this please again

**Comment by chibenwa** [comment]
Green.

3/10 runs

test this please

**Comment by chibenwa** [comment]
We passed it.

4/10 runs

test this please

**Comment by chibenwa** [comment]
Green

5/10 runs

test this please

**Comment by chibenwa** [comment]
`Building Apache James :: Server :: JMAP (draft) :: Cassandra Integration testing 3.6.0-SNAPSHOT [235/247]`

Passed it once again so test this please 

6/10 runs - starts feeling confident

**Comment by chibenwa** [comment]
Green test this please

7/10 runs

**Comment by chibenwa** [comment]
Green test this please

8/10 runs

**Comment by chibenwa** [comment]
Passed it

9/10 runs

test this please

**Comment by chibenwa** [comment]
Green

10/10 runs.

We should be good now i am undrafting this.

**Review by LanKhuat — APPROVED** [review]

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
