### PR TITLE
JAMES-3437 Provide a bash script wrapper for James Webadmin Cli

### PR DESCRIPTION
**Pull request by quantranhong1999**

### CODE REVIEW

**Comment by chibenwa** [comment]
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (default) on project webadmin-cli: You have 9 Checkstyle violations. -> [Help 1]`

**Comment by quantranhong1999** [comment]
> `[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (default) on project webadmin-cli: You have 9 Checkstyle violations. -> [Help 1]`

Fixed

**Comment by chibenwa** [comment]
Can we clean up this history?

**Comment by chibenwa** [comment]
You still need a rebase here

**Comment by chibenwa** [comment]
Do we need to modify the README to make it use this script?

**Comment by quantranhong1999** [comment]
> Do we need to modify the README to make it use this script?

It is already in https://github.com/linagora/james-project/pull/3917/commits/a2100010e7db8ad7f79d48d6d3f209eb5c864e1d
Or should I separate it?

**Comment by chibenwa** [comment]
> It is already in a210001

In which PR is this commit?

**Comment by chibenwa** [comment]
Ok in https://github.com/linagora/james-project/pull/3917/commits

You need to be more carefull about bundling related changes together ...

**Review by chibenwa — APPROVED** [review]

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
