### PR TITLE
Increase ForkCount on critical projects

### PR DESCRIPTION
**Pull request by chibenwa**
Before:

```
ObjectStorage: [06:04 min]
mailbox/cassandra: [06:04 min]
mpt/imap/cassandra: [04:53 min]
```

### CODE REVIEW

**Comment by remk** [comment]
```
[5f4a6c36356b3a2b7735cf6e570dc7f9929c1905] [ERROR] Tests run: 130, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 194.225 s &lt;&lt;&lt; FAILURE! - in org.apache.james.mailrepository.cassandra.CassandraMailRepositoryTest
[5f4a6c36356b3a2b7735cf6e570dc7f9929c1905] [ERROR] storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult[41]  Time elapsed: 2.776 s  &lt;&lt;&lt; ERROR!
[5f4a6c36356b3a2b7735cf6e570dc7f9929c1905] java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during CAS write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
[5f4a6c36356b3a2b7735cf6e570dc7f9929c1905] Caused by: java.lang.RuntimeException: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during CAS write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
[5f4a6c36356b3a2b7735cf6e570dc7f9929c1905] Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during CAS write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
[5f4a6c36356b3a2b7735cf6e570dc7f9929c1905] Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during CAS write query at consistency SERIAL (1 replica were required but only 0 acknowledged the write)
[5f4a6c36356b3a2b7735cf6e570dc7f9929c1905] 
```

test this please

**Comment by chibenwa** [comment]
After:

```
ObjectStorage: [09:14 min] Counter productive
mailbox/cassandra: [04:26 min] Gain: 1 min 38
mpt/imap/cassandra: [04:31 min] Gain 20s: Not woth it...
```

**Comment by Arsnael** [comment]
```
[a5ab5aeec255bd431b42a16be7fc923fb211a849] [ERROR] Failures: 
[a5ab5aeec255bd431b42a16be7fc923fb211a849] [ERROR]   DiscreteDistributionTest.streamOfSpecificDistributionMapShouldReturnTwiceMoreA:99 
[a5ab5aeec255bd431b42a16be7fc923fb211a849] Expecting:
[a5ab5aeec255bd431b42a16be7fc923fb211a849]   <664971L>
[a5ab5aeec255bd431b42a16be7fc923fb211a849] to be close to:
[a5ab5aeec255bd431b42a16be7fc923fb211a849]   <670058L>
[a5ab5aeec255bd431b42a16be7fc923fb211a849] by less than <5000L> but difference was <5087L>.
[a5ab5aeec255bd431b42a16be7fc923fb211a849] (a difference of exactly <5000L> being considered valid)
```
test this please

**Comment by chibenwa** [comment]
`WithEncryptedSwiftTest.mailsShouldBeWellReceived » ConditionTimeout Condition ...`

Unrelated 

test this please

**Comment by chibenwa** [comment]
```
[94d186c550b27048ee1eff04e0c44660abcfd05e] [ERROR]   MemoryTerminationSubscriberTest.dynamicListeningEventsShouldGetOnlyNewEvents 
[94d186c550b27048ee1eff04e0c44660abcfd05e] Expecting:
[94d186c550b27048ee1eff04e0c44660abcfd05e]   <[Cancelled(TaskAggregateId(TaskId{value=6eb9267c-3ec2-486d-9a2c-c19edd2482d7}),EventId{value=42})]>
[94d186c550b27048ee1eff04e0c44660abcfd05e] to contain exactly (and in same order):
[94d186c550b27048ee1eff04e0c44660abcfd05e]   <[Failed(TaskAggregateId(TaskId{value=0f60972f-1365-4a67-8f8e-730bb01209a6}),EventId{value=42}),
[94d186c550b27048ee1eff04e0c44660abcfd05e]     Cancelled(TaskAggregateId(TaskId{value=6eb9267c-3ec2-486d-9a2c-c19edd2482d7}),EventId{value=42})]>
[94d186c550b27048ee1eff04e0c44660abcfd05e] but could not find the following elements:
[94d186c550b27048ee1eff04e0c44660abcfd05e]   <[Failed(TaskAggregateId(TaskId{value=0f60972f-1365-4a67-8f8e-730bb01209a6}),EventId{value=42})]>
```

test this please

**Comment by chibenwa** [comment]
```
MemorySpamAssassinContractTest.imapCopiesToSpamMailboxShouldBeConsideredAsSpam » ConditionTimeout
[94d186c550b27048ee1eff04e0c44660abcfd05e] [INFO] 
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
