### PR TITLE
demonstrate the use of single-active consumer and information retriev…

### PR DESCRIPTION
**Pull request by mbaechler**
…al about it

### CODE REVIEW

**Comment by mbaechler** [comment]
```
[db7902e63330cecc41dfb09a297bfb09567eedfa] [ERROR] Failures: 
[db7902e63330cecc41dfb09a297bfb09567eedfa] [ERROR]   MemoryTerminationSubscriberTest.multipleListeningEventsShouldShareEvents 
[db7902e63330cecc41dfb09a297bfb09567eedfa] Expecting:
[db7902e63330cecc41dfb09a297bfb09567eedfa]  <[Failed(TaskAggregateId(TaskId{value=cfb60176-5369-491b-8a38-5801ab71734e}),EventId{value=42}),
[db7902e63330cecc41dfb09a297bfb09567eedfa]     Cancelled(TaskAggregateId(TaskId{value=9f856918-00b6-457d-8b16-f2644d97e355}),EventId{value=42})]>
[db7902e63330cecc41dfb09a297bfb09567eedfa] to be equal to:
[db7902e63330cecc41dfb09a297bfb09567eedfa]  <[Completed(TaskAggregateId(TaskId{value=78f6c76c-3d6e-4c64-9d23-58509314828a}),EventId{value=42},COMPLETED),
[db7902e63330cecc41dfb09a297bfb09567eedfa]     Failed(TaskAggregateId(TaskId{value=cfb60176-5369-491b-8a38-5801ab71734e}),EventId{value=42}),
[db7902e63330cecc41dfb09a297bfb09567eedfa]     Cancelled(TaskAggregateId(TaskId{value=9f856918-00b6-457d-8b16-f2644d97e355}),EventId{value=42})]>
[db7902e63330cecc41dfb09a297bfb09567eedfa] but was not.
[db7902e63330cecc41dfb09a297bfb09567eedfa] [INFO] 
```
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
RabbitMQTest are failing

**Comment by remk** [comment]
We will have to create a migration doc.
Where we should highlight that : 
 - we need to stop receiving new tasks
 - wait until all the message in the queue have been consumed
 - stop all james instances
 - delete the queue
 - relaunch james for it to recreate the queue with the exclusive consumer property.

If there is another way to avoid down time, it's better.

**Comment by chibenwa** [comment]
That is not released. Do we really want to support a migration?

**Comment by remk** [comment]
> That is not released. Do we really want to support a migration?

Depends, it was supposed to be released at linagora without rabbitmq 3.8.

**Pull request closed without merging**
