### PR TITLE
JAMES-2855 junit 5 and surefire plugin upgrades

### PR DESCRIPTION
**Pull request by Arsnael**
Just testing with the CI for now...

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[74fb456d20b68551e52481d512b1a0a822d42107] [ERROR] Errors: 
[74fb456d20b68551e52481d512b1a0a822d42107] [ERROR]   MemoryLinshareBlobExportMechanismIntegrationTest.exportShouldSendAnEmailToShareeWhenImapDelete » PreconditionViolation
[74fb456d20b68551e52481d512b1a0a822d42107] [ERROR]   MemoryLinshareBlobExportMechanismIntegrationTest.exportShouldSendAnEmailToShareeWhenJmapDelete » PreconditionViolation
[74fb456d20b68551e52481d512b1a0a822d42107] [ERROR]   MemoryLinshareBlobExportMechanismIntegrationTest.exportShouldShareNonEmptyZipViaLinshareWhenImapDelete » PreconditionViolation
[74fb456d20b68551e52481d512b1a0a822d42107] [ERROR]   MemoryLinshareBlobExportMechanismIntegrationTest.exportShouldShareNonEmptyZipViaLinshareWhenJmapDelete » PreconditionViolation
[74fb456d20b68551e52481d512b1a0a822d42107] [ERROR]   MemoryLinshareBlobExportMechanismIntegrationTest.exportShouldShareTheDocumentViaLinshareWhenImapDelete » PreconditionViolation
[74fb456d20b68551e52481d512b1a0a822d42107] [ERROR]   MemoryLinshareBlobExportMechanismIntegrationTest.exportShouldShareTheDocumentViaLinshareWhenJmapDelete » PreconditionViolation
```

**Comment by chibenwa** [comment]
test this please (restart)

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[f2862ac7df19317080fad6b183789743afa7b98a] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project mock-smtp-server: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test failed: java.lang.NoClassDefFoundError: org/junit/platform/launcher/core/LauncherFactory: org.junit.platform.launcher.core.LauncherFactory -> [Help 1]
```

On it

**Comment by chibenwa** [comment]
We checked: all tests are played!

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
