### PR TITLE
James 2110

### PR DESCRIPTION
**Pull request by rouazana**
Build testing after autosquash

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[eaedcd2182fbc39578f81eaf4a1ab07983ec6e06] + docker build --tag git/publish-james-2110-90f35e9b-2c55-4a93-a117-bae42c4b47ad -f dockerfiles/merge/Dockerfile .
[eaedcd2182fbc39578f81eaf4a1ab07983ec6e06] Could not load X509 key pair: crypto/tls: failed to parse certificate PEM data. Make sure the key is not encrypted
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Woooooooooooooot!!!!

Who's the CI boss :trollface:  ?

**Pull request merged**
