### PR TITLE
[NO_REVIEW]

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
Bingo 

`Caused by: java.io.FileNotFoundException: null/dockerfiles/run/guice/cassandra-rabbitmq-ldap/destination/conf/blob.properties (No such file or directory)`

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [INFO] --- scala-maven-plugin:3.4.4:compile (scala-compile-first) @ james-server-task-memory ---
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [INFO] /james-project/server/task/task-memory/src/main/java:-1: info: compiling
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [INFO] /james-project/server/task/task-memory/src/main/scala:-1: info: compiling
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [INFO] Compiling 18 source files to /james-project/server/task/task-memory/target/classes at 1595318805573
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [ERROR] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000633c00000, 484442112, 0) failed; error='Not enough space' (errno=12)
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [ERROR] OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000633c00000, 484442112, 0) failed; error='Not enough space' (errno=12)#
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [INFO] # There is insufficient memory for the Java Runtime Environment to continue.
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [INFO] # Native memory allocation (mmap) failed to map 484442112 bytes for committing reserved memory.
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [ERROR] # An error report file with more information is saved as:
[93c836de35cc54ae5078c8e7f14e52fe78c03571] [INFO] # /james-project/hs_err_pid2110.log
```

test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Pull request closed without merging**
