### PR TITLE
JAMES-2675 Fix flaky test on master

### PR DESCRIPTION
**Pull request by rouazana**
Rewrite flaky Cucumber test (not really retrying) to plain Java

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[ec765e8db71395e15189132bd980ebf29a2b5ba1] com.fasterxml.jackson.databind.JsonMappingException: value should be positive and less than 2^53
[ec765e8db71395e15189132bd980ebf29a2b5ba1]  at [Source: (String)"{"position":90071992547409921}"; line: 1, column: 13] (through reference chain: org.apache.james.jmap.model.GetMessageListRequest$Builder["position"])
...
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Errors: 
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR]   MemoryUploadCucumberTest » Socket Broken pipe (Write failed)
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [INFO] 
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Tests run: 656, Failures: 0, Errors: 1, Skipped: 2
```

**Comment by rouazana** [comment]
seems unrelated, test this please

**Comment by rouazana** [comment]
```
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: https://api.github.com/repos/linagora/james-project
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at org.kohsuke.github.Requester.parse(Requester.java:454)
	... 63 more
Finished: FAILURE
```
test this please

**Comment by trantienduchn** [comment]
```
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Command was /bin/sh -c cd /james-project/server/protocols/webadmin/webadmin-data && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms512m -Xmx1024m -jar /james-project/server/protocols/webadmin/webadmin-data/target/surefire/surefirebooter7576735146494103950.jar /james-project/server/protocols/webadmin/webadmin-data/target/surefire 2019-03-11T17-09-10_404-jvmRun4 surefire1084582235740476280tmp surefire_3788414470532485470347tmp
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Error occurred in starting fork, check output in log
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Process Exit Code: 100
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Crashed tests:
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] org.apache.james.webadmin.routes.DomainMappingsRoutesTest$NormalBehaviour
```
test this please

**Comment by chibenwa** [comment]
```
[ec765e8db71395e15189132bd980ebf29a2b5ba1] [ERROR] Failed to execute goal on project apache-james-mpt-imapmailbox-cyrus: Could not resolve dependencies for project org.apache.james:apache-james-mpt-imapmailbox-cyrus:jar:3.4.0-SNAPSHOT: Could not transfer artifact com.spotify:docker-client:jar:8.11.7 from/to central (https://repo.maven.apache.org/maven2): GET request of: com/spotify/docker-client/8.11.7/docker-client-8.11.7.jar from central failed: Connection reset -> [Help 1]
```

You seem lucky today :trollface: 

test this please

**Pull request merged**
