### PR TITLE
JAMES-3359 Mailbox/set update '/' in properties is implicit

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Review by Arsnael — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please (deployment test)

**Review by remk — COMMENTED** [review]
Are the two syntax supported ?
Should we need a test to demonstrate that the client can make a request with or without '/' ?

**Comment by chibenwa** [comment]
> Are the two syntax supported ?

Only "name" is supported, not "/name"

**Comment by chibenwa** [comment]
> Should we need a test to demonstrate that the client can make a request with or without '/' ?

We can demonstrate `/name` is an unknown property

**Review by Arsnael — APPROVED** [review]

**Review by remk — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
