### PR TITLE
Issue 24 http server

### PR DESCRIPTION
**Pull request by mbaechler**
It's not a real PR : commits needs the right ticket version and it lacks integration with other JMAP commits, it's intended for review only

### CODE REVIEW

**Comment by chibenwa** [comment]
Hi Matthieu !

A big :+1: 

I think we do have convergent needs. I thought of adding a Jetty server for my Hystrix related PR (I need to rebase it by the way... ), as I need to serve to servlets for : 
  - exposing metrics
  - expose Hystix dashboard

Once you release this, would it be possible to : 
  - add it to apache before JMAP ?
  - add a few doc for developpers on how to easily enable servlets ?

Thanks by advance :-)

**Comment by aduprat** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Comment by rouazana** [comment]
new PR https://github.com/linagora/james-project/pull/40

**Pull request closed without merging**
