### PR TITLE
Demonstrate how exclusive consumer works

### PR DESCRIPTION
**Pull request by mbaechler**
You can review it but it won't be merged as-is, it's part of distributed workqueue task

### CODE REVIEW

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
```
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [ERROR] Tests run: 102, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 143.111 s <<< FAILURE! - in org.apache.james.mailbox.events.RabbitMQEventBusTest
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [ERROR] concurrentDispatchShouldDeliverAllEventsToListenersWithSingleEventBus  Time elapsed: 0.337 s  <<< ERROR!
[1869da7a3bca024c2c34e6cea2a57d157975b16c] com.rabbitmq.client.AlreadyClosedException: connection is already closed due to connection error; cause: java.lang.IllegalStateException: Unsolicited delivery - see Channel.setDefaultConsumer to handle this case.
[1869da7a3bca024c2c34e6cea2a57d157975b16c] 
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [INFO] 
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [INFO] Results:
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [INFO] 
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [ERROR] Errors: 
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [ERROR]   RabbitMQEventBusTest$ConcurrentTest.concurrentDispatchShouldDeliverAllEventsToListenersWithSingleEventBus » AlreadyClosed
```
test this please

**Comment by chibenwa** [comment]
```
[1869da7a3bca024c2c34e6cea2a57d157975b16c] [ERROR] shouldStartOnConfiguredPort(org.apache.james.http.jetty.JettyHttpServerTest)  Time elapsed: 0.03 s  <<< ERROR!
[1869da7a3bca024c2c34e6cea2a57d157975b16c] java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:53146
[1869da7a3bca024c2c34e6cea2a57d157975b16c] 	at org.apache.james.http.jetty.JettyHttpServerTest.shouldStartOnConfiguredPort(JettyHttpServerTest.java:106)
[1869da7a3bca024c2c34e6cea2a57d157975b16c] Caused by: java.net.BindException: Address already in use
[1869da7a3bca024c2c34e6cea2a57d157975b16c] 	at org.apache.james.http.jetty.JettyHttpServerTest.shouldStartOnConfiguredPort(JettyHttpServerTest.java:106)
```

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
