### PR TITLE
JAMES-2946 Return InvalidArgument when a MailRepository is tried to be created with an unsupported protocol

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by Arsnael** [comment]
CI restart...
test this please

**Comment by blackheaven** [comment]
```
[ERROR]   MemorySpamAssassinContractTest.movingAMailToTrashShouldNotImpactSpamassassinLearning » ConditionTimeout
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
CI restart...

test this please

**Comment by blackheaven** [comment]
no logs

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
