### PR TITLE
JAMES-2109 Consolidate INSTALL intructions for Guice

### PR DESCRIPTION
**Pull request by chibenwa**
capture d ecran de 2017-08-04 11-09-33

capture d ecran de 2017-08-04 11-09-21

capture d ecran de 2017-08-04 11-09-18

capture d ecran de 2017-08-04 11-09-16

capture d ecran de 2017-08-04 11-09-09

### CODE REVIEW

**Comment by chibenwa** [comment]
What di you mean?

**Comment by mbaechler** [comment]
sometime we use -Dworking.directory=sample-configuration  and sometimes -Dworking.directory=.

**Comment by chibenwa** [comment]
Well catch!

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
