### PR TITLE
[Refactoring] Resolve most warnings for mailbox javadoc

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (default) on project apache-james-mailbox-api: You have 1 Checkstyle violation.
```

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
