### PR TITLE
Better jpa isolation

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by remk** [comment]
```
file - write (28: No space left on device) Error writing to file - write (28: No space left on device)
[00956f2308e067aec6215c04c99e034fa265a1dd] E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device)
[00956f2308e067aec6215c04c99e034fa265a1dd] E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  Error writing to output file - write (28: No space left on device) Error writing to file - write (28: No space left on device)
[00956f2308e067aec6215c04c99e034fa265a1dd] E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by mbaechler** [comment]
test this please

**Comment by rouazana** [comment]
```
[00956f2308e067aec6215c04c99e034fa265a1dd] [INFO] There are 4 errors reported by Checkstyle 8.18 with checkstyle.xml ruleset.
[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[24,8] (imports) UnusedImports: Unused import - org.apache.james.mailbox.MailboxSession.
[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[26,8] (imports) UnusedImports: Unused import - org.apache.james.mailbox.exception.MailboxException.
[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[27,8] (imports) UnusedImports: Unused import - org.apache.james.mailbox.jpa.mail.JPAMailboxMapper.
[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[38,8] (imports) UnusedImports: Unused import - org.apache.james.mailbox.store.transaction.Mapper.
```

**Comment by chibenwa** [comment]
```
[00956f2308e067aec6215c04c99e034fa265a1dd] [INFO] Apache James :: Mailbox :: JPA ..................... FAILURE [  8.181 s]


[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[24,8] (imports) UnusedImports: Unused import - org.apache.james.mailbox.MailboxSession.
[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[26,8] (imports) UnusedImports: Unused import - org.apache.james.mailbox.exception.MailboxException.
[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[27,8] (imports) UnusedImports: Unused import - org.apache.james.mailbox.jpa.mail.JPAMailboxMapper.
[00956f2308e067aec6215c04c99e034fa265a1dd] [ERROR] src/main/java/org/apache/james/mailbox/jpa/JPAMailboxManager.java:[38,8] (imports) UnusedImports: Unused import - 
```

**Comment by mbaechler** [comment]
this PR was green before JIRA number affectation.

**Pull request merged**
