### PR TITLE
JAMES-3290 Rely on dead letter exchanges for MailQueue discarded messages

### PR DESCRIPTION
**Pull request by chibenwa**
The test fails. Help welcomed.

### CODE REVIEW

**Comment by chibenwa** [comment]
Cc @mbaechler

**Comment by remk** [comment]
I don't see the nack in case of serialization error. Where is it ?

**Comment by chibenwa** [comment]
> I don't see the nack in case of serialization error. Where is it ?

That was it. Thanks.

**Comment by chibenwa** [comment]
As it is working, and desirable, I integrate this work in https://github.com/linagora/james-project/pull/3532

**Pull request closed without merging**
