### PR TITLE
JAMES-2441 Remove other profiles disabling tests

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by aduprat** [comment]
```

Tests in error: 
  CassandraNodeConfTest.serverShouldStartWhenOneCassandraNodeIsUnreachable:88->assertThatServerStartCorrectly:101 » Provision
```

**Comment by aduprat** [comment]
test this please

**Comment by chibenwa** [comment]
```
[75f58671b6704c60488c6e59291459937325d6ec] Tests in error: 
[75f58671b6704c60488c6e59291459937325d6ec]   CassandraNodeConfTest.serverShouldStartWhenOneCassandraNodeIsUnreachable:88->assertThatServerStartCorrectly:101 » Provision
```

This one was unstable before, no?

**Comment by aduprat** [comment]
Build triggered. sha1 is merged.

**Comment by aduprat** [comment]
Build started sha1 is merged.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
Build triggered. sha1 is merged.

**Comment by aduprat** [comment]
Build started sha1 is merged.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
Build triggered. sha1 is merged.

**Comment by aduprat** [comment]
Build started sha1 is merged.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
Build triggered. sha1 is merged.

**Comment by aduprat** [comment]
Build started sha1 is merged.

**Comment by aduprat** [comment]
Build finished. No test results found.

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
The last fix is due to recent modification on default property separator.
We have chosen to use the semi-colon instead of the coma in order to be able to read correctly LDAP elements in properties files.

**Comment by aduprat** [comment]
```
Failed tests: 
  ManageableMailQueueContract.concurrentEnqueueShouldNotAlterBrowsing:245 
Actual and expected should have same size but actual size was:
  <3>
while expected size was:
  <2>
Actual was:
  <["name1", "name2", "name3"]>
Expected was:
  <["name1", "name2"]>
```
test this please

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by chibenwa** [comment]
```
[06548ad364251dc43765e15478725ceb6da8f02d]   ElasticSearchConfigurationTest.getMaxRetriesShouldReturnConfiguredValue:100 expected:<[36]> but was:<[7]>
[06548ad364251dc43765e15478725ceb6da8f02d]   ElasticSearchConfigurationTest.getMinDelayShouldReturnConfiguredValue:124 expected:<3[6]> but was:<3[000]>
```

Strange, I don't have that failure locally.

test this please

**Comment by chibenwa** [comment]
Again

```
[06548ad364251dc43765e15478725ceb6da8f02d]   ElasticSearchConfigurationTest.getMaxRetriesShouldReturnConfiguredValue:100 expected:<[36]> but was:<[7]>
[06548ad364251dc43765e15478725ceb6da8f02d]   ElasticSearchConfigurationTest.getMinDelayShouldReturnConfiguredValue:124 expected:<3[6]> but was:<3[000]>
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[285300a26fb7415700403e3a6ce46ee827375259] Failed tests: 
[285300a26fb7415700403e3a6ce46ee827375259]   ManageableMailQueueContract.concurrentEnqueueShouldNotAlterBrowsing:245 
[285300a26fb7415700403e3a6ce46ee827375259] Actual and expected should have same size but actual size was:
[285300a26fb7415700403e3a6ce46ee827375259]   <3>
[285300a26fb7415700403e3a6ce46ee827375259] while expected size was:
[285300a26fb7415700403e3a6ce46ee827375259]   <2>
[285300a26fb7415700403e3a6ce46ee827375259] Actual was:
[285300a26fb7415700403e3a6ce46ee827375259]   <["name1", "name2", "name3"]>
[285300a26fb7415700403e3a6ce46ee827375259] Expected was:
[285300a26fb7415700403e3a6ce46ee827375259]   <["name1", "name2"]>
[285300a26fb7415700403e3a6ce46ee827375259] 
```

test this please

**Comment by chibenwa** [comment]
Grrr

```
[285300a26fb7415700403e3a6ce46ee827375259] Failed tests: 
[285300a26fb7415700403e3a6ce46ee827375259]   ManageableMailQueueContract.concurrentEnqueueShouldNotAlterBrowsing:245 
[285300a26fb7415700403e3a6ce46ee827375259] Actual and expected should have same size but actual size was:
[285300a26fb7415700403e3a6ce46ee827375259]   <3>
[285300a26fb7415700403e3a6ce46ee827375259] while expected size was:
[285300a26fb7415700403e3a6ce46ee827375259]   <2>
[285300a26fb7415700403e3a6ce46ee827375259] Actual was:
[285300a26fb7415700403e3a6ce46ee827375259]   <["name1", "name2", "name3"]>
[285300a26fb7415700403e3a6ce46ee827375259] Expected was:
[285300a26fb7415700403e3a6ce46ee827375259]   <["name1", "name2"]>
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
