### PR TITLE
James 3308: add test in RabbitMQTerminationSubscriberTest

### PR DESCRIPTION
**Pull request by nvduc91**
Add test in RabbitMQTerminationSubscriberTest for deserialization error handling.

### CODE REVIEW

**Comment by nvduc91** [comment]
test this please.

```[913582056fe8b7a9c7482c8dc134c09cf3766c5f] 13:34:09.286 [ERROR] o.a.j.PeriodicalHealthChecks - UNHEALTHY: Guice application lifecycle : James server is not started.```

**Comment by nvduc91** [comment]
I dont know it related to my ticket or not but
test this please

```
[913582056fe8b7a9c7482c8dc134c09cf3766c5f] [ERROR]   DiscreteDistributionTest.partitionShouldSupportDuplicatedDistributionEntry:112 
[913582056fe8b7a9c7482c8dc134c09cf3766c5f] Expecting:
[913582056fe8b7a9c7482c8dc134c09cf3766c5f]   <668532L>
[913582056fe8b7a9c7482c8dc134c09cf3766c5f] to be close to:
[913582056fe8b7a9c7482c8dc134c09cf3766c5f]   <662936L>
[913582056fe8b7a9c7482c8dc134c09cf3766c5f] by less than <5000L> but difference was <5596L>.
[913582056fe8b7a9c7482c8dc134c09cf3766c5f] (a difference of exactly <5000L> being considered valid)
```

**Comment by Arsnael** [comment]
James-3541? (in your title) that ticket doesn't exist in JIRA :P

**Comment by nvduc91** [comment]
> James-3541? (in your title) that ticket doesn't exist in JIRA :P

Linked

**Comment by Arsnael** [comment]
> Linked

Still doesn't answer why the title of your PR has for ticket number James-3541? :)

**Comment by nvduc91** [comment]
> > Linked
> 
> Still doesn't answer why the title of your PR has for ticket number James-3541? :)

I just updated the name, should be JAMES-3542

**Comment by Arsnael** [comment]
> I just updated the name, should be JAMES-3542

Talking about JIRA ticket, not github issue :)

**Comment by nvduc91** [comment]
> Talking about JIRA ticket, not github issue :)

Oh sorry, i misunderstand. BTW we dont have Jira issue for #3541 also, should i create them all?

**Comment by nvduc91** [comment]
https://issues.apache.org/jira/browse/JAMES-3308 
@Arsnael let me know if anything wrong, pls.

**Comment by Arsnael** [comment]
> https://issues.apache.org/jira/browse/JAMES-3308
> @Arsnael let me know if anything wrong, pls.

Looks good, just don't forget to update the ticket number on the commits too :)

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
