### PR TITLE
Improvments for the README and Download page

### PR DESCRIPTION
**Pull request by chibenwa**
## Why

GitHub is an important place to get traction and READMEs are the primary document people look at.

They should be both informative AND easy to read.

My personnal feeling is that James README is polluted by too much information, not readable and misses most of the points.

The download page suffers similar flows.

I would like to improve the current situation with this humble PR.

## How

The goal is to keep the same level of information on the README but link external pages rather than polluting the README with content not pertinant for most readers.

Also I propose using badges at the top for important links: download, license, website, CI, documentation, docker hub, websites posts. Hopefully these contents would get more visibility.

I drastically simplified the index in the README that was clearly overcharged to me (takes more than my screen!) thus unreadable.

Finally I also sanitised the download page as stated in https://www.mail-archive.com/server-dev@james.apache.org/msg71016.html

## Preview

Preview these changes on my personnal repository: https://github.com/chibenwa/james-project/tree/improve-reame-14-09-2021

### CODE REVIEW

**Review by rouazana — COMMENTED** [review]
I had a very quick look. "How to contribute" is not with the other "How to". I was a little lost by that. Would you mind to fix this?

**Comment by rouazana** [comment]
This PR should be created on apache/james-project?

**Comment by chibenwa** [comment]
> This PR should be created on apache/james-project?

Of course, it is a mistake.

**Comment by chibenwa** [comment]
(I updated linagora master branch now I'm lost when I open PRs)

**Comment by chibenwa** [comment]
CF https://github.com/apache/james-project/pull/654

**Pull request closed without merging**
