### PR TITLE
[NO_REVIEW] [CI] JAMES-1481 About SMTP greetings in sample SMTP configuration

### PR DESCRIPTION
**Pull request by chibenwa**
See https://github.com/apache/james-project/pull/203

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[8169b6dcb2756bb847a438839089af25e59f40ff] [ERROR] Failures: 
[8169b6dcb2756bb847a438839089af25e59f40ff] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.connectSMTPServerShouldSendShabangOnConnect 
[8169b6dcb2756bb847a438839089af25e59f40ff] Expecting:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 Apache JAMES awesome SMTP Server
[8169b6dcb2756bb847a438839089af25e59f40ff] ">
[8169b6dcb2756bb847a438839089af25e59f40ff] to start with:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 JAMES Linagora's SMTP awesome Server">
[8169b6dcb2756bb847a438839089af25e59f40ff] 
[8169b6dcb2756bb847a438839089af25e59f40ff] [ERROR]   CassandraJamesServerTest.connectSMTPServerShouldSendShabangOnConnect 
[8169b6dcb2756bb847a438839089af25e59f40ff] Expecting:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 Apache JAMES awesome SMTP Server
[8169b6dcb2756bb847a438839089af25e59f40ff] ">
[8169b6dcb2756bb847a438839089af25e59f40ff] to start with:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 JAMES Linagora's SMTP awesome Server">
[8169b6dcb2756bb847a438839089af25e59f40ff] 
[8169b6dcb2756bb847a438839089af25e59f40ff] [ERROR]   CassandraWithTikaTest.connectSMTPServerShouldSendShabangOnConnect 
[8169b6dcb2756bb847a438839089af25e59f40ff] Expecting:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 Apache JAMES awesome SMTP Server
[8169b6dcb2756bb847a438839089af25e59f40ff] ">
[8169b6dcb2756bb847a438839089af25e59f40ff] to start with:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 JAMES Linagora's SMTP awesome Server">
[8169b6dcb2756bb847a438839089af25e59f40ff] 
[8169b6dcb2756bb847a438839089af25e59f40ff] [ERROR]   WithCassandraBlobStoreTest.connectSMTPServerShouldSendShabangOnConnect 
[8169b6dcb2756bb847a438839089af25e59f40ff] Expecting:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 Apache JAMES awesome SMTP Server
[8169b6dcb2756bb847a438839089af25e59f40ff] ">
[8169b6dcb2756bb847a438839089af25e59f40ff] to start with:
[8169b6dcb2756bb847a438839089af25e59f40ff]  <"220 JAMES Linagora's SMTP awesome Server">
```

**Comment by Arsnael** [comment]
build logs lost...

test this please

**Comment by chibenwa** [comment]
build output lost

test this please

**Comment by chibenwa** [comment]
Was aborted. test this please

**Comment by chibenwa** [comment]
build output lost

test this please

**Comment by chibenwa** [comment]
```
[c6842072d05c013705c6bd3ef23af462609246e3] [INFO] Running org.apache.james.JPAJamesServerTest
[c6842072d05c013705c6bd3ef23af462609246e3] [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.517 s <<< FAILURE! - in org.apache.james.JPAJamesServerTest
[c6842072d05c013705c6bd3ef23af462609246e3] [ERROR] connectSMTPServerShouldSendShabangOnConnect  Time elapsed: 6.51 s  <<< FAILURE!
[c6842072d05c013705c6bd3ef23af462609246e3] java.lang.AssertionError: 
[c6842072d05c013705c6bd3ef23af462609246e3] 
[c6842072d05c013705c6bd3ef23af462609246e3] Expecting:
[c6842072d05c013705c6bd3ef23af462609246e3]  <"220 Apache JAMES awesome SMTP Server
[c6842072d05c013705c6bd3ef23af462609246e3] ">
[c6842072d05c013705c6bd3ef23af462609246e3] to start with:
[c6842072d05c013705c6bd3ef23af462609246e3]  <"220 JAMES Linagora's SMTP awesome Server">
[c6842072d05c013705c6bd3ef23af462609246e3] 
[c6842072d05c013705c6bd3ef23af462609246e3] 	at org.apache.james.JPAJamesServerTest.connectSMTPServerShouldSendShabangOnConnect(JPAJamesServerTest.java:87)
[c6842072d05c013705c6bd3ef23af462609246e3] 
[c6842072d05c013705c6bd3ef23af462609246e3] [INFO] 
[c6842072d05c013705c6bd3ef23af462609246e3] [INFO] Results:
[c6842072d05c013705c6bd3ef23af462609246e3] [INFO] 
[c6842072d05c013705c6bd3ef23af462609246e3] [ERROR] Failures: 
[c6842072d05c013705c6bd3ef23af462609246e3] [ERROR]   JPAJamesServerTest.connectSMTPServerShouldSendShabangOnConnect:87 
[c6842072d05c013705c6bd3ef23af462609246e3] Expecting:
[c6842072d05c013705c6bd3ef23af462609246e3]  <"220 Apache JAMES awesome SMTP Server
[c6842072d05c013705c6bd3ef23af462609246e3] ">
[c6842072d05c013705c6bd3ef23af462609246e3] to start with:
[c6842072d05c013705c6bd3ef23af462609246e3]  <"220 JAMES Linagora's SMTP awesome Server">
```

**Comment by chibenwa** [comment]
`ConsistencyTasksIntegrationTest.shouldRecomputeMailboxCounters:268 » ConditionTimeout`

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
