### PR TITLE
[Refactoring] Remove some unused methods in mailbox-store

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
MemorySpamAssassinContractTest.movingAMailToTrashShouldNotImpactSpamassassinLearning » ConditionTimeout
```

test this please

**Comment by chibenwa** [comment]
```
[fb9fe72ea9ffd295c2124598dbb447f70127015d] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[fb9fe72ea9ffd295c2124598dbb447f70127015d] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
[fb9fe72ea9ffd295c2124598dbb447f70127015d] [ERROR]   CassandraMailRepositoryTest.storingAndRemovingMessagesConcurrentlyShouldLeadToConsistentResult » Execution
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please (after CI restart)

**Comment by openpaas-james** [comment]
Build finished. No test results found.

**Comment by chibenwa** [comment]
test this please (after CI restart)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
