### PR TITLE
JAMES-2733 RabbitMQ should not dequeue deleted elements

### PR DESCRIPTION
**Pull request by chibenwa**
We should check upon dequeue if an element had been removed or not.

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[cd2c59e21621871a098bc7ffe014d22441c30749] [ERROR]   ForwardSmtpTest.forwardingAnEmailShouldWork:79 » ConditionTimeout Assertion co...
```

**Comment by chibenwa** [comment]
```
[INFO] Apache James MPT SMTP Cassandra RabbitMQ Object Storage FAILURE [03:25 min]

[ERROR]   ForwardSmtpTest.forwardingAnEmailShouldWork:79 » ConditionTimeout Assertion co...

[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 05:38:53.142 [ERROR] o.a.j.m.i.JamesMailSpooler - Exception processing mail while spooling org.apache.james.queue.api.RawMailQueueItem@50fd206f
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:258)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:427)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at com.rabbitmq.client.impl.AMQChannel.transmit(AMQChannel.java:421)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at com.rabbitmq.client.impl.recovery.RecoveryAwareChannelN.basicNack(RecoveryAwareChannelN.java:106)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.basicNack(AutorecoveringChannel.java:433)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at reactor.rabbitmq.AcknowledgableDelivery.nack(AcknowledgableDelivery.java:87)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at reactor.rabbitmq.AcknowledgableDelivery.nack(AcknowledgableDelivery.java:104)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at org.apache.james.queue.rabbitmq.Dequeuer.lambda$ack$2(Dequeuer.java:117)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at com.github.fge.lambdas.consumers.ThrowingConsumer.accept(ThrowingConsumer.java:22)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at org.apache.james.queue.rabbitmq.Dequeuer$RabbitMQMailQueueItem.done(Dequeuer.java:63)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at org.apache.james.queue.api.RawMailQueueItem.done(RawMailQueueItem.java:39)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at org.apache.james.mailetcontainer.impl.JamesMailSpooler.processMail(JamesMailSpooler.java:143)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at org.apache.james.mailetcontainer.impl.JamesMailSpooler.handleOnQueueItem(JamesMailSpooler.java:126)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:350)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[5d0db3ecdccb584e2c5ebdb9d8b0aba0801de082] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
`java.net.BindException: Address already in use` test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
That is unexpected. Let's double check... test this please

**Comment by chibenwa** [comment]
That's OK, only deployment tests.

Let's merge this.

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
