### PR TITLE
JAMES-2704 RandomStoring code improvments

### PR DESCRIPTION
**Pull request by chibenwa**
That may not be what's causing the test failures, but that is also clearly an enhancement!

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[ERROR]   SmtpRandomStoringTest.messagesShouldBeRandomlyAssignedToEveryMailboxesOfEveryUsers:179 » ConditionTimeout
```
erf... test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test thos please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[ERROR]   SmtpRandomStoringTest.messagesShouldBeRandomlyAssignedToEveryMailboxesOfEveryUsers:181 » ConditionTimeout
```
test this please

**Comment by Arsnael** [comment]
Logs not found... test this please

**Comment by chibenwa** [comment]
test this please (after CI restart)

**Comment by chibenwa** [comment]
test this please

:green_apple: mvn test

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
