### PR TITLE
JAMES-3028 Adapt the script for performance testing for the new s3 provisioning

### PR DESCRIPTION
**Pull request by Arsnael**
This is the new script I will need to test when the provisioning is finished.

### CODE REVIEW

**Review by chibenwa — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
The UNFAMOUS deployment tests

test this please

**Review by nvduc91 — APPROVED** [review]

**Comment by Arsnael** [comment]
I aborted the build, it was stuck... It passed the deployment tests and anyway this should not influence the build neither the project, this is for performance testing with our perf server. So let's restart builds on this anymore thanks :)

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
