### PR TITLE
Mailbox 305 new table attachmentId -> messageIds

### PR DESCRIPTION
**Pull request by rouazana**
replaces #961

### CODE REVIEW

**Comment by chibenwa** [comment]
I will contribute the *delete* code this moning.

**Comment by chibenwa** [comment]
I was just thinking the delete code is not needed.

CassandraMessageDAO::delete is never called. Messages are just no more referenced from MessageIdTable and ImapToUidTable.

Doing the delete requires additional information like list of attachment and is hard to get. I would prefer letting CassandraMessageIdManager naturally filter out non existing MessageIds when securing the Attachment endpoint.

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by aduprat** [comment]
Merge: https://github.com/linagora/james-project/pull/975

**Pull request closed without merging**
