### PR TITLE
JAMES-2022 Add ES logback appender as a guice-cassandra dependency

### PR DESCRIPTION
**Pull request by chibenwa**
screenshot from 2017-05-11 11-04-48

ES searchable logs with rotating indexes <3

Will try to plug Kibana...

The configuration used for ES APPENDER:

```
    <appender name="ELASTIC" class="com.internetitem.logback.elasticsearch.ElasticsearchAppender">
        <url>http://172.17.0.4:9200/_bulk</url>
        <index>logs-%date{yyyy-MM-dd}</index>
        <type>tester</type>
        <properties>
            <property>
                <name>host</name>
                <value>${HOSTNAME}</value>
                <allowEmpty>false</allowEmpty>
            </property>
            <property>
                <name>severity</name>
                <value>%level</value>
            </property>
            <property>
                <name>thread</name>
                <value>%thread</value>
            </property>
            <property>
                <name>stacktrace</name>
                <value>%ex</value>
            </property>
            <property>
                <name>logger</name>
                <value>%logger</value>
            </property>
        </properties>
        <headers>
            <header>
                <name>Content-Type</name>
                <value>text/plain</value>
            </header>
        </headers>
    </appender>
```

### CODE REVIEW

**Comment by chibenwa** [comment]
Logstash compatibility can be found here : https://www.elastic.co/support/matrix#show_compatibility

**Comment by chibenwa** [comment]
screenshot from 2017-05-11 11-19-43

**Comment by mbaechler** [comment]
This is great overall, but i'm not sure we should add that as a dependency, can't we drop the jar in the right directory instead ?

**Comment by chibenwa** [comment]
@mbaechler we can include that as a common facility for cassandra-guice user, who already uses ElasticSearch

Thus we can not attach a class at runtime for arbitrary purpose (without breaking the manifest). At least we don't know how to do this.

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Pull request merged**
