### PR TITLE
JAMES-2174: Updating Swagger documentation about defineGetQuota()

### PR DESCRIPTION
**Pull request by omarmjhd**
Updated swagger documentation with a note about the expected return of the function if there is no limitation for count and/or size. Change made in regards to Issue #1019

### CODE REVIEW

**Comment by aduprat** [comment]
Can one of the admins verify this patch?

**Comment by chibenwa** [comment]
test this please

**Comment by omarmjhd** [comment]
@chibenwa do you mean just to pull up the swagger page to ensure that the new note is being shown?

**Comment by chibenwa** [comment]
Ha just a small remark: Can you rewind your commit message to integrate **JAMES-2174** prefix?

**Comment by omarmjhd** [comment]
@chibenwa accidentally commited a VCS file when updating that commit message, so I'm closing this PR and opening another one at #1033 with the correct commit message and changes

**Pull request closed without merging**
