### PR TITLE
[Barcamp] Arbitrary ES schema migration !!!

### PR DESCRIPTION
**Pull request by chibenwa**
### Steps to handle almost zero downtime schema upgrade in James

 - Step 0: Always use configurable aliases
 - Step1: Versioned query, insert and schema version. The version to be used is loaded from the configuration
 - Step 2: I can ask James to create an Index with a specific version via WebAdmin
 - Step 3: I can add an additional indexer pointing to a configurable alias and version (Handles updates) via web admin
 - Step 4: I can trigger an ElasticSearch specific reindexing process reading from DB and populating a specific alias with a document of a specific version.

Here are update steps from V1 to V2:

 - James uses index 1 with logic 1
 - I ask James to create an indexV2 (Step 2)
 - I ask James to index also upcoming changes to indexV2 (Step 3)
 - I ask James to write all documents to index2 (Step 4)
 - When finished...
 - I restart James, ask it to use writeAlias on indexV2, read-Alias on indexV2 and uses logic2 (edit conf files, edit directly aliases on ES)
 - DONE

You will note that this process allows ARBITRARY index document structure changes.

Note also steps 0,1,2 allow to deal with other source of re-indexing like:
 - Internal to ES (reindex API)
 - Node script with limited document transformation logic
 - Etc...

Steps 3 adds "no update lost during reindexing process".

### CODE REVIEW

**Comment by chibenwa** [comment]
I added Luc fix as a **versionned schema 2**.

**Comment by chibenwa** [comment]
```
[dcf5581836a19c504bd18b00631f6a22417788f9] [INFO] Results:
[dcf5581836a19c504bd18b00631f6a22417788f9] [INFO] 
[dcf5581836a19c504bd18b00631f6a22417788f9] [ERROR] Errors: 
[dcf5581836a19c504bd18b00631f6a22417788f9] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToCassandraWhenStartService:82->assertThatServerStartCorrectly:111 » Provision
[dcf5581836a19c504bd18b00631f6a22417788f9] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToElasticSearchWhenStartService:92->assertThatServerStartCorrectly:111 » Provision
[dcf5581836a19c504bd18b00631f6a22417788f9] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldStartAtDefault:72->assertThatServerStartCorrectly:111 » Provision
[dcf5581836a19c504bd18b00631f6a22417788f9] [INFO] 
```

May deserve investigations ;-)

**Comment by chibenwa** [comment]
test this please

**Comment by openpaas-james** [comment]
Build triggered. sha1 is original commit.

**Comment by openpaas-james** [comment]
Build started sha1 is original commit.

**Comment by openpaas-james** [comment]
Build finished. No test results found.

**Comment by openpaas-james** [comment]
Build finished. No test results found.

**Comment by chibenwa** [comment]
Won't come anytime soon. Closing this.

**Pull request closed without merging**
