### PR TITLE
Optimize tests 2 fix

### PR DESCRIPTION
**Pull request by rouazana**
Test PR reverting only last commit. Seems to make SMTP tests to work.

### CODE REVIEW

**Comment by chibenwa** [comment]
:+1:

**Comment by aduprat** [comment]
This information is important for this review:
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache James Project ............................... SUCCESS [ 10.254 s]
[INFO] Apache James :: Server ............................. SUCCESS [  0.800 s]
[INFO] Apache James :: Server :: Common Utilities :: Java 8 SUCCESS [  5.063 s]
[INFO] Apache JAMES backends common ....................... SUCCESS [  0.136 s]
[INFO] Apache James Cassandra backend ..................... SUCCESS [ 14.667 s]
[INFO] Apache James :: Mailbox ............................ SUCCESS [  0.122 s]
[INFO] Apache James :: Mailbox :: API ..................... SUCCESS [  5.029 s]
[INFO] Apache James :: Mailbox :: Store Framework ......... SUCCESS [ 32.978 s]
[INFO] Apache James :: Mailbox :: Caching ................. SUCCESS [  0.687 s]
[INFO] Apache James :: Mailbox :: Cassandra ............... SUCCESS [02:28 min]
[INFO] Apache James :: Mailbox :: Tika .................... SUCCESS [ 10.223 s]
[INFO] Apache James :: Mailbox :: In Memory ............... SUCCESS [  4.259 s]
[INFO] Apache James :: Mailbox :: ElasticSearch ........... SUCCESS [02:15 min]
[INFO] Apache James :: Mailbox :: HBase ................... SUCCESS [01:52 min]
[INFO] Apache James :: Mailbox :: JCR ..................... SUCCESS [  4.335 s]
[INFO] Apache James :: Mailbox :: JPA ..................... SUCCESS [  5.056 s]
[INFO] Apache James :: Mailbox :: Lucene Index ............ SUCCESS [  2.273 s]
[INFO] Apache James :: Mailbox :: Maildir ................. SUCCESS [  2.031 s]
[INFO] Apache James :: Mailbox :: Tools ................... SUCCESS [  4.271 s]
[INFO] Apache James :: Mailbox :: Spring .................. SUCCESS [  9.943 s]
[INFO] Apache James :: Mailbox :: Zookeeper Sequence Provider SUCCESS [  3.021 s]
[INFO] Apache James :: Mailbox :: Kafka ................... SUCCESS [  2.635 s]
[INFO] Apache James :: Mailets parent and aggregator ...... SUCCESS [  0.593 s]
[INFO] Apache James :: Mailet API ......................... SUCCESS [  0.866 s]
[INFO] Apache James :: Basic Mailet Toolkit ............... SUCCESS [  1.728 s]
[INFO] Apache James :: Mailetdocs Maven Plugin ............ SUCCESS [  4.260 s]
[INFO] Apache James :: Crypto Mailets ..................... SUCCESS [  0.676 s]
[INFO] Apache James :: Standard Mailets ................... SUCCESS [ 17.610 s]
[INFO] Apache James :: AI Mailets ......................... SUCCESS [  0.243 s]
[INFO] Apache James :: Protocols .......................... SUCCESS [  0.114 s]
[INFO] Apache James :: Protocols :: API ................... SUCCESS [  1.668 s]
[INFO] Apache James :: Protocols :: IMAP .................. SUCCESS [ 26.738 s]
[INFO] Apache James MPT ................................... SUCCESS [  0.114 s]
[INFO] Apache James MPT Core .............................. SUCCESS [  7.228 s]
[INFO] Apache James MPT AntLib ............................ SUCCESS [  3.679 s]
[INFO] Apache James MPT Application ....................... SUCCESS [  2.061 s]
[INFO] Apache James MPT All ............................... SUCCESS [  2.204 s]
[INFO] Apache James MPT Imap Mailbox ...................... SUCCESS [  0.112 s]
[INFO] Apache James MPT Imap Mailbox Core ................. SUCCESS [  3.512 s]
[INFO] Apache James MPT Imap Mailbox - Cassandra .......... SUCCESS [11:27 min]
[INFO] Apache James MPT Imap Mailbox - Cyrus .............. SUCCESS [  3.954 s]
[INFO] Apache James MPT Imap Mailbox - ElasticSearch ...... SUCCESS [ 14.859 s]
[INFO] Apache James MPT Imap Mailbox - External James ..... SUCCESS [  0.719 s]
[INFO] Apache James MPT Imap Mailbox - HBase .............. SUCCESS [  1.491 s]
[INFO] Apache James MPT Imap Mailbox - InMemory ........... SUCCESS [  8.381 s]
[INFO] Apache James MPT Imap Mailbox - JCR ................ SUCCESS [  0.521 s]
[INFO] Apache James MPT Imap Mailbox - JPA ................ SUCCESS [  0.211 s]
[INFO] Apache James MPT Imap Mailbox - Maildir ............ SUCCESS [  0.160 s]
[INFO] Apache James :: Server :: Data  :: API ............. SUCCESS [  0.453 s]
[INFO] Apache James :: Protocols :: ManageSieve ........... SUCCESS [  4.701 s]
[INFO] Apache James MPT ManageSieve ....................... SUCCESS [  0.109 s]
[INFO] Apache James MPT ManageSieve Core .................. SUCCESS [  0.422 s]
[INFO] Apache James :: Server :: Lifecycle API ............ SUCCESS [  0.197 s]
[INFO] Apache James :: Server :: Filesystem API ........... SUCCESS [  0.253 s]
[INFO] Apache James :: Server :: DNS Service :: API ....... SUCCESS [  0.622 s]
[INFO] Apache James :: Server :: Core ..................... SUCCESS [ 11.403 s]
[INFO] Apache James :: Server :: Data :: Library .......... SUCCESS [  3.589 s]
[INFO] Apache James :: Server :: Data :: File Persistence . SUCCESS [  4.938 s]
[INFO] Apache James :: Server :: Data  :: MEMORY .......... SUCCESS [  2.880 s]
[INFO] Apache James MPT ManageSieve File .................. SUCCESS [  0.501 s]
[INFO] Apache James :: Server :: Data :: Cassandra Persistence SUCCESS [01:31 min]
[INFO] Apache James MPT ManageSieve Cassandra ............. SUCCESS [ 23.192 s]
[INFO] Apache James MPT SMTP .............................. SUCCESS [  0.109 s]
[INFO] Apache James MPT SMTP Core ......................... SUCCESS [  3.041 s]
[INFO] Apache James :: Server :: Data :: JMAP ............. SUCCESS [  6.519 s]
[INFO] Apache James :: Server :: Data :: JMAP :: Cassandra persistance SUCCESS [ 16.722 s]
[INFO] Apache James :: Server :: Mailbox Adapter .......... SUCCESS [  1.259 s]
[INFO] Apache James :: Server :: Client ................... SUCCESS [  2.973 s]
[INFO] Apache James :: Server :: DNS Service :: Implementation SUCCESS [  1.075 s]
[INFO] Apache James :: Server :: DNS Service :: Library ... SUCCESS [  2.076 s]
[INFO] Apache James :: Server :: Jetty .................... SUCCESS [  4.237 s]
[INFO] Apache James :: Server :: Mail Queue :: API ........ SUCCESS [  0.275 s]
[INFO] Apache James :: Server :: Common Utilities ......... SUCCESS [  2.210 s]
[INFO] Apache James :: Server :: JMAP ..................... SUCCESS [01:01 min]
[INFO] Apache James :: Protocols :: Netty Implementation .. SUCCESS [  0.230 s]
[INFO] Apache James :: Protocols :: SMTP .................. SUCCESS [ 11.570 s]
[INFO] Apache James :: Server :: Mailets .................. SUCCESS [ 12.432 s]
[INFO] Apache James :: Server :: Mailetcontainer API ...... SUCCESS [  0.188 s]
[INFO] Apache James :: Server :: Mailetcontainer Camel .... SUCCESS [  5.131 s]
[INFO] Apache James :: Server :: Protocols Library ........ SUCCESS [  0.401 s]
[INFO] Apache James :: Server :: IMAP ..................... SUCCESS [  0.476 s]
[INFO] Apache James :: Server :: SMTP ..................... SUCCESS [ 13.193 s]
[INFO] Apache James :: Protocols :: LMTP .................. SUCCESS [  4.690 s]
[INFO] Apache James :: Server :: LMTP ..................... SUCCESS [  0.564 s]
[INFO] Apache James :: Server :: ManageSieve .............. SUCCESS [  0.345 s]
[INFO] Apache James :: Protocols :: POP3 .................. SUCCESS [  4.342 s]
[INFO] Apache James :: Server :: POP3 ..................... SUCCESS [  4.471 s]
[INFO] Apache James :: Server :: Mail Queue :: JMS ........ SUCCESS [ 22.576 s]
[INFO] Apache James :: Server :: Mail Queue :: ActiveMQ ... SUCCESS [ 23.353 s]
[INFO] Apache James :: Server :: Guice .................... SUCCESS [  0.109 s]
[INFO] Apache James :: Server :: Guice Common ............. SUCCESS [ 11.627 s]
[INFO] Apache James :: Server :: Cassandra - guice injection SUCCESS [01:37 min]
[INFO] Apache James MPT SMTP Cassandra .................... SUCCESS [ 39.750 s]
[INFO] Apache James MPT Maven2 Plugin ..................... SUCCESS [  1.794 s]
[INFO] Apache James :: Server :: Container Spring ......... SUCCESS [  1.567 s]
[INFO] Apache James :: Server :: Data :: LDAP Implementation SUCCESS [  0.290 s]
[INFO] Apache James :: Server :: FetchMail ................ SUCCESS [  0.388 s]
[INFO] Apache James :: Server :: Mail Queue :: File ....... SUCCESS [  0.141 s]
[INFO] Apache James :: Server :: Data :: JPA Persistence .. SUCCESS [ 41.157 s]
[INFO] Apache James :: Server :: Data :: JDBC Persistence . SUCCESS [03:32 min]
[INFO] Apache James :: Server :: Data :: HBase Persistence  SUCCESS [01:29 min]
[INFO] Apache James :: Server :: Data :: JCR Persistence .. SUCCESS [  4.120 s]
[INFO] Apache James :: Server :: App ...................... SUCCESS [  9.978 s]
[INFO] Apache James :: Karaf :: Features .................. SUCCESS [  0.249 s]
[INFO] Apache James :: Karaf :: James Server .............. SUCCESS [  8.295 s]
[INFO] Apache James :: Karaf :: Integration tests ......... SUCCESS [  4.251 s]
[INFO] Apache James :: Server :: Memory - guice injection . SUCCESS [  9.667 s]
[INFO] Apache James :: Server :: JMAP :: Integration testing SUCCESS [  0.113 s]
[INFO] Apache James :: Server :: JMAP :: Integration testing Common SUCCESS [ 11.809 s]
[INFO] Apache James :: Server :: JMAP :: Cassandra Integration testing SUCCESS [23:17 min]
[INFO] Apache James :: Server :: JMAP :: Memory Integration testing SUCCESS [01:48 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 h
[INFO] Finished at: 2016-06-16T15:11:22+00:00
[INFO] Final Memory: 341M/2903M
[INFO] ------------------------------------------------------------------------

**Comment by aduprat** [comment]
Some results from other PRs:
[INFO] Total time: 01:02 h
[INFO] Total time: 01:03 h
[INFO] Total time: 01:01 h

**Comment by mbaechler** [comment]
@aduprat do you mean we don't gain anything ?

**Comment by rouazana** [comment]
Build time is not a very good indicator, but it shows we don't have a significant gain.
On the other hand, manually launching in memory tests in IDE is clearly faster, so this PR is still valuable.

**Comment by aduprat** [comment]
Well, that's difficult to judge with one run; but it seems that... yes.
(i've checked that the other results are from others PRs)

**Comment by aduprat** [comment]
I'm ok with Raphael, a gain in the development phase is always a gain.

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
Already merged #288

**Pull request closed without merging**
