### PR TITLE
JAMES-2855 Upgrade build Dockerfiles

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
(Just rebased)

**Comment by trantienduchn** [comment]
```
[0bc3ed2aedf4e5938b61bbe26d08290321c2bda9] [ERROR] Errors: 
[0bc3ed2aedf4e5938b61bbe26d08290321c2bda9] [ERROR]   MemoryUploadCucumberTest » Socket Broken pipe (Write failed)
```
test this please

**Comment by chibenwa** [comment]
MemoryUploadCucumberTest » Socket Broken pipe (Write failed)

test this please

**Comment by chibenwa** [comment]
test this please (restart)

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
