### PR TITLE
JAMES-3472: Email/changes method test for distributed environment

### PR DESCRIPTION
**Pull request by LanKhuat**

### CODE REVIEW

**Comment by LanKhuat** [comment]
test this please

**Review by chibenwa — APPROVED** [review]

**Comment by Arsnael** [comment]
test this please

**Review by Arsnael — APPROVED** [review]

**Comment by LanKhuat** [comment]
test this please

**Review by remk — APPROVED** [review]

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
