### PR TITLE
James 2675 3.3

### PR DESCRIPTION
**Pull request by rouazana**
Backport of JAMES-2675 on 3.3x branch. No change at all on commits.

### CODE REVIEW

**Comment by aduprat** [comment]
```
[ERROR] Errors: 
[ERROR]   RabbitMQIMAPInconsistenciesTest » ConditionTimeout Condition with lambda expre...
```

**Comment by rouazana** [comment]
Cannot reproduce :/ test this please

**Comment by chibenwa** [comment]
`RabbitMQIMAPInconsistenciesTest » ConditionTimeout Condition with lambda expre...`

test this please

**Comment by rouazana** [comment]
This test has been removed in this PR. It's seems to be a rebase issue. @aduprat maybe?

**Comment by rouazana** [comment]
I just changed the base branch of this PR, test this please

**Comment by rouazana** [comment]
still not compiling on the good branch :/
```
[56f10016f122b456b6e0246350b994d12e1d9e8c] [ERROR] Errors: 
[56f10016f122b456b6e0246350b994d12e1d9e8c] [ERROR]   RabbitMQIMAPInconsistenciesTest » ConditionTimeout Condition with lambda expre...
```

**Comment by rouazana** [comment]
closing because github don't let me reopen the same pr

**Pull request closed without merging**
