### PR TITLE
JAMES-2892 Implement request-level error handling (fix)

### PR DESCRIPTION
**Pull request by rouazana**
Continuation of #3594 . I was not able to push on your branch, so I create a new PR, but feel free to cherry-pick my commit.

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] 16:04:53.220 [ERROR] r.c.s.Schedulers - Scheduler worker in group main failed with an uncaught exception
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] org.apache.http.ConnectionClosedException: Connection closed unexpectedly
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] MailboxSerializationTest:
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] Serialize Mailbox
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] - should succeed 
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] SessionRoutesTest:
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] get
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] WARNING: An illegal reflective access operation has occurred
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/root/.m2/repository/org/codehaus/groovy/groovy/2.5.6/groovy-2.5.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] WARNING: All illegal access operations will be denied in a future release
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] - should return OK status
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] get
[d6ca7a5bb0eb8567216177cc5597340e663f70ea] - should return correct session *** FAILED ***
```

test this please

**Comment by rouazana** [comment]
it's related, I'm having a look

**Comment by rouazana** [comment]
it seems I could have fixed https://github.com/linagora/james-project/issues/3609 at the same time

**Comment by chibenwa** [comment]
Needs a rebase

**Comment by chibenwa** [comment]
Still

```
[a1db32ac263aea056dd7216e83fbcf28ac947c71] - should serialize session *** FAILED ***
[a1db32ac263aea056dd7216e83fbcf28ac947c71]   {"capabilities":{"urn:ietf:params:jmap:core":{"maxSizeUpload":50000000,"maxConcurrentUpload":8,"maxSizeRequest":10000000,"maxConcurrentRequests":10000000,"maxCallsInRequest":32,"maxObjectsInGet":256,"maxObjectsInSet":128,"collationAlgorithms":["i;ascii-numeric","i;ascii-casemap","i;unicode-casemap"]},"urn:ietf:params:jmap:mail":{"maxMailboxesPerEmail":9359,"maxMailboxDepth":1432,"maxSizeMailboxName":9000,"maxSizeAttachmentsPerEmail":890099,"emailQuerySortOptions":["size"],"mayCreateTopLevelMailbox":true},"urn:apache:james:params:jmap:mail:quota":{},"urn:apache:james:params:jmap:mail:shares":{}},"accounts":{"807a5306ccb4527af7790a0f9b48a776514bdbfba064e355461a76bcffbf2c90":{"name":"user1@james.org","isPersonal":true,"isReadOnly":false,"accountCapabilities":{"urn:ietf:params:jmap:core":{"maxSizeUpload":50000000,"maxConcurrentUpload":8,"maxSizeRequest":10000000,"maxConcurrentRequests":10000000,"maxCallsInRequest":32,"maxObjectsInGet":256,"maxObjectsInSet":128,"collationAlgorithms":["i;ascii-numeric","i;ascii-casemap","i;unicode-casemap"]}}},"a9b46834e106ff73268a40a34ffba9fcfeee8bdb601939d1a96ef9199dc2695c":{"name":"user2@james.org","isPersonal":false,"isReadOnly":false,"accountCapabilities":{"urn:ietf:params:jmap:core":{"maxSizeUpload":50000000,"maxConcurrentUpload":8,"maxSizeRequest":10000000,"maxConcurrentRequests":10000000,"maxCallsInRequest":32,"maxObjectsInGet":256,"maxObjectsInSet":128,"collationAlgorithms":["i;ascii-numeric","i;ascii-casemap","i;unicode-casemap"]}}}},"primaryAccounts":{"urn:ietf:params:jmap:mail":"807a5306ccb4527af7790a0f9b48a776514bdbfba064e355461a76bcffbf2c90","urn:ietf:params:jmap:contact":"807a5306ccb4527af7790a0f9b48a776514bdbfba064e355461a76bcffbf2c90"},"username":"user1@james.org","apiUrl":"http://james.org","downloadUrl":"http://james.org","uploadUrl":"http://james.org","eventSourceUrl":"http://james.org","state":"fda9342jcm"} did not equal {"capabilities":{"urn:ietf:params:jmap:core":{"maxSizeUpload":50000000,"maxConcurrentUpload":8,"maxSizeRequest":10000000,"maxConcurrentRequests":10000000,"maxCallsInRequest":32,"maxObjectsInGet":256,"maxObjectsInSet":128,"collationAlgorithms":["i;ascii-numeric","i;ascii-casemap","i;unicode-casemap"]},"urn:ietf:params:jmap:mail":{"maxMailboxesPerEmail":9359,"maxMailboxDepth":1432,"maxSizeMailboxName":9000,"maxSizeAttachmentsPerEmail":890099,"emailQuerySortOptions":["size"],"mayCreateTopLevelMailbox":true}},"accounts":{"807a5306ccb4527af7790a0f9b48a776514bdbfba064e355461a76bcffbf2c90":{"name":"user1@james.org","isPersonal":true,"isReadOnly":false,"accountCapabilities":{"urn:ietf:params:jmap:core":{"maxSizeUpload":50000000,"maxConcurrentUpload":8,"maxSizeRequest":10000000,"maxConcurrentRequests":10000000,"maxCallsInRequest":32,"maxObjectsInGet":256,"maxObjectsInSet":128,"collationAlgorithms":["i;ascii-numeric","i;ascii-casemap","i;unicode-casemap"]}}},"a9b46834e106ff73268a40a34ffba9fcfeee8bdb601939d1a96ef9199dc2695c":{"name":"user2@james.org","isPersonal":false,"isReadOnly":false,"accountCapabilities":{"urn:ietf:params:jmap:core":{"maxSizeUpload":50000000,"maxConcurrentUpload":8,"maxSizeRequest":10000000,"maxConcurrentRequests":10000000,"maxCallsInRequest":32,"maxObjectsInGet":256,"maxObjectsInSet":128,"collationAlgorithms":["i;ascii-numeric","i;ascii-casemap","i;unicode-casemap"]}}}},"primaryAccounts":{"urn:ietf:params:jmap:mail":"807a5306ccb4527af7790a0f9b48a776514bdbfba064e355461a76bcffbf2c90","urn:ietf:params:jmap:contact":"807a5306ccb4527af7790a0f9b48a776514bdbfba064e355461a76bcffbf2c90"},"username":"user1@james.org","apiUrl":"http://james.org","downloadUrl":"http://james.org","uploadUrl":"http://james.org","eventSourceUrl":"http://james.org","state":"fda9342jcm"} (SessionSerializationTest.scala:208)
```

**Comment by rouazana** [comment]
integrated into #3594

**Pull request closed without merging**
