### PR TITLE
JAMES-2620 Build deployment test in parallel

### PR DESCRIPTION
**Pull request by chibenwa**
This currently takes 2 minutes and is called 5 time by james-jenkins build
pipeline. Significant gains expected.

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:499
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] LastClientMsg: c SEARCH FLAGGED
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Expected: '\* SEARCH 1 2 3 4'
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Actual   : '* SEARCH'
```

test this please

**Comment by Arsnael** [comment]
weird that it breaks on that again...
```
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:499
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] LastClientMsg: c SEARCH FLAGGED
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Expected: '\* SEARCH 1 2 3 4'
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Actual   : '* SEARCH'
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeployment(DeploymentValidation.java:81)
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
```
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] LastClientMsg: c SEARCH FLAGGED
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Expected: '\* SEARCH 1 2 3 4'
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Actual   : '* SEARCH'
```

test this please

**Comment by chibenwa** [comment]
```
[INFO] Total time: 02:12 h
```

**Comment by chibenwa** [comment]
```
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Expected: '\* SEARCH 1 2 3 4'
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] Actual   : '* SEARCH'
```

pffff

**Comment by Arsnael** [comment]
Deployment tests again...

test this please

**Comment by Arsnael** [comment]
```
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] Failed to execute goal on project james-server-filesystem-api: Could not resolve dependencies for project org.apache.james:james-server-filesystem-api:bundle:3.4.0-SNAPSHOT: Failed to collect dependencies at com.sparkjava:spark-core:jar:2.8.0: Failed to read artifact descriptor for com.sparkjava:spark-core:jar:2.8.0: Could not transfer artifact com.sparkjava:spark-core:pom:2.8.0 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] 
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] 
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] 
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] After correcting the problems, you can resume the build with the command
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR]   mvn <goals> -rf :james-server-filesystem-api
```
....... test this please

**Comment by chibenwa** [comment]
:green_apple: but suspicious : test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
:green_apple: one more time to be sure: test this please

**Comment by Arsnael** [comment]
```
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] Errors: 
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR]   BucketBlobStoreContract.saveConcurrentlyWithNonPreExistingBucketShouldNotFail:153 » NotTerminated

[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR] After correcting the problems, you can resume the build with the command
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] [ERROR]   mvn <goals> -rf :blob-objectstorage
```
test this please

**Comment by chibenwa** [comment]
(build was :green_apple: )

```
[a79dbda02f3332ddd8d4dd6d1da2582e78dc6fdc] docker: Error response from daemon: Cannot link to a non running container: /rabbitmq-speedup-build-f4d5f4fe-89c2-4fcd-8d69-d5ff8a112410 AS /james-server-cassandra-rabbitmq-speedup-build-f4d5f4fe-89c2-4fcd-8d69-d5ff8a112410/rabbitmq.
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Pull request closed without merging**
