### PR TITLE
JAMES-2767 prevent import of commons-logging to make log go through s…

### PR DESCRIPTION
**Pull request by mbaechler**
…lf4j

### CODE REVIEW

**Comment by mbaechler** [comment]
Error on github side.

test this pleas

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
```
LinshareBlobExportMechanismProvidingTest.<clinit>:29 » ExceptionInInitializer

[fd613c32fb622388469dcc06335be0a1c074f5bd] [INFO] Running org.apache.james.LinshareBlobExportMechanismProvidingTest
[fd613c32fb622388469dcc06335be0a1c074f5bd] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.014 s <<< FAILURE! - in org.apache.james.LinshareBlobExportMechanismProvidingTest
[fd613c32fb622388469dcc06335be0a1c074f5bd] [ERROR] org.apache.james.LinshareBlobExportMechanismProvidingTest  Time elapsed: 0.014 s  <<< ERROR!
[fd613c32fb622388469dcc06335be0a1c074f5bd] java.lang.ExceptionInInitializerError
[fd613c32fb622388469dcc06335be0a1c074f5bd] 	at org.apache.james.LinshareBlobExportMechanismProvidingTest.<clinit>(LinshareBlobExportMechanismProvidingTest.java:29)
[fd613c32fb622388469dcc06335be0a1c074f5bd] Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
[fd613c32fb622388469dcc06335be0a1c074f5bd] 	at org.apache.james.LinshareBlobExportMechanismProvidingTest.<clinit>(LinshareBlobExportMechanismProvidingTest.java:29)
[fd613c32fb622388469dcc06335be0a1c074f5bd] Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
[fd613c32fb622388469dcc06335be0a1c074f5bd] 	at org.apache.james.LinshareBlobExportMechanismProvidingTest.<clinit>(LinshareBlobExportMechanismProvidingTest.java:29)
[fd613c32fb622388469dcc06335be0a1c074f5bd] Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
[fd613c32fb622388469dcc06335be0a1c074f5bd] 	at org.apache.james.LinshareBlobExportMechanismProvidingTest.<clinit>(LinshareBlobExportMechanismProvidingTest.java:29)
[fd613c32fb622388469dcc06335be0a1c074f5bd] Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*The following user provider for domain '.*' was successfully created.*'
[fd613c32fb622388469dcc06335be0a1c074f5bd] 	at org.apache.james.LinshareBlobExportMechanismProvidingTest.<clinit>(LinshareBlobExportMechanismProvidingTest.java:29)
```

test this please

**Comment by mbaechler** [comment]
It's green, only failing in last steps of Dockerfile.

**Pull request merged**
