### PR TITLE
JAMES-3276 Isolate TemporaryJamesServer

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR] Failures: 
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.mailsFromAuthorizedNetworksShouldBeDeliveredWithRemoteAddrInNetwork Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.mailsFromAuthorizedNetworksShouldBeDeliveredWithRemoteAddrNotInNetwork Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.mailsFromNonAuthorizedNetworksShouldNotBeDeliveredWithRemoteAddrInNetwork Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.mailsFromNonAuthorizedNetworksShouldNotBeDeliveredWithRemoteAddrNotInNetwork Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportLargerMask Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportRangesDefinedByAMiddleIp Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportRangesDefinedByEndingIp Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportRangesWithNonEightMultipleSubMasks Multiple Failures (2 failures)
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] 	<no message> in java.lang.NullPointerException
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR] Errors: 
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   ToSenderDomainRepositoryTest.incomingMailShouldBeIgnoredWhenRepositoryDoesNotExistAndNotAllowedToCreateRepository:133->startJamesServerWithMailetContainer:206 » NullPointer
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   ToSenderDomainRepositoryTest.incomingMailShouldBeStoredInCorrespondingMailRepository:69->startJamesServerWithMailetContainer:206 » NullPointer
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   ToSenderDomainRepositoryTest.incomingMailShouldBeStoredWhenRepositoryDoesNotExistAndAllowedToCreateRepository:89->startJamesServerWithMailetContainer:206 » NullPointer
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   ToSenderDomainRepositoryTest.incomingMailShouldBeStoredWhenRepositoryExistsAndAllowedToCreateRepository:110->startJamesServerWithMailetContainer:206 » NullPointer
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   ToSenderDomainRepositoryTest.incomingMailShouldBeStoredWhenRepositoryExistsAndNotAllowedToCreateRepository:159->startJamesServerWithMailetContainer:206 » NullPointer
[8d66d86ce1261e48e02f642071da73860f92a67e] [ERROR]   ToSenderDomainRepositoryTest.incomingMailsShouldBeStoredInCorrespondingMailRepository:182->startJamesServerWithMailetContainer:206 » NullPointer
```

**Comment by blackheaven** [comment]
MemoryTerminationSubscriberTest

test this please

**Comment by blackheaven** [comment]
MailboxesRoutesTest

test this please

**Comment by Arsnael** [comment]
```
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR] Failures: 
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.mailsFromAuthorizedNetworksShouldBeDeliveredWithRemoteAddrInNetwork Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.mailsFromAuthorizedNetworksShouldBeDeliveredWithRemoteAddrNotInNetwork Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.mailsFromNonAuthorizedNetworksShouldNotBeDeliveredWithRemoteAddrInNetwork Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.mailsFromNonAuthorizedNetworksShouldNotBeDeliveredWithRemoteAddrNotInNetwork Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportLargerMask Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportRangesDefinedByAMiddleIp Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportRangesDefinedByEndingIp Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] [ERROR]   NetworkMatcherIntegrationTest.remoteAddrInNetworkShouldSupportRangesWithNonEightMultipleSubMasks Multiple Failures (2 failures)
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
[8f18a35e571e6cc0f72f1d2392a3bc094f60a708] 	<no message> in java.lang.NullPointerException
```

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
