### PR TITLE
James 1670 : ToRecipientFolder mailet should use init parameters

### PR DESCRIPTION
**Pull request by chibenwa**
Rework of https://github.com/apache/james-project/pull/34

I followed review comments there and upgraded the code.

I also found a bugg with consume parameter (present from the beginning, due to wrong mailet configuration override...) wich was always true in the underlying SieveMailet.

### CODE REVIEW

**Comment by mbaechler** [comment]
@chibenwa : you didn't pushed any fixup for this PR, could you update it ?

**Comment by chibenwa** [comment]
Sorry about that...

**Comment by aduprat** [comment]
:+1:

**Comment by mbaechler** [comment]
:+1:

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Comment by chibenwa** [comment]
test this please

**Pull request closed without merging**
