### PR TITLE
JAMES-2495 Clone

### PR DESCRIPTION
**Pull request by blackheaven**
See #1577

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
[599669deb6f065050ebc060174af03ad2bed3ee5] [ERROR] fromStrictNoUnwrapShouldThrowWhenEmpty  Time elapsed: 0.001 s  <<< ERROR!
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
[599669deb6f065050ebc060174af03ad2bed3ee5] [ERROR] fromShouldThrowWhenBlank  Time elapsed: 0 s  <<< ERROR!
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
[599669deb6f065050ebc060174af03ad2bed3ee5] [ERROR] fromShouldThrowWhenEmpty  Time elapsed: 0.001 s  <<< ERROR!
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
[599669deb6f065050ebc060174af03ad2bed3ee5] [ERROR] fromShouldThrowWhenEmptyAfterRemoveTags  Time elapsed: 0.001 s  <<< ERROR!
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
[599669deb6f065050ebc060174af03ad2bed3ee5] [ERROR] fromStrictNoUnwrapShouldThrowWhenNull  Time elapsed: 0 s  <<< ERROR!
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
[599669deb6f065050ebc060174af03ad2bed3ee5] [ERROR] fromShouldThrowWhenNull  Time elapsed: 0.001 s  <<< ERROR!
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
[599669deb6f065050ebc060174af03ad2bed3ee5] [ERROR] fromStrinctNoUnwrapShouldThrowWhenBlank  Time elapsed: 0.001 s  <<< ERROR!
[599669deb6f065050ebc060174af03ad2bed3ee5] java.lang.NoClassDefFoundError: org/junit/internal/matchers/StacktracePrintingMatcher
[599669deb6f065050ebc060174af03ad2bed3ee5] 
```

Here we go, let the fun begin <3

**Comment by trantienduchn** [comment]
test this please (no build result)

**Comment by chibenwa** [comment]
Same failure :trollface:  

```
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR] Errors: 
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   MessageUidTest.distanceShouldThrowWhenNullArgument » NoClassDefFound org/hamcr...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromShouldThrowWhenBlank » NoClassDefFound org/junit/internal/matchers...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromShouldThrowWhenBlankAfterRemoveTags » NoClassDefFound org/junit/in...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromShouldThrowWhenEmpty » NoClassDefFound org/junit/internal/matchers...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromShouldThrowWhenEmptyAfterRemoveTags » NoClassDefFound org/junit/in...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromShouldThrowWhenNull » NoClassDefFound org/junit/internal/matchers/...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromStrictNoUnwrapShouldThrowWhenEmpty » NoClassDefFound org/junit/int...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromStrictNoUnwrapShouldThrowWhenNull » NoClassDefFound org/junit/inte...
[8053067b0017ea6efd998c5ceaba16a266cee424] [ERROR]   CidTest.fromStrinctNoUnwrapShouldThrowWhenBlank » NoClassDefFound org/junit/in...
```

**Comment by mbaechler** [comment]
```
org.apache.james.mailbox.lucene.search.LuceneMessageSearchIndex for org.apache.james.mailbox.store.event.EventFactory.AddedImpl
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] java.lang.IllegalStateException: Capabilities should prevent calling this method
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.mail.model.DefaultMessageId.serialize(DefaultMessageId.java:26)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.search.SearchUtil.getSerializedMessageIdIfSupportedByUnderlyingStorageOrNull(SearchUtil.java:184)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.lucene.search.LuceneMessageSearchIndex.createMessageDocument(LuceneMessageSearchIndex.java:556)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.lucene.search.LuceneMessageSearchIndex.add(LuceneMessageSearchIndex.java:1252)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.search.ListeningMessageSearchIndex.addMessage(ListeningMessageSearchIndex.java:128)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.search.ListeningMessageSearchIndex.event(ListeningMessageSearchIndex.java:82)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.event.SynchronousEventDelivery.deliver(SynchronousEventDelivery.java:46)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.event.DefaultDelegatingMailboxListener.deliverEventToGlobalListeners(DefaultDelegatingMailboxListener.java:116)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.event.DefaultDelegatingMailboxListener.event(DefaultDelegatingMailboxListener.java:91)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.event.MailboxEventDispatcher.added(MailboxEventDispatcher.java:83)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.event.MailboxEventDispatcher.added(MailboxEventDispatcher.java:91)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.StoreMessageManager.lambda$appendMessage$0(StoreMessageManager.java:421)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.AbstractMailboxPathLocker.executeWithLock(AbstractMailboxPathLocker.java:38)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mailbox.store.StoreMessageManager.appendMessage(StoreMessageManager.java:416)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.AppendProcessor.appendToMailbox(AppendProcessor.java:137)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.AppendProcessor.doProcess(AppendProcessor.java:77)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.AppendProcessor.doProcess(AppendProcessor.java:57)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:110)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.AbstractMailboxProcessor.process(AbstractMailboxProcessor.java:97)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:89)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.AbstractMailboxProcessor.doProcess(AbstractMailboxProcessor.java:71)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:57)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.processor.base.AbstractChainedProcessor.process(AbstractChainedProcessor.java:66)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.main.AbstractImapRequestHandler.doProcessRequest(AbstractImapRequestHandler.java:57)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.imap.decode.main.ImapRequestStreamHandler.handleRequest(ImapRequestStreamHandler.java:79)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mpt.host.JamesImapHostSystem$Session.readLine(JamesImapHostSystem.java:141)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mpt.protocol.ProtocolSession$ContinuationElement.testProtocol(ProtocolSession.java:493)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mpt.protocol.ProtocolSession.runSessions(ProtocolSession.java:111)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mpt.script.GenericSimpleScriptedTestProtocol.runSessions(GenericSimpleScriptedTestProtocol.java:175)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mpt.script.GenericSimpleScriptedTestProtocol.run(GenericSimpleScriptedTestProtocol.java:128)
[d1cf44b6b98211f7bea6d0b9dd28e1c5b8337d11] 	at org.apache.james.mpt.imapmailbox.suite.Select.testSelectUnseenUS(Select.java:52)
```

**Comment by mbaechler** [comment]
test this please

**Comment by chibenwa** [comment]
See https://github.com/linagora/james-project/pull/1631

**Pull request closed without merging**
