### PR TITLE
[CI_ONLY] Disable mvn tests for checking deployment tests

### PR DESCRIPTION
**Pull request by Arsnael**
Just a quick way to check our deployment tests are still working, until we find something better...

### CODE REVIEW

**Comment by Arsnael** [comment]
test this please

**Comment by chibenwa** [comment]
test this please :red_circle:

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
I close this as it seems we have more stability now

**Pull request closed without merging**
