### PR TITLE
See if not reusing forks helps testing stability of mailbox/cassandra

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
With reuseForks, build is fast for mailbox/cassandra

```
[INFO] Apache James :: Mailbox :: Cassandra ............... SUCCESS [02:44 min]
```

However I suspect an impact on overall stability.

**Comment by chibenwa** [comment]
Start several build for faster feedback

I gonna abort them after 30 mins, when mailbox/cassandra will be passed

test this please (build 2)

**Comment by chibenwa** [comment]
test this please (build 3)

**Comment by chibenwa** [comment]
test this please (build 4)

**Comment by chibenwa** [comment]
test this please (build 2)

**Comment by chibenwa** [comment]
test this please (build 3)

**Comment by chibenwa** [comment]
test this please (build 4)

**Comment by chibenwa** [comment]
Build time is now 

```
[INFO] Apache James :: Mailbox :: Cassandra ............... FAILURE [25:27 min]
```

**Comment by chibenwa** [comment]
Build 1 -> `mailbox/cassandra` :green_apple:

**Comment by chibenwa** [comment]
Build 2 -> `mailbox/cassandra` :green_apple:

**Comment by chibenwa** [comment]
Build 3 -> `mailbox/cassandra` :green_apple:

**Comment by hoangdat** [comment]
Read it.

**Comment by chibenwa** [comment]
Build 4 -> `mailbox/cassandra` :green_apple:

**Comment by chibenwa** [comment]
:green_apple:  cf https://james.open-paas.org/job/workflow/282/

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
