### PR TITLE
JAMES-2771 Launch stress test jobs with provisioned instance

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by blackheaven** [comment]
```
[ERROR]   SpamAssassinContract.expungingSpamMessageShouldNotImpactSpamAssassinState:493 » ConditionTimeout
```

test this please

**Comment by Arsnael** [comment]
```
[58c25076fc67774d44b5c39d2faf9a79c6056bdc] [ERROR]   RabbitMQEventBusTest$LifeCycleTest$SingleEventBus.dispatchShouldWorkAfterNetworkIssuesForOldRegistration:323 
[58c25076fc67774d44b5c39d2faf9a79c6056bdc] Wanted but not invoked:
[58c25076fc67774d44b5c39d2faf9a79c6056bdc] mailboxListener.event(
[58c25076fc67774d44b5c39d2faf9a79c6056bdc]     org.apache.james.mailbox.events.MailboxListener$MailboxAdded@bf1a1130
[58c25076fc67774d44b5c39d2faf9a79c6056bdc] );
[58c25076fc67774d44b5c39d2faf9a79c6056bdc] -> at org.apache.james.mailbox.events.RabbitMQEventBusTest$LifeCycleTest$SingleEventBus.dispatchShouldWorkAfterNetworkIssuesForOldRegistration(RabbitMQEventBusTest.java:323)
[58c25076fc67774d44b5c39d2faf9a79c6056bdc] Actually, there were zero interactions with this mock.
```
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Pull request closed without merging**
