### PR TITLE
Glowroot plugins

### PR DESCRIPTION
**Pull request by remk**
add a glowroot plugin to give insight into what happen in the mail spooler.
add also another one to add a metric on time spent storing blob in the blobstore

### CODE REVIEW

**Comment by remk** [comment]
Capture d’écran de 2019-11-19 15-37-48

**Comment by remk** [comment]
Capture d’écran de 2019-11-19 15-40-32

**Comment by chibenwa** [comment]
Merged

**Comment by mbaechler** [comment]
:heart:

**Pull request closed without merging**
