### PR TITLE
JAMES-2949 username strongtyping in mailbox subscriptions storage APIs

### PR DESCRIPTION
**Pull request by chibenwa**
Missing part of #2815

### CODE REVIEW

**Comment by chibenwa** [comment]
`ConcurrentTestRunnerTest.runShouldPerformAllOperationsEvenOnOccasionalExceptions:230 » NotTerminated`

test this please

**Comment by Arsnael** [comment]
```
[68080de4990c20905c959643332519d379a13750] [ERROR] Errors: 
[68080de4990c20905c959643332519d379a13750] [ERROR]   CassandraSubscriptionManagerTest.close:72->AbstractSubscriptionManagerTest.teardown:49 » InvalidType
[68080de4990c20905c959643332519d379a13750] [ERROR]   CassandraSubscriptionManagerTest>AbstractSubscriptionManagerTest.unsubscribeShouldBeIdempotent:97 » InvalidType
[68080de4990c20905c959643332519d379a13750] [ERROR]   CassandraSubscriptionManagerTest.close:72->AbstractSubscriptionManagerTest.teardown:49 » InvalidType
[68080de4990c20905c959643332519d379a13750] [ERROR]   CassandraSubscriptionManagerTest.close:72->AbstractSubscriptionManagerTest.teardown:49 » InvalidType
[68080de4990c20905c959643332519d379a13750] [ERROR]   CassandraSubscriptionManagerTest>AbstractSubscriptionManagerTest.user1ShouldBeAbleToUnsubscribeOneMailbox:88 » InvalidType
[68080de4990c20905c959643332519d379a13750] [ERROR]   CassandraSubscriptionMapperTest>SubscriptionMapperTest.deleteShouldRemoveSubscription:125 » InvalidType
```

**Comment by chibenwa** [comment]
```
[817e25022827415f5e4cf3dc24fcbe1481adf85e] [ERROR]   CassandraSchemaVersionStartUpCheckTest.serverShouldNotStartWhenUnderMinVersion:126 
[817e25022827415f5e4cf3dc24fcbe1481adf85e] Expecting:
[817e25022827415f5e4cf3dc24fcbe1481adf85e]   <com.google.inject.CreationException: Unable to create injector, see the following errors:
[817e25022827415f5e4cf3dc24fcbe1481adf85e] 
[817e25022827415f5e4cf3dc24fcbe1481adf85e] 1) No implementation for org.apache.james.mailbox.store.user.SubscriptionMapperFactory was bound.
[817e25022827415f5e4cf3dc24fcbe1481adf85e]   while locating org.apache.james.mailbox.store.user.SubscriptionMapperFactory
[817e25022827415f5e4cf3dc24fcbe1481adf85e]     for the 1st parameter of org.apache.james.mailbox.store.StoreSubscriptionManager.<init>(StoreSubscriptionManager.java:48)
[817e25022827415f5e4cf3dc24fcbe1481adf85e]   at org.apache.james.modules.mailbox.CassandraMailboxModule.configure(CassandraMailboxModule.java:128) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.apache.james.modules.mailbox.CassandraMailboxModule)
[817e25022827415f5e4cf3dc24fcbe1481adf85e] 
[817e25022827415f5e4cf3dc24fcbe1481adf85e] 1 error>
[817e25022827415f5e4cf3dc24fcbe1481adf85e] to be an instance of:
[817e25022827415f5e4cf3dc24fcbe1481adf85e]   <org.apache.james.StartUpChecksPerformer.StartUpChecksException>
[817e25022827415f5e4cf3dc24fcbe1481adf85e] but was:
[817e25022827415f5e4cf3dc24fcbe1481adf85e]   <"com.google.inject.CreationException: Unable to create injector, see the following errors:
[817e25022827415f5e4cf3dc24fcbe1481adf85e] 
[817e25022827415f5e4cf3dc24fcbe1481adf85e] 1) No implementation for org.apache.james.mailbox.store.user.SubscriptionMapperFactory was bound.
[817e25022827415f5e4cf3dc24fcbe1481adf85e]   while locating org.apache.james.mailbox.store.user.SubscriptionMapperFactory
[817e25022827415f5e4cf3dc24fcbe1481adf85e]     for the 1st parameter of org.apache.james.mailbox.store.StoreSubscriptionManager.<init>(StoreSubscriptionManager.java:48)
[817e25022827415f5e4cf3dc24fcbe1481adf85e]   at org.apache.james.modules.mailbox.CassandraMailboxModule.configure(CassandraMailboxModule.java:128) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.apache.james.modules.mailbox.CassandraMailboxModule)
```

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
