### PR TITLE
James 2949 add integration test and update documentation

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[ERROR] Failed to execute goal on project apache-james-backends-jpa: Could not resolve dependencies for project org.apache.james:apache-james-backends-jpa:jar:3.5.0-SNAPSHOT: Failed to collect dependencies at com.google.guava:guava:jar:25.1-jre: Failed to read artifact descriptor for com.google.guava:guava:jar:25.1-jre: Could not transfer artifact com.google.guava:guava:pom:25.1-jre from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/com/google/guava/guava/25.1-jre/guava-25.1-jre.pom.part (No such file or directory) -> [Help 1]
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
just rebased on 2902 last updates and on master

**Comment by rouazana** [comment]
just rebased with last fixups

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
