### PR TITLE
[FIX] Synchronize WebAdmin server startup at the JVM level to avoid p…

### PR DESCRIPTION
**Pull request by chibenwa**
…ort allocation conflicts

### CODE REVIEW

**Comment by mbaechler** [comment]
I don't deny it will fix some occurrences but:
* you are still exposed to situations where two tests run in different JVM
* spark has a very poor default policy : 
```
        if (port == 0) {
            try (ServerSocket s = new ServerSocket(0)) {
                port = s.getLocalPort();
            } catch (IOException e) {
                logger.error("Could not get first available port (port set to 0), using default: {}", SPARK_DEFAULT_PORT);
                port = SPARK_DEFAULT_PORT;
            }
        }
```
As the socket is closed once you get a port, the chances are high that the OS allocate the same port for the next code doing the same operation resulting in a port conflict.
* spark is trying to handle something that jetty does much better (note that `JettyHttpServer` does support random port allocation the way it should be done)

So ok to merge that if it solves a short-term problem but please at least open a JIRA to describe what the right solution is (fixing Spark to let Jetty allocate the port itself).

**Comment by chibenwa** [comment]
After reading your comment, this effort seems pointless (as parrallel surefire forks runs on different JVM).

I'm in the end not sure that the cost (added complexity) outweight the benefits of a situation we don't have (each fork starts strictly one server at any given time, that don't happen to share the same JVM), and might result on an unjustified feeling of safety.

Another suggestion might be to have a retry strategy?

**Comment by mbaechler** [comment]
> Another suggestion might be to have a retry strategy?

That's a solution. It's not as good as fixing sparkjava

**Comment by chibenwa** [comment]
```
[1d7752c6e3312860981595376896ed1b4efa5ad9] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project memory-jmap-draft-integration-testing: There was a timeout or other error in the fork -> [Help 1]
```

test this please

(unrelated)

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
