### PR TITLE
JAMES-2607 don't warn on missing batchsizes configuration file

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
Duplicates of https://github.com/linagora/james-project/pull/1957 ???

**Comment by hoangdat** [comment]
Build triggered. sha1 is merged.

**Comment by hoangdat** [comment]
Build started sha1 is merged.

**Comment by hoangdat** [comment]
Build finished. No test results found.

**Comment by hoangdat** [comment]
Build triggered. sha1 is merged.

**Comment by hoangdat** [comment]
Build started sha1 is merged.

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
```
[8e45d2c061033b46c1b07ffddc725f36d4ebd616] [ERROR] Failures: 
[8e45d2c061033b46c1b07ffddc725f36d4ebd616] [ERROR]   ManageableMailQueueContract.browsingShouldNotAffectDequeue:496 expected:<"name[1]"> but was:<"name[2]">
```
test this please

**Pull request merged**
