### PR TITLE
Exclude test jar dependencies

### PR DESCRIPTION
**Pull request by rouazana**
Rebase of #1657 on master with some fixes

### CODE REVIEW

**Comment by rouazana** [comment]
```
[9ec280420e16edfb5257adde971853dc10b858b0] [ERROR] Failures: 
[9ec280420e16edfb5257adde971853dc10b858b0] [ERROR]   ESReporterTest.esMetricReporterShouldProduceDocumentsOnAnElasticsearchContainer Multiple Failures (2 failures)
[9ec280420e16edfb5257adde971853dc10b858b0] 	Mapped port can only be obtained after the container is started
[9ec280420e16edfb5257adde971853dc10b858b0] 	<no message> in java.lang.NullPointerException
[9ec280420e16edfb5257adde971853dc10b858b0] [ERROR]   ESReporterTest.esMetricReporterShouldProduceDocumentsOnAnElasticsearchContainerWhenRecordingTimeMetric Multiple Failures (2 failures)
[9ec280420e16edfb5257adde971853dc10b858b0] 	Mapped port can only be obtained after the container is started
[9ec280420e16edfb5257adde971853dc10b858b0] 	<no message> in java.lang.NullPointerException
```
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
```
[9ec280420e16edfb5257adde971853dc10b858b0] [ERROR] Failures: 
[9ec280420e16edfb5257adde971853dc10b858b0] [ERROR]   ESReporterTest.esMetricReporterShouldProduceDocumentsOnAnElasticsearchContainer Multiple Failures (2 failures)
[9ec280420e16edfb5257adde971853dc10b858b0] 	Mapped port can only be obtained after the container is started
[9ec280420e16edfb5257adde971853dc10b858b0] 	<no message> in java.lang.NullPointerException
[9ec280420e16edfb5257adde971853dc10b858b0] [ERROR]   ESReporterTest.esMetricReporterShouldProduceDocumentsOnAnElasticsearchContainerWhenRecordingTimeMetric Multiple Failures (2 failures)
[9ec280420e16edfb5257adde971853dc10b858b0] 	Mapped port can only be obtained after the container is started
[9ec280420e16edfb5257adde971853dc10b858b0] 	<no message> in java.lang.NullPointerException
[9ec280420e16edfb5257adde971853dc10b858b0] [INFO] 
[9ec280420e16edfb5257adde971853dc10b858b0] [ERROR] Tests run: 8, Failures: 2, Errors: 0, Skipped: 0
```
weird. Maybe es ports(9200,9300) on CI are in use

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Force pushed to solve conflicts

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Build was no more triggered. See https://github.com/linagora/james-project/pull/1695

**Pull request closed without merging**
