### PR TITLE
Use a single HashedWheelTimer in the whole application as recommended…

### PR DESCRIPTION
**Pull request by mbaechler**
… by its documentation

Build will probably fail because of spring ... but let's check

### CODE REVIEW

**Comment by mbaechler** [comment]
@chibenwa : no, but I wrote it already

**Comment by chibenwa** [comment]
Lost build results

test this please

**Comment by chibenwa** [comment]
```
[90d3af7c8ab132f32cdac135f2b78446452b7a58] [INFO] Apache James :: Server :: App ...................... FAILURE [ 16.182 s]
```

Gotcha! Your broke Spring ;-)

```
[90d3af7c8ab132f32cdac135f2b78446452b7a58] Failed tests: 
[90d3af7c8ab132f32cdac135f2b78446452b7a58]   JamesSpringContextTest.springShouldLoadAndAddOnlyOneQuotaUpdaterListener Multiple Failures (2 failures)
[90d3af7c8ab132f32cdac135f2b78446452b7a58] 	Error creating bean with name 'smtpserver' defined in class path resource [META-INF/spring/smtpserver-context.xml]: Unsatisfied dependency expressed through constructor argument with index 4 of type [org.jboss.netty.util.HashedWheelTimer]: : No qualifying bean of type [org.jboss.netty.util.HashedWheelTimer] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.jboss.netty.util.HashedWheelTimer] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
[90d3af7c8ab132f32cdac135f2b78446452b7a58] 	<no message> in java.lang.NullPointerException
[90d3af7c8ab132f32cdac135f2b78446452b7a58] Tests in error: 
[90d3af7c8ab132f32cdac135f2b78446452b7a58]   JamesAppSpringMainTest.testServer:27 » UnsatisfiedDependency Error creating be...
```

**Comment by mbaechler** [comment]
can't approve my own PR, but 👍

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
