### PR TITLE
JAMES-3157 Fix support for bench profiles

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[d1d0b773b8c20dacc1dd250a0f0b60998f7a5d03] [ERROR]   JMSCacheableMailQueueTest.constructorShouldRegisterGetQueueSizeGauge 
[d1d0b773b8c20dacc1dd250a0f0b60998f7a5d03] Expecting:
[d1d0b773b8c20dacc1dd250a0f0b60998f7a5d03]  <0L>
[d1d0b773b8c20dacc1dd250a0f0b60998f7a5d03] to be equal to:
[d1d0b773b8c20dacc1dd250a0f0b60998f7a5d03]  <3L>
[d1d0b773b8c20dacc1dd250a0f0b60998f7a5d03] but was not.
```

test this please

**Comment by blackheaven** [comment]
test this please

**Comment by Arsnael** [comment]
Ouput log lost

test this please

**Comment by blackheaven** [comment]
CI do not test it

**Comment by chibenwa** [comment]
Build output lost

test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
