### PR TITLE
Full, generic test suite for mail queues and memory mail queue

### PR DESCRIPTION
**Pull request by chibenwa**
Aggregate of already (almost) approuved PRs.

Remaining PR comments are the easy to spot comments.

### CODE REVIEW

**Comment by chibenwa** [comment]
No I will add it in a separate PR.

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
I push force to solve conflicts, the bad thing is that commit order is now broken, here is the good order given by `git log --oneline`:
```
2431689 fixup! JAMES-2305 MailQueueItemView should be a class
f7f420c JAMES-2288 MemoryMailQueue should be manageable
3e3dd4a JAMES-2288 Fix a test in ManageableMailQueue
992e1a8 JAMES-2305 MailQueueItemView should be a class
93e8a6d JAMES-2285 MailSpoolTest should rely on MemoryMailQueue
aef7b3e JAMES-2285 Rely on MemoryMailQueue in SMTPServerTest
d777a12 JAMES-2285 Move test and fix memory mailqueue to a new module
86814bd JAMES-2285 FakeMail should be serializable
3d7c37d JAMES-2285 ActiveMQ should rely on generic tests
6f90503 fixup! JAMES-2285 Contracts for delayed mail queues
17be5fa fixup! JAMES-2285 Contracts for prioritized mail queues
0731f56 JAMES-2285 Contracts for prioritized mail queues
5de88d2 JAMES-2285 Contracts for delayed mail queues
```

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
