### PR TITLE
Replacing NoopMetric by the RecordingMetric

### PR DESCRIPTION
**Pull request by trantienduchn**
I hope you can read though this before going into reviews, Cause it might save your time!

Recently, there is a MetricContract provided in
#2993

Started from the discussion in #2993 (comment)

I came to a conclusion that the NoopMetric should follow the contract
while its purpose is only to satisfy the compiler in tests but not a
working Metric. Thus it will break almost tests in the contract because
of fake behaviors. This issue can by addressed by several ways:

 - @mbaechler option: Make NoopMetric really works, but it conflicts with the RecordingMetric
 - @chibenwa otpion: Throw exceptions in NoopMetric methods, it provide fake answers, where it does not thing => could breaks a lot of tests
 - @chibenwa otpion: Having a ReadingMetricFactory implement Metric, and leave NoopMetric
 - @chibenwa otpion: Replace NoopMetric by RecordingMetric if possible.

I decided to take the 4th solution.

**Update 1**: After trying to replace and drop the NoopMetric, there is a class in production `LMTPProtocolHandlerChain` uses the `NoopMetric` which I though meant for only testing and I feel that it really need a metric that do nothing. Which lead me to the though that NoopMetric is still valid but just the name doesn't describe it exactly. And finally I renamed it to `IdleMetric` at the last commit and really prefer the idea reverting everything and just rename it. WDYT ?

**Update 2**: LMTPProtocolHandlerChain is used only in test. I will try to move it in test package with the Recording metric, that will ease the process of removing NoopMetric

### CODE REVIEW

**Comment by chibenwa** [comment]
If lmtpHandler chain stuff is only used by tests then we should move it in the test package, no?

Then using RecordingMetric there should not hurt.

**Comment by Arsnael** [comment]
```
[995c9aa23c2005471789df86f974d9765c1923e5] [ERROR] Errors: 
[995c9aa23c2005471789df86f974d9765c1923e5] [ERROR]   SetCustomFlagOnBigMessagesTest.beforeEach:68 » NoClassDefFound org/apache/jame...
[995c9aa23c2005471789df86f974d9765c1923e5] [ERROR]   SetCustomFlagOnBigMessagesTest.beforeEach:68 » NoClassDefFound org/apache/jame...
[995c9aa23c2005471789df86f974d9765c1923e5] [ERROR]   SetCustomFlagOnBigMessagesTest.beforeEach:68 » NoClassDefFound org/apache/jame...
[995c9aa23c2005471789df86f974d9765c1923e5] [ERROR]   SetCustomFlagOnBigMessagesTest.beforeEach:68 » NoClassDefFound org/apache/jame...
[995c9aa23c2005471789df86f974d9765c1923e5] [ERROR]   SetCustomFlagOnBigMessagesTest.beforeEach:68 » NoClassDefFound org/apache/jame...
[995c9aa23c2005471789df86f974d9765c1923e5] [ERROR]   SetCustomFlagOnBigMessagesTest.beforeEach:68 » NoClassDefFound org/apache/jame...
```

**Comment by Arsnael** [comment]
```
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR] Errors: 
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldGroupSizeAndCountNotificationsWhenTriggeredByASingleEvent » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendDuplicates » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenNoThresholdUpdateForCount » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenNoThresholdUpdate » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenThresholdOverPassedRecentlyForCount » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenThresholdOverPassedRecently » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenUnderAllThresholds » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotifySeparatelyCountAndSize » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassedForCount » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassedOverGracePeriodForCount » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassedOverGracePeriod » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassed » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendOneMailUponConcurrentEvents » NoClassDefFound
[8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendOneNoticePerThreshold » NoClassDefFound
```
test this please

**Comment by trantienduchn** [comment]
> ```
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR] Errors: 
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldGroupSizeAndCountNotificationsWhenTriggeredByASingleEvent » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendDuplicates » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenNoThresholdUpdateForCount » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenNoThresholdUpdate » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenThresholdOverPassedRecentlyForCount » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenThresholdOverPassedRecently » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotSendMailWhenUnderAllThresholds » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldNotifySeparatelyCountAndSize » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassedForCount » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassedOverGracePeriodForCount » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassedOverGracePeriod » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendMailWhenThresholdOverPassed » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendOneMailUponConcurrentEvents » NoClassDefFound
> [8b64a4f666d75f65cc35473112e1da89963b4afe] [ERROR]   CassandraQuotaMailingListenersIntegrationTest.shouldSendOneNoticePerThreshold » NoClassDefFound
> ```
> 
> test this please

it's real error :)

**Comment by chibenwa** [comment]
> it's real error :)

I think you missed a metrics-test import :trollface:

**Comment by chibenwa** [comment]
```
[fae6ca27254a6d72d4257bb353d1437422a61c1b] [INFO] Running org.apache.james.mailbox.tools.copier.MailboxCopierTest
[fae6ca27254a6d72d4257bb353d1437422a61c1b] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.32 s <<< FAILURE! - in org.apache.james.mailbox.tools.copier.MailboxCopierTest
[fae6ca27254a6d72d4257bb353d1437422a61c1b] [ERROR] testMailboxCopy  Time elapsed: 0.311 s  <<< ERROR!
[fae6ca27254a6d72d4257bb353d1437422a61c1b] java.lang.NoClassDefFoundError: org/apache/james/metrics/tests/RecordingMetricFactory
[fae6ca27254a6d72d4257bb353d1437422a61c1b] 	at org.apache.james.mailbox.tools.copier.MailboxCopierTest.newInMemoryMailboxManager(MailboxCopierTest.java:139)
[fae6ca27254a6d72d4257bb353d1437422a61c1b] 	at org.apache.james.mailbox.tools.copier.MailboxCopierTest.setup(MailboxCopierTest.java:75)
[fae6ca27254a6d72d4257bb353d1437422a61c1b] Caused by: java.lang.ClassNotFoundException: org.apache.james.metrics.tests.RecordingMetricFactory
[fae6ca27254a6d72d4257bb353d1437422a61c1b] 	at org.apache.james.mailbox.tools.copier.MailboxCopierTest.newInMemoryMailboxManager(MailboxCopierTest.java:139)
[fae6ca27254a6d72d4257bb353d1437422a61c1b] 	at org.apache.james.mailbox.tools.copier.MailboxCopierTest.setup(MailboxCopierTest.java:75)
```

**Comment by chibenwa** [comment]
```
[52f42652346fb53afc1490d267b8ce2365c75f70] [ERROR] Failed to execute goal on project apache-james-backends-jpa: Could not resolve dependencies for project org.apache.james:apache-james-backends-jpa:jar:3.5.0-SNAPSHOT: Failed to collect dependencies at com.google.guava:guava:jar:25.1-jre: Failed to read artifact descriptor for com.google.guava:guava:jar:25.1-jre: Could not transfer artifact com.google.guava:guava:pom:25.1-jre from/to central (https://repo.maven.apache.org/maven2): /root/.m2/repository/com/google/guava/guava/25.1-jre/guava-25.1-jre.pom.part (No such file or directory) -> [Help 1]
```

test this please

**Comment by trantienduchn** [comment]
```
[52f42652346fb53afc1490d267b8ce2365c75f70] [INFO] Running org.apache.james.mpt.imapmailbox.elasticsearch.ElasticSearchUidSearchOnIndexTest
[52f42652346fb53afc1490d267b8ce2365c75f70] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 18.379 s <<< FAILURE! - in org.apache.james.mpt.imapmailbox.elasticsearch.ElasticSearchUidSearchOnIndexTest
[52f42652346fb53afc1490d267b8ce2365c75f70] [ERROR] testSearchAtomsUS  Time elapsed: 18.368 s  <<< ERROR!
[52f42652346fb53afc1490d267b8ce2365c75f70] java.lang.NoClassDefFoundError: org/apache/james/metrics/tests/RecordingMetricFactory
[52f42652346fb53afc1490d267b8ce2365c75f70] 	at org.apache.james.mpt.imapmailbox.elasticsearch.ElasticSearchUidSearchOnIndexTest.setUp(ElasticSearchUidSearchOnIndexTest.java:36)
[52f42652346fb53afc1490d267b8ce2365c75f70] Caused by: java.lang.ClassNotFoundException: org.apache.james.metrics.tests.RecordingMetricFactory
[52f42652346fb53afc1490d267b8ce2365c75f70] 	at org.apache.james.mpt.imapmailbox.elasticsearch.ElasticSearchUidSearchOnIndexTest.setUp(ElasticSearchUidSearchOnIndexTest.java:36)
```

**Comment by chibenwa** [comment]
`InMemoryAuthenticatePlainTest.setUp:35 » NoClassDefFound org/apache/james/metr...`

**Comment by chibenwa** [comment]
```
[93d7385f993a4986451ebb6f7e411c5933c04274] [ERROR]   CassandraMigrationRoutesTest.postShouldNotUpdateVersionWhenCurrentVersionIsNewerThan Multiple Failures (2 failures)
[93d7385f993a4986451ebb6f7e411c5933c04274] 	java.lang.NoClassDefFoundError: org/apache/james/metrics/tests/RecordingMetricFactory
[93d7385f993a4986451ebb6f7e411c5933c04274] 	java.lang.NullPointerException: <no message>
```

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
