### PR TITLE
[REFACTORING] Merge MessageMetaData & MetadataWithMailboxId POJOs

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[ee464b2fcbc9569b295ec611deeb35ecdc819199] [ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.4.4:compile (scala-compile-first) on project apache-james-mailbox-event-json: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
I just created https://issues.apache.org/jira/browse/MAILBOX-394

**Comment by mbaechler** [comment]
I'm sorry but I now doubt the goal of this PR: I understand the will to remove duplicate concepts to simplify the codebase. 

However, it means we now publish events with useless data _and_ it breaks the event format contract for no functional gain.

Why it's so important to merge these two types together ?

**Comment by chibenwa** [comment]
> Why it's so important to merge these two types together ?

It's not.

I just did the refactoring first and encountered the JSON issue after.

I think this exploratory work can safely be discarded as well.

**Pull request closed without merging**
