### PR TITLE
JAMES-2678 Remove deprecate Mailet API methods and attribute

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by rouazana** [comment]
new version, so we remove deprecated methods, no?

**Comment by blackheaven** [comment]
Spring cleanup!

**Comment by Arsnael** [comment]
```
[193da52aa4aad2b74f8b5c4cda83a6b516441f97] [ERROR] Errors: 
[193da52aa4aad2b74f8b5c4cda83a6b516441f97] [ERROR]   MailImplTest.mailImplShouldBeSerializable:305 » NotSerializable org.apache.jam...
[193da52aa4aad2b74f8b5c4cda83a6b516441f97] [ERROR]   MailImplTest.mailImplShouldBeSerializableWithCollectionAttribute:347 » NotSerializable
[193da52aa4aad2b74f8b5c4cda83a6b516441f97] [ERROR]   MailImplTest.mailImplShouldBeSerializableWithOptionalAttribute:326 » NotSerializable
```

**Comment by joecoc1916** [comment]
Thank You,

God Bless.

Joseph C.

**Pull request closed without merging**
