### PR TITLE
JAMES-2993 ReIndexing endpoints should be resource oriented

### PR DESCRIPTION
**Pull request by chibenwa**
- Re-arrange their documentation

 - Also, we relocate `POST /mailboxes?user=bob` to the existing `POST /users/bob/mailboxes` endpoint.

### CODE REVIEW

**Comment by chibenwa** [comment]
`[INFO] Apache James :: Server :: Web Admin :: mailbox ..... FAILURE [  02:00 h]`

Deadlock ! Running classes one by one: no issue. Running classes together: :bomb: !

**Comment by chibenwa** [comment]
`boundedElastic` to be blamed here!

**Comment by chibenwa** [comment]
```
[4d066474705891a4517aba7bc166a024aba7096d] [ERROR]   MemoryJmapJamesServerTest$JamesServerJmapConfigurationTest$BadSecretKeyStore.jamesShouldNotStartWhenBadSecret:96 
[4d066474705891a4517aba7bc166a024aba7096d] Expecting:
[4d066474705891a4517aba7bc166a024aba7096d]   <com.google.inject.CreationException: Unable to create injector, see the following errors:
[4d066474705891a4517aba7bc166a024aba7096d] 
[4d066474705891a4517aba7bc166a024aba7096d] 1) No implementation for org.apache.james.mailbox.indexer.ReIndexer was bound.
[4d066474705891a4517aba7bc166a024aba7096d]   while locating org.apache.james.mailbox.indexer.ReIndexer
[4d066474705891a4517aba7bc166a024aba7096d]     for the 5th parameter of org.apache.james.webadmin.routes.UserMailboxesRoutes.<init>(UserMailboxesRoutes.java:84)
[4d066474705891a4517aba7bc166a024aba7096d]   at org.apache.james.modules.server.MailboxRoutesModule.configure(MailboxRoutesModule.java:43) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.apache.james.modules.server.MailboxRoutesModule)
[4d066474705891a4517aba7bc166a024aba7096d] 
[4d066474705891a4517aba7bc166a024aba7096d] 1 error>
[4d066474705891a4517aba7bc166a024aba7096d] to be an instance of:
[4d066474705891a4517aba7bc166a024aba7096d]   <org.apache.james.StartUpChecksPerformer.StartUpChecksException>
[4d066474705891a4517aba7bc166a024aba7096d] but was:
[4d066474705891a4517aba7bc166a024aba7096d]   <"com.google.inject.CreationException: Unable to create injector, see the following errors:
[4d066474705891a4517aba7bc166a024aba7096d] 
[4d066474705891a4517aba7bc166a024aba7096d] 1) No implementation for org.apache.james.mailbox.indexer.ReIndexer was bound.
[4d066474705891a4517aba7bc166a024aba7096d]   while locating org.apache.james.mailbox.indexer.ReIndexer
[4d066474705891a4517aba7bc166a024aba7096d]     for the 5th parameter of org.apache.james.webadmin.routes.UserMailboxesRoutes.<init>(UserMailboxesRoutes.java:84)
[4d066474705891a4517aba7bc166a024aba7096d]   at org.apache.james.modules.server.MailboxRoutesModule.configure(MailboxRoutesModule.java:43) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.apache.james.modules.server.MailboxRoutesModule)
```

**Comment by Arsnael** [comment]
```
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR] Errors: 
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.connectIMAPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.connectLMTPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.connectOnSecondaryIMAPServerIMAPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.connectPOP3ServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.connectSMTPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.hostnameShouldBeRetrievedWhenRestarting » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   AuthenticatedCassandraJamesServerTest$AuthenticationTest.hostnameShouldBeUsedAsDefaultDomain » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.connectIMAPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.connectLMTPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.connectOnSecondaryIMAPServerIMAPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.connectPOP3ServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.connectSMTPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.copyBatchSizeShouldEqualsConfigurationValue » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.hostnameShouldBeRetrievedWhenRestarting » Creation Un...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.hostnameShouldBeUsedAsDefaultDomain » Creation Unable...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJamesServerTest.moveBatchSizeShouldEqualsConfigurationValue » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraJmapJamesServerTest.connectJMAPServerShouldRespondBadRequest » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraMailRepositoryIntegrationTest.deniedSenderMailShouldBeStoredInCassandraMailRepositoryWhenConfigured » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraNodeConfTest$NormalBehaviour.serverShouldStartServiceWhenNodeIsReachable:80 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraNodeConfTest$OneFailedNode.serverShouldStartServiceWhenNodeIsReachable:100 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraNodeConfTest$UseMappedPort.configShouldWorkWithNonDefaultPort:117 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraWithTikaTest.connectIMAPServerShouldSendShabangOnConnect » Creation U...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraWithTikaTest.connectLMTPServerShouldSendShabangOnConnect » Creation U...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraWithTikaTest.connectOnSecondaryIMAPServerIMAPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraWithTikaTest.connectPOP3ServerShouldSendShabangOnConnect » Creation U...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraWithTikaTest.connectSMTPServerShouldSendShabangOnConnect » Creation U...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraWithTikaTest.hostnameShouldBeRetrievedWhenRestarting » Creation Unabl...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraWithTikaTest.hostnameShouldBeUsedAsDefaultDomain » Creation Unable to...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   DefaultCassandraJamesServerTest.cassandraJamesServerShouldStartWithNoConfigurationFile » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   ESReporterTest.timeMetricsShouldBeReportedWhenImapCommandsReceived » Creation ...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   ESReporterTest.timeMetricsShouldBeReportedWhenJmapRequestsReceived » Creation ...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   FixingGhostMailboxTest.ghostMailboxBugShouldChangeMailboxId » Creation Unable ...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   FixingGhostMailboxTest.ghostMailboxBugShouldDiscardOldContent » Creation Unabl...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   FixingGhostMailboxTest.mergingMailboxTaskShouldBeInformative » Creation Unable...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   FixingGhostMailboxTest.oldGhostedMailboxShouldNoMoreBeAccessible » Creation Un...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   FixingGhostMailboxTest.webadminCanMergeTwoMailboxes » Creation Unable to creat...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   FixingGhostMailboxTest.webadminCanMergeTwoMailboxesRights » Creation Unable to...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToCassandraWhenStartService:90->assertThatServerStartCorrectly:114 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldRetryToConnectToElasticSearchWhenStartService:99->assertThatServerStartCorrectly:114 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   JamesServerWithRetryConnectionTest.serverShouldStartAtDefault:81->assertThatServerStartCorrectly:114 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.connectIMAPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.connectJMAPServerShouldRespondBadRequest » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.connectLMTPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.connectOnSecondaryIMAPServerIMAPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.connectPOP3ServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.connectSMTPServerShouldSendShabangOnConnect » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.hostnameShouldBeRetrievedWhenRestarting » Creation ...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.hostnameShouldBeUsedAsDefaultDomain » Creation Unab...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.mailsShouldBeWellReceived » Creation Unable to crea...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   WithCassandraBlobStoreTest.oneHundredMailsShouldBeWellReceived » Creation Unab...
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraSchemaVersionStartUpCheckTest.serverShouldStartSuccessfullyWhenBetweenMinAndMaxVersion:105 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraSchemaVersionStartUpCheckTest.serverShouldStartSuccessfullyWhenMaxVersion:95 » Creation
[699cc45a10bf9df30b618258ef08e7b4f38f9ab8] [ERROR]   CassandraSchemaVersionStartUpCheckTest.serverShouldStartSuccessfullyWhenMinVersion:115 » Creation
```

**Comment by chibenwa** [comment]
```
[2b87b8b6ae12703bbe72baef94762644d2352c31] [INFO] Apache James :: Server :: Memory - guice injection . FAILURE [  02:01 h]
```

Arf

```
[2b87b8b6ae12703bbe72baef94762644d2352c31] java.lang.IllegalStateException: null
[2b87b8b6ae12703bbe72baef94762644d2352c31] 	at com.google.common.base.Preconditions.checkState(Preconditions.java:491)
[2b87b8b6ae12703bbe72baef94762644d2352c31] 	at org.apache.james.webadmin.tasks.TaskFromRequestRegistry$Builder.build(TaskFromRequestRegistry.java:78)
```

**Comment by chibenwa** [comment]
Explanation: for memory, no endpoint is bound, which violates the TaskFromRequestRegistry precondition.

We should not expose endpoint if no task is associated to it.

**Comment by Arsnael** [comment]
Is `user mbx` a fixup commit?

**Comment by chibenwa** [comment]
> Is user mbx a fixup commit?

Yes let me reword that

**Comment by chibenwa** [comment]
```
[efa6382db9018066cda2be5203e96dab05a4ba8f] [ERROR] Failures: 
[efa6382db9018066cda2be5203e96dab05a4ba8f] [ERROR]   WebAdminServerTaskSerializationIntegrationTest.userReindexingShouldComplete:327 1 expectation failed.
[efa6382db9018066cda2be5203e96dab05a4ba8f] JSON path type doesn't match.
[efa6382db9018066cda2be5203e96dab05a4ba8f] Expected: is "user-reindexing"
[efa6382db9018066cda2be5203e96dab05a4ba8f]   Actual: full-reindexing
[efa6382db9018066cda2be5203e96dab05a4ba8f] 
```

???

**Comment by chibenwa** [comment]
```
CassandraAccessTokenRepositoryTest>AccessTokenRepositoryTest.validTokenMustBeRetrieved:45 » InvalidAccessToken
```

So unfair.

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
