### PR TITLE
It migrates progressively some modules to junit5

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by mbaechler** [comment]
```

[ec5126bfe6be31882e870ebe1f156c618a90d6ca] [INFO] 
[ec5126bfe6be31882e870ebe1f156c618a90d6ca] [ERROR] Failures: 
[ec5126bfe6be31882e870ebe1f156c618a90d6ca] [ERROR]   AnnotationMapperTest.insertAnnotationShouldThrowExceptionWithNilData:67 
[ec5126bfe6be31882e870ebe1f156c618a90d6ca] Expecting:
[ec5126bfe6be31882e870ebe1f156c618a90d6ca]   <java.lang.NullPointerException>
[ec5126bfe6be31882e870ebe1f156c618a90d6ca] to be an instance of:
[ec5126bfe6be31882e870ebe1f156c618a90d6ca]   <java.lang.IllegalArgumentException>
[ec5126bfe6be31882e870ebe1f156c618a90d6ca] but was:
[ec5126bfe6be31882e870ebe1f156c618a90d6ca]   <"java.lang.NullPointerException
[ec5126bfe6be31882e870ebe1f156c618a90d6ca] 	at org.apache.james.mailbox.store.mail.model.AnnotationMapperTest.lambda$insertAnnotationShouldThrowExceptionWithNilData$0(AnnotationMapperTest.java:66)
```

**Comment by hoangdat** [comment]
Build triggered. sha1 is original commit.

**Comment by openpaas-james** [comment]
Build finished. No test results found.

**Comment by chibenwa** [comment]
Too much conflicts that will not be fixed anytime soon, an automated refactoring obfuscate the history, and mailbox/* modules do now rely on junit 5

**Pull request closed without merging**
