### PR TITLE
JAMES-3309 Avoid a NPE in FetchProcessor when SelectedMailbox is unselected

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
```

[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d] [ERROR] Failures: 
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d] [ERROR]   MemoryTerminationSubscriberTest.dynamicListeningEventsShouldGetOnlyNewEvents 
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d] Expecting:
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d]   <[Cancelled(TaskAggregateId(TaskId{value=651b4ab0-b9d4-4441-b44f-06049ad2a272}),EventId(42),None)]>
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d] to contain exactly (and in same order):
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d]   <[Failed(TaskAggregateId(TaskId{value=39b0a35f-e7a5-452c-a16f-c97776737d71}),EventId(42),None,None,None),
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d]     Cancelled(TaskAggregateId(TaskId{value=651b4ab0-b9d4-4441-b44f-06049ad2a272}),EventId(42),None)]>
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d] but could not find the following elements:
[3673b443c1f7c30815ec3c6de1cc1e18b7445d8d]   <[Failed(TaskAggregateId(TaskId{value=39b0a35f-e7a5-452c-a16f-c97776737d71}),EventId(42),None,None,None)]>
```

test this please

**Comment by rouazana** [comment]
not able to write a test reproducing the issue?

**Comment by chibenwa** [comment]
> not able to write a test reproducing the issue?

No, sorry. Maybe a unit test?

**Comment by rouazana** [comment]
> > not able to write a test reproducing the issue?
> 
> No, sorry. Maybe a unit test?

Yes it would be nice at least.

**Comment by chibenwa** [comment]
> Yes it would be nice at least.

Testing this is a several man day effort. We don't have at all the test infrastructure for this.

FetchProcessor code is not nice, dependencies are legion, mocks everywhere. We have no instrumentation code over IMAP. We have no integration tests, and MPT is not suited for concurrency at the level of a single session.

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
