### PR TITLE
Grafana zooming fix, changing `nullPointMode` to `connected`

### PR DESCRIPTION
**Pull request by trantienduchn**
Now I can zoom boards without loosing the line.

new

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[6a46ed24d56994c762946c9a95be24f1402ba2ee] [ERROR] Errors: 
[6a46ed24d56994c762946c9a95be24f1402ba2ee] [ERROR]   SelectedInbox.testStringArgsUS » Runtime java.io.IOException: Unable to delete...
[6a46ed24d56994c762946c9a95be24f1402ba2ee] [INFO] 
[6a46ed24d56994c762946c9a95be24f1402ba2ee] [ERROR] Tests run: 315, Failures: 0, Errors: 1, Skipped: 0
```
test this please

**Comment by chibenwa** [comment]
`SwiftTempAuthObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:94 » Timeout`

We need to be investigating...

test this please

**Comment by chibenwa** [comment]
`SwiftTempAuthObjectStorageBlobsDAOBuilderTest.builtBlobsDAOCanStoreAndRetrieve:94 » Timeout`

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
