### PR TITLE
JAMES-2285 Additional changes for mail queues

### PR DESCRIPTION
**Pull request by chibenwa**
Requested on https://github.com/linagora/james-project/pull/1238 and related PRs

### CODE REVIEW

**Comment by rouazana** [comment]
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a] Failed tests: 
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a]   ManageableMailQueueContract.clearShouldRemoveAllElements:473 
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a] Expecting empty but was:<[org.apache.james.queue.api.ManageableMailQueue$MailQueueItemView@3e44f2a5]>
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a]   ManageableMailQueueContract.concurrentEnqueueShouldNotAlterBrowsing:245 
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a] Actual and expected should have same size but actual size was:
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a]   <3>
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a] while expected size was:
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a]   <2>
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a] Actual was:
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a]   <["name1", "name2", "name3"]>
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a] Expected was:
[dd3c68ef76fe301eca0b5d35b9117aba5aa6b80a]   <["name1", "name2"]>

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
test this please

**Comment by chibenwa** [comment]
```
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65] Failed tests: 
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65]   TasksRoutesTest.listShouldReturnTaskDetailsWhenTaskInProgress:106 1 expectation failed.
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65] JSON path [0].status doesn't match.
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65] Expected: is "inProgress"
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65]   Actual: waiting
```

test this please

**Comment by chibenwa** [comment]
```
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65]   TasksRoutesTest.listShouldReturnTaskDetailsWhenTaskInProgress:106 1 expectation failed.
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65] JSON path [0].status doesn't match.
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65] Expected: is "inProgress"
[fcae0090f3e6466b7a8892e27fea9e1d4db76a65]   Actual: waiting
```

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
