### PR TITLE
JAMES-3111 Use a retry policy to decrease consistency level when All

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
tests are :green_apple: , deployment test failed

**Comment by Arsnael** [comment]
test this please

**Comment by chibenwa** [comment]
Was :green_apple: , rebased and force pushed to update ticket ID

**Comment by mbaechler** [comment]
We can merge that if you want but the current analysis is: ALL is due to read_repair happening

**Comment by chibenwa** [comment]
>

https://docs.datastax.com/en/archived/cassandra/3.0/cassandra/operations/opsRepairNodesReadRepair.html

I dounbt this:

> For QUORUM, only the nodes that the query touches are repaired, not all nodes.

**Comment by Arsnael** [comment]
Merged

**Comment by mbaechler** [comment]
> > We can merge that if you want but the current analysis is: ALL is due to read_repair happening
> 
> https://docs.datastax.com/en/archived/cassandra/3.0/cassandra/operations/opsRepairNodesReadRepair.html
> 
> I doubt this:
> 
> > For QUORUM, only the nodes that the query touches are repaired, not all nodes.

Well, just open the code: https://github.com/apache/cassandra/blob/cassandra-3.11/src/java/org/apache/cassandra/service/StorageProxy.java#L1801

**Pull request closed without merging**
