### PR TITLE
[NO_REVIEW] JAMES-3026 Fix OpenJPA transaction memory leak

### PR DESCRIPTION
**Pull request by chibenwa**
CI for https://github.com/apache/james-project/pull/181

### CODE REVIEW

**Comment by chibenwa** [comment]
```
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (default) on project apache-james-backends-jpa: You have 14 Checkstyle violations. -> [Help 1]

[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[26] (imports) CustomImportOrder: Import statement for 'javax.persistence.EntityManagerFactory' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [INFO] Building jar: /james-project/event-sourcing/event-sourcing-pojo/target/event-sourcing-pojo-3.5.0-SNAPSHOT-tests.jar
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[26,8] (imports) UnusedImports: Unused import - javax.persistence.EntityManagerFactory.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[27] (imports) CustomImportOrder: Import statement for 'javax.persistence.EntityTransaction' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[27,8] (imports) UnusedImports: Unused import - javax.persistence.EntityTransaction.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[28] (imports) CustomImportOrder: Import statement for 'javax.persistence.PersistenceException' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [INFO] 
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[28,8] (imports) UnusedImports: Unused import - javax.persistence.PersistenceException.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [INFO] 
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[29] (imports) CustomImportOrder: Import statement for 'java.util.function.Consumer' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [INFO] >>> maven-source-plugin:3.1.0:test-jar (attach-sources) > generate-sources @ javax-mail-extension >>>
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[29,8] (imports) UnusedImports: Unused import - java.util.function.Consumer.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [INFO] --- maven-jar-plugin:3.1.2:test-jar (default) @ metrics-api ---
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[30] (imports) CustomImportOrder: Import statement for 'java.util.function.Function' is in the wrong order. Should be in the 'STANDARD_JAVA_PACKAGE' group, expecting not assigned imports on this line.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [INFO] 
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ javax-mail-extension ---
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[30,8] (imports) UnusedImports: Unused import - java.util.function.Function.
[303077bb3ef9fd3ed5e695f77e428fd100fab69c] [ERROR] src/main/java/org/apache/james/backends/jpa/EntityManagerUtils.java:[40,26] (whitespace) WhitespaceAround: WhitespaceAround: '==' is not preceded with whitespace.
```

**Comment by Arsnael** [comment]
CI restart

test this please

**Comment by Arsnael** [comment]
```
[c80d6ca62edb5260040af16eae0e26da93bb4364] [ERROR] Failures: 
[c80d6ca62edb5260040af16eae0e26da93bb4364] [ERROR]   FixingGhostMailboxTest.ghostMailboxBugShouldDiscardOldContent:215 1 expectation failed.
[c80d6ca62edb5260040af16eae0e26da93bb4364] JSON path [0][1].messageIds doesn't match.
[c80d6ca62edb5260040af16eae0e26da93bb4364] Expected: a collection with size <1>
[c80d6ca62edb5260040af16eae0e26da93bb4364]   Actual: []
```
test this please

**Comment by Arsnael** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
