### PR TITLE
JAMES-3004 avoid starvation issues by use Schedulers.elastic instead …

### PR DESCRIPTION
**Pull request by mbaechler**
…of boundedElastic

### CODE REVIEW

**Comment by remk** [comment]
I am not really satisfied with this solution as it tends to hide problems more than solving them.
Can't you change it only in the place related to https://github.com/linagora/james-project/pull/2971 ?

Or use a dedicated scheduler like you mentioned in this PR ?

**Comment by Arsnael** [comment]
> I am not really satisfied with this solution as it tends to hide problems more than solving them.

I'm sorry I disagree with that. I encountered similar issues with provisioning and `RandomStoring` for example before. As I think Matthieu said, it seems that we have too many blocks and the `boundedElastic` can lead to deadlocks in some complex corner cases that are hard to catch. If we wait to observe by ourselves every time a thread starvation to take care of it granually, I don't think it's good. Think also about the people in the community that might experience similar issues without understanding why it's happening.

I think `boundedElastic` introduced probably more problems than solving issues in James case for now. I'm in favor of reverting it

**Comment by Arsnael** [comment]
test this please

**Comment by remk** [comment]
Before : 
Capture d’écran de 2019-12-11 13-37-41
Capture d’écran de 2019-12-11 14-29-54

After : 

Capture d’écran de 2019-12-11 15-37-13

Capture d’écran de 2019-12-11 14-30-12


In conclusion this change do two things : 

- Slightly improve enqueue performance ( 10%)
- Significantly decrease dequeue performance (30%)

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
```
[ERROR] ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```
test this please

**Comment by mbaechler** [comment]
@remk : could you describe what you stress tested?

**Comment by remk** [comment]
> @remk : could you describe what you stress tested?
I stress tested the smpt subsystem / spooler by using the same tests we have done on activemq recently :  `smtp.FeederNoAuthenticationNoEncryptionSimulation` with 600 different users.

**Comment by remk** [comment]
> > @remk : could you describe what you stress tested?
> > I stress tested the smpt subsystem / spooler by using the same tests we have done on activemq recently :  `smtp.FeederNoAuthenticationNoEncryptionSimulation` with 600 different users.

The tests were done on the cassandra rabbitmq product.

**Comment by Arsnael** [comment]
```
[762af85469cda18414bde9f21f32bf359855c77e] 13:42:32.348 [ERROR] spark.Spark - ignite failed
[762af85469cda18414bde9f21f32bf359855c77e] java.net.BindException: Address already in use
```
test this please

**Comment by chibenwa** [comment]
Morning thought: I think this dead lock behavior comes from nested reactor calls (like the one we identified in https://github.com/linagora/james-project/pull/2992 )

**Comment by remk** [comment]
rebased

**Comment by Arsnael** [comment]
test this please

**Comment by mbaechler** [comment]
> Morning thought: I think this dead lock behavior comes from nested reactor calls (like the one we identified in #2992 )

Yes, we agree.

**Pull request merged**
