### PR TITLE
JAMES-2854 Rework ConfigurationPerformer

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[76f20ff58d9bf87acd5a6962a346cb777d64fa6d] [ERROR] src/main/java/org/apache/james/modules/server/WebAdminServerModule.java:[31] (imports) CustomImportOrder: Wrong lexicographical order for 'org.apache.james.utils.GuiceProbe' import. Should be before 'org.apache.james.utils.InitialisationOperation'.
```

**Comment by Arsnael** [comment]
```
[b46e82067c496682bb399012adbf969071ba08ef] [ERROR] Errors: 
[b46e82067c496682bb399012adbf969071ba08ef] [ERROR]   BucketBlobStoreContract.saveConcurrentlyWithNonPreExistingBucketShouldNotFail:153 » NotTerminated

[b46e82067c496682bb399012adbf969071ba08ef] [ERROR] After correcting the problems, you can resume the build with the command
[b46e82067c496682bb399012adbf969071ba08ef] [ERROR]   mvn <goals> -rf :blob-objectstorage
```
Second time I see this on the CI today... Might need to check it out perhaps

test this please

**Comment by chibenwa** [comment]
:green_apple: before CI reboot

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
