### PR TITLE
JAMES-2989 JMAP MessagePreviewStore contract + memory impl

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
> Can we use this wonderful preview type? Like in MessagePreviewGenerator ?

Strong typing enforcing will be taking care on another PR

**Comment by Arsnael** [comment]
CI restart...

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by Arsnael** [comment]
Merged

**Pull request closed without merging**
