### PR TITLE
JAMES-2632 Reduce read level upon JMAP SetMessage

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by hoangdat** [comment]
Read it.

**Comment by chibenwa** [comment]
Looks like a shared pom issue

```
[c0990cb98c490b18ecafd3e757d1c0e1e36c68c3] [ERROR] Failed to execute goal on project apache-james-mpt-external-james: Could not resolve dependencies for project org.apache.james:apache-james-mpt-external-james:jar:3.4.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.james:apache-james-mailbox-api:jar:3.4.0-SNAPSHOT, org.apache.james:apache-james-mpt-core:jar:3.4.0-SNAPSHOT, org.apache.james:metrics-logger:jar:3.4.0-SNAPSHOT: Could not find artifact org.apache.james:apache-james-mailbox-api:jar:3.4.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/snapshots) -> [Help 1]
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
