### PR TITLE
JAMES-8255 rest-assured lib upgrade

### PR DESCRIPTION
**Pull request by Arsnael**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.getGlobalSieveQuotaShouldReturn204WhenNoQuotaSet:67 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.getGlobalSieveQuotaShouldReturnStoredValue:79 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <200> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.getPerUserQuotaShouldReturn204WhenNoQuotaSetForUser:142 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.getPerUserSieveQuotaShouldReturnStoredValue:154 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <200> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.removeGlobalSieveQuotaShouldRemoveGlobalSieveQuota:134 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.removeGlobalSieveQuotaShouldReturn204WhenNoQuotaSet:124 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.removePerUserSieveQuotaShouldRemoveQuotaForUser:209 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.removePerUserSieveQuotaShouldReturn204WhenNoQuotaSetForUser:199 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.updateGlobalSieveQuotaShouldReturn400WhenMalformedJSON:107 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.updateGlobalSieveQuotaShouldReturn400WhenRequestedSizeNotPositiveInteger:116 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.updateGlobalSieveQuotaShouldUpdateStoredValue:96 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.updatePerUserSieveQuotaShouldReturn400WhenMalformedJSON:182 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.updatePerUserSieveQuotaShouldReturn400WhenRequestedSizeNotPositiveInteger:191 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveQuotaRoutesTest.updatePerUserSieveQuotaShouldUpdateStoredValue:171 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptAddScriptSucceededOneWhenNotAddActivateParam:194 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptGetActiveShouldThrowsExceptionWhenAddActivateParamFalse:228 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptInvokeShouldReturnBadRequestWhenAddActivateParamWithNotBooleanValue:244 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptSetActiveTrueWhenAddActivateParamTrue:211 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptShouldReturnBadRequestWhenScriptIsNotSet:166 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptShouldReturnNotFoundWhenScriptNameIsWhiteSpace:129 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptShouldReturnNotFoundWhenUserNameWhiteSpace:151 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <400> but was <404>.
[20a187539523b86937795a61f69648d2a0097354] 
[20a187539523b86937795a61f69648d2a0097354] [ERROR]   SieveScriptRoutesTest.defineAddActiveSieveScriptShouldReturnSucceededWhenScriptIsWhiteSpace:178 1 expectation failed.
[20a187539523b86937795a61f69648d2a0097354] Expected status code <204> but was <404>.
```
known issue... investigating

**Comment by Arsnael** [comment]
Like above, not found route in multiple test classes in `james-server-webadmin-mailbox` module. Will fix

**Comment by Arsnael** [comment]
There is error messages like this for example : 
```
"message": "GET /users/username/mailboxes/quota/domains/trouvé.com/count can not be found"
```
When you look at the prefix it's obvious it's different base paths that have been concatenated together somehow... which is weird... Like it doesn't really clean the base path when creating a new `RequestSpecBuilder` ?

**Comment by Arsnael** [comment]
```
[ERROR]   BucketBlobStoreContract.saveConcurrentlyWithNonPreExistingBucketShouldNotFail:153 » NotTerminated
```
test this please

**Comment by Arsnael** [comment]
```
[ERROR]   MailsShouldBeWellReceived.mailsShouldBeWellReceived:63 » ConditionTimeout Cond.
```
test this please

**Comment by trantienduchn** [comment]
```
[c2a33a253d485d66ee5bb60c6f422e962e9b2d0f] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:499
[c2a33a253d485d66ee5bb60c6f422e962e9b2d0f] LastClientMsg: c SEARCH FLAGGED
[c2a33a253d485d66ee5bb60c6f422e962e9b2d0f] Expected: '\* SEARCH 1 2 3 4'
[c2a33a253d485d66ee5bb60c6f422e962e9b2d0f] Actual   : '* SEARCH'
[c2a33a253d485d66ee5bb60c6f422e962e9b2d0f] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeployment(DeploymentValidation.java:81)
```
test this please

**Comment by trantienduchn** [comment]
```
[c2a33a253d485d66ee5bb60c6f422e962e9b2d0f] [ERROR] Errors: 
[c2a33a253d485d66ee5bb60c6f422e962e9b2d0f] [ERROR]   MailsShouldBeWellReceived.mailsShouldBeWellReceived:63 » ConditionTimeout Cond...
```
test this please

**Pull request closed without merging**
