### PR TITLE
Increase wait time in DeploymentValidation script

### PR DESCRIPTION
**Pull request by chibenwa**
This test was proved flacky

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please

**Comment by trantienduchn** [comment]
test this please. no error output

**Comment by chibenwa** [comment]
test this please

**Comment by aduprat** [comment]
```
[ERROR] Failed to execute goal on project blob-objectstorage-guice: Could not resolve dependencies for project org.apache.james:blob-objectstorage-guice:jar:3.2.0-SNAPSHOT: Could not find artifact org.apache.james:blob-objectstorage:jar:tests:3.2.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
```

**Comment by aduprat** [comment]
test this please

**Comment by aduprat** [comment]
same
```
[ERROR] Failed to execute goal on project blob-objectstorage-guice: Could not resolve dependencies for project org.apache.james:blob-objectstorage-guice:jar:3.2.0-SNAPSHOT: Could not find artifact org.apache.james:blob-objectstorage:jar:tests:3.2.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
```

**Comment by chibenwa** [comment]
test this please

https://github.com/linagora/james-project/pull/1840 is supposed to have solved the CI issue encountered here.

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
