### PR TITLE
try to limit cassandra memory to not depend on host memory

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by mbaechler** [comment]
build is green

**Comment by mbaechler** [comment]
pushed force to put the JIRA number in the commit

**Comment by rouazana** [comment]
test this please

**Comment by chibenwa** [comment]
```
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] [ERROR] Failures: 
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] [ERROR]   EventDeadLettersIntegrationTest.taskShouldBeCompletedAfterSuccessfulRedelivery:289 1 expectation failed.
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] JSON path additionalInformation.eventId doesn't match.
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] Expected: is "30db4ff8-11e5-45d5-b070-817f9003955b"
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678]   Actual: null
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] 
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] [ERROR]   WebAdminServerIntegrationTest.postShouldDoMigrationAndUpdateCurrentVersion:269 1 expectation failed.
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] Response body doesn't match expectation.
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] Expected: is "{\"version\":7}"
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678]   Actual: {"version":4}
```

test this please

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
```

[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] [ERROR] dequeueShouldDecreaseQueueSize  Time elapsed: 0.181 s  <<< ERROR!
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] 	at org.apache.james.queue.api.ManageableMailQueueContract.dequeueShouldDecreaseQueueSize(ManageableMailQueueContract.java:81)
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] 
```
test this please

**Comment by Arsnael** [comment]
Test build was a success but dockerize step crashed

**Comment by Arsnael** [comment]
test this please

**Comment by Arsnael** [comment]
```
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] [ERROR] Errors: 
[144480f87e7a49bbd3a2f97e5d5e9d29e222e678] [ERROR]   ManageableMailQueueContract.dequeueShouldDecreaseQueueSize:81 » AlreadyClosed ...
```
test this please

**Comment by chibenwa** [comment]
Well, very likely this PR is **not stable**

I propose increasing the memory limit to 1 GB then 2 GB then... Until we find something that pass...

**Comment by mbaechler** [comment]
> I propose increasing the memory limit to 1 GB then 2 GB then... Until we find something that pass...

What about waiting for container restart policy to be merged before changing that limit?

**Comment by chibenwa** [comment]
Agree

**Comment by mbaechler** [comment]
```
[452eb9fa7439a28bc60a82714587c63c69b620f7] [ERROR] Errors: 
[452eb9fa7439a28bc60a82714587c63c69b620f7] [ERROR]   MemoryUploadCucumberTest » Socket Broken pipe (Write failed)
```
It should definitely not be related

test this please

**Comment by Arsnael** [comment]
```
Running: End of Workflow
java.io.IOException: {
  "message": "Server Error"
}
```
at the beginning of the job, right after the checkout... not related

test this please

**Comment by Arsnael** [comment]
```
[452eb9fa7439a28bc60a82714587c63c69b620f7] [ERROR] Errors: 
[452eb9fa7439a28bc60a82714587c63c69b620f7] [ERROR]   FilterTest.messageShouldBeAppendedInSpecificMailboxWhenFromRuleMatches:749 » ConditionTimeout
```
test this please

**Comment by blackheaven** [comment]
test this please

**Comment by blackheaven** [comment]
test this please

**Pull request merged**
