### PR TITLE
JAMES-2717 Enable parrallel inMemory testing in MPT IMAP Lucene tests

### PR DESCRIPTION
**Pull request by chibenwa**
InMemory RAMDirectory mostly contributes the desired isolation. Time enhancement is
achieved through the now possible parrallel test execution.

Test time went (locally) from 7:06 to 3:19

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[38fa3de36eb82e274fd12ad81415ed0dfdf54383] 	Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://172.17.0.1:56008], URI [/quota_ratio_v1?master_timeout=30s&timeout=30s], status line [HTTP/1.1 403 Forbidden]
[38fa3de36eb82e274fd12ad81415ed0dfdf54383] {"error":{"root_cause":[{"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"}],"type":"cluster_block_exception","reason":"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];"},"status":403}

[INFO] Apache James :: Server :: Cassandra - guice injection FAILURE [01:38 min]
```
new unstable test

**Comment by chibenwa** [comment]
```
[38fa3de36eb82e274fd12ad81415ed0dfdf54383] [INFO] Apache James MPT Imap Mailbox - LuceneSearch ....... SUCCESS [06:16 min]
```

Instead of

```
[INFO] Apache James MPT Imap Mailbox - LuceneSearch ....... SUCCESS [07:35 min]
```

Even if that's still good to take this is a huge personal disapointment...

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Build is :green_apple: , deployment tests are annoying...

test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
