### PR TITLE
JAMES-3295 Use MessageManager::listMessagesMetadata more widely

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
No, it unlocks significant performance enhencemantsby skipping reads on messagev2 table

**Comment by rouazana** [comment]
I don't get why you don't take the time to do the 4 clicks to ensure that you are really improving perfs

**Comment by chibenwa** [comment]
Because I need to manually launch the load testing as IMAP performance tests are broken when launched on charge-02

**Comment by rouazana** [comment]
let's fix them then!

**Pull request merged**
