### PR TITLE
[DONT REVIEW] WIP reducing retries in integration tests

### PR DESCRIPTION
**Pull request by trantienduchn**

### CODE REVIEW

**Comment by trantienduchn** [comment]
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:07 h
[INFO] Finished at: 2020-04-10T08:33:25Z
```

doesn't gain any thing, It would provide a significant different in tests that pausing rabbitMQ. there is non of those tests in our integration test suit.

**Comment by trantienduchn** [comment]
```
[INFO] Apache James :: Mailbox :: Event :: RabbitMQ implementation SUCCESS [16:39 min]
[INFO] Apache James :: Server :: Web Admin server integration tests :: Distributed SUCCESS [15:28 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:58 h
[INFO] Finished at: 2020-04-10T18:27:02Z
[INFO] ------------------------------------------------------------------------
```

comparing to the #3276 
```
[INFO] Apache James :: Mailbox :: Event :: RabbitMQ implementation SUCCESS [26:29 min]
[INFO] Apache James :: Server :: Web Admin server integration tests :: Distributed SUCCESS [16:35 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:11 h
[INFO] Finished at: 2020-04-10T07:39:51Z
[INFO] ------------------------------------------------------------------------
```

~10 mintues gain

**Comment by chibenwa** [comment]
Looks great.

test this please

(passed maven tests)

**Comment by chibenwa** [comment]
This had been implemented by injecting a custom configuration POJO

**Pull request closed without merging**
