### PR TITLE
 JAMES-2855 Upgrade to maven 3.6.2 

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by mbaechler** [comment]
```
[1f4191a4a97b723b1429bcfa9b903dfcfe87358a] 
[1f4191a4a97b723b1429bcfa9b903dfcfe87358a] Location: /org/apache/james/imap/scripts/ValidateDeployment.test:499
[1f4191a4a97b723b1429bcfa9b903dfcfe87358a] LastClientMsg: c SEARCH FLAGGED
[1f4191a4a97b723b1429bcfa9b903dfcfe87358a] Expected: '\* SEARCH 1 2 3 4'
[1f4191a4a97b723b1429bcfa9b903dfcfe87358a] Actual   : '* SEARCH'
[1f4191a4a97b723b1429bcfa9b903dfcfe87358a] 
```
test this please

**Comment by chibenwa** [comment]
Merged

**Comment by mbaechler** [comment]
is it actually faster?

**Comment by chibenwa** [comment]
Yes, 1 minute for build, 1 minute for test

**Pull request closed without merging**
