### PR TITLE
JAMES-1950 Add operations per minute curves to count graphics

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by mbaechler** [comment]
As already stated, it's more a metric problem than a graph one, see http://metrics.dropwizard.io/3.1.0/manual/core/#histograms for example

**Comment by chibenwa** [comment]
@rouazana Did you forgot SMTP count board ?

@mbaechler  The derivate will give the rate, what the ticket is asking for. Without putting more pressure on James server, without being invasive in the code, without taking us much time to implement, and without storing yet another metric is ES. I would propose to live with this in a first time and see how it goes on...

**Comment by rouazana** [comment]
@btellier No, it's committed.
@mbaechler I don't see why we should add new metrics while the current ones have all the informations to compute the values we need.

**Comment by chibenwa** [comment]
Merged

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
