### PR TITLE
James 1663 : support spring / java6

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by rouazana** [comment]
So no more support for Spring + Cassandra?

**Comment by aduprat** [comment]
:+1:

**Comment by mbaechler** [comment]
@rouazana : I don't think it's very useful, I decided to drop it.

**Comment by aduprat** [comment]
I agree with Matthieu.

**Comment by rouazana** [comment]
:+1:

**Comment by aduprat** [comment]
:+1:

**Comment by mbaechler** [comment]
superseded by https://github.com/linagora/james-project/pull/111

**Pull request closed without merging**
