### PR TITLE
Checkstyle and Eclipse warnings fixes

### PR DESCRIPTION
**Pull request by rouazana**

### CODE REVIEW

**Comment by Arsnael** [comment]
```
[ERROR] Tests run: 16, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 39.382 s <<< FAILURE! - in org.apache.james.jmap.cassandra.CassandraSetMessagesMethodTest
[ERROR] mailboxIdsShouldBeInDestinationWhenUsingForMove  Time elapsed: 1.001 s  <<< ERROR!
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=invalid_alias_name_exception, reason=Invalid alias name [quota_ratio_write_alias], an index exists with the same name as the alias]
    at org.apache.james.jmap.methods.integration.SetMessagesMethodTest.setup(SetMessagesMethodTest.java:162)
```
test this please

**Comment by rouazana** [comment]
test this please

**Comment by rouazana** [comment]
test this please

**Comment by mbaechler** [comment]
Merged

**Pull request closed without merging**
