### PR TITLE
James 2117 don't leak Cassandra Cluster object on init failure

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
Equality failure?

```
Results :

Failed tests: 
  CassandraAnnotationMapperTest>AnnotationMapperTest.annotationShouldBeCaseInsentive:208 
Expecting:
  <[MailboxAnnotation{key=/private/comment, value=Optional.of(The annotation with upper key)}]>
to contain only:
  <[MailboxAnnotation{key=/private/comment, value=Optional.of(The annotation with upper key)}]>
but the following elements were unexpected:
  <[MailboxAnnotation{key=/private/comment, value=Optional.of(The annotation with upper key)}]>
```

**Comment by mbaechler** [comment]
Yes, it's fixed in 2107 branch

**Comment by chibenwa** [comment]
Could you cherry-pick when fixed?

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
