### PR TITLE
JAMES-2198 Upgrades related to Java deserialization vulnerabilities

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by rouazana** [comment]
StringEscapeUtils and RandomStringUtils are deprecated, you must use the version in commons-text now.

**Comment by rouazana** [comment]
What about aopalliance:1.0 and ActiveMQ?

**Comment by chibenwa** [comment]
ActiveMQ is not vulnerable on master

aopalliance:1.0 seems to be a spring dependancy...

```
StringEscapeUtils and RandomStringUtils are deprecated, you must use the version in commons-text now.
```

Funny I did not saw deprecation messages....

**Comment by chibenwa** [comment]
aopalliance 1.0 is bringed in by Guice, no fix available for it...

**Comment by mbaechler** [comment]
```
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec] [ERROR] /james-project/mailbox/store/src/test/java/org/apache/james/mailbox/store/StoreMessageIdManagerTestSystem.java:[111,15] no suitable constructor found for NotImplementedException(no arguments)
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]     constructor org.apache.commons.lang3.NotImplementedException.NotImplementedException(java.lang.String) is not applicable
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]       (actual and formal argument lists differ in length)
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]     constructor org.apache.commons.lang3.NotImplementedException.NotImplementedException(java.lang.Throwable) is not applicable
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]       (actual and formal argument lists differ in length)
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]     constructor org.apache.commons.lang3.NotImplementedException.NotImplementedException(java.lang.String,java.lang.Throwable) is not applicable
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]       (actual and formal argument lists differ in length)
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]     constructor org.apache.commons.lang3.NotImplementedException.NotImplementedException(java.lang.String,java.lang.String) is not applicable
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]       (actual and formal argument lists differ in length)
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]     constructor org.apache.commons.lang3.NotImplementedException.NotImplementedException(java.lang.Throwable,java.lang.String) is not applicable
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]       (actual and formal argument lists differ in length)
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]     constructor org.apache.commons.lang3.NotImplementedException.NotImplementedException(java.lang.String,java.lang.Throwable,java.lang.String) is not applicable
[b2e0ef3fa48f4dd120715c7162db90b4699ad1ec]       (actual and formal argument lists differ in length)
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
I don't succeed to relaunch unit test with the trigger phrase

**Pull request closed without merging**
