### PR TITLE
JAMES-3436 Email/set create - specify Email metadata properties

### PR DESCRIPTION
**Pull request by chibenwa**
Follow up PR for convenience headers ;-)

### CODE REVIEW

**Review by LanKhuat — APPROVED** [review]

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

`docker: Error response from daemon: No such container: git-publish-james-3436-2-9bcc87bb-7a75-461a-830f-446028ede946.`

**Review by nvduc91 — APPROVED** [review]

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
