### PR TITLE
[NO_REVIEW] JAMES-2855 Dependencies upgrade aggregated pull rebaset

### PR DESCRIPTION
**Pull request by chibenwa**
This, is a rebase of all :green_apple: and robusta beans approuved PR:

 - Ease merge
 - Ensure PRs do not 'conflict' with each others.

With that merging them "with a safe mind" will be easier.

Individual PRs includes:

 - https://github.com/linagora/james-project/pull/2596
 - https://github.com/linagora/james-project/pull/2595
 - https://github.com/linagora/james-project/pull/2592
 - https://github.com/linagora/james-project/pull/2590
 - https://github.com/linagora/james-project/pull/2589
 - https://github.com/linagora/james-project/pull/2588
 - https://github.com/linagora/james-project/pull/2586
 - https://github.com/linagora/james-project/pull/2585
 - https://github.com/linagora/james-project/pull/2584
 - https://github.com/linagora/james-project/pull/2583
 - https://github.com/linagora/james-project/pull/2582
 - https://github.com/linagora/james-project/pull/2581
 - https://github.com/linagora/james-project/pull/2579
 - https://github.com/linagora/james-project/pull/2577
 - https://github.com/linagora/james-project/pull/2576
 - https://github.com/linagora/james-project/pull/2597 
 - https://github.com/linagora/james-project/pull/2594

### CODE REVIEW

**Comment by trantienduchn** [comment]
work flow job is 🍏 but the build is stuck for 10 hours. test this please

**Comment by Arsnael** [comment]
tests are :green_apple: 

```
docker: Error response from daemon: Cannot link to a non running container: /rabbitmq-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d AS /james-server-cassandra-rabbitmq-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d/rabbitmq.
```
test this please

**Comment by chibenwa** [comment]
```
[8c4f3c2221addc040c0e4c455e739997116582c7] + docker run --detach=true --name=james-server-cassandra-rabbitmq-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d --hostname james.linagora.com --expose=143 --expose=587 --publish-all=true --link cassandra-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d:cassandra --link elasticSearch-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d:elasticsearch --link rabbitmq-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d:rabbitmq --link swift-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d:swift james-server-cassandra-rabbitmq-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d
[8c4f3c2221addc040c0e4c455e739997116582c7] de60aa4ad69f646a169183af2127da8181a8ee1c65248105441960ff75699914
[8c4f3c2221addc040c0e4c455e739997116582c7] docker: Error response from daemon: Cannot link to a non running container: /rabbitmq-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d AS /james-server-cassandra-rabbitmq-james-2855-97dc605b-d7d6-4aab-99ae-6c6bde3da23d/rabbitmq.
```

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
Merged

**Pull request closed without merging**
