### PR TITLE
JAMES-1708 Use MOVE Capability in JMAP

### PR DESCRIPTION
**Pull request by rouazana**
The biggest part is to check the capability is supported by MailboxManager and the test of this check.

### CODE REVIEW

**Comment by aduprat** [comment]
:+1:

**Comment by aduprat** [comment]
Can one of the admins verify this patch?

**Comment by aduprat** [comment]
Can one of the admins verify this patch?

**Comment by mbaechler** [comment]
:+1:

**Comment by mbaechler** [comment]
test this please

**Comment by mbaechler** [comment]
merged

**Pull request closed without merging**
