### PR TITLE
Communicate guice cassandra

### PR DESCRIPTION
**Pull request by aduprat**
I upgrade the version of maven-site-plugin in order to get rid of
http://stackoverflow.com/questions/22018350/sqoop2-build-fails-missing-org-sonatype-aether-graph-dependencyfilter

### CODE REVIEW

**Comment by mbaechler** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Comment by aduprat** [comment]
Rebased on apache/trunk

**Comment by mbaechler** [comment]
:+1:

**Comment by rouazana** [comment]
:+1:

**Pull request closed without merging**
