### PR TITLE
James 2504 : make docker image test work again

### PR DESCRIPTION
**Pull request by mbaechler**

### CODE REVIEW

**Comment by chibenwa** [comment]
test this please (no build output)

**Comment by chibenwa** [comment]
```
[3d1fee43c7fdbc5eddb5046d72540b377125562e] Tests in error: 
[3d1fee43c7fdbc5eddb5046d72540b377125562e]   RabbitMQClusterTest$ClusterNodesFailure.connectingToAClusterWithAFailedRabbit:225 » AlreadyClosed
```

**Comment by chibenwa** [comment]
test this please (with JAMES-2500)

**Comment by mbaechler** [comment]
```
org.apache.james.mpt.imapmailbox.external.james.JamesDeploymentValidation
[3d1fee43c7fdbc5eddb5046d72540b377125562e] validateDeployment  Time elapsed: 0.21 sec  <<< ERROR!
[3d1fee43c7fdbc5eddb5046d72540b377125562e] java.net.ConnectException: Connection refused
[3d1fee43c7fdbc5eddb5046d72540b377125562e] 	at org.apache.james.mpt.imapmailbox.external.james.DeploymentValidation.validateDeployment(DeploymentValidation.java:50)
[3d1fee43c7fdbc5eddb5046d72540b377125562e] 
```

**Comment by mbaechler** [comment]
@chibenwa : can you have a look at that tomorrow, it's probably a wrong API used to retrieve the container IP.

**Comment by chibenwa** [comment]
Yes, it looks like 'ISSUE-101' in james-jenkins. I will meege it tomorrow.

**Comment by chibenwa** [comment]
test this please 

(https://github.com/linagora/james-jenkins/pull/110 ISSUE-101 merged)

**Comment by chibenwa** [comment]
test this please

Test freeze in org.apache.james.queue.rabbitmq.RabbitMQClusterTest

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please (schedule on another server, not anakin)

**Comment by chibenwa** [comment]
test this please

**Comment by mbaechler** [comment]
merged

**Pull request closed without merging**
