### PR TITLE
JAMES-2927 [Cassandra] unset null binding fields in insert queries

### PR DESCRIPTION
**Pull request by trantienduchn**
Alternative with #2778

### CODE REVIEW

**Comment by remk** [comment]
I think that you should add a test that demonstrate that if you want to update an existing Optional value to none. After the update, the retrieved value is empty as expected.
Otherwise that seems nice :)

**Comment by trantienduchn** [comment]
> I think that you should add a test that demonstrate that if you want to update an existing Optional value to none. After the update, the retrieved value is empty as expected.

Oh shit :fearful:

**Comment by trantienduchn** [comment]
There's no way to distinguish intention and un-intention null set from the CassandraExecutor side. I will close this PR. 

The reason I created this PR is I couldn't find any clean way to deal with null checking binding at the DAO side

**Comment by trantienduchn** [comment]
I have another option. Using a decorator

**Comment by chibenwa** [comment]
Why cant the cassandraAsyncExecutor caller can't avoid doing the null binding in the first place?

**Comment by trantienduchn** [comment]
> Why cant the cassandraAsyncExecutor caller can't avoid doing the null binding in the first place?

No, actually I'm following that idea. Just finding the way to get out of if else blocks...

**Comment by trantienduchn** [comment]
not found, stop right here

**Pull request closed without merging**
