### PR TITLE
JAMES-3093 Apply JWT authntication strategy before access token one

### PR DESCRIPTION
**Pull request by chibenwa**

### CODE REVIEW

**Comment by chibenwa** [comment]
Merged

**Comment by mbaechler** [comment]
Where are the tests?

**Comment by chibenwa** [comment]
> Where are the tests?

Nowhere.

If we wonna write them, it would be `JWT auth don't generate long stacktraces.` but so far we did not write tests on loggers much.

Would you think we should write them?

**Comment by mbaechler** [comment]
The stacktrace is a consequence, there are probably ways to test that without going to the log level like: provide a throwing access token authenticator and check that when providing a jwt token we don't throw.

**Comment by mbaechler** [comment]
And I guess, when you don't find any way to test something, you could ask people if they have any idea.

**Comment by chibenwa** [comment]
I think it is really related with this discussion: https://github.com/linagora/james-project/pull/3398#discussion_r433769892 , by solving it we would also address this issue.

**Pull request closed without merging**
