### PR TITLE
JAMES-2306 Docker website generation helper should not overwrite unre…

### PR DESCRIPTION
**Pull request by chibenwa**
…lated content

Before, specifying website directory as destination deleted site archives.

### CODE REVIEW

**Comment by rouazana** [comment]
other fixes are needed, I will add them later

**Comment by rouazana** [comment]
I added the needed fix. The skin version commit should be modified when the new version is out.
I will also update the doc when I have some time.

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by chibenwa** [comment]
test this please

**Comment by rouazana** [comment]
documentation update. Maybe we can wait for the release of james-skin to update the pom and merge this.

**Comment by chibenwa** [comment]
Merged.

**Pull request closed without merging**
